### PR TITLE
chore(buffers): fix unconstrained generic parameter in `EventCount` impl

### LINKED ISSUE #12858: chore(buffers): fix dangerous impl of `EventCount` for unconstrained `Vec<T>`
As mentioned in #12755 ([comment here](https://github.com/vectordotdev/vector/pull/12755#discussion_r881634613)), I wrote a not-smart trait implementation of `EventCount` for `Vec<T>`, with no constraint on `T`. This was to satisfy getting the length of things like `Vec<LokiRecord>` in a `RequestBuilder` implementation, but poses a risk of providing incorrect data such as, to follow the comment, `Vec<EventArray>` using `Vec::len` for its event count, instead of the correct summation of the event count for each array element.

Again, as mentioned in the comments, the simplest and most indisputably correct fix would simply be to implement `EventCount` where necessary to allow us to constrain the trait implementation via `T: EventCount`, and then do the summation.

### PR DESCRIPTION
**Pull request by tobz**
In #12755, I incorrectly added a blanket implementation of `EventCount` for `Vec<T>`, but did not constrain `T` such that a construction such as `Vec<EventArray>` would receive the blanket implementation and, yet, return a potentially very incorrect value for event count: the length of the vector, rather than the sum of the event count of all elements.

This PR properly constrains the implementation and sums the event count of each element. Additionally, we've added blanket implementations for references to types implementing `EventCount`, as well as `ByteSizeOf`, to make things a little cleaner as well.

Fixes #12858.

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Sweet, thanks for cleaning this up.

**Review by lukesteensen — APPROVED** [review]

File: lib/vector-core/src/event/mod.rs [hunk 1]
```diff
@@ -65,28 +65,12 @@ impl ByteSizeOf for Event {
...
-impl ByteSizeOf for &Event {
-    fn allocated_bytes(&self) -> usize {
-        match self {
-            Event::Log(log_event) => log_event.allocated_bytes(),
-            Event::Metric(metric_event) => metric_event.allocated_bytes(),
-            Event::Trace(trace_event) => trace_event.allocated_bytes(),
-        }
-    }
-}
-
```
Comment (bruceg) [inline lib/vector-core/src/event/mod.rs:77]: Woot! Removed lines > added lines.
