### PR TITLE
fix(cli): Use user-provided array values in vector config --include-defaults

### LINKED ISSUE #12329: `vector config --include-defaults` duplicates array fields
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Running `vector --config ... config --include-defaults` duplicates elements in array fields.

### Configuration

```text
[sources.source0]
type = "stdin"

[sinks.sink0]
inputs = ["source0"]
type = "console"

[sinks.sink0.encoding]
codec = "json"
only_fields = ["foo"]
```

### Version

vector 0.21.0 (aarch64-apple-darwin)

### Debug Output

```text
{
  "data_dir": "/var/lib/vector/",
  "api": {
    "enabled": false,
    "address": "127.0.0.1:8686",
    "playground": true
  },
  "schema": {
    "enabled": false
  },
  "enterprise": null,
  "healthchecks": {
    "enabled": true,
    "require_healthy": false
  },
  "enrichment_tables": {},
  "sources": {
    "source0": {
      "type": "stdin",
      "max_length": 102400,
      "host_key": null,
      "framing": {
        "method": "newline_delimited"
      },
      "decoding": {
        "codec": "bytes"
      }
    }
  },
  "sinks": {
    "sink0": {
      "inputs": [
        "source0",
        "source0"
      ],
      "healthcheck_uri": null,
      "healthcheck": {
        "enabled": true,
        "uri": null
      },
      "buffer": {
        "type": "memory",
        "max_events": 500,
        "when_full": "block"
      },
      "type": "console",
      "target": "stdout",
      "encoding": {
        "codec": "json",
        "only_fields": [
          "foo",
          "foo"
        ]
      }
    }
  },
  "transforms": {},
  "tests": [],
  "provider": null
}
```

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by 001wwang**
Closes #12329 

This PR adjusts `vector config --include-defaults` behavior to directly use user-provided array values rather than merge them with the related `ConfigBuilder`'s array values. This avoids duplicates.

### Example

With the following configuration,
```
[sources.source0]
type = "stdin"

[sinks.sink0]
type = "blackhole"
inputs = ["*"]
```

Running 

```
vector -c {{your config path}} config --include-defaults
```

should generate the following  (trimmed for brevity). Previously, this output would include `inputs: ["*", "*"]`.

```
{
 ...
  "sinks": {
    "sink0": {
      ...
      "inputs": [
        "*"
      ],
      ...
    }
  ...
}
```

### CODE REVIEW

File: src/config/cmd.rs [hunk 1]
```diff
@@ -26,9 +26,6 @@ fn merge_json(a: &mut Value, b: Value) {
         (Value::Array(ref mut a), Value::Object(b)) => {
             a.extend([Value::Object(b)]);
         }
```
Comment (jszwedko) [inline src/config/cmd.rs:28]: This block strikes me as a bit weird too. Maybe it should also just map to `b`? Or throw an error.

**Review by jszwedko — APPROVED** [review]
One comment unrelated to the specific fix here. Thanks @001wwang !

File: src/config/cmd.rs (hunk 1 above)
Comment (001wwang) [reply src/config/cmd.rs:28]: @leebenson was there a specific case this was covering? Otherwise, happy to update this.

Comment (leebenson) [reply src/config/cmd.rs:28]: Looking at this again, I think this can be dropped. Arrays should be overridden rather than combined, and I can't think why Value::Object was added as an exception.
