### PR TITLE
fix(socket source): discard udp frames greater than max_length.

### LINKED ISSUE #11512: `socket`/`tcp` source: `max_length` configuration discards messages instead of truncating
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

According to the [official documentation](https://vector.dev/docs/reference/configuration/sources/socket/#max_length) for the `max_length` configuration in the `socket` source:

> The maximum buffer size of incoming messages. Messages larger than this are truncated.

However, when the socket is in `tcp` mode, a larger message gets discarded, not truncated. In `udp` mode the behaviour is correct.

For example, consider the Vector configuration shown below, and start Vector:
```
$ vector -c vector.yaml
2022-02-22T15:51:38.899961Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
2022-02-22T15:51:38.900265Z  INFO vector::app: Loading configs. paths=["vector.yaml"]
2022-02-22T15:51:38.907676Z  INFO vector::topology::running: Running healthchecks.
2022-02-22T15:51:38.908138Z  INFO vector::topology::running: Starting source. key=socket
2022-02-22T15:51:38.908514Z  INFO vector::topology::running: Starting sink. key=sink0
2022-02-22T15:51:38.909878Z  INFO vector: Vector has started. debug="false" version="0.20.0" arch="x86_64" build_id="2a706a3 2022-02-11"
2022-02-22T15:51:38.910088Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
2022-02-22T15:51:38.914960Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-02-22T15:51:38.925094Z  INFO source{component_kind="source" component_id=socket component_type=socket component_name=socket}: vector::sources::util::tcp: Listening. addr=0.0.0.0:8080
```

Then, in another terminal, send a simple TCP message larger than 10 bytes using `socat`:
```
$ echo "hello world" | socat -u -dd stdin tcp-connect:localhost:8080
2022/02/22 15:51:41 socat[4504] N using stdin for reading
2022/02/22 15:51:41 socat[4504] N opening connection to AF=2 127.0.0.1:8080
2022/02/22 15:51:41 socat[4504] N successfully connected from local address AF=2 127.0.0.1:36892
2022/02/22 15:51:41 socat[4504] N starting data transfer loop with FDs [0,0] and [5,5]
2022/02/22 15:51:41 socat[4504] N socket 1 (fd 0) is at EOF
2022/02/22 15:51:41 socat[4504] N exiting with status 0
```

Now observe how Vector discarded the message instead of truncating as stated in the documentation:
```
2022-02-22T15:51:41.809346Z  WARN source{component_kind="source" component_id=socket component_type=socket component_name=socket}:connection{peer_addr=127.0.0.1:36892}: vector::codecs::decoding::framing::character_delimited: Discarding frame larger than max_length. buf_len=12 max_length=10 internal_log_rate_secs=30
```

As mentioned, in `udp` mode, the message does get truncated as documented:
```
2022-02-22T15:47:53.006849Z  INFO source{component_kind="source" component_id=socket component_type=socket component_name=socket}: vector::sources::socket::udp: Listening. address=0.0.0.0:8080
{"host":"127.0.0.1:51050","message":"hello worl","source_type":"socket","timestamp":"2022-02-22T15:47:59.297358700Z"}
```

### Configuration

```text
sources:
  socket:
    type: socket
    mode: tcp
    address: 0.0.0.0:8080
    max_length: 10

sinks:
  sink0:
    type: console
    inputs:
      - socket
    encoding: json
```

### Version

vector 0.20.0 (x86_64-unknown-linux-gnu 2a706a3 2022-02-11)

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by StephenWakely**
Closes #11512 

This discards udp frames that are greater than max_length in the socket source.

Due to the way [recv_from](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.recv_from) works, any data beyond the buffer size is automatically truncated. There is no indication if the data has been truncated in order for us to determine if the event should be dropped. To work around this this PR fetches `max_length + 1` bytes. If we actually fill all bytes we know that the data would have been truncated at  `max_length`. We can then know that we need to drop the event.

I would welcome any suggestions if there is a better way to approach this.

Signed-off-by: Stephen Wakely <fungus.humungus@gmail.com>

### CODE REVIEW

File: src/sources/socket/udp.rs [hunk 1]
```diff
@@ -121,37 +122,52 @@ pub fn udp(
...
-                                    }
+
+                                if last && truncated {
+                                    // The last event in this payload was truncated, so we want to drop it.
+                                    let _ = events.pop();
+                                    warn!(
+                                        message = "Discarding frame larger than max_length.",
+                                        max_length = max_length,
+                                        internal_log_rate_secs = 30
+                                    );
```
Comment (jszwedko) [inline src/sources/socket/udp.rs:141]: I think this should emit an internal event with the appropriate metrics per https://github.com/vectordotdev/vector/blob/master/docs/specs/component.md#error

File: src/sources/socket/udp.rs [hunk 2]
```diff
@@ -92,7 +92,7 @@ pub fn udp(
             .expect("Failed to bind to udp listener socket");
 
         if let Some(receive_buffer_bytes) = receive_buffer_bytes {
-            if let Err(error) = udp::set_receive_buffer_size(&socket, receive_buffer_bytes) {
+            if let Err(error) = udp::set_receive_buffer_size(&socket, receive_buffer_bytes + 1) {
```
Comment (jszwedko) [inline src/sources/socket/udp.rs:95]: I think this could be interpreted as a little misleading since the option is documented as:

> Configures the receive buffer size using the SO_RCVBUF option on the socket.

https://vector.dev/docs/reference/configuration/sources/vector/#receive_buffer_bytes

I don't think we need to modify this though? This configuration is for the entire receive buffer. I think we only need to add 1 when creating the buffer to receive into?

**Review by jszwedko — COMMENTED** [review]
Nice! I just left a few comments below.

**Review by jdrouet — APPROVED** [review]
besides the point mentioned by @jszwedko about the instrumentation, that looks good to me 👍

File: src/sources/socket/udp.rs (hunk 1 above)
Comment (StephenWakely) [reply src/sources/socket/udp.rs:141]: There are some problems with this.  The [TCP source](https://github.com/vectordotdev/vector/blob/master/lib/codecs/src/decoding/framing/character_delimited.rs#L95-L100) and probably others also doesn't emit an internal event.  So this remains consistent with that. 

It is not completely straightforward to change the TCP source to emit an internal event, since the decoding is in a separate library and the code for events are in the main Vector project - so this would involve some refactoring to enable this.

I think we should keep it like this and have an issue to sort out the events for everything in one go?

Comment (jszwedko) [reply src/sources/socket/udp.rs:141]: Aha, I didn't realize that. It seems like it was an oversight in #11124 then. 👍 to spinning it off into its own issue.

File: src/sources/socket/udp.rs [hunk 3]
```diff
@@ -121,37 +122,52 @@ pub fn udp(
...
+                                        internal_log_rate_secs = 30
+                                    );
                                 }
 
-                                tokio::select!{
-                                    result = out.send_batch(events) => {
-                                        if let Err(error) = result {
-                                            emit!(StreamClosedError { error, count });
-                                            return Ok(())
+                                if !events.is_empty() {
```
Comment (jszwedko) [inline src/sources/socket/udp.rs:144]: Not a big deal, but I might have done an "early return" pattern here to avoid nesting like:

```rust
if events.is_empty() {
  continue;
}
```

Just a suggestion for the future.

**Review by jszwedko — APPROVED** [review]
Looks good!

**Review by lukesteensen — APPROVED** [review]

**Review by jszwedko — CHANGES_REQUESTED** [review]
Just blocking the automerge until we resolve the metrics comment. Otherwise looks good though! Good work tracking the Windows issue down.

**Review by jszwedko — APPROVED** [review]
Forgot we already discussed metrics in https://github.com/vectordotdev/vector/pull/12023/files#r838734839 . We'll defer that as out of scope for this PR.
