### PR TITLE
fix(api): Update error metrics in vector top

### LINKED ISSUE #11960: errors not reported by `top`
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Event annotation errors are not being reported in the errors column of `vector top`

### Configuration

```text
[default agent config](https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/configmap.yaml#L58-L86)


    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      kubernetes_logs:
        type: kubernetes_logs
      host_metrics:
        filesystem:
          devices:
            excludes: [binfmt_misc]
          filesystems:
            excludes: [binfmt_misc]
          mountPoints:
            excludes: ["*/proc/sys/fs/binfmt_misc"]
        type: host_metrics
      internal_metrics:
        type: internal_metrics
    sinks:
      prom_exporter:
        type: prometheus_exporter
        inputs: [host_metrics, internal_metrics]
        address: 0.0.0.0:9090
      stdout:
        type: console
        inputs: [kubernetes_logs]
        encoding:
          codec: json
```

### Version

master@f64798723e460fed2ad490be375bd5747d3bd66f

### Debug Output

_No response_

### Example Data

Start your `minikube`, run `tilt up` to deploy your vector agent. Run a `flog` pod to create a bunch of logs

```bash
kubectl create deployment flog --image=mingrammer/flog -- flog -l
```

After waiting a bit to let the logs build up, delete `flog`

```bash
kubectl delete deployments.apps flog
```

After ~60 seconds the metadata will be deleted and errors will be visible in Vector's output, but running `top` will not show any errors for the source:

```bash
kubectl exec -it daemonset/vector -- vector top
```

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by 001wwang**
Closes #11960 

This PR properly subscribes to `ComponentErrorsTotals` and updates the metric in the `vector top` dashboard. This behavior was missing previously. 

Note that `ComponentErrorsTotals` provides, per component, a summation of metrics that end in `_errors_total`, not strictly just the `component_errors_total` metric.

### Testing

Borrowing Jesse's configuration from #11960:
```toml
data_dir = "/var/lib/vector/"

[api]
enabled = true
playground = true

[sources.source0]
type = "stdin"

[transforms.transform0]
inputs = ["source0"]
type = "remap"
source = ". = parse_json!(.message)"

[sinks.sink0]
inputs = ["transform0"]
print_interval_secs = 1
type = "blackhole"

[sinks.sink0.healthcheck]
enabled = true

[sinks.sink0.buffer]
type = "memory"
max_events = 500
when_full = "block"

[sources.metrics]
scrape_interval_secs = 2
type = "internal_metrics"

[sinks.prometheus]
inputs = ["metrics"]
address = "0.0.0.0:9598"
type = "prometheus"
```

You can run this configuration with bad input (i.e. invalid message for the `remap` transform)
```console
while true :; do echo "nah"; sleep 1; done | target/debug/vector -c {{the config path}}
```

Then, open `vector top`, and you'll see the `Errors` column of `transform0` steadily increase.

Screen Shot 2022-03-24 at 12 56 39 PM

### CODE REVIEW

File: lib/vector-api-client/src/test/mod.rs [hunk 1]
```diff
@@ -21,15 +21,6 @@ pub struct ComponentLinksQuery;
 )]
 pub struct ErrorsTotalSubscription;
 
-/// Component errors totals subscription
```
Comment (001wwang) [inline lib/vector-api-client/src/test/mod.rs:24]: By instinct, I moved the subscription and related code away from this `vector-api-client/src/test/` directory and into the usual `vector-api-client/src/gql` directory. I'm not clear on why this `vector-api-client/src/test/` directory exists, so do let me know if there's something I'm missing. cc: @leebenson

**Comment by hhromic** [comment]
> It'd be nice to have a rate for this like we do for events, but we can leave that as a follow-up.

I think, for errors, a rate does not make much sense. What you usually expect is that the number of errors remains at zero or doesn't constantly increase. It doesn't really matter how fast it increases.

I'm commenting this because the screen real state of `vector top` with the current layout is quite limited :)

**Review by spencergilbert — APPROVED** [review]
I'd probably also lean towards consistency and providing the rate at some point in the future 👍

File: lib/vector-api-client/src/test/mod.rs (hunk 1 above)
Comment (001wwang) [reply lib/vector-api-client/src/test/mod.rs:24]: With CI passing, I'll go ahead and merge this, but happy to change it up if needed.

Comment (leebenson) [reply lib/vector-api-client/src/test/mod.rs:24]: Post-merge comment for posterity: `test` was an attempt at distinguishing the domain of each query, so it was clearer which queries are part of the API surface, and which exist solely for integration tests.

It's not necessary to have this separation, since attributes drive compilation. It's fine either way 👍🏻
