### PR TITLE
fix(journald source): Fix handling of message array data

### LINKED ISSUE #1714: JSON Parse Errors in `journald` source JSON
While running the `journald` source I saw this error, along with several more:

```
Feb 05 10:37:20.199 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 121 text={"_CAP_EFFECTIVE":"3fffffffff","_COMM":"dockerd","PRIORITY":"6","CONTAINER_NAME":"condescending_chandrasekhar","MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,97,108,105,100,32,45,32,100,111,99,115,46,103,108,111,115,115,97,114,121,35,98,117,102,102,101,114,32,45,32,47,100,111,99,115,47,109,101,116,97,47,103,108,111,115,115,97,114,121,47,35,98,117,102,102,101,114,27,91,48,109,13],"_SOURCE_REALTIME_TIMESTAMP":"1580926120442151","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","_SYSTEMD_SLICE":"system.slice","_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","__REALTIME_TIMESTAMP":"1580926120442157","_UID":"0","SYSLOG_IDENTIFIER":"8ebe7b24a555","_HOSTNAME":"obsidian","CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","_SYSTEMD_UNIT":"docker.service","_PID":"1550","CONTAINER_TAG":"8ebe7b24a555","IMAGE_NAME":"timberiodev/vector-checker:latest","_TRANSPORT":"journal","_GID":"0","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd","_SYSTEMD_CGROUP":"/system.slice/docker.service","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbba;b=ec4d5b8401af429caeae51f32477c916;m=b7208c7a;t=59dd80bd3392d;x=8d056e4616c9a4bd","__MONOTONIC_TIMESTAMP":"3072363642","CONTAINER_ID":"8ebe7b24a555"}
```

This looks like a Serde error at around `"MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,9...`.

I tried having the `file` source take in this JSON then parsed it with `json_parser` just fine.

This seems to be specific to the **Nvidia-docker** runtime. https://github.com/NVIDIA/nvidia-docker

##

Other errors:

```
Feb 05 10:37:20.198 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 402 text={"_COMM":"dockerd","PRIORITY":"6","_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","_CAP_EFFECTIVE":"3fffffffff","IMAGE_NAME":"timberiodev/vector-checker:latest","__MONOTONIC_TIMESTAMP":"3072341730","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbb3;b=ec4d5b8401af429caeae51f32477c916;m=b72036e2;t=59dd80bd2e395;x=5a2779f5a77c268b","MESSAGE":[32,32,32,32,32,121,13],"CONTAINER_TAG":"8ebe7b24a555","_PID":"1550","_SYSTEMD_UNIT":"docker.service","_HOSTNAME":"obsidian","_SYSTEMD_SLICE":"system.slice","SYSLOG_IDENTIFIER":"8ebe7b24a555","_UID":"0","_SOURCE_REALTIME_TIMESTAMP":"1580926120420237","CONTAINER_NAME":"condescending_chandrasekhar","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd","_SYSTEMD_CGROUP":"/system.slice/docker.service","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","_GID":"0","CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","_TRANSPORT":"journal","__REALTIME_TIMESTAMP":"1580926120420245","CONTAINER_ID":"8ebe7b24a555"}

Feb 05 10:37:20.198 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 246 text={"_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd","CONTAINER_TAG":"8ebe7b24a555","_TRANSPORT":"journal","_CAP_EFFECTIVE":"3fffffffff","MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,97,108,105,100,32,45,32,100,111,99,115,46,100,97,116,97,45,109,111,100,101,108,32,45,32,47,100,111,99,115,47,97,98,111,117,116,47,100,97,116,97,45,109,111,100,101,108,47,27,91,48,109,13],"_SYSTEMD_SLICE":"system.slice","CONTAINER_ID":"8ebe7b24a555","IMAGE_NAME":"timberiodev/vector-checker:latest","__MONOTONIC_TIMESTAMP":"3072347037","SYSLOG_IDENTIFIER":"8ebe7b24a555","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","_GID":"0","CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","PRIORITY":"6","_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","_UID":"0","_SOURCE_REALTIME_TIMESTAMP":"1580926120425510","_HOSTNAME":"obsidian","_SYSTEMD_CGROUP":"/system.slice/docker.service","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbb4;b=ec4d5b8401af429caeae51f32477c916;m=b7204b9d;t=59dd80bd2f850;x=cfb7a6963cac3370","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","CONTAINER_NAME":"condescending_chandrasekhar","__REALTIME_TIMESTAMP":"1580926120425552","_PID":"1550","_COMM":"dockerd","_SYSTEMD_UNIT":"docker.service"}

Feb 05 10:37:20.198 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 11 text={"MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,97,108,105,100,32,45,32,100,111,99,115,46,105,110,115,116,97,108,108,97,116,105,111,110,46,111,112,101,114,97,116,105,110,103,95,115,121,115,116,101,109,115,46,97,109,97,122,111,110,45,108,105,110,117,120,32,45,32,47,100,111,99,115,47,115,101,116,117,112,47,105,110,115,116,97,108,108,97,116,105,111,110,47,111,112,101,114,97,116,105,110,103,45,115,121,115,116,101,109,115,47,97,109,97,122,111,110,45,108,105,110,117,120,47,27,91,48,109,13],"_GID":"0","CONTAINER_ID":"8ebe7b24a555","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","_COMM":"dockerd","CONTAINER_NAME":"condescending_chandrasekhar","_SYSTEMD_SLICE":"system.slice","__REALTIME_TIMESTAMP":"1580926120427802","_UID":"0","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","IMAGE_NAME":"timberiodev/vector-checker:latest","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbb5;b=ec4d5b8401af429caeae51f32477c916;m=b7205467;t=59dd80bd3011a;x=6973aecc88d7a0e8","CONTAINER_TAG":"8ebe7b24a555","_SYSTEMD_CGROUP":"/system.slice/docker.service","PRIORITY":"6","_SYSTEMD_UNIT":"docker.service","__MONOTONIC_TIMESTAMP":"3072349287","_SOURCE_REALTIME_TIMESTAMP":"1580926120427796","CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd","_CAP_EFFECTIVE":"3fffffffff","_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","_PID":"1550","_TRANSPORT":"journal","SYSLOG_IDENTIFIER":"8ebe7b24a555","_HOSTNAME":"obsidian"}

Feb 05 10:37:20.198 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 461 text={"_CAP_EFFECTIVE":"3fffffffff","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","_SYSTEMD_CGROUP":"/system.slice/docker.service","_COMM":"dockerd","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd","_SOURCE_REALTIME_TIMESTAMP":"1580926120427804","CONTAINER_NAME":"condescending_chandrasekhar","_HOSTNAME":"obsidian","_PID":"1550","CONTAINER_TAG":"8ebe7b24a555","_TRANSPORT":"journal","CONTAINER_ID":"8ebe7b24a555","MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,97,108,105,100,32,45,32,100,111,99,115,46,105,110,115,116,97,108,108,97,116,105,111,110,46,111,112,101,114,97,116,105,110,103,95,115,121,115,116,101,109,115,46,99,101,110,116,111,115,32,45,32,47,100,111,99,115,47,115,101,116,117,112,47,105,110,115,116,97,108,108,97,116,105,111,110,47,111,112,101,114,97,116,105,110,103,45,115,121,115,116,101,109,115,47,99,101,110,116,111,115,47,27,91,48,109,13],"IMAGE_NAME":"timberiodev/vector-checker:latest","_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","_GID":"0","_UID":"0","CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","PRIORITY":"6","SYSLOG_IDENTIFIER":"8ebe7b24a555","_SYSTEMD_SLICE":"system.slice","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbb6;b=ec4d5b8401af429caeae51f32477c916;m=b72054a5;t=59dd80bd30158;x=dcc2315a6d35192","_SYSTEMD_UNIT":"docker.service","__MONOTONIC_TIMESTAMP":"3072349349","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","__REALTIME_TIMESTAMP":"1580926120427864"}

Feb 05 10:37:20.198 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 614 text={"_TRANSPORT":"journal","_UID":"0","_SYSTEMD_CGROUP":"/system.slice/docker.service","_SYSTEMD_SLICE":"system.slice","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","_COMM":"dockerd","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbb7;b=ec4d5b8401af429caeae51f32477c916;m=b72057dc;t=59dd80bd3048f;x=262a1173db49309c","_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,97,108,105,100,32,45,32,100,111,99,115,46,100,101,112,108,111,121,109,101,110,116,46,116,111,112,111,108,111,103,105,101,115,32,45,32,47,100,111,99,115,47,115,101,116,117,112,47,100,101,112,108,111,121,109,101,110,116,47,116,111,112,111,108,111,103,105,101,115,47,27,91,48,109,13],"PRIORITY":"6","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","_SYSTEMD_UNIT":"docker.service","SYSLOG_IDENTIFIER":"8ebe7b24a555","CONTAINER_NAME":"condescending_chandrasekhar","_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","_PID":"1550","__REALTIME_TIMESTAMP":"1580926120428687","_HOSTNAME":"obsidian","_SOURCE_REALTIME_TIMESTAMP":"1580926120428682","_CAP_EFFECTIVE":"3fffffffff","_GID":"0","CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","CONTAINER_ID":"8ebe7b24a555","__MONOTONIC_TIMESTAMP":"3072350172","CONTAINER_TAG":"8ebe7b24a555","IMAGE_NAME":"timberiodev/vector-checker:latest"}

Feb 05 10:37:20.198 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 22 text={"_GID":"0","MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,97,108,105,100,32,45,32,100,111,99,115,46,105,110,115,116,97,108,108,97,116,105,111,110,46,111,112,101,114,97,116,105,110,103,95,115,121,115,116,101,109,115,46,109,97,99,111,115,32,45,32,47,100,111,99,115,47,115,101,116,117,112,47,105,110,115,116,97,108,108,97,116,105,111,110,47,111,112,101,114,97,116,105,110,103,45,115,121,115,116,101,109,115,47,109,97,99,111,115,47,27,91,48,109,13],"CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","SYSLOG_IDENTIFIER":"8ebe7b24a555","_SYSTEMD_CGROUP":"/system.slice/docker.service","_HOSTNAME":"obsidian","_SOURCE_REALTIME_TIMESTAMP":"1580926120441500","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","_UID":"0","CONTAINER_TAG":"8ebe7b24a555","_SYSTEMD_UNIT":"docker.service","PRIORITY":"6","CONTAINER_ID":"8ebe7b24a555","_SYSTEMD_SLICE":"system.slice","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","_TRANSPORT":"journal","_CAP_EFFECTIVE":"3fffffffff","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd","CONTAINER_NAME":"condescending_chandrasekhar","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbb8;b=ec4d5b8401af429caeae51f32477c916;m=b7208a0d;t=59dd80bd336c0;x=b5419f44a48e616e","IMAGE_NAME":"timberiodev/vector-checker:latest","_COMM":"dockerd","__MONOTONIC_TIMESTAMP":"3072363021","_PID":"1550","_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","__REALTIME_TIMESTAMP":"1580926120441536"}

Feb 05 10:37:20.198 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 746 text={"PRIORITY":"6","_PID":"1550","CONTAINER_TAG":"8ebe7b24a555","_UID":"0","_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","CONTAINER_ID":"8ebe7b24a555","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd","_HOSTNAME":"obsidian","_COMM":"dockerd","_SYSTEMD_SLICE":"system.slice","_GID":"0","IMAGE_NAME":"timberiodev/vector-checker:latest","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,97,108,105,100,32,45,32,100,111,99,115,46,100,101,112,108,111,121,109,101,110,116,46,114,111,108,101,115,32,45,32,47,100,111,99,115,47,115,101,116,117,112,47,100,101,112,108,111,121,109,101,110,116,47,114,111,108,101,115,47,27,91,48,109,13],"CONTAINER_NAME":"condescending_chandrasekhar","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbb9;b=ec4d5b8401af429caeae51f32477c916;m=b7208ac8;t=59dd80bd3377b;x=2bcd16562723f014","_SYSTEMD_UNIT":"docker.service","_SYSTEMD_CGROUP":"/system.slice/docker.service","_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","SYSLOG_IDENTIFIER":"8ebe7b24a555","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","_SOURCE_REALTIME_TIMESTAMP":"1580926120441719","__REALTIME_TIMESTAMP":"1580926120441723","_CAP_EFFECTIVE":"3fffffffff","__MONOTONIC_TIMESTAMP":"3072363208","_TRANSPORT":"journal"}

Feb 05 10:37:20.199 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 121 text={"_CAP_EFFECTIVE":"3fffffffff","_COMM":"dockerd","PRIORITY":"6","CONTAINER_NAME":"condescending_chandrasekhar","MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,97,108,105,100,32,45,32,100,111,99,115,46,103,108,111,115,115,97,114,121,35,98,117,102,102,101,114,32,45,32,47,100,111,99,115,47,109,101,116,97,47,103,108,111,115,115,97,114,121,47,35,98,117,102,102,101,114,27,91,48,109,13],"_SOURCE_REALTIME_TIMESTAMP":"1580926120442151","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","_SYSTEMD_SLICE":"system.slice","_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","__REALTIME_TIMESTAMP":"1580926120442157","_UID":"0","SYSLOG_IDENTIFIER":"8ebe7b24a555","_HOSTNAME":"obsidian","CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","_SYSTEMD_UNIT":"docker.service","_PID":"1550","CONTAINER_TAG":"8ebe7b24a555","IMAGE_NAME":"timberiodev/vector-checker:latest","_TRANSPORT":"journal","_GID":"0","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd","_SYSTEMD_CGROUP":"/system.slice/docker.service","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbba;b=ec4d5b8401af429caeae51f32477c916;m=b7208c7a;t=59dd80bd3392d;x=8d056e4616c9a4bd","__MONOTONIC_TIMESTAMP":"3072363642","CONTAINER_ID":"8ebe7b24a555"}

Feb 05 10:37:20.199 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 456 text={"_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","__MONOTONIC_TIMESTAMP":"3072363709","_UID":"0","_SYSTEMD_SLICE":"system.slice","__REALTIME_TIMESTAMP":"1580926120442225","MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,97,108,105,100,32,45,32,100,111,99,115,46,105,110,115,116,97,108,108,97,116,105,111,110,46,111,112,101,114,97,116,105,110,103,95,115,121,115,116,101,109,115,46,117,98,117,110,116,117,32,45,32,47,100,111,99,115,47,115,101,116,117,112,47,105,110,115,116,97,108,108,97,116,105,111,110,47,111,112,101,114,97,116,105,110,103,45,115,121,115,116,101,109,115,47,117,98,117,110,116,117,47,27,91,48,109,13],"_GID":"0","_TRANSPORT":"journal","IMAGE_NAME":"timberiodev/vector-checker:latest","_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","_COMM":"dockerd","CONTAINER_NAME":"condescending_chandrasekhar","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbbb;b=ec4d5b8401af429caeae51f32477c916;m=b7208cbd;t=59dd80bd33971;x=3b2b18c75e785677","CONTAINER_ID":"8ebe7b24a555","_SYSTEMD_UNIT":"docker.service","PRIORITY":"6","_SOURCE_REALTIME_TIMESTAMP":"1580926120442220","_HOSTNAME":"obsidian","_SYSTEMD_CGROUP":"/system.slice/docker.service","CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","_PID":"1550","CONTAINER_TAG":"8ebe7b24a555","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","_CAP_EFFECTIVE":"3fffffffff","SYSLOG_IDENTIFIER":"8ebe7b24a555","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd"}

Feb 05 10:37:20.240 ERROR source{name=input type=journald}:journald-server{}: vector::sources::journald: Invalid record from journald, discarding error=invalid type: sequence, expected a string at line 1 column 434 text={"SYSLOG_IDENTIFIER":"8ebe7b24a555","_EXE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd","_MACHINE_ID":"df0fb2db7347478da7b7f3a55a4f5b5d","_UID":"0","IMAGE_NAME":"timberiodev/vector-checker:latest","CONTAINER_ID":"8ebe7b24a555","_BOOT_ID":"ec4d5b8401af429caeae51f32477c916","_SOURCE_REALTIME_TIMESTAMP":"1580926120442227","CONTAINER_TAG":"8ebe7b24a555","_SYSTEMD_UNIT":"docker.service","MESSAGE":[27,91,51,50,109,45,45,45,62,32,86,97,108,105,100,32,45,32,100,111,99,115,46,105,110,115,116,97,108,108,97,116,105,111,110,46,111,112,101,114,97,116,105,110,103,95,115,121,115,116,101,109,115,46,114,97,115,112,98,105,97,110,32,45,32,47,100,111,99,115,47,115,101,116,117,112,47,105,110,115,116,97,108,108,97,116,105,111,110,47,111,112,101,114,97,116,105,110,103,45,115,121,115,116,101,109,115,47,114,97,115,112,98,105,97,110,47,27,91,48,109,13],"_CAP_EFFECTIVE":"3fffffffff","_PID":"1550","_SYSTEMD_INVOCATION_ID":"3dcf8cc63e604db49e33813d9aaa19d0","_COMM":"dockerd","__MONOTONIC_TIMESTAMP":"3072363751","CONTAINER_NAME":"condescending_chandrasekhar","PRIORITY":"6","__CURSOR":"s=9a9e910b180c45e69f11aedc1676e14c;i=dbbc;b=ec4d5b8401af429caeae51f32477c916;m=b7208ce7;t=59dd80bd3399a;x=75ce6fc67f1a5e6f","_SYSTEMD_CGROUP":"/system.slice/docker.service","_SYSTEMD_SLICE":"system.slice","_CMDLINE":"/nix/store/z1ia4bbp8gfplmfmasmhcgvkjn31qbyf-docker-19.03.5/libexec/docker/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore --add-runtime nvidia=/nix/store/4vcizxp2x3wk3ibsb3a3a5sraw3k95yq-nvidia-docker-2.0.3/bin/nvidia-container-runtime","CONTAINER_ID_FULL":"8ebe7b24a5551a06c6202256d1eefaeca1dc55a7f8984b52ea20ddc2947a84fd","__REALTIME_TIMESTAMP":"1580926120442266","_TRANSPORT":"journal","_HOSTNAME":"obsidian","_GID":"0"}
```

## Config

I was testing #1521 at the time with the following config:

```
data_dir = "./tmp/data"

[sources.input]
   type = "journald" # must be: "journald"

[sinks.logdna]
type = "logdna"
inputs = ["input"]
api_key = "newp sorry not here"
hostname = "ana-banana"
```

### PR DESCRIPTION
**Pull request by bruceg**
Closes #1714

### CODE REVIEW

**Review by binarylogic — APPROVED** [review]
Docs look great!

File: src/sources/journald.rs [hunk 1]
```diff
@@ -325,6 +322,35 @@ where
...
+fn decode_record(text: &str) -> Result<Record, JsonError> {
+    let mut record = serde_json::from_str::<JsonValue>(&text)?;
+    // journalctl will output non-ASCII messages using an array
+    // of integers. Look for those messages and re-parse them.
+    record.get_mut("MESSAGE").and_then(|message| {
+        message
+            .as_array()
+            .and_then(decode_array)
+            .map(|decoded| *message = decoded)
+    });
```
Comment (Hoverbear) [inline src/sources/journald.rs]:
```suggestion
    }).ok(); // Intentionally ignored error.
```

**Review by Hoverbear — APPROVED** [review]
