### PR TITLE
fix(journald source): Handle missing source timestamp

### LINKED ISSUE #2384: journald source missing timestamp if journal entry missing _SOURCE_REALTIME_TIMESTAMP
The `journald` source uses the timestamp from the `_SOURCE_REALTIME_TIMESTAMP` field by default.  That field is not always present. I *think* `_SOURCE_REALTIME_TIMESTAMP` depends on the `_TRANSPORT` field. In my repro, entries where `_TRANSPORT=stdout` do not have the timestamp.  Entries where `TRANSPORT=journal` do have the timestamp.

I think Vector should first try to use the `_SOURCE_REALTIME_TIMESTAMP`. If that field is missing, Vector should fallback to `__REALTIME_TIMESTAMP`.  The man page (http://manpages.ubuntu.com/manpages/bionic/man7/systemd.journal-fields.7.html) defines the fields as follows: 

> - `_SOURCE_REALTIME_TIMESTAMP` - The earliest trusted timestamp of the message, if any is known that is different from the reception time of the journal. This is the time in microseconds since the epoch UTC, formatted as a decimal string.
>
> - `__REALTIME_TIMESTAMP` - The wallclock time (CLOCK_REALTIME) at the point in time the entry was received by the journal, in microseconds since the epoch UTC, formatted as a decimal string. This has different properties from "_SOURCE_REALTIME_TIMESTAMP=", as it is usually a bit later but more likely to be monotonic.

## Repro

I ran a bash script under Systemd that printed a timestamp to stdout every second.  Below is an entry reported by journalctl and corresponding log line captured by vector.  The vector log line does not have a `timestamp` field.

### Entry from journalctl

```
sudo journalctl -u test-vector -o json-pretty --no-pager | head -120
```

```json
{
  "MESSAGE" : "test vector: TIME: 2020-04-21T16:39:50,001877814+00:00",
  "PRIORITY" : "6",
  "SYSLOG_FACILITY" : "3",
  "SYSLOG_IDENTIFIER" : "test-vector.sh",
  "_AUDIT_SESSION" : "65653",
  "_CMDLINE" : "bash /tmp/vector-out/test-vector.sh",
  "_COMM" : "bash",
  "_EXE" : "/bin/bash",
  "_STREAM_ID" : "6f869ba7d66e4fbdaa0b0c5a5a0030f4",
  "_SYSTEMD_UNIT" : "test-vector.service",
  "_TRANSPORT" : "stdout",
  "__MONOTONIC_TIMESTAMP" : "6371453461339",
  "__REALTIME_TIMESTAMP" : "1587487190002130",
}
```
### Corresponding log line from vector (same _STREAM_ID)

```json
{
  "PRIORITY": "6",
  "SYSLOG_FACILITY": "3",
  "SYSLOG_IDENTIFIER": "test-vector.sh",
  "_CMDLINE": "bash /tmp/vector-out/test-vector.sh",
  "_COMM": "bash",
  "_EXE": "/bin/bash",
  "_STREAM_ID": "6f869ba7d66e4fbdaa0b0c5a5a0030f4",
  "_SYSTEMD_UNIT": "test-vector.service",
  "_TRANSPORT": "stdout",
  "_UID": "0",
  "__MONOTONIC_TIMESTAMP": "6371453461339",
  "__REALTIME_TIMESTAMP": "1587487190002130",
  "message": "test vector: TIME: 2020-04-21T16:39:50,001877814+00:00",
  "source_type": "journald"
}
```

The `__REALTIME_TIMESTAMP` is:

    Tuesday, April 21, 2020 4:39:50.002 UTC

### /etc/vector /test-vector.service

```systemd
[Unit]
Description=Test vector

[Service]
ExecStart=/tmp/vector-out/test-vector.sh

[Install]
WantedBy=multi-user.target
```

### /tmp/vector-out/test-vector.sh

```bash
#!/usr/bin/env bash

set -euo pipefail

for i in $(seq 100); do
  echo "test vector: TIME: $(date --iso-8601=ns)"
  sleep 1
done
```

### /etc/vector/test.toml

```toml
data_dir = "/var/lib/vector"

[sources.journald_raw_src]
  type = "journald"
  current_boot_only = true
  units = ["test-vector"]

[sinks.journald_raw_sink]
  type = "file"
  inputs = ["journald_raw_src"]
  path = "/tmp/vector-out/raw-journald.log"
  encoding.codec = "ndjson"
```

### PR DESCRIPTION
**Pull request by bruceg**
If a source does not give journald a timestamp, the resulting record
will be missing the `_SOURCE_REALTIME_TIMESTAMP` field that this source
relies on. This patch adds a fallback to `__REALTIME_TIMESTAMP` if the
above is not available, which is always present.

Closes #2384 

Signed-off-by: Bruce Guenter <bruce@timber.io>

### CODE REVIEW

File: src/sources/journald.rs [hunk 1]
```diff
@@ -163,7 +164,7 @@ fn create_event(record: Record) -> Event {
         log.insert(event::log_schema().host_key().clone(), host);
     }
     // Translate the timestamp, and so leave both old and new names.
-    if let Some(timestamp) = log.get(&TIMESTAMP) {
+    if let Some(timestamp) = log.get(&SOURCE_TIMESTAMP).or(log.get(&RECEIVED_TIMESTAMP)) {
```
Comment (ktff) [inline src/sources/journald.rs:167]: We could use `or_else` here and avoid the extra `log.get`.

**Review by ktff — APPROVED** [review]
LGTM, although that `or_else` would be nice to add.
