### PR TITLE
fix(stdin source): Resolve inability to shutdown Vector when std…

### LINKED ISSUE #932: Update `stdin` source to use a thread instead of using the tokio version
Related to #546 and a bug in tokio where blocking annotations can not be shutdown via a drop in the task. This causes `stdin` sources to hang when a user attempts to shut it down.

# Specification

Update the `stdin` source to use a similar strategy to what the `file` source uses by spawning a thread and using [`stdin`](https://doc.rust-lang.org/beta/std/io/fn.stdin.html) directly. Then using the `out` channel passed into the `SourceConfig::build` fn to send events back into the topology. This will stop the `stdin` source from blocking shutdown.

To send events down the out channel you should use https://docs.rs/futures/0.1.29/futures/sync/mpsc/struct.Sender.html#method.try_send to send the event. 

To fetch lines off of `stdin`, https://doc.rust-lang.org/std/io/struct.Stdin.html#method.read_line should be used. Once, there is a `String` this should be converted into an `Event` as seen [here](https://github.com/timberio/vector/blob/master/src/sources/stdin.rs#L74).

### PR DESCRIPTION
**Pull request by AlyHKafoury**
Closes https://github.com/timberio/vector/issues/932

Signed-off-by: AlyHKafoury <aly.kafoury@gmail.com>

### CODE REVIEW

**Comment by LucioFranco** [comment]
@AlyHKafoury thank you for this! I will give it a proper review tomorrow/later this week!

**Comment by AlyHKafoury** [comment]
> @AlyHKafoury thank you for this! I will give it a proper review tomorrow/later this week!

Thanks alot I really like the project and hope to be able to contribute alot to it.

File: src/sources/stdin.rs [hunk 1]
```diff
@@ -40,32 +36,58 @@ impl SourceConfig for StdinConfig {
...
-            BytesDelimitedCodec::new_with_max_length(b'\n', config.max_length),
-        )
-        .map(move |line| create_event(line, &host_key, &hostname))
-        .map_err(|e| error!("error reading line: {:?}", e))
-        .forward(out.sink_map_err(|e| error!("Error sending in sink {}", e)))
-        .map(|_| info!("finished sending"));
+        let (mut tx, rx) = futures::sync::mpsc::channel(1024);
+
+        thread::spawn(move || {
+            println!("Loaded thread");
```
Comment (LucioFranco) [inline src/sources/stdin.rs]: I don't think this println is no longer needed?

File: src/sources/stdin.rs [hunk 2]
```diff
@@ -40,32 +36,58 @@ impl SourceConfig for StdinConfig {
...
+            loop {
+                let mut buf = String::new();
+                match stdin.read_line(&mut buf) {
+                    Err(e) => {
+                        error!("Error reading from source: stdin: {}", e);
```
Comment (LucioFranco) [inline src/sources/stdin.rs]: Since we are using the `tracing` crate for logging this is the preferred way to setup printing errors.
```suggestion
                        error!(message = "Unable to read from source.", error = %e);
```

File: src/sources/stdin.rs [hunk 3]
```diff
@@ -40,32 +36,58 @@ impl SourceConfig for StdinConfig {
...
+                    Ok(0) => {
+                        break;
+                    }
+                    _ => (),
+                }
+                while let Err(e) = tx.try_send(buf.clone()) {
+                    if e.is_full() {
+                        continue;
+                    }
+                    error!("Error sending : {}", e);
```
Comment (LucioFranco) [inline src/sources/stdin.rs]:
```suggestion
					error!(message = "Unable to send event.", error = %e);
```

File: src/sources/stdin.rs [hunk 4]
```diff
@@ -40,32 +36,58 @@ impl SourceConfig for StdinConfig {
...
+                    break;
+                }
+            }
+        });
+
+        let source = rx
+            .map(move |line| create_event(Bytes::from(line.trim()), &host_key, &hostname))
+            .map_err(|e| error!("error reading line: {:?}", e))
+            .forward(out.sink_map_err(|e| error!("Error sending in sink {}", e)))
```
Comment (LucioFranco) [inline src/sources/stdin.rs]:
```suggestion
            .forward(out.sink_map_err(|e| error!(message = "Unable to send event to out.", error = %e)))
```

File: src/sources/stdin.rs [hunk 5]
```diff
@@ -40,32 +36,58 @@ impl SourceConfig for StdinConfig {
...
-        .map(move |line| create_event(line, &host_key, &hostname))
-        .map_err(|e| error!("error reading line: {:?}", e))
-        .forward(out.sink_map_err(|e| error!("Error sending in sink {}", e)))
-        .map(|_| info!("finished sending"));
+        let (mut tx, rx) = futures::sync::mpsc::channel(1024);
+
+        thread::spawn(move || {
+            println!("Loaded thread");
+            loop {
+                let mut buf = String::new();
```
Comment (LucioFranco) [inline src/sources/stdin.rs]: I wonder if we can reuse this buf instead of allocating a new one each iteration. Another idea also is to use `bytes::BytesMut` and `BytesMut::freeze` once we've collected the whole event and want to send it.

**Review by LucioFranco — CHANGES_REQUESTED** [review]
This looks like a really awesome start! Let me know if you have any questions, I left some comments inline.

**Comment by AlyHKafoury** [comment]
@LucioFranco  Great, I'll be working on these changes in a couple of days and get back to you

**Comment by AlyHKafoury** [comment]
@LucioFranco won't reusing the buffer cause us to need to clear it in each iteration, I don't know the performance of that compared to re allocating, I working on that though and please enlighten me about this part

File: src/sources/stdin.rs [hunk 6]
```diff
@@ -40,32 +36,60 @@ impl SourceConfig for StdinConfig {
...
-            BytesDelimitedCodec::new_with_max_length(b'\n', config.max_length),
-        )
-        .map(move |line| create_event(line, &host_key, &hostname))
-        .map_err(|e| error!("error reading line: {:?}", e))
-        .forward(out.sink_map_err(|e| error!("Error sending in sink {}", e)))
-        .map(|_| info!("finished sending"));
+        let (mut tx, rx) = futures::sync::mpsc::channel(1024);
+
+        thread::spawn(move || {
+            let mut buf = Box::new(BytesMut::new());
```
Comment (LucioFranco) [inline src/sources/stdin.rs]: Not sure we need to box here?

Comment (LucioFranco) [reply src/sources/stdin.rs]: So we actually don't need a buffer because internally `lines()` does that. What we will want to do is use the `Bytes::from(<string>)` function to go from string -> bytes that we can send down the channel. Hopefully that makes sense :)

Comment (AlyHKafoury) [reply src/sources/stdin.rs]: Yes sure I am currently working on it

File: src/sources/stdin.rs [hunk 7]
```diff
@@ -60,26 +60,23 @@ where
...
                         error!(message = "Unable to read from source.", error = %e);
                         break;
                     }
                     Ok(string_data) => {
-                        &mut buf.extend_from_slice(string_data.as_bytes());
-                        ()
+                        let msg = Bytes::from(string_data);
+                        while let Err(e) = tx.try_send(msg.clone()) {
+                            if e.is_full() {
+                                continue;
```
Comment (LucioFranco) [inline src/sources/stdin.rs]: a sleep here might be good

**Review by LucioFranco — APPROVED** [review]
Thanks for this!
