### PR TITLE
fix(host_metrics source): Fix handling parsing Linux hybrid cgroups

### LINKED ISSUE #11251: Collector "host_metrics" looking at wrong place and not seeing the SUSE host metirc.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

elksuse:~ # vector --version
vector 0.19.1 (x86_64-unknown-linux-gnu 3cf70cf 2022-01-25)
...
```

### Vector Configuration File

<!--
Paste the relevant parts of your `vector.toml` configuration between the ``` marks below.

!! If your config files contain sensitive information please remove it !!
-->

```toml
[api]
enabled = true

[sources.suse_metrics]
type = "host_metrics"
collectors = [ "cgroups", "cpu", "disk", "filesystem", "load", "host", "memory", "network" ]
scrape_interval_secs = 15

[sinks.es_cluster]
#inputs = ["suse_logs"]
inputs = ["suse_metrics"]
type = "elasticsearch"
#index = "vector-%Y-%m-%d"
endpoint = "https://URL"

auth.user = "elastic"
auth.password = "************"
auth.strategy = "basic"
mode = "bulk"
pipeline = "vector-elk"

...
```

### PR DESCRIPTION
**Pull request by bruceg**
With hybrid cgroups, the `cpu` and `memory` controllers are split
between the base directory (containing the legacy controllers) and the
`unified` subdirectory (containing the modern groups). The `cpu`
controller is usually found in the modern groups, but the top-level
stats are found under the legacy controller in some setups. Similarly,
the `memory` controller can be found in either location.

As such, while autodetecting what mode cgroups are running in (legacy,
hybrid, or modern) is straightforward, detecting if certain controllers
are in use is more complicated. So, this rewrites the cgroup metrics
parsing to recurse into all of the relevant directories, scan for the
cpu and memory data files, and emit metrics for any that are found. This
unfortunately prevents us from emitting the warning about the memory
controller not being enabled, but does give coverage for actually
emitting the metrics for any memory controller configuration.

This should close #11251

### CODE REVIEW

File: src/sources/host_metrics/cgroups.rs [hunk 1]
```diff
@@ -364,15 +442,11 @@ define_stat_struct! { MemoryStat(
 )}
 
 fn is_dir(path: impl AsRef<Path>) -> bool {
-    std::fs::metadata(path.as_ref())
-        .map(|metadata| metadata.is_dir())
-        .unwrap_or(false)
+    std::fs::metadata(path.as_ref()).map_or(false, |metadata| metadata.is_dir())
```
Comment (spencergilbert) [inline src/sources/host_metrics/cgroups.rs:445]: Any particular reason we're not `use`ing here, rather than qualifying?

**Review by spencergilbert — APPROVED** [review]
LGTM, just dinged on checks

**Review by jszwedko — APPROVED** [review]
Nice work on the added tests!

**Review by jdrouet — APPROVED** [review]
LGTM

File: src/sources/host_metrics/cgroups.rs (hunk 1 above)
Comment (bruceg) [reply src/sources/host_metrics/cgroups.rs:444]: Pretty much that it's just used once AFAICR.
