### PR TITLE
fix(axiom sink): Rebase sink on `http` sink and remove `elasticsearch` compatibility

### LINKED ISSUE #21292: Rework the Vector Axiom Sink to use Axiom's ingest endpoint instead of the ElasticSearch _bulk endpoint
### A note for the community

Our vector users are reporting issues with vector axiom sinks that we believe can be avoided
by changing the axiom sink to use the native axiom ingest endpoint instead of the emulated
elasticsearch _bulk endpoint.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Primary reason is to avoid confusion of vector users configuring the axiom sink:
* The behaviour of `_timestamp` differs across elasticsearch and opensearch versions and has
  resulted in changes to the axiom sink to hardcode a solution ( cause was changes to elastics own behaviour itself! )
* Experienced axiom users assume the vector sink to be an axiom ingest based sink.
  + Configuration of query parameters and http headers from this endpoint does not work on
     our elastic _bulk compatible endpoint ( nor should they work on any elastic _bulk compatible endpoint )

### Attempted Solutions

We propose to rework the sink to use the axiom ingest endpoint which will avoid all the above
points of confusion and simplify configuration for our vector users.

### Proposal

We propose that we at Axiom contribute the work and contribute to any future maintenance
as may be needed from time to time. We basically avoid needing ES compatibility for the vector
axiom sink

### References

Useful references

* https://axiom.co/docs/process-data/destinations/elastic-bulk
* https://axiom.co/docs/send-data/ingest
* https://github.com/vectordotdev/vector/issues/12882

One primary source of confusion around `_timestamp` and `@timestamp`. The confusion here is I believe
a result of changes to default behaviour in elasticsearch circa v5.5 on `_timestamp` handling that in turn
cascade to vector's elasticsearch sink, and reached the vector axiom sink in the below PR.

* https://github.com/vectordotdev/vector/pull/16536 

Some documentation impact expected:
* https://axiom.co/docs/send-data/vector#timestamp-field
* The ES compatibility constraint would be lifted/replaced with compatibility on `_time` semantics for axiom.
* However, we would need a migration note for existing users if this proposal is acceptable

TL;DR I think we can avoid all future confusion at least for the vector axiom sink by migrating it to use the ingest endpoint. This in turn reduces maintenance overheads on the elasticsearch endpoint if/when there are changes to elasticsearch as it won't affect the axiom sink once we decouple the sinks so that they can evolve independently

Useful people at Axiom happy to contribute: @darach @Licenser @bahlo 

### Version

v0.41.1

### PR DESCRIPTION
**Pull request by darach**
Fixes #21292

The `axiom` sink has been rebased from `elasticsearch` to `http` per the issue.
Deprecated headers removed in favor of aligning with the `http` `request` configuration
scope, and the `compression` configuration now defaults to `gzip`.

The sink now conforms to Axiom's native ingest API:

  https://axiom.co/docs/send-data/ingest#ingest-api

The `_time` field vector event data is no longer rejected. This was a source of
confusion for vector axiom users in the past as `elasticsearch` semantics were
imposed as the sink was based on the `elasticsearch` sink and hence field
semantics and constraints.

For existing vector users, the `_time` field is documented and aligns well with
vectors own timestamp mechanics:

  https://axiom.co/docs/reference/field-restrictions#requirements-of-the-timestamp-field

If a `@timestamp` field is sent to the axiom sink it is now treated as a normal field. This
is a non breaking change.

If a `_time` field is sent to Axiom it no longer raises a 4XX error, so this is effectively a fix.

As the `axiom` sink is now HTTP based the full wealth of vectors http configuration apparatus
are now available to users of the axiom sink.

### CODE REVIEW

**Review by drichards-87 — APPROVED** [review]

**Review by jszwedko — COMMENTED** [review]
Thank you @darach ! I'll aim to review this next week.

File: src/sinks/axiom.rs [hunk 1]
```diff
@@ -41,20 +48,32 @@ pub struct AxiomConfig {
...
+    #[configurable(metadata(docs::examples = "vector_rocks"))]
     dataset: String,
 
     #[configurable(derived)]
     #[serde(default)]
     request: RequestConfig,
 
+    /// The compression algorithm to use.
+    ///
+    /// Supported values: `none` ( not recommended ), `zstd` ( recommended, default ), `gzip`, `deflate`
```
Comment (jszwedko) [inline src/sinks/axiom.rs:60]:
```suggestion
```

In the docs the enum values are rendered (including the default) so I don't think we need this additional description.

**Review by jszwedko — COMMENTED** [review]
Thanks @darach ! This looks great and honestly isn't any more code than the ES implementation due to reuse of the HTTP sink 😅 We probably could have just went this way initially. I just left one docs comment, but otherwise I think this is good to go.
