### PR TITLE
fix(buffers): fix buffer metrics when using DropNewest

### LINKED ISSUE #11151: bug(buffers): `buffer_events` incremented even when event is dropped
A user on Discord had pointed out that there `buffer_events` metric for a particular sink kept incrementing monotonically even though the sink seemed to be spitting out as many events as were coming in.

Upon closer inspection, their sink used the `drop_newest` behavior when full, which lead to `buffer_events` growing in bursts when spikes of events came in.  Looking at the `BufferSender<T>` code, we appear to increment `buffer_events` even when we drop the event, which is incorrect as there is no way for a corresponding decrement to be generated.

We need to avoid incrementing in the first place when we drop an event.

### PR DESCRIPTION
**Pull request by tobz**
As described in the title, this PR fixes an issue where events that were dropped in DropNewest mode were also counted as having been sent to the buffer, which would lead to incorrect buffer metrics over time.

I also tweaked the use of `tracing` in `vector-common` to make it a non-optional crate, as well as skipping the extern import and requiring direct `use tracing::...` statements to bring clarity to what was being used and how it was being imported.  The only reason I touched this code in particular was that the `tracing` dependency was set to optional which meant things broke if you were pulling the crate in without also setting certain feature flags, and `vector-buffers` was not setting those flags... because they're entirely unrelated to what `vector-buffers` needs out of the crate.

Fixes #11151.

Signed-off-by: Toby Lawrence <toby@nuclearfurnace.com>

### CODE REVIEW

File: lib/vector-buffers/src/topology/channel/sender.rs [hunk 1]
```diff
@@ -304,7 +304,7 @@ impl<T: Bufferable> Sink<T> for BufferSender<T> {
         let this = self.project();
         let item_size = this.instrumentation.as_ref().map(|_| item.size_of());
 
-        let result = match this.state {
+        match mem::replace(this.state, SendState::Idle) {
```
Comment (jszwedko) [inline lib/vector-buffers/src/topology/channel/sender.rs:307]: Nice, I didn't think about `mem::replace`.

**Review by jszwedko — APPROVED** [review]
Looks good! Thank you for adding the tests.

File: lib/vector-buffers/src/topology/channel/sender.rs (hunk 1 above)
Comment (tobz) [reply lib/vector-buffers/src/topology/channel/sender.rs:307]: I feel like I end up using it almost every single time I write a FSM in Rust, haha.
