### PR TITLE
fix(remap): correctly handle nested map insertions

### LINKED ISSUE #5538: Remap will overwrite a map rather than add the field to it
From the Repl:

```
$ .foo = 3
3

$ .
{ "foo": 3 }

$ .bar = 4
4

$ .
{ "bar": 4 }
```

I would expect when setting `.bar` that it would add that field to the map. It doesn't, it overwrites the entire map.

It should do:

```
$ .foo = 3
3

$ .
{ "foo": 3 }

$ .bar = 4
4

$ .
{ "bar": 4,  "foo": 3 }
```

I believe in the Remap transform, this won't happen with the root object as that is handled differently from `Value::Map` fields. If you try to set the field to any child maps, this will occur.

### PR DESCRIPTION
**Pull request by JeanMertz**
closes #5538.

### CODE REVIEW

File: lib/remap-lang/src/value.rs [hunk 1]
```diff
@@ -999,21 +999,25 @@ impl Value {
...
             let key = field.as_str().to_owned();
-            let mut map = BTreeMap::default();
+
+            // `handle_field` is used to update map values, if the current value
+            // isn't a map, we need to make it one.
+            if !matches!(self, Value::Map(_)) {
+                *self = BTreeMap::default().into()
+            }
+
+            let map = match self {
```
Comment (FungusHumungus) [inline lib/remap-lang/src/value.rs:1009]: Clearly it is working, but I don't quite understand why this doesn't have to be `let mut`?

**Review by StephenWakely — APPROVED** [review]
Nice.

File: lib/remap-lang/src/value.rs (hunk 1 above)
Comment (JeanMertz) [reply lib/remap-lang/src/value.rs:1009]: `self` is already a `&mut self` in this case, so that's what we're getting back from the inner value as well.
