### PR TITLE
fix(aws): Implement support for AWS credentials files

### LINKED ISSUE #16632: Trying to use a credentials file with AWS auth throws an error
### A note for the community

I have a PR ready to go to fix this.

### Problem

The Vector docs indicate that AWS credential files are supported as an authentication method, however that doesn't seem to be the case. Attempting to use a credentials file in a sink ends up with a log message indicating an error (`Overriding the credentials file is not supported.`). Reading the code, it looks like the credentials provider implementation does not actually support this method.

Since this method of AWS authentication is intended to be supported, it should actually work.

### Configuration

_No response_

### Version

0.28.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by protochron**
It looks like when Vector converted from rusoto to the official AWS SDK that support for AWS credentials files was dropped. The docs indicate this is supposed to be a supported option, so this PR adds support for AWS credentials files by adding the correct credential provider.

Closes #16632.

### CODE REVIEW

**Comment by spencergilbert** [comment]
Sorry! I've had a packed week, I promise I'll be reviewing this next week.

**Comment by jsoref** [comment]
You're going to need to merge to master to get Check Spelling to run.

File: src/aws/auth.rs [hunk 1]
```diff
@@ -163,8 +170,23 @@ impl AwsAuthentication {
...
-                Err("Overriding the credentials file is not supported.".into())
+            AwsAuthentication::File {
+                credentials_file,
+                profile,
+            } => {
+                // The SDK uses the default profile out of the box, but doesn't provide an optional
+                // type in the builder. We can just hardcode it so that everything works.
+                let profile_name = profile
+                    .clone()
+                    .unwrap_or_else(|| DEFAULT_PROFILE_NAME.to_string());
```
[the remark this answers is not in the document]
Comment (spencergilbert) [reply src/aws/auth.rs:181]: That'd be great, when you add the `serde::default` you'll also need to run `make generate-component-docs` to update the documentation with the new default value.

[the remark this answers is not in the document]
Comment (protochron) [reply src/aws/auth.rs]: Added both the default profile and the updated docs in the last few commits!

**Review by spencergilbert — COMMENTED** [review]
I was just adding suggestions to appease the spellchecker 😂 

Looks like two more small changes to the tests now that the profile is a String rather than an Option<String> - otherwise LGTM!

File: src/aws/auth.rs [hunk 2]
```diff
@@ -138,8 +152,21 @@ impl AwsAuthentication {
...
+            } => {
+                // The SDK uses the default profile out of the box, but doesn't provide an optional
+                // type in the builder. We can just hardcode it so that everything works.
+                let profile_name = profile;
+                let profile_files = ProfileFiles::builder()
+                    .with_file(ProfileFileKind::Credentials, credentials_file)
+                    .build();
+                let profile_provider = ProfileFileCredentialsProvider::builder()
+                    .profile_files(profile_files)
+                    .profile_name(profile_name)
```
Comment (spencergilbert) [inline src/aws/auth.rs:167]:
```suggestion
                    .profile_name(profile)
```
🤔 shouldn't this work and avoid the `let` on line 161?

File: src/aws/auth.rs [hunk 3]
```diff
@@ -138,8 +152,21 @@ impl AwsAuthentication {
...
             ))),
-            AwsAuthentication::File { .. } => {
-                Err("Overriding the credentials file is not supported.".into())
+            AwsAuthentication::File {
+                credentials_file,
+                profile,
+            } => {
+                // The SDK uses the default profile out of the box, but doesn't provide an optional
+                // type in the builder. We can just hardcode it so that everything works.
+                let profile_name = profile;
```
Comment (spencergilbert) [inline src/aws/auth.rs:161]:
```suggestion
```

Noticed this while looking at the other PR that had come in around AWS auth.

File: src/aws/auth.rs (hunk 2 above)
Comment (protochron) [reply src/aws/auth.rs:167]: Yeah, that should work now that it's not optional. I can go ahead and fix it.

Comment (spencergilbert) [reply src/aws/auth.rs:167]: Nice, sorry for the late request on that 😅 I'll hit the merge button as soon as that's updated. Thanks for putting up with my endless requests 😄

**Review by spencergilbert — APPROVED** [review]

**Comment by spencergilbert** [comment]
🚀 merge enabled, thanks again for the contribution!
