### PR TITLE
fix(metrics): Deny adding aggregated summaries

### LINKED ISSUE #7723: Addition of aggregated summary metrics does not make sense
> This looks like we're taking two quantiles that are, say, individually representing something like `50ms at the 50th percentile`, and then doing `50 + 50`.... but I can't think of a situation where this behavior would ever be correct.

_Originally posted by @tobz in https://github.com/timberio/vector/pull/7699#discussion_r644162929_

### PR DESCRIPTION
**Pull request by bruceg**
An aggregated summary is composed of a set of quantiles, which aggregate
values across *variable* buckets, where the division points of the
buckets are dependent on the total number of observations going into
each bucket. As the data changes, the actual division points change, and
so adding two summaries together is statistically meaningless.

Note that I punted on how to make the metrics buffer emit incremental aggregated summaries. Since adding them doesn't make sense, there isn't much use in even allowing them to be emitted, and I *think* most of the metrics buffer users coerce these to be absolutes anyways. I am open to better ideas, as this is deeply dissatisfying to me, but I can't conceive of a simple solution that doesn't totally special-case this type of metric.

Signed-off-by: Bruce Guenter <bruce.guenter@datadoghq.com>

Closes #7723

### CODE REVIEW

File: src/sinks/util/buffer/metrics.rs [hunk 1]
```diff
@@ -792,18 +791,11 @@ mod test {
 
     #[test]
     fn inc_buffer_aggregated_summaries() {
-        let buffer = rebuffer_aggregated_summaries::<IncrementalMetricNormalize>();
+        let buffer = dbg!(rebuffer_aggregated_summaries::<IncrementalMetricNormalize>());
```
Comment (tobz) [inline src/sinks/util/buffer/metrics.rs:794]: Do we still want this `dbg!` here?

**Review by tobz — APPROVED** [review]

File: src/sinks/util/buffer/metrics.rs (hunk 1 above)
Comment (bruceg) [reply src/sinks/util/buffer/metrics.rs:794]: Oh, no, of course not. I'll nuke that.
