### PR TITLE
fix(datadog_metrics sink): fix counter datapoint aggregation for identical timestamps

### LINKED ISSUE #13867: bug(datadog_metrics sink): lack of counter datapoint aggregation leads to loss of updates
## Problem

Currently, the `datadog_metrics` sink does not do any windowing/aggregation of metrics itself. In some cases, this might mean that it generates requests that update the same series (name + tags + metric type) multiple times within that request. Further, datapoints in a request to the Datadog metrics intake API have a timestamp with second granularity... and so it is possible to generate a request that essentially updates the same series multiple times, all with identical timestamps for the datapoints, even if the values are different.

However, the Datadog metrics intake, in the case of counters, will process these in a last-write win fashion. To wit, a single request with 10 series updates for the same series, with an identical number of datapoints sharing the same timestamp... leading to that series, when graphed, showing a value equal to the value in the last update in that request for the given series.

## Required Changes

Conceptually, we need to perform some level of aggregation within the source itself to ensure that we are summing changes to counters for identical datapoints. We do not need to perform any sort of roll-up aggregation (i.e. all metrics in the last 10 seconds, etc) and we also do not need to change the logic for gauges or distributions/histograms: their behavior is already correct.

It's not currently clear to me what the best way to approach this aggregation is, but we should be able to do it fairly performantly since it's only scoped to counters and boils down to a map lookup and adding an integer together versus some of the stuff we would have to do to merge together histograms, etc.

### LINKED ISSUE #13870: chore(datadog_metrics sink): avoid sending an interval for non-rate counters
Currently, the sink calculates an interval as the number of seconds since we last generated an encoded payload and applies that to counters which do not have their own interval.

While this doesn't seem to actually affect the display of these counters when graphed, given that they're marked as counts, and not rates... it's still confusing that we calculate and apply this, given that it seems to have no effect.

We could simplify the code in that area by avoiding constructing an interval (that ultimately does nothing) and only using one if the metric itself has one defined.

### PR DESCRIPTION
**Pull request by tobz**
This PR addresses the primary issue described in #13867, which relates to multiple counters of the same series, carrying a datapoint with the same timestamp, only being ingested in a last-write-wins fashion.

Such behavior is easy to run into when counters are being emitted at a high rate (such as incrementing the counter when an event occurs) as timestamps on the Datadog side only have second resolution.

We've also dropped passing a computed interval for counters where no interval was present, as doing so seems to lead to no visible change in metric value/output, and it's cleaner to have the model of "rates have intervals, counts don't".

Fixes #13870.
Fixes #13867.

### CODE REVIEW

File: lib/vector-core/src/event/metric/arbitrary.rs [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+                sum,
+            }
+        }),
+        any::<(Vec<Quantile>, u64, f64)>().prop_map(|(quantiles, count, sum)| {
+            MetricValue::AggregatedSummary {
+                quantiles,
+                count,
+                sum,
+            }
+        }),
```
Comment (bruceg) [inline lib/vector-core/src/event/metric/arbitrary.rs:27]: Is it valid for these values to really be _any_ here? Ie, `count` and `sum` would normally be related to the contents of the `buckets`/`quantiles`.

File: lib/vector-core/src/stream/batcher/reducer.rs [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+    state: S,
+    len: usize,
+}
+
+impl<F, S> FunctionReducer<F, S>
+where
+    S: Default,
+{
+    /// Creates a `FunctionReducer` with the given reducer function and default state.
+    pub fn with_default_state(reducer: F) -> Self {
```
Comment (bruceg) [inline lib/vector-core/src/stream/batcher/reducer.rs:15]: TIOLI _bikeshedding_ I would just call this `fn from_reducer`.

File: src/sinks/datadog/metrics/sink.rs [hunk 3]
```diff
@@ -145,3 +154,270 @@ where
...
+                    Metric::new(name, MetricKind::Incremental, value).with_timestamp(Some(ts))
+                })
+                .collect()
+        })
+    }
+
+    fn create_counter(name: &str, value: f64) -> Metric {
+        Metric::new(
+            name,
+            MetricKind::Incremental,
```
Comment (bruceg) [inline src/sinks/datadog/metrics/sink.rs:301]: Would it be worth testing handling of absolute counters, or is that not relevant here?

Comment (tobz) [reply src/sinks/datadog/metrics/sink.rs:301]: We always force counters to be incremental for the `datadog_metrics` sink in particular, which is why these tests elide testing both variants.

File: lib/vector-core/src/stream/batcher/reducer.rs (hunk 2 above)
Comment (tobz) [reply lib/vector-core/src/stream/batcher/reducer.rs:15]: Oh, doh... I did not mean to leave these changes in. I was originally thinking of trying to do this collapsing in the batcher itself, and then realize the existing code didn't necessarily provide enough of the extensibility that I needed to do so, and went with the more brute force approach.

I'll rewind the changes in this area.

File: lib/vector-core/src/event/metric/arbitrary.rs (hunk 1 above)
Comment (tobz) [reply lib/vector-core/src/event/metric/arbitrary.rs:27]: So, good eye, it's not!

I basically scaffolded out the `Arbitrary` implementations just enough to get the property test running, but I can go back and fix this up quickly, since it's not much work to do so.

Comment (tobz) [reply lib/vector-core/src/event/metric/arbitrary.rs]: Sorted this out in 9179db442.

File: lib/vector-core/src/stream/batcher/reducer.rs (hunk 2 above)
Comment (tobz) [reply lib/vector-core/src/stream/batcher/reducer.rs]: Backed out the changes in this area in 9179db442.

File: src/sinks/datadog/metrics/sink.rs [hunk 4]
```diff
@@ -145,3 +154,270 @@ where
...
+        let counter_value = 42.0;
+        let input = vec![
+            create_counter("basic", 42.0),
+            create_counter("basic", 42.0),
+            create_counter("basic", 42.0),
+            create_counter("basic", 42.0),
+            create_counter("basic", 42.0),
+            create_counter("basic", 42.0),
+            create_counter("basic", 42.0),
+        ];
```
Comment (spencergilbert) [inline src/sinks/datadog/metrics/sink.rs:362]: Should these `create_counter` just use the `counter_value` var?

**Review by spencergilbert — APPROVED** [review]
These changes seemed logically correct, and well documented - I left one nit on a test, but would still like to get @bruceg or another to give it a once over as well.

File: src/sinks/datadog/metrics/sink.rs (hunk 4 above)
Comment (tobz) [reply src/sinks/datadog/metrics/sink.rs:362]: Oh, derp. Yes, they should.

Comment (tobz) [reply src/sinks/datadog/metrics/sink.rs]: Fixed in a764ee8.

File: lib/vector-core/src/event/metric/arbitrary.rs [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+    ];
+    strategy.boxed()
+}
+
+impl Arbitrary for MetricValue {
+    type Parameters = ();
+    type Strategy = BoxedStrategy<MetricValue>;
+
+    fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
+        arb_metric_value()
```
Comment (bruceg) [inline lib/vector-core/src/event/metric/arbitrary.rs:60]: I think I missed this before. What is the motivation for moving the implementation for this into a function? This appears to be the only caller.

File: lib/vector-core/src/event/metric/arbitrary.rs [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+    let strategy = prop_oneof![any::<AgentDDSketch>().prop_map(MetricSketch::AgentDDSketch),];
+    strategy.boxed()
+}
+
+impl Arbitrary for MetricSketch {
+    type Parameters = ();
+    type Strategy = BoxedStrategy<MetricSketch>;
+
+    fn arbitrary_with(_: Self::Parameters) -> Self::Strategy {
+        arb_metric_sketch()
```
Comment (bruceg) [inline lib/vector-core/src/event/metric/arbitrary.rs:74]: Ditto single-line function as the only caller of another function looks like superfluous indirection, and repeated below.

**Review by bruceg — APPROVED** [review]
Looks good. I am curious about what looks like extraneous indirection below, though.

File: lib/vector-core/src/event/metric/arbitrary.rs (hunk 5 above)
Comment (tobz) [reply lib/vector-core/src/event/metric/arbitrary.rs:60]: There's a typical pattern of defining functions for generating custom strategies which can then be called as the default value in a `proptest` callsite, which looks something like `fn my_proptest_fn(input in arb_metric_value())`.

That's how I started off, and then I just implemented the trait so I could let `proptest` do the inference for me without the references to the functions... and I just never collapsed them.

I'll do that.
