### PR TITLE
fix(prometheus_remote_write sink): Default timestamp to now

### LINKED ISSUE #6814: `prometheus_remote_write` writes metrics with a timestamp of 0 if the metrics source has no timestamp
I'm unsure if this is a bug with the `prometheus_scrape` source or the `prometheus_remote_write` sink, but a user discovered that Grafana Cloud was rejecting their metrics because the timestamp was out-of-bounds: https://discord.com/channels/742820443487993987/746070591097798688/822181386924457984

I ran a test and it seems like, if `prometheus_scrape` scrapes a prometheus exporter that doesn't publish timestamps, piping this into the `prometheus_remote_write` sink results in vector sending the metrics with a unix timestamp of `0`.

To test I used:

* The [`node_exporter`](https://github.com/prometheus/node_exporter) as the source of the metrics
* An example [test server](https://github.com/prometheus/prometheus/tree/main/documentation/examples/remote_storage/example_write_adapter) to receive the `remote_write` messages and log them out

```toml
[sources.localhost]
type = "prometheus_scrape"
endpoints = ["http://localhost:9100/metrics"]
scrape_interval_secs = 2

[sinks.grafana_cloud]
inputs              = ["localhost"]
type                = "prometheus_remote_write"
endpoint            = "http://localhost:1234/receive"
healthcheck.enabled = false
```

Sample output from the test server:

```
node_network_up{device="eth0"}
  1.000000 0
node_network_iface_link_mode{device="lo"}
  0.000000 0
node_network_device_id{device="veth963a53c"}
  0.000000 0
node_softnet_processed_total{cpu="1"}
  3723029.000000 0
node_xfs_read_calls_total{device="nvme0n1p1"}
  31224930.000000 0
node_schedstat_running_seconds_total{cpu="6"}
  13115.416296 0
node_softnet_processed_total{cpu="7"}
  3904592.000000 0
node_network_transmit_fifo_total{device="docker0"}
  0.000000 0
node_scrape_collector_success{collector="zfs"}
  1.000000 0
node_cpu_guest_seconds_total{cpu="6", mode="user"}
  0.000000 0
node_network_carrier_changes_total{device="docker0"}
  118.000000 0
go_memstats_gc_sys_bytes
  3582216.000000 0
go_threads
  13.000000 0
node_network_transmit_fifo_total{device="br-7926c8e16fd6"}
  0.000000 0
node_cpu_seconds_total{cpu="6", mode="steal"}
  1601.590000 0
node_softnet_processed_total{cpu="4"}
  3627108.000000 0
```

We may want to do a quick audit of other handling of metric timestamps as it seems like we've had a few issues with them recently:

* https://github.com/timberio/vector/issues/6725
* https://github.com/timberio/vector/issues/5916

### PR DESCRIPTION
**Pull request by bruceg**
When encoding a metric to the remote write protocol, a timestamp field
must be present. When presented with a metric without a timestamp, this
sink encoded a timestamp of `0`, which is almost certainly not the
correct value. This changes that default to the current time.

Closes #6814 

Signed-off-by: Bruce Guenter <bruce.guenter@datadoghq.com>

### CODE REVIEW

**Comment by bruceg** [comment]
Note, a second PR will be coming shortly to handle the other part of #6814.

File: src/sinks/prometheus/collector.rs [hunk 1]
```diff
@@ -298,6 +300,12 @@ impl TimeSeries {
         labels.sort();
         labels
     }
+
+    fn now(&mut self) -> i64 {
+        *self
+            .now
+            .get_or_insert_with(|| Utc::now().timestamp_millis())
```
Comment (jszwedko) [inline src/sinks/prometheus/collector.rs:307]: The naming of this function wouldn't indicate to me that it caches the value of `now`. I'm wondering if we should just remove that caching.

Alternatively, I could see making this a top-level function and using `cfg(test)` to define a mock implementation with a known value that the tests could depend on here.

**Review by jszwedko — COMMENTED** [review]
This looks good! I just have one question about the `now` mocking.

Also, could we document this behavior in the external docs? I could see adding a `trace` level log the timestamp is default to now to help debugging.

File: src/sinks/prometheus/collector.rs (hunk 1 above)
Comment (bruceg) [reply src/sinks/prometheus/collector.rs:307]: I figured it being both a simple optimization and a way of providing that all metrics in a batch used the same default timestamp. It has to be per-batch, as otherwise all metrics without a timestamp would share the same time again.

Comment (bruceg) [reply src/sinks/prometheus/collector.rs:307]: That said, I am definitely open to renaming it to indicate the purpose better. I'll figure a more descriptive name.

Comment (jszwedko) [reply src/sinks/prometheus/collector.rs:307]: I can see why it might be desirable for all metrics in the same batch to have the same default timestamp value, but is that an actual requirement? I was thinking it could just always use whatever `Utc::now()` is, without the caching.

Comment (jszwedko) [reply src/sinks/prometheus/collector.rs:307]: 👍 the naming is definitely better now though.

Comment (bruceg) [reply src/sinks/prometheus/collector.rs:307]: No, it's not a requirement, just an optimization. On my desktop, `Utc::now` is 4-6x as expensive as cloning a string, though amusingly it's *faster* than cloning on my MBP (which hints that MacOS has an *aweful* malloc implementation).

**Review by jszwedko — APPROVED** [review]
