### PR TITLE
fix(s3-source): ensure batch status is updated

### LINKED ISSUE #16741: S3 source deadlocks with sink acknowledgments enabled
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The observed behavior is that S3 source hangs, and never reads more from the queue when the downstream sink has acks enabled.

This is apparent when turning down the `client_concurrency`. The example config below demonstrates the behavior:

1. Start vector
2. Add an object to the bucket
3. Confirm data arrives in the output file
4. Add another object
5. Notice data never arrives in the output file, and the SQS queue is never drained 

### Configuration

```text
data_dir = "/tmp"

[sources.s3]
type = "aws_s3"
compression = "auto"
region = "us-east-1"
strategy = "sqs"

  [sources.s3.auth]
  access_key_id = "<id>"
  secret_access_key = "<key>"

  [sources.s3.sqs]
  queue_url = "<your queue url>"
  client_concurrency = 1


[sinks.file]
type = "file"
path = "/tmp/vector-%Y-%m-%d.log"
inputs = ["s3"]

  [sinks.file.acknowledgements]
  enabled = true

  [sinks.file.encoding]
  codec = "json"
```

### Version

0.27.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by mdeltito**
Previously, with acknowledgments enabled on a sink the S3 source would get into a state where it was waiting for a message on a `BatchNotifier` channel that would never be sent. This is because the notifier itself was being cloned for each event in the batch, but the final reference was not dropped prior to awaiting the channel.

Fixes #16741

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Almost seems too easy... but it makes sense - I'll wait @bruceg's confirmation before merging.

Thanks for the contribution @mdeltito!

File: src/sources/aws_s3/sqs.rs [hunk 1]
```diff
@@ -614,6 +614,10 @@ impl IngestorProcess {
         // so we explicitly drop it so that we can again utilize `read_error` below.
         drop(stream);
 
+        // The BatchNotifier is cloned for each LogEvent in the batch stream, but the last
+        // reference must be dropped before the status of the batch is sent to the channel.
+        drop(batch);
```
Comment (bruceg) [inline src/sources/aws_s3/sqs.rs:619]: This should actually be done before the send, as the events themselves hold a copy of the batch during the send.

**Review by bruceg — APPROVED** [review]
Thanks for this fix. The drop can be done slightly earlier, as detailed below, but this should work as it is.

File: src/sources/aws_s3/sqs.rs (hunk 1 above)
Comment (mdeltito) [reply src/sources/aws_s3/sqs.rs]: Thanks @bruceg, good catch - fixed in 45dc94f

Comment (mdeltito) [reply src/sources/aws_s3/sqs.rs]: Thanks @bruceg, good catch - fixed in 45dc94f

**Comment by spencergilbert** [comment]
Thanks for the contribution @mdeltito!
