### PR TITLE
fix(vrl): correctly type-def external root path

### LINKED ISSUE #12777: False-positive for fallibility in if/else block in VRL
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

VRL seems to not be properly scoping updates to field types. In the below configuration, the `. = merge(., {})` seems to cause the `else if` condition to "forget" that `.image` is always a string.

### Configuration

```text
[sources.stdin]
type = "stdin"
decoding.codec = "json"

[transforms.remap]
type = "remap"
inputs = [ "stdin" ]
source = '''
.image = string(.image) ?? "unknown"
if starts_with(.image, "foo") {
  . = merge(., {})
  # null # if used instead of the above line, false positive does not appear
} else if contains(.image, "bar") {
  null
}
'''

[sinks.my_sink_id]
type = "console"
inputs = [ "remap" ]
encoding.codec = "json"
```

### Version

vector 0.21.1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by JeanMertz**
fixes #12777.

### CODE REVIEW

File: lib/vrl/compiler/src/expression/query.rs [hunk 1]
```diff
@@ -120,19 +120,11 @@ impl Expression for Query {
...
-                }
-
-                match state.1.target() {
-                    None => TypeDef::any().infallible(),
-                    Some(details) => details.clone().type_def.at_path(&self.path.to_lookup()),
-                }
-            }
+            External => match state.1.target() {
+                None if self.path.is_root() => TypeDef::object(Collection::any()).infallible(),
+                None => TypeDef::any().infallible(),
```
Comment (JeanMertz) [inline lib/vrl/compiler/src/expression/query.rs:125]: I left this in because I didn't think @fuchsnj's PR of allowing the root to be any type hadn't landed yet, but it seems that it did.

Did you intentionally not touch this code, or missed it? I guess we'll want to remove the `is_root` variant in this list now, correct?

Comment (fuchsnj) [reply lib/vrl/compiler/src/expression/query.rs:125]: I missed it. I assumed a few things like this would get missed until I finish more of the work and do full testing of it.

**Review by fuchsnj — APPROVED** [review]

File: lib/vrl/compiler/src/expression/query.rs (hunk 1 above)
Comment (JeanMertz) [reply lib/vrl/compiler/src/expression/query.rs:125]: Gotcha. I'll remove the conditional above, and type-def it to `any` if no information is known about the root of the target.

**Review by jszwedko — APPROVED** [review]
Looks good! Thanks for the quick fix here.

File: lib/vrl/compiler/src/expression/query.rs (hunk 1 above)
Comment (JeanMertz) [reply lib/vrl/compiler/src/expression/query.rs]: I backed out of this, as it would be a breaking change that exposed itself through a bunch of VRL integration tests that started failing.

We can still move forward with this, but we'd have to use schema support to inject the proper root type into the VRL compiler. Nothing we can't do, but also nothing I want to do in this fix PR.
