### PR TITLE
fix(sinks): ack and don't stop on request errors

### LINKED ISSUE #2623: [aws_s3] vector is unable to start if ec2 instance does not have rw to S3 bucket.
We use healthcheck for S3 sink but still vector is unable to start when he get `403` from S3 bucket api and stop.
Output: 
```
May 15 10:29:14.240 ERROR sink{name=s3_archives type=aws_s3}:request{request_id=1}: vector::sinks::util::retries: encountered non-retriable error. error=Sts AssumeRoleError: Unknown(BufferedHttpResponse {status: 403, body: "<ErrorResponse xmlns=\"https://sts.amazonaws.com/doc/2011-06-15/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>AccessDenied</Code>\n    <Message>User: arn:aws:sts::xxxx is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxx</Message>\n  </Error>\n  <RequestId>xxxx</RequestId>\n</ErrorResponse>\n", headers: {"x-amzn-requestid": "xxxx", "content-type": "text/xml", "content-length": "425", "date": "Fri, 15 May 2020 10:29:13 GMT"} })
May 15 10:29:14.240 ERROR sink{name=s3_archives type=aws_s3}: vector::sinks::util::sink: Request failed. error=Sts AssumeRoleError: Unknown(BufferedHttpResponse {status: 403, body: "<ErrorResponse xmlns=\"https://sts.amazonaws.com/doc/2011-06-15/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>AccessDenied</Code>\n    <Message>User: arn:aws:sts::xxxx is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxx</Message>\n  </Error>\n  <RequestId>xxxx</RequestId>\n</ErrorResponse>\n", headers: {"x-amzn-requestid": "xxxx", "content-type": "text/xml", "content-length": "425", "date": "Fri, 15 May 2020 10:29:13 GMT"} })
May 15 10:29:14.240 ERROR sink{name=s3_archives type=aws_s3}: vector::sinks::aws_s3: Sink failed to flush: Sts AssumeRoleError: Unknown(BufferedHttpResponse {status: 403, body: "<ErrorResponse xmlns=\"https://sts.amazonaws.com/doc/2011-06-15/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>AccessDenied</Code>\n    <Message>User: arn:aws:sts::xxxx is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxx</Message>\n  </Error>\n  <RequestId>-xxxx</RequestId>\n</ErrorResponse>\n", headers: {"x-amzn-requestid": "xxxx", "content-type": "text/xml", "content-length": "425", "date": "Fri, 15 May 2020 10:29:13 GMT"} })
May 15 10:29:14.244 ERROR vector::topology: Unhandled error
```
Our configuration: 
```
sinks.s3_archives_auth ]
  inputs       = ["file_auth"] # don't sample
  type         = "aws_s3"
  region       = "us-east-1"
  bucket       = "BUCKET_NAME"
  encoding     = "text"
  compression  = "gzip"
  healthcheck  = true # optional, default
  # Batch
  batch.max_size     = 100000000 # uncompressed bytes
  batch.timeout_secs = 900 # optional, default, seconds
  # Buffer
  buffer.type      = "memory" # optional, default
  buffer.max_events = 500
  #buffer.max_size  = 253741824 # required, bytes, required when type = "disk"
  buffer.when_full = "block" # optional, default
  # Encryption
  server_side_encryption = "AES256" # optional, no default
  assume_role = "IAM_ROLE_NAME"
  # Metadata not more than 10 keys
  tags.source = "system-auth"
  tags.hostname = "${VECTOR_HOSTNAME}"
  tags.role = "${VECTOR_ROLE}"
  tags.cluster = "${VECTOR_CLUSTER}"
  # Naming
  filename_append_uuid = true # optional, default
  filename_extension = "log" # optional, default
  filename_time_format = "%s" # optional, default
  key_prefix = "system/auth/%Y/%m/%d/${VECTOR_HOSTNAME}_" # optional, default
  # Request
  request.in_flight_limit = 50 # optional, default, requests
  request.rate_limit_duration_secs = 1 # optional, default, seconds
  request.rate_limit_num = 250 # optional, default
  request.retry_attempts = 300 # optional, default
```
Base on doc: https://vector.dev/docs/reference/sinks/aws_s3/#health-checks vector should log alert and start.

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #2623 

This fixes two pretty important bugs with service-based sinks:

1. As of #2111 we incorrectly propagated individual request errors all the way to the sink level, which causes them to shut down instead of continuing to send future requests.

2. As of forever(?), we did not ack events from a failed request. This would be fine if acks were event-specific, but they're just offsets into a sequence. By not acking failed events, we'd start to slowly diverge from the actual count of events and potentially leave some events forever un-acked.

### CODE REVIEW

File: src/sinks/util/sink.rs [hunk 1]
```diff
@@ -643,16 +643,25 @@ where
...
-            })
             .map_err(Into::into)
-            .then(|res| {
+            .then(move |result| {
+                match result {
+                    Ok(response) => {
+                        trace!(message = "Response successful.", ?response);
+                    }
+                    Err(error) => {
+                        error!(
```
Comment (Hoverbear) [inline src/sinks/util/sink.rs:653]: Might be worth rate limiting this?

**Review by Hoverbear — APPROVED** [review]

File: src/sinks/util/sink.rs (hunk 1 above)
Comment (lukesteensen) [reply src/sinks/util/sink.rs:653]: I agreed initially but after thinking more I'm going to leave it out. We generally rate limit event-level logs where there could potentially be hundreds of thousands per second. This is a request-level logs where the value is likely higher and we have default rate limits around how many we'll do in a given period of time (usually tens or hundreds per second at most).

That said, we can always revisit.
