### PR TITLE
fix(unit tests): Error on non-existent extract_from, no_outputs_from targets

### LINKED ISSUE #11338: unit tests panic if consuming from non-existent input
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.20.0 (x86_64-apple-darwin 2a706a3 2022-02-10)
```

### Vector Configuration File

```yaml
sources:
  syslog:
    type: socket
    mode: tcp
    address: 0.0.0.0:9999

transforms:
  parse-syslog:
    type: remap
    inputs:
      - syslog
    drop_on_error: true
    source: |-
      host = string!(.host)
      message = string!(.message)
      ., err = parse_syslog(message)
      if err != null {
        log("invalid syslog message from <" + host + ">: " + message, level: "warn")
        abort
      }
      .host = host

sinks:
  console:
    type: console
    inputs:
      - parse-syslog
    encoding: json

tests:
  - name: crash
    inputs:
      - insert_at: parse-syslog
        type: log
        log_fields:
          host: test
          message: >-
            May 31 10:01:02 app LOG-MESSAGE
    outputs:
      - extract_from: parse-ssyslog  # typo in purpose!
        conditions:
          - type: vrl
            source: |-
              assert!(1 == 1)
```

### Debug Output

```
Running tests
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/config/mod.rs:648:65
stack backtrace:
   0:        0x1099e3206 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c059b532d34bdd
   1:        0x1090e63eb - core::fmt::write::hefb311138778afb5
   2:        0x1099e1d4a - std::io::Write::write_fmt::h0e0ed87b18ae870c
   3:        0x1099e2538 - std::panicking::default_hook::{{closure}}::h43f0e51e5825bd5b
   4:        0x1099e198f - std::panicking::rust_panic_with_hook::h0db3c4ba5fb4dc12
   5:        0x109a1728a - std::panicking::begin_panic_handler::{{closure}}::hc6d8c92efeef5a19
   6:        0x109a17229 - std::sys_common::backtrace::__rust_end_short_backtrace::h7ffb59e898e02a83
   7:        0x109a171e5 - _rust_begin_unwind
   8:        0x10bfae43f - core::panicking::panic_fmt::h7d73f67464d78916
   9:        0x10bfae567 - core::panicking::panic::h9721d5a8c5d33ad7
  10:        0x10b23d862 - vector::config::TestDefinition<alloc::string::String>::resolve_outputs::he6bb174a5e5ed961
  11:        0x10b628cd2 - vector::config::unit_test::build_unit_tests::{{closure}}::h5b4ed336422a10d4
  12:        0x10b5fcf48 - vector::app::Application::prepare_from_opts::{{closure}}::heb79e7d3c4f1467c
  13:        0x10b5f2e79 - vector::app::Application::prepare_from_opts::h6d58f6ce126bcfb6
  14:        0x108d30066 - vector::main::h9ae6803fb2955449
  15:        0x108d30006 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbaf3b8396009ee17
  16:        0x108d31da9 - _main
```

Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.

### Expected Behavior

Vector runs the tests.

### Actual Behavior

Vector panics.

### Additional Context

This worked in v0.19

### PR DESCRIPTION
**Pull request by 001wwang**
Closes #11338

This PR adds informative error messages at unit test build time when non-existent targets are specified in `extract_from` and `no_outputs_from`, avoiding a panic. Note, when any build errors occur, no tests are run.

For the example described in #11338, you'll now see the following output:
```
Failed to build test 'crash':
  Invalid extract_from target in test 'crash': transform 'parse-ssyslog' does not exist
```

### CODE REVIEW

File: src/config/mod.rs [hunk 1]
```diff
@@ -631,36 +631,58 @@ pub struct TestDefinition<T = OutputId> {
...
-                extract_from: output_map.get(&old.extract_from).unwrap().clone(),
-                conditions: old.conditions,
+            .filter_map(|old| {
+                if let Some(output_id) = output_map.get(&old.extract_from) {
+                    Some(TestOutput {
+                        extract_from: output_id.clone(),
+                        conditions: old.conditions,
+                    })
+                } else {
+                    errors.push(format!(r#"Invalid extract_from target in test '{}': transform '{}' does not exist"#, name, old.extract_from));
```
Comment (jszwedko) [inline src/config/mod.rs:658]: Is it definitely a `transform`? Could we just say `input` here?

File: src/config/mod.rs [hunk 2]
```diff
@@ -631,36 +631,58 @@ pub struct TestDefinition<T = OutputId> {
...
             .collect();
 
         let no_outputs_from = no_outputs_from
             .into_iter()
-            .map(|o| output_map.get(&o).unwrap().clone())
+            .filter_map(|o| {
+                if let Some(output_id) = output_map.get(&o) {
+                    Some(output_id.clone())
+                } else {
+                    errors.push(format!(r#"Invalid no_outputs_from target in test '{}': transform '{}' does not exist"#, name, o));
```
Comment (jszwedko) [inline src/config/mod.rs:670]: And here.

File: Cargo.toml [hunk 3]
```diff
@@ -791,6 +791,19 @@ dnstap-integration-tests = ["sources-dnstap", "bollard"]
...
+  "transforms-add_fields",
+  "transforms-remap",
+  "transforms-route",
+  "transforms-filter",
+  "transforms-reduce",
+  "transforms-compound",
+  "transforms-add_tags",
+  "transforms-log_to_metric",
+  "transforms-remove_fields",
+  "sinks-console"
```
Comment (jszwedko) [inline Cargo.toml:805]: Are all these features needed? The added test seems to just be using `add_fields`.

**Review by jszwedko — COMMENTED** [review]
Nice, thanks for the quick fix and the added test. Could we also add this to the `known_issues` for 0.20.0 and as part of the 0.20.0 upgrade guide? I realize the fix will be in 0.20.0, but the break in behavior is part of the 0.20 series.

File: Cargo.toml (hunk 3 above)
Comment (001wwang) [reply Cargo.toml:805]: Yes, they weren't all specified previously. Other tests make use of the various other included features.

File: src/config/mod.rs (hunk 1 above)
Comment (001wwang) [reply src/config/mod.rs:658]: For now, yes since we only support unit testing transforms. Happy to generalize it, though `input` seems a little confusing since it's part of configuring test output assertions. Maybe I can just remove `transform`?

**Comment by 001wwang** [comment]
> Nice, thanks for the quick fix and the added test. Could we also add this to the `known_issues` for 0.20.0 and as part of the 0.20.0 upgrade guide? I realize the fix will be in 0.20.0, but the break in behavior is part of the 0.20 series.

Ah totally, will do.

File: src/config/mod.rs (hunk 1 above)
Comment (jszwedko) [reply src/config/mod.rs:658]: Mmm, yeah, that's true. We can just drop `transform` then.

**Review by jszwedko — APPROVED** [review]
Looks great, thank you!
