### PR TITLE
fix(buffers): deadlock when seeking after entire write fails to be flushed

### LINKED ISSUE #17644: Stuck in infinite loop after disk buffer corruption
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello,

We've been facing multiple buffer corruption & partial write since before 0.30.0, due to hardware reset of our hosts.
0.30.0 has greatly improved the situation, however we're still facing issues from time to time.
Those issues are critical and unrecoverable without human intervention for two reasons:

- Restarting vector doesn't fix the issue: buffer needs to be manually erased to recover
- Vector stop responding to SIGINT  signal, only SIGKILL works.

What we see is that vector quickly ends up in an infinite loop, as shown in logs below:
```
2023-06-08T09:51:40.330230Z DEBUG vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2023-06-08T09:51:40.331718Z  INFO vector::app: Log level is enabled. level="vector=debug,codec=debug,vrl=debug,file_source=debug,tower_limit=trace,rdkafka=debug,buffers=debug,lapin=debug,kube=debug"
2023-06-08T09:51:40.336196Z  INFO vector::app: Loading configs. paths=["config.yaml"]
2023-06-08T09:51:40.348440Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
2023-06-08T09:51:40.368077Z DEBUG vector::topology::builder: Building new source. component=input
2023-06-08T09:51:40.371782Z DEBUG vector::topology::builder: Building new sink. component=output
2023-06-08T09:51:40.376510Z DEBUG vector_buffers::variants::disk_v2::ledger: Found existing data file. data_file="buffer-data-1.dat" file_size=2296 total_buffer_size=2296
2023-06-08T09:51:40.376541Z DEBUG vector_buffers::variants::disk_v2::ledger: Found existing data file. data_file="buffer-data-2.dat" file_size=6128776 total_buffer_size=6131072
2023-06-08T09:51:40.377051Z DEBUG validate_last_write: vector_buffers::variants::disk_v2::writer: Validating last written record in current data file. current_writer_data_file="./buffer/v2/output/buffer-data-2.dat"
2023-06-08T09:51:40.377155Z DEBUG validate_last_write:ensure_ready_for_write: vector_buffers::variants::disk_v2::writer: Opened data file for writing. data_file_path="./buffer/v2/output/buffer-data-2.dat" existing_file_size=6128776
2023-06-08T09:51:40.384223Z ERROR validate_last_write: vector_buffers::variants::disk_v2::writer: Last record written to data file is behind expected position. Events have likely been lost. ledger_next=666400 last_record_id=666376 record_events=23
2023-06-08T09:51:40.385170Z DEBUG vector_buffers::variants::disk_v2::reader: Seeking to last acknowledged record for reader. last_acknowledged_record_id=666399
2023-06-08T09:51:40.385743Z DEBUG vector_buffers::variants::disk_v2::reader: Opened data file for reading. data_file_path="./buffer/v2/output/buffer-data-2.dat"
2023-06-08T09:51:40.457316Z DEBUG vector_buffers::variants::disk_v2::reader: Current data file has no more data. bytes_read=6128776
2023-06-08T09:51:40.457367Z DEBUG vector_buffers::variants::disk_v2::reader: Current data file has no more data. bytes_read=6128776
2023-06-08T09:51:40.457401Z DEBUG vector_buffers::variants::disk_v2::reader: Current data file has no more data. bytes_read=6128776
2023-06-08T09:51:40.457421Z DEBUG vector_buffers::variants::disk_v2::reader: Current data file has no more data. bytes_read=6128776
2023-06-08T09:51:40.457458Z DEBUG vector_buffers::variants::disk_v2::reader: Current data file has no more data. bytes_read=6128776

… forever …
```

### Configuration

```text
I imported our production buffer directory on my local setup, and loaded it using following configuration:

data_dir: "./"
sources:
  input:
    type: demo_logs
    format: apache_common
    lines:
      - line1
sinks:
  output:
    type: console
    buffer:
    - type: disk
      max_size: 1073741824 # 1GiB.
      when_full: drop_newest
    encoding:
      codec: json
    inputs:
      - input
```

### Version

0.30.0

### Debug Output

```text
2023-06-08T12:56:10.674301Z DEBUG vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2023-06-08T12:56:10.674409Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,lapin=trace,kube=trace"
2023-06-08T12:56:10.675480Z  INFO vector::app: Loading configs. paths=["config.yaml"]
2023-06-08T12:56:10.677789Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
2023-06-08T12:56:10.679238Z DEBUG vector::topology::builder: Building new source. component=input
2023-06-08T12:56:10.679721Z DEBUG vector::topology::builder: Building new sink. component=output
2023-06-08T12:56:10.682285Z DEBUG vector_buffers::variants::disk_v2::ledger: Found existing data file. data_file="buffer-data-1.dat" file_size=2296 total_buffer_size=2296
2023-06-08T12:56:10.682334Z DEBUG vector_buffers::variants::disk_v2::ledger: Found existing data file. data_file="buffer-data-2.dat" file_size=6128776 total_buffer_size=6131072
2023-06-08T12:56:10.682386Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=0 new_buffer_size=6131072
2023-06-08T12:56:10.682446Z DEBUG validate_last_write: vector_buffers::variants::disk_v2::writer: Validating last written record in current data file. current_writer_data_file="./buffer/v2/output/buffer-data-2.dat"
2023-06-08T12:56:10.682637Z DEBUG validate_last_write:ensure_ready_for_write: vector_buffers::variants::disk_v2::writer: Opened data file for writing. data_file_path="./buffer/v2/output/buffer-data-2.dat" existing_file_size=6128776
2023-06-08T12:56:10.688705Z ERROR validate_last_write: vector_buffers::variants::disk_v2::writer: Last record written to data file is behind expected position. Events have likely been lost. ledger_next=666400 last_record_id=666376 record_events=23
2023-06-08T12:56:10.689234Z DEBUG vector_buffers::variants::disk_v2::reader: Seeking to last acknowledged record for reader. last_acknowledged_record_id=666399
2023-06-08T12:56:10.689548Z DEBUG vector_buffers::variants::disk_v2::reader: Opened data file for reading. data_file_path="./buffer/v2/output/buffer-data-2.dat"
2023-06-08T12:56:10.690606Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=6131072 new_buffer_size=6083104
2023-06-08T12:56:10.690889Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=6083104 new_buffer_size=6074616
2023-06-08T12:56:10.690929Z TRACE vector_buffers::topology::acks: Added acknowledgements. unclaimed_acks=112 added_acks=112
2023-06-08T12:56:10.690940Z TRACE vector_buffers::topology::acks: Searching for eligible marker. acked_marker_id=666400 effective_acked_marker_id=666512 unclaimed_acks=112 pending_markers=0
2023-06-08T12:56:10.691082Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=6074616 new_buffer_size=6066128
2023-06-08T12:56:10.691112Z TRACE vector_buffers::topology::acks: Added acknowledgements. unclaimed_acks=136 added_acks=24
2023-06-08T12:56:10.691121Z TRACE vector_buffers::topology::acks: Searching for eligible marker. acked_marker_id=666400 effective_acked_marker_id=666536 unclaimed_acks=136 pending_markers=0
2023-06-08T12:56:10.691213Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=6066128 new_buffer_size=6057968
2023-06-08T12:56:10.691235Z TRACE vector_buffers::topology::acks: Added acknowledgements. unclaimed_acks=160 added_acks=24
2023-06-08T12:56:10.691244Z TRACE vector_buffers::topology::acks: Searching for eligible marker. acked_marker_id=666400 effective_acked_marker_id=666560 unclaimed_acks=160 pending_markers=0
2023-06-08T12:56:10.691381Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=6057968 new_buffer_size=6049624
2023-06-08T12:56:10.691410Z TRACE vector_buffers::topology::acks: Added acknowledgements. unclaimed_acks=170 added_acks=10
2023-06-08T12:56:10.691419Z TRACE vector_buffers::topology::acks: Searching for eligible marker. acked_marker_id=666400 effective_acked_marker_id=666570 unclaimed_acks=170 pending_markers=0
2023-06-08T12:56:10.691455Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=6049624 new_buffer_size=6048760
2023-06-08T12:56:10.691466Z TRACE vector_buffers::topology::acks: Added acknowledgements. unclaimed_acks=193 added_acks=23
2023-06-08T12:56:10.691474Z TRACE vector_buffers::topology::acks: Searching for eligible marker. acked_marker_id=666400 effective_acked_marker_id=666593 unclaimed_acks=193 pending_markers=0
2023-06-08T12:56:10.691535Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=6048760 new_buffer_size=6044768
2023-06-08T12:56:10.691551Z TRACE vector_buffers::topology::acks: Added acknowledgements. unclaimed_acks=194 added_acks=1
2023-06-08T12:56:10.691559Z TRACE vector_buffers::topology::acks: Searching for eligible marker. acked_marker_id=666400 effective_acked_marker_id=666594 unclaimed_acks=194 pending_markers=0
2023-06-08T12:56:10.691572Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=6044768 new_buffer_size=6044248
2023-06-08T12:56:10.691582Z TRACE vector_buffers::topology::acks: Added acknowledgements. unclaimed_acks=195 added_acks=1
2023-06-08T12:56:10.691591Z TRACE vector_buffers::topology::acks: Searching for eligible marker. acked_marker_id=666400 effective_acked_marker_id=666595 unclaimed_acks=195 pending_markers=0
2023-06-08T12:56:10.692388Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=6044248 new_buffer_size=5996280
2023-06-08T12:56:10.692504Z TRACE vector_buffers::topology::acks: Added acknowledgements. unclaimed_acks=196 added_acks=1
2023-06-08T12:56:10.692513Z TRACE vector_buffers::topology::acks: Searching for eligible marker. acked_marker_id=666400 effective_acked_marker_id=666596 unclaimed_acks=196 pending_markers=0
2023-06-08T12:56:10.692651Z TRACE vector_buffers::variants::disk_v2::ledger: Updated buffer size. previous_buffer_size=5996280 new_buffer_size=5987792


… forever …
```

### Example Data

_No response_

### Additional Context

Right now I can't share my buffer-data-1.dat file because it contains business critical data, but I can try scrubing any sensitive data if needed

### References

_No response_

### PR DESCRIPTION
**Pull request by tobz**
## Context

In #17644, a user reported disk buffers getting stuck in an infinite loop, and thus deadlocking, when restarting after a crash. They provided some very useful debug information, going as far to evaluate, add some logging, and get some values of internal state for the reader.

When a disk buffer is initialized -- either for the first time or after Vector is restarted and the buffer must resume where it left off -- both the reader and writer perform a catch-up phase. For the writer, it checks the current data file and tries to figure out if the last record written matches where it believes it left off. For the reader, it actually has to dynamically seek to where it left off within the the given data file, since we can't just open the file and start from the beginning: data files are append-only.

As part of the seek logic, there's a loop where we just call `Reader::next` until we read the record we supposedly left off on, and then we know we're caught up. This loop only breaks on two conditions:

- `self.last_reader_record_id < ledger_last`, which implies we haven't yet read the last record we left off on (otherwise it would be equal to `ledger_last`)
- `maybe_record.is_none() && self.last_reader_record_id == 0`, which would tell us that we reached EOF on the data file (no more records) but nothing was in the file (`last_reader_record_id` still being 0)

While the first conditional is correct, the second one is not. The user that originally reported the issue [said as much](https://github.com/vectordotdev/vector/issues/17644#issuecomment-1584256140), but dropping the `&& self.last_reader_record_id == 0` fixes the issue.

In this case, there can exist a scenario where Vector crashes and writes that the reader had read and acknowledged never actually make it to disk. Both the reader/writer are able to outpace the data on disk because the reader can read yet-to-be-flushed records since they exist as dirty pages in the page cache.

When this happens, the reader may have indicated to the ledger that it, for example, has read up to record ID 10 while the last record _on disk_ when Vector starts up is record ID 5. When the seek logic runs, it knows the last read record ID was 10. It will do some number of reads while seeking, eventually reading record ID 5, and updating `self.last_reader_record_id` accordingly. On the next iteration of the loop, it tries to read but hits EOF: the data file indeed has nothing left. However, `self.last_reader_record_id < ledger_last` is still true while `maybe_record.is_none() && self.last_reader_record_id == 0` is not, as `self.last_reader_record_id` is set to `5`.

Alas, deadlock.

## Solution

The solution is painfully simple, and the user that originally reported the issue [said as much](https://github.com/vectordotdev/vector/issues/17644#issuecomment-1584256140): drop `&& self.last_reader_record_id == 0`.

Given the loop's own condition, the inner check for `self.last_reader_record_id == 0` was redundant... but obviously also logically incorrect, too, in the case where we had missing writes. I'm still not entirely sure how existing tests didn't already catch this, but it was easy enough to spot the error once I knew where to look, and the resulting unit test I added convincingly showed that it was broken, and after making the change, indeed fixed.

## Reviewer Note(s)

I added two unit tests: one for the fix as shown and one for what I thought was another bug. Turns out that the "other bug" wasn't a bug, and this unit test isn't _explicitly_ required, but it's a simple variation of other tests with a more straightforward invariant that it tries to demonstrate, so I just left it in.

Fixes #17644.

### CODE REVIEW

File: lib/vector-buffers/src/variants/disk_v2/tests/invariants.rs [hunk 1]
```diff
@@ -820,3 +821,107 @@ async fn writer_updates_ledger_when_buffered_writer_reports_implicit_flush() {
...
+            // control how many records make it into a given data file. Just another way to ensure
+            // we're testing the position logic with multiple writes to one data file, one write to
+            // a data file, etc.
+            let (mut writer, mut reader, ledger) =
+                create_buffer_v2_with_max_data_file_size(data_dir, 256).await;
+
+            // We'll write multi-event records with N events based on these sizes, and as we do so,
+            // we'll assert that our writer position moves as expected after the write, and that
+            // after reading and acknowledging, the reader position also moves as expected.
+            let record_sizes = &[176, 52, 91, 137, 54, 87];
```
Comment (spencergilbert) [inline lib/vector-buffers/src/variants/disk_v2/tests/invariants.rs:851]: Are these chosen for any reason? Could/should they be randomized or something to avoid magic numbers?

**Review by spencergilbert — APPROVED** [review]

File: lib/vector-buffers/src/variants/disk_v2/tests/invariants.rs (hunk 1 above)
Comment (spencergilbert) [reply lib/vector-buffers/src/variants/disk_v2/tests/invariants.rs:851]: Got it, might be worth adding a comment to explain the reason behind the numbers down the line.
