### PR TITLE
fix(tests): Handle early return from influxdb create database

### LINKED ISSUE #5612: sinks::prometheus::remote_write::integration_tests::insert_metrics_over_http  CI failure
This is the first time I've seen this failure, but putting it here to track. It passes locally for me.

https://github.com/timberio/vector/runs/1578308476?check_suite_focus=true#step:9:566

```
test sinks::prometheus::remote_write::integration_tests::insert_metrics_over_http ... Dec 18 18:18:03.124 DEBUG http: vector::internal_events::http_client: Sending HTTP request. uri=http://localhost:8086/api/v1/prom/write?db=testdb0 method=POST version=HTTP/1.1 headers={"x-prometheus-remote-write-version": "0.1.0", "content-encoding": "snappy", "content-type": "application/x-protobuf", "user-agent": "Vector/0.12.0 (x86_64-unknown-linux-gnu)", "accept-encoding": "identity"} body=[188 bytes]
Dec 18 18:18:03.166 DEBUG http: vector::internal_events::http_client: HTTP response. status=404 Not Found version=HTTP/1.1 headers={"content-type": "application/json", "request-id": "5e1c9907-415d-11eb-8003-0242ac120002", "x-influxdb-build": "OSS", "x-influxdb-error": "database not found: \"testdb0\"", "x-influxdb-version": "1.8.3", "x-request-id": "5e1c9907-415d-11eb-8003-0242ac120002", "date": "Fri, 18 Dec 2020 18:18:03 GMT", "content-length": "44"} body=[44 bytes]
Dec 18 18:18:03.167 ERROR request{request_id=0}: vector::sinks::util::retries: Not retriable; dropping the request. reason="response status: 404 Not Found"
Dec 18 18:18:03.168 ERROR request{request_id=0}: vector::sinks::util::sink: Response wasn't successful. response=Response { status: 404, version: HTTP/1.1, headers: {"content-type": "application/json", "request-id": "5e1c9907-415d-11eb-8003-0242ac120002", "x-influxdb-build": "OSS", "x-influxdb-error": "database not found: \"testdb0\"", "x-influxdb-version": "1.8.3", "x-request-id": "5e1c9907-415d-11eb-8003-0242ac120002", "date": "Fri, 18 Dec 2020 18:18:03 GMT", "content-length": "44"}, body: b"{\"error\":\"database not found: \\\"testdb0\\\"\"}\n" }
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/sinks/prometheus/remote_write.rs:241:38
stack backtrace:
   0:     0x557fa290b6a0 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x557fa290b6a0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x557fa290b6a0 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x557fa290b6a0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x557fa2978e9c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x557fa28fd1d2 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x557fa291044d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x557fa291044d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x557fa291044d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x557fa29100f8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x557fa2910c71 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x557fa2910819 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x557fa290bb0c - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x557fa29107d9 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x557fa29759a1 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x557fa29758ed - core::panicking::panic::h184ede6dd822ffb4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:     0x557fa0f5487c - core::option::Option<T>::unwrap::h12f5af527d79c71f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  42:     0x557fa168b068 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc48829c2ba8b55d6
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:308
  43:     0x557fa168b068 - std::panicking::try::do_call::h95feedb4d9e8dd5b
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  44:     0x557fa168b068 - std::panicking::try::hc4c23f5f7d3bdd43
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  45:     0x557fa168b068 - std::panic::catch_unwind::hf3a57d903cc5007a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  46:     0x557fa168b068 - test::run_test_in_process::h09c598ed2a1f6695
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/lib.rs:543
  47:     0x557fa168b068 - test::run_test::run_test_inner::{{closure}}::h0723a32c882738ea
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/lib.rs:449
  48:     0x557fa168a75d - test::run_test::run_test_inner::hc4b9c44ce6ecf9ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/lib.rs:474
  49:     0x557fa16888de - test::run_test::h0db11a6e3cda4ec7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/lib.rs:504
  50:     0x557fa16759f0 - test::run_tests::hc96070f51a12d729
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/lib.rs:283
  51:     0x557fa16759f0 - test::console::run_tests_console::h11e87d1a2904198b
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/console.rs:280
  52:     0x557fa1684487 - test::test_main::h377dafce3c4130c7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/lib.rs:121
  53:     0x557fa1685829 - test::test_main_static::hf9870a0e0ff80b56
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/test/src/lib.rs:140
  54:     0x557fa06f6096 - vector::main::h0692b03911947697
  55:     0x557fa02ed77b - core::ops::function::FnOnce::call_once::ha4f0baac09e9c368
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
  56:     0x557fa02d7d2e - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f0dd362ff2ec3e1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:137
  57:     0x557f9fd98c81 - std::rt::lang_start::{{closure}}::h5ed6416a2be9cc5d
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:66
  58:     0x557fa2911187 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  59:     0x557fa2911187 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  60:     0x557fa2911187 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  61:     0x557fa2911187 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  62:     0x557fa2911187 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  63:     0x557f9fd98c57 - std::rt::lang_start::hcaf5cc05b5811d60
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:65
  64:     0x557fa06f60ca - main
  65:     0x7f1a321f60b3 - __libc_start_main
  66:     0x557f9fd7f6be - _start
  67:                0x0 - <unknown>
FAILED
```

### PR DESCRIPTION
**Pull request by bruceg**
Sometimes, the influxdb v1 server will return early from creating the
    database, providing an OK response code before the database is actually
    created. Subsequent sink calls will then encounter a NOT_FOUND response
    when trying to write to the database, resulting in a spurious failure.
    This tests for database existence after creating it by doing an empty
    write, and looping until that returns NO_CONTENT.

Closes #5612 

Signed-off-by: Bruce Guenter <bruce@timber.io>

### CODE REVIEW

File: src/sinks/influxdb/mod.rs [hunk 1]
```diff
@@ -392,25 +392,38 @@ pub mod test_util {
...
-        assert!(
-            status == http::StatusCode::OK,
-            format!("UnexpectedStatus: {}", status)
-        );
+        assert_eq!(status, http::StatusCode::OK, "UnexpectedStatus: {}", status);
+        // Some times InfluxDB will return OK before it can actually
+        // accept writes to the database, leading to test failures. Test
+        // this with empty writes and loop if it reports the database
+        // does not exist yet.
+        loop {
```
Comment (jszwedko) [inline src/sinks/influxdb/mod.rs:403]: I think it'd be good to have this loop break after, say, 10 iterations (5 seconds) to avoid this test hanging forever.

**Review by jszwedko — APPROVED** [review]
Nice! Looks good. I like the approach of looping until it is available.

I do think it'd be good to cap the loop so tests don't hang forever in extreme circumstances. You might just be able to use `test_util::wait_for_duration`? https://github.com/timberio/vector/blob/411100307f44d1d73933b0080dca1da254cd914d/src/test_util/mod.rs#L297-L309

**Review by jszwedko — APPROVED** [review]
