### PR TITLE
fix(buffers): fix shutdown bug with disk_v2 buffer

### LINKED ISSUE #10428: bug(buffers): disk buffer v2 doesn't close when vector triggers shutdown
When running a sink with the `disk_v2` buffer, shutting down Vector does not correctly trigger the buffer to shutdown, leading to the graceful shutdown running the full duration and finally triggering a forceful shutdown.

This may be due to `poll_close` not being actually called.  While the disk buffers v1 depends on checking the `Arc` strong count of the LevelDB `Database` handle, v2 depends on an explicit flag set when either `Writer::close` is called or the `Writer` is dropped.

### LINKED ISSUE #10429: bug(buffers): differentiate data directories for disk buffers v1 and v2
Currently, disk buffers end up using a data directory that is based on the global `data_dir` configuration value as well as the name of the sink the buffer was created for.

Technically speaking, the "final" data directory used already differs between `disk_v1` and `disk_v2`. For example, here are the resulting directories used when the config only differs by buffer type:
- `disk_v1`: `/tmp/vector/blackhole_id`
- `disk_v2`: `/tmp/vector/blackhole`

However, we should make this a little more explicit by encoding `v2` into the directory name for `disk_v1`, which will more clearly demonstrate that buffer is of the v2 variant.

### PR DESCRIPTION
**Pull request by tobz**
This PR fixes a bug with the disk_v2 buffer logic that prevented a reader from completing when the writer had shut down and all outstanding records had been read.

I'm going to try hard to avoid making this PR description longer than it should be.  The code comments themselves should be able to succinctly explain the "why" of the change.

Also, we've changed the data directory layout for disk_v2 buffers to further isolate them from disk_v1 buffers, per #10429.

Fixes #10428.
Fixes #10429.

### CODE REVIEW

File: lib/vector-core/buffers/src/disk_v2/reader.rs [hunk 1]
```diff
@@ -674,7 +674,7 @@ where
                 return Ok(None);
             }
 
-            self.ensure_ready_for_read().await.context(Io)?;
+            self.ensure_ready_for_read().await.context(IoSnafu)?;
```
Comment (spencergilbert) [inline lib/vector-core/buffers/src/disk_v2/reader.rs:677]: :chefkiss:

**Review by lukesteensen — APPROVED** [review]
