### PR TITLE
fix(buffers): apply stricter file permissions to buffer data files when possible

### LINKED ISSUE #18853: bug(buffers): disk buffer should attempt to constrain file permissions when possible
Currently, disk buffers do not explicitly attempt to set permissions on the directories/files they create, instead relying solely on whatever the prevailing system configuration dictates (i.e. Linux's `umask` setting).

This means that, in some cases, disk buffer files are world readable. While we do provide an [option](https://github.com/vectordotdev/vector/blob/master/distribution/systemd/hardened-vector.service#L53C7-L53C10) for hardening Vector, in terms of default file permissions, this is opt-in... and we can generally do better than that.

We should attempt to at least mark disk buffer directories/files as readable/writable by the owner and group, but entirely inaccessible by others/world. Given that Vector itself is the only process that should be touching the files, it stands to reason that we should not allow world/others to ever read or write to those files.

### PR DESCRIPTION
**Pull request by tobz**
This PR adds logic that constrains the file permissions for disk buffer data files, as well as the ledger, to only be readable/writable by the file owner: the user that the Vector process is running as.

Currently, the default permissions will typically to the files being readable by the group owner and world/other. There is no reason for outside processes to be able to read the disk buffer files. With the addition of secrets metadata to events stored in disk buffers, we want to ensure that the data files are as narrowly scoped to Vector as possible.

This has no affect on Windows systems, where setting file ACLs is more complex and does not have anywhere near as easy of a solution in code as doing so for Unix-based systems. This will likely be addressed in a future PR.

Fixes #18853.

### CODE REVIEW

File: lib/vector-buffers/src/variants/disk_v2/io.rs [hunk 1]
```diff
@@ -129,21 +131,21 @@ impl Filesystem for ProductionFilesystem {
...
-            .read(true)
-            .create(true)
-            .open(path)
-            .await
+        let mut open_options = tokio::fs::OpenOptions::new();
+        open_options.append(true).read(true).create(true);
+
+        configure_file_open_options_for_write(&mut open_options);
+
+        open_options.open(path).await
```
Comment (bruceg) [inline lib/vector-buffers/src/variants/disk_v2/io.rs:139]: This is an undesirable pattern (passing `&mut open_options`) compared to the builder pattern of the original. Since the ordering of the mode option doesn't matter (I think? correct me if I'm wrong), could we wrap the `new` and `mode` bits into the custom function, resulting in something like:
```suggestion
        new_file_with_write_options()
            .append(true)
            .read(true)
            .create(true)
            .open(path)
            .await
```

Comment (tobz) [reply lib/vector-buffers/src/variants/disk_v2/io.rs]: In ba90f4421, I've taken your suggestion and applied it to all areas that were creating some configuration of `OpenOptions`.

It's a little more code changed, but it deduplicates more code and the helper methods are at least documented so they drive home more of the intent, I believe.

**Review by bruceg — APPROVED** [review]
