### PR TITLE
fix(gcp_pubsub source): Handle connection errors by retrying

### LINKED ISSUE #12608: GCP PubSub source failing and not restarting
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using the PubSub source, after a period of time of successful event processing, the source throws and error and does not restart itself. Once the error has occured the pubsub source stops pulling events from PubSub

### Configuration

```text
---
sources:
  source_gcp_pubsub:
    type: gcp_pubsub
    project: <project>
    subscription: <subscription>
    ack_deadline_seconds: 10
```

### Version

nightly-2022-05-05-alpine

### Debug Output

```text
2022-05-05T11:25:32.385264Z ERROR source{component_kind="source" component_id=source_gcp_pubsub component_type=gcp_pubsub component_name=source_gcp_pubsub}: vector::internal_events::gcp_pubsub: Failed to fetch pub/sub events. error=status: InvalidArgument, message: "Request contains an invalid argument.", details: [], metadata: MetadataMap { headers: {"content-disposition": "attachment"} } error_code="failed_fetching_events" error_type="request_failed" stage="receiving"

2022-05-05T11:25:32.385339Z ERROR source{component_kind="source" component_id=source_gcp_pubsub component_type=gcp_pubsub component_name=source_gcp_pubsub}: vector::internal_events::gcp_pubsub: Failed to fetch pub/sub events. error=status: Unknown, message: "error reading a body from connection: stream error received: not a result of an error", details: [], metadata: MetadataMap { headers: {} } error_code="failed_fetching_events" error_type="request_failed" stage="receiving"
```

### Example Data

_No response_

### Additional Context

Running on Google Cloud Run using implicit auth

### References

_No response_

### PR DESCRIPTION
**Pull request by bruceg**
While the `gcp_pubsub` source catches errors, it does not actually try to reconnect when it encounters one that drops the connection. This fixes that.

Closes #12608

### CODE REVIEW

File: src/sources/gcp_pubsub.rs [hunk 1]
```diff
@@ -199,16 +199,21 @@ struct PubsubSource {
 
 impl PubsubSource {
     async fn run(mut self) -> crate::Result<()> {
+        while self.run_once().await? {}
```
Comment (jszwedko) [inline src/sources/gcp_pubsub.rs:202]: Under which conditions _would_ we like the source to exit on error?

Comment (bruceg) [reply src/sources/gcp_pubsub.rs]: Well, it's not exiting on error but on shutdown. I just added a patch that moves all other errors of `run_once` except for connections, which cause an exit.

Comment (jszwedko) [reply src/sources/gcp_pubsub.rs]: Ah, but wouldn't the `?` there cause it to exit on error too?

Should we exit if there was a connection error? I would think we'd just retry.

Comment (bruceg) [reply src/sources/gcp_pubsub.rs]: I see what you mean. Hmm, I think I'll punt that to a second issue and PR. This doesn't change that behavior, but AFAICT it _does_ fix the issue the OP had, as I saw it retry after that condition happened. We'll probably also want to add some configuration for that issue (retrying instantly is probably bad, etc).

**Review by jszwedko — APPROVED** [review]
