### PR TITLE
fix(elasticsearch sink): Gunzip Elasticsearch responses 

### LINKED ISSUE #8439: Compression between vector and ElasticSearch is not working for egress traffic
### Vector Version
```
0.15.0
```

### Vector Configuration File

```toml
    [sinks.es]
      type = "elasticsearch"
      inputs = ["es_timestamp"]
      healthcheck.enabled = true

      auth.strategy = "basic"
      auth.user = "---"
      auth.password = "---"
      endpoint = "---:9200"
      mode = "data_stream"
      data_stream.auto_routing = false
      data_stream.sync_fields = false
      data_stream.type = "---"
      data_stream.dataset = "logs"
      data_stream.namespace = "ds"

      compression = "gzip"

      batch.max_bytes = 50000000
      batch.timeout_secs = 1
      buffer.max_events = 10000000
      buffer.type = "memory"
      buffer.when_full = "block"

```

### Expected Behavior
When we configure compression = "gzip" for ElasticSearch sink it is expected that compression is applied in both directions - ingress and egress.
### Actual Behavior
Compression is applied only to ingress traffic.

### Workaround

Custom headers applied on the vector side fix the situation and the return traffic is also compressed.

```toml
    [sinks.es]
      compression = "gzip"
      # response compression
      request.headers.Accept-Encoding = "gzip"

```

### Additional Context

ES version - 7.13.1
Also tested with vector - 0.12.2

Compression is clearly enabled on all ES nodes.

It might be that vector is not configuring its headers correctly when compression is enabled. 
It seems that ES is expecting to receive specific headers that will instruct it for using compression on the reply traffic (egress)
https://discuss.elastic.co/t/http-compression-enabled-but-response-not-compressed/103513/7

Ingress Traffic Rates when we apply Compression
inbound_traffic_es
Egress Traffic Rates when we apply Compression
outbound_traffic_es
Egress Traffic Rates when we apply custom Headers and Compression
outbound_traffic_es_headers

### PR DESCRIPTION
**Pull request by davidhuie-dd**
Closes #8439

This PR enables support for gzip-encoded responses from ES. To do so, I bring in decompression courtesy of the tower_http library (thanks @spencergilbert). This also fixes a bug where gzipped responses from ES hid potential errors, as mentioned in the issue. This is because we performed a search for the string `\"errors\":true` [(here)](https://github.com/vectordotdev/vector/blob/67513b7db5689011b66430fa7545ecd9f0b886e1/src/sinks/elasticsearch/service.rs#L197) in ES responses to test for issues, so that string would be scrambled in a gzipped response.

In a previous PR (#15440), I experimented with adding decompression support globally to HttpClients. I decided that this is an easier change to introduce first, then we can discuss broader support.

### CODE REVIEW

File: src/sinks/elasticsearch/integration_tests.rs [hunk 1]
```diff
@@ -281,6 +281,23 @@ async fn insert_events_over_http() {
     .await;
 }
 
+#[tokio::test]
+async fn insert_events_over_http_with_compression() {
```
Comment (neuronull) [inline src/sinks/elasticsearch/integration_tests.rs:285]: Nit, same for the other function name.


```suggestion
async fn insert_events_over_http_with_gzip_compression() {
```

**Review by neuronull — APPROVED** [review]
Nice!

**Review by spencergilbert — APPROVED** [review]
