### PR TITLE
fix(cli): vector top is not refreshing

### LINKED ISSUE #22630: `vector top` no longer refreshes in 0.45.0
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The metrics in `vector top` no longer automatically refresh as of 0.45.0. I've attached a minimal config below which can reproduce this. The bug is not present in 0.44.0.

### Configuration

```text
api:
  enabled: true

sources:
  my_source_id:
    type: demo_logs
    format: apache_common
    lines:
      - line1

transforms: {}

sinks:
  my_sink_id:
    type: console
    inputs:
      - my_source_id
    encoding:
      codec: json
```

### Version

vector 0.45.0 (x86_64-unknown-linux-gnu 063cabb 2025-02-24 14:52:02.810034614)

### Debug Output

```text

```

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by JakubOnderka**
## Summary
Closes #22630

`connection_init` command should be send from client to API just once. 

It looks like that in `async-graphql` version 7.0.7 when this command was send multiple times, error message `{"type":"connection_error","payload":{"message":"Too many initialisation requests."}}` was returned to client, but the connection still operates and error message was silently ignored by client.

Since `async-graphql` version 7.0.8, that error message is also send to client, but also connection is closed by server.

This pull request changes client behavior that connection is initialized just once.

As this error is pretty annoying, it would be great that this PR will be merged soon.

## Change Type
- [x] Bug fix
- [ ] New feature
- [ ] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?
- [ ] Yes
- [x] No

## How did you test this PR?
By running `vector top` command

## Does this PR include user facing changes?

- [x] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the "no-changelog" label to this PR.

## Checklist
- [x] Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
  - `make check-all` is a good command to run locally. This check is
    defined [here](https://github.com/vectordotdev/vector/blob/1ef01aeeef592c21d32ba4d663e199f0608f615b/Makefile#L450-L454). Some of these
    checks might not be relevant to your PR. For Rust changes, at the very least you should run:
    - `cargo fmt --all`
    - `cargo clippy --workspace --all-targets -- -D warnings`
    - `cargo nextest run --workspace` (alternatively, you can run `cargo test --all`)
- [ ] If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
  run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

### CODE REVIEW

File: lib/vector-api-client/src/subscription.rs [hunk 1]
```diff
@@ -182,6 +172,9 @@ pub async fn connect_subscription_client(
     let (send_tx, mut send_rx) = mpsc::unbounded_channel::<Payload>();
     let (recv_tx, recv_rx) = mpsc::unbounded_channel::<Payload>();
 
+    // Initialize the connection
+    _ = ws_tx.send(Message::Text(r#"{"type":"connection_init"}"#.to_string())).await;
```
Comment (pront) [inline lib/vector-api-client/src/subscription.rs:176]: Thanks for the PR @JakubOnderka.

Nit: 

Did you try with:
```
_ = self.tx.send(Payload::init(id));
```
Because this hardcoded string payload is a bit arcane

**Review by pront — APPROVED** [review]
Tested this locally and it works. Thanks for diving into this!

File: lib/vector-api-client/src/subscription.rs (hunk 1 above)
Comment (JakubOnderka) [reply lib/vector-api-client/src/subscription.rs]: `Payload::init` requires uuid, that in that case is useless and putting random or null uuid is weird for me.

Second option is to use `serde_json::to_string(&json!({"type": "connection_init"})).unwrap()`, but I wanted to avoid unnecessary unwrapping.

**Comment by JakubOnderka** [comment]
Test for vector tap should be fixed now.

**Comment by JakubOnderka** [comment]
tap test is very unreliable, latest change should make it more reliable, but even then this test fails in 20 % of cases on my machine.

**Comment by pront** [comment]
> tap test is very unreliable, latest change should make it more reliable, but even then this test fails in 20 % of cases on my machine.

🤔 This wasn't the case before this fix. Any ideas how to make it stable?

File: lib/vector-tap/src/lib.rs [hunk 2]
```diff
@@ -294,13 +294,25 @@ mod tests {
         let server = tokio::spawn(async move {
             let (stream, _) = listener.accept().await.unwrap();
             let mut ws_stream = accept_async(stream).await.unwrap();
+            // The first message should be connection_init
```
Comment (pront) [inline lib/vector-tap/src/lib.rs:297]: I am convinced this is a test only failure. I tried this on my macos and my ubuntu machines. Also, this test has a lot of timeouts and is not reliable. Let's just remove the test.
