### PR TITLE
fix(gcp service): Apply `api_key` configuration to all GCP components

### LINKED ISSUE #13221: api_key for GCP Storage sink not working
### A note for the community

_No response_

### Problem

The docs mention using `api_key` for the GCP Storage sink but it did not work when I tried it. I took a look at the code and it seems like it's not being referenced anywhere: https://github.com/vectordotdev/vector/blob/39c5f13ac6956a577e3f333b54bc6b7ca2995fbc/src/sinks/gcp/cloud_storage.rs

Is this feature supposed to work, or is it mis-documented? Note, `api_key` appears in the following screenshot but is not listed as an actually argument on the same page.

image

### Configuration

```text
[sinks.out_gcp_storage]
type = "gcp_cloud_storage"
inputs = ["extract_pubsub_message"]
bucket = "railway-develop-logs"
key_prefix = "logs/{{ appname }}/"
api_key = "${LOGGER_GCP_API_KEY}"
```

### Version

vector 0.22.0 (x86_64-apple-darwin 5e937e3 2022-06-01)

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by bruceg**
This is both a bug fix and an enhancement, as it unifies all of the GCP authorization handling and applies it to all GCP components. This adds support for `api_key` and the internal `skip_authentication` to several components that were missing support, fixing the components to match the documentation.

Closes #13221

### CODE REVIEW

File: src/gcp.rs [hunk 1]
```diff
@@ -79,68 +82,90 @@ pub struct GcpAuthConfig {
...
+            Self::Credentials(_) | Self::None => (),
+            Self::ApiKey(api_key) => {
+                let mut parts = uri.clone().into_parts();
+                let path = parts
+                    .path_and_query
+                    .as_ref()
+                    .map_or("/", PathAndQuery::path);
+                let paq = format!("{path}?key={api_key}");
+                parts.path_and_query = Some(paq.parse().expect("FIXME"));
+                *uri = Uri::from_parts(parts).expect("FIXME");
```
Comment (spencergilbert) [inline src/gcp.rs:166]: Probably shouldn't leave as FIXME

Comment (jszwedko) [inline src/gcp.rs:166]: Seems like we need to update these `expect`s. Is there any way that a user could cause this to fail via configuration?

File: src/gcp.rs [hunk 2]
```diff
@@ -79,68 +82,90 @@ pub struct GcpAuthConfig {
...
+    pub fn apply_uri(&self, uri: &mut Uri) {
+        match self {
+            Self::Credentials(_) | Self::None => (),
+            Self::ApiKey(api_key) => {
+                let mut parts = uri.clone().into_parts();
+                let path = parts
+                    .path_and_query
+                    .as_ref()
+                    .map_or("/", PathAndQuery::path);
+                let paq = format!("{path}?key={api_key}");
```
Comment (jszwedko) [inline src/gcp.rs:164]: Wondering if we should percent encode the api_key just-in-case.

**Review by jszwedko — COMMENTED** [review]
Nice! I like the refactoring to share the logic. Just a couple of comments below (also some compilation errors which I'm sure you'll see :) ).

File: src/gcp.rs (hunk 2 above)
Comment (bruceg) [reply src/gcp.rs:164]: The `from_api_key` function checks to ensure the `api_key` is valid base64, which is a subset of what can be parsed here, so it will never fail to parse nor require encoding.

File: src/gcp.rs (hunk 1 above)
Comment (bruceg) [reply src/gcp.rs]: Fixed in 8f3946441

File: src/gcp.rs (hunk 2 above)
Comment (jszwedko) [reply src/gcp.rs:164]: Ah, cool, thanks for confirming 👍

**Review by jszwedko — APPROVED** [review]

**Review by jszwedko — COMMENTED** [review]
Looks like one last compilation error.

**Review by spencergilbert — APPROVED** [review]
