### PR TITLE
fix(file source): emit the correct start offset for multiline aggregated lines

### LINKED ISSUE #18955: wrong offset if first line is a multiline
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When a file source is configured with multiline and the first line of the file is a multiline, the offset property is not zero.

### Configuration

```text
sources:
  my_test_file:
    type: "file"
    include:
      - "/input/test.log"
    multiline:
      start_pattern: '^--'
      mode: "halt_before"
      condition_pattern: '^--'
      timeout_ms: 1000
    offset_key: "log.file.offset"
    read_from: "beginning"

sinks:
  my_sink_id:
    type: console
    inputs:
      - my_test_file
    encoding:
      codec: "json"
```

### Version

0.33

### Debug Output

```text
https://gist.github.com/mathiaz/3b4fee568c697fcb776b135d3bd66108
```

### Example Data

With the following test.log file:

```
--First
multi
line
```

vector outputs the following message:

```
2023-10-26T22:53:45.885048Z  INFO source{component_kind="source" component_id=my_test_file component_type=file component_name=my_test_file}:file_server: vector::internal_events::file::source: Found new file to watch. file=/input/test.log
{"file":"/input/test.log","host":"a66a2053b590","offset":15,"message":"-- First\nmulti\nline","source_type":"file","timestamp":"2023-10-26T22:53:46.888961982Z"}
```

Note that offset is set to 15 rather than 0.

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jches**
This should fix https://github.com/vectordotdev/vector/issues/18955 by updating `line_agg::Aggregate<C>` so that it carries both an initial context for the first line seen, and optionally (in the case of lines being merged) the context associated with the last line seen. The file source is then able to use those context objects to emit the correct start `offset` value for aggregated lines (the start position of the first line), and use the correct end offset for checkpointing. 

Related to this previous change: https://github.com/vectordotdev/vector/pull/14858

Fixes: https://github.com/vectordotdev/vector/issues/18955

### CODE REVIEW

File: src/sources/docker_logs/mod.rs [hunk 1]
```diff
@@ -1308,7 +1308,7 @@ fn line_agg_adapter(
         (stream, message, log)
     });
     let line_agg_out = LineAgg::<_, Bytes, LogEvent>::new(line_agg_in, logic);
-    line_agg_out.map(move |(_, message, mut log)| {
+    line_agg_out.map(move |(_, message, mut log, _)| {
```
Comment (jches) [inline src/sources/docker_logs/mod.rs:1311]: I am not sure whether it makes a difference that for lines that merged, `log` here changes from being the `LogEvent` generated by the first line, rather than the last line. I suspect not, but wanted to draw attention to this subtle change for reviewers.

File: src/line_agg.rs [hunk 2]
```diff
@@ -359,23 +363,25 @@ where
 
 struct Aggregate<C> {
     lines: Vec<Bytes>,
-    context: C,
+    initial_context: C,
+    context: Option<C>,
```
Comment (dsmith3197) [inline src/line_agg.rs:367]:
```suggestion
    initial_context: C,
    last_context: Option<C>,
```

**Review by dsmith3197 — CHANGES_REQUESTED** [review]
This looks good overall. Thanks for fixing this. There are some small comments to addressed before merging.

File: src/line_agg.rs [hunk 3]
```diff
@@ -254,14 +255,17 @@ where
         let val = match val {
             // If we have to emit just one line - that's easy,
             // we just return it.
-            (src, Emit::One((line, context))) => (src, line, context),
+            (src, Emit::One((line, context, last_context))) => (src, line, context, last_context),
```
[the remark this answers is not in the document]
Comment (jches) [reply src/line_agg.rs]: Yeah, good call. I've updated so now it should be: "context" anywhere it's the context of a specific line (e.g. in `handle_line`), and either "intitial_context" or "last_context" where it's associated with the aggregate.

**Review by dsmith3197 — APPROVED** [review]
Looks good. Thank you for fixing this!

File: src/line_agg.rs [hunk 4]
```diff
@@ -753,7 +782,7 @@ mod tests {
 
         assert_results(
             results.await.unwrap(),
-            &[(expected.as_str(), lines.len() - 1)],
+            &[(expected.as_str(), lines.len() - 1, None)],
```
Comment (jches) [inline src/line_agg.rs:785]: Looks like this test case is failing..the assertion should have zero as the initial context, and `Some(lines.len() - 1)` as the last_context.
