### PR TITLE
fix(prometheus_exporter sink): Escape quotes in tag values

### LINKED ISSUE #11823: Prometheus exporter sink does not escape double quotes in tag values
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Double quotes in tag values should be escaped using backslashes. Vector gives
```
# HELP 1m_load_avg 1m_load_avg
# TYPE 1m_load_avg gauge
1m_load_avg{host="host"1""} 1
```
While it should be
```
# HELP 1m_load_avg 1m_load_avg
# TYPE 1m_load_avg gauge
1m_load_avg{host="host\"1\""} 1
```

### Configuration

```text
sources:
  exec:
    type: exec
    mode: scheduled
    command:
      - echo
      - '{"host": "host\"1\"", "1m_load_avg": 1}'
transforms:
  remap:
    type: remap
    inputs:
      - exec
    source: |
      . = parse_json!(.message)
  log_to_metric:
    type: log_to_metric
    inputs:
      - remap
    metrics:
      - type: gauge
        field: 1m_load_avg
        tags:
          host: "{{ host }}"
sinks:
  prometheus_exporter:
    type: prometheus_exporter
    inputs:
      - log_to_metric
    address: 0.0.0.0:8080
```

### Version

0.20.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by bruceg**
Closes #11823

### CODE REVIEW

File: src/sinks/prometheus/collector.rs [hunk 1]
```diff
@@ -301,6 +301,20 @@ impl StringCollector {
     }
 }
 
+fn format_tag(key: &str, mut value: &str) -> String {
+    let mut result = String::with_capacity(key.len() + value.len() + 4);
+    result.push_str(key);
+    result.push_str("=\"");
+    while let Some(quote) = value.find('"') {
```
Comment (shenxn) [inline src/sinks/prometheus/collector.rs:308]: I think backslashes should be escaped as well. For example, `host\"1\"` should be formatted as `"host\\\"1\\\""` instead of `host\\"1\\"`

**Review by jszwedko — COMMENTED** [review]
👍 I agree with @shenxn that we should escape `\`s too.

File: src/sinks/prometheus/collector.rs (hunk 1 above)
Comment (bruceg) [reply src/sinks/prometheus/collector.rs]: Fixed

File: src/sinks/prometheus/collector.rs [hunk 2]
```diff
@@ -299,6 +299,22 @@ impl StringCollector {
             fullname, name, fullname, r#type
         )
     }
+
+    fn format_tag(key: &str, mut value: &str) -> String {
+        let mut result = String::with_capacity(key.len() + value.len() + 4);
```
Comment (jszwedko) [inline src/sinks/prometheus/collector.rs:304]: Nit, it seems like there is only a static extra 3 characters here? `="` and `"`.

**Review by jszwedko — APPROVED** [review]
Nice, thanks!
