### PR TITLE
fix(cli): Fix `top` quitting when the host has gone away

### LINKED ISSUE #8449: `vector top` doesn't shutdown on `esc`, `q`, or `ctrl-c` if  `vector` is shutdown before it
### Vector Version

```
vector 0.15.0 (x86_64-unknown-linux-gnu 994d812 2021-07-16)
```

### Vector Configuration File

Any with `api` enabled.

### Expected Behavior

`vector top` closing on `esc`, `q`, or `ctrl-c`.

### Actual Behavior

`vector top` stalls.

### Steps to reproduce it

1. Run  `vector -c ./...` with any config with `api` enabled.
2. Start `vector top`.
3. Shutdown `vector -c ./...` and wait for it to finish.
4. Try to close `vector top` which will then stall with just this printed in the console
```
Jul 25 11:28:37.566  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info" enable_datadog_tracing=false


```

### References

#7757 is maybe relevant.

### PR DESCRIPTION
**Pull request by leebenson**
Fixes #8449.

Note: This PR handles exiting gracefully (preventing the terminal stalling, and returning the cursor back to the active session). 

It doesn't tackle the CPU spike which still occurs when the host process is terminated. Tracking in #8770.

Signed-off-by: Lee Benson <lee@leebenson.com>

### CODE REVIEW

File: src/top/cmd.rs [hunk 1]
```diff
@@ -64,7 +64,8 @@ pub async fn cmd(opts: &super::Opts) -> exitcode::ExitCode {
 
     // Initialize the dashboard
     match init_dashboard(url.as_str(), opts, sender).await {
-        Ok(_) => exitcode::OK,
+        // Exit the process to clean up any lingering subscriptions.
+        Ok(_) => std::process::exit(0),
```
Comment (jszwedko) [inline src/top/cmd.rs:68]: This feels a bit weird to me in that the other match arm here returns the exit code rather than terminating the process directly. Is there a reason you needed to do this here rather than having the caller handle the exit code?

**Review by jszwedko — COMMENTED** [review]
~~🤔 I might be missing something, but this doesn't _seem_ to address the issue? I built it locally, but I was still unable to exit `vector top` (via `q`) if the other vector process serving the API exited first.~~

Thanks for looking into this though 😄  It has been a pet peeve of mine.

**EDIT** I was running `vector top` rather than `./target/debug/vector top` 🤦

File: src/top/cmd.rs (hunk 1 above)
Comment (leebenson) [reply src/top/cmd.rs:68]: The reason for the hard shut down at this point is to work around an active tungstenite client that's attempting to fire queries against a dead Websocket.

Even though the exit code is returned, since the thread is active, it prevents the process from quitting.

In #8770, I intend to introduce more granular control into the GraphQL subscription client for handling re-connection and ad hoc shutdown, which would make this block more elegant and allow it to propagate an exit code with any active subscriptions already cleaned up.

Another alternative would be to hard exit _after_ the sub-command block, rather than propagate the code back up as an `Err` (even if it's just `exitcode::OK` that's returned), but that seemed like a more invasive change rather than something that was specifically scoped to `top`.

For that reason, I elected to shutdown in the `top` command itself. Open to changing that per preference, however.

Comment (jszwedko) [reply src/top/cmd.rs:68]: Ah, yeah, I see. I'm fine with deferring the clean-up until we address https://github.com/vectordotdev/vector/issues/8770 . Would you want to just drop a link to that with a comment about cleaning up the subscriptions? I think that would make it less confusing for future readers who might have the same question I did.

Comment (leebenson) [reply src/top/cmd.rs]: 👍🏻 Added the following comment in 7be37e6754e9eceb48f45a5f6952ac91d5a98852:

> // Even though we could return an `exitcode::OK` here, the upstream block_on won't
> // return due to lingering subscriptions, which manifests as a hung cursor in the
> // terminal. To work around this for now, exit immediately.
> // TODO: https://github.com/vectordotdev/vector/issues/9206

**Review by jszwedko — APPROVED** [review]
The comment looks good, thank you!
