### PR TITLE
fix(transforms): optional metric namespace in `log_to_metric` transform

### LINKED ISSUE #21423: Metric namespace in `log_to_metric` transform is mandatory
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We were trying the newly introduced `parse_influxdb` vrl function, and as the [docs states](https://vector.dev/docs/reference/vrl/functions/#parse_influxdb), we should pass its output to a `log_to_metric` transform to generate Vector metric events from it (contrary to the `decoding.codec=influxdb`, which outputs _real_ metrics without the need of that transform)

We found that the `parse_influxdb` function does not output events with the namespace field
Example:
```json
{"gauge":{"value":82.0},"kind":"absolute","name":"weather_temperature","tags":{"location":"us-midwest"},"timestamp":"2016-06-13T17:43:50.100400200Z"}
```

And although in Vector's metric model the namespace is optional https://github.com/vectordotdev/vector/blob/88d6fe7faca520bd28eba308bf08846eb1823975/lib/vector-core/src/event/metric/series.rs#L99

It seems to be required by the `log_to_metric` transform https://github.com/vectordotdev/vector/blob/88d6fe7faca520bd28eba308bf08846eb1823975/src/transforms/log_to_metric.rs#L800

Should the `log_to_metric` transform to optionally populate the `namespace` field, only if present, and not fail if the namespace field is not present?

I can submit a PR addressing it, just want to ask if this is a desired behaviour

Thanks

### Configuration

```text
[sources.sample]
type = "demo_logs"
lines = ["weather,location=us-midwest temperature=82 1465839830100400200"]
format = "shuffle"

[transforms.influx]
type = "remap"
inputs = ["sample"]
source = """
. = parse_influxdb!(.message)
"""

[transforms.log_to_metric]
type = "log_to_metric"
inputs = ["influx"]
all_metrics = true
metrics = []

[sinks.console]
type = "console"
inputs = ["log_to_metric"]
encoding.codec = "json"
```

### Version

vector 0.41.1 (x86_64-unknown-linux-gnu)

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jorgehermo9**
Closes #21423

Now this config

```toml
[sources.sample]
type = "demo_logs"
lines = ["weather,location=us-midwest temperature=82 1465839830100400200"]
format = "shuffle"

[transforms.influx]
type = "remap"
inputs = ["sample"]
source = """
. = parse_influxdb!(.message)
"""

[transforms.log_to_metric]
type = "log_to_metric"
inputs = ["influx"]
all_metrics = true
metrics = []

[sinks.console]
type = "console"
inputs = ["log_to_metric"]
encoding.codec = "native_json"
```

Produces the following output:

```console
2024-10-05T09:19:29.994825Z  INFO vector::app: Log level is enabled. level="info"
2024-10-05T09:19:29.996361Z  INFO vector::app: Loading configs. paths=["config.toml"]
2024-10-05T09:19:30.009987Z  INFO vector::topology::running: Running healthchecks.
2024-10-05T09:19:30.010365Z  INFO vector::topology::builder: Healthcheck passed.
2024-10-05T09:19:30.010418Z  INFO vector: Vector has started. debug="true" version="0.42.0" arch="x86_64" revision=""
2024-10-05T09:19:30.010485Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
{"metric":{"name":"weather_temperature","tags":{"location":"us-midwest"},"timestamp":"2016-06-13T17:43:50.100400200Z","kind":"absolute","gauge":{"value":82.0}}}
{"metric":{"name":"weather_temperature","tags":{"location":"us-midwest"},"timestamp":"2016-06-13T17:43:50.100400200Z","kind":"absolute","gauge":{"value":82.0}}}
{"metric":{"name":"weather_temperature","tags":{"location":"us-midwest"},"timestamp":"2016-06-13T17:43:50.100400200Z","kind":"absolute","gauge":{"value":82.0}}}
```

### CODE REVIEW

File: src/transforms/log_to_metric.rs [hunk 1]
```diff
@@ -1608,11 +1611,19 @@ mod tests {
     }
 
     //  Metric Metadata Tests
+    //
     fn create_log_event(json_str: &str) -> Event {
+        create_log_event_with_namespace(json_str, Some("test_namespace"))
+    }
+
+    fn create_log_event_with_namespace(json_str: &str, namespace: Option<&str>) -> Event {
```
Comment (jorgehermo9) [inline src/transforms/log_to_metric.rs:1619]: Refactored this function a little bit to not duplicate code

File: src/transforms/log_to_metric.rs [hunk 2]
```diff
@@ -2003,4 +2014,42 @@ mod tests {
             .with_timestamp(Some(ts()))
         );
     }
+
+    #[tokio::test]
+    async fn transform_all_metrics_optional_namespace() {
```
Comment (jorgehermo9) [inline src/transforms/log_to_metric.rs:2019]: Added just one test with the `counter` metric kind. 

If you find that it would be useful to replicate this test but with the other metric kinds, tell me

File: changelog.d/21423-optional-namespace-log-to-metric.fix.md [hunk 3]
```diff
@@ -0,0 +1,2 @@
+When using the `all_metrics: true` flag in `log_to_metric` transform, the `namespace` field is now optional and no longer required. If the `namespace` field is not provided,
+the produced metric will not have a namespace at all.
```
Comment (jszwedko) [inline changelog.d/21423-optional-namespace-log-to-metric.fix.md:2]:
```suggestion
the produced metric will not have a namespace at all.

authors: jorgehermo9
```

**Review by jszwedko — APPROVED** [review]
Thanks for this quick fix!
