### PR TITLE
enhancement(regex_parser transform): Add support for `target_field`

### LINKED ISSUE #1812: `regex_parser` transform doesn't work with nested fields
Currently the `regex` crate which underlies our `regex_parser` implementation supports only `[_0-9a-zA-Z]+` as possible names for captures groups. Thus nested fields of form `x.y.z` cannot be captured.

For example, the following config unit test

```toml
[transforms.regex_parser_nested]
  inputs = []
  type = "regex_parser"
  regex = "^(?P<nested.timestamp>[\\w\\-:\\+]+) (?P<nested.level>\\w+) (?P<doubly.nested.message>.*)$"
[[tests]]
  name = "regex_parser_nested"
  [tests.input]
    insert_at = "regex_parser_nested"
    type = "raw"
    value = "2020-01-01T12:34:56Z INFO hello"
  [[tests.outputs]]
    extract_from = "regex_parser_nested"
    [[tests.outputs.conditions]]
      type = "check_fields"
      "nested.timestamp.equals" = "2020-01-01T12:34:56Z"
      "nested.level.equals" = "INFO"
      "doubly.nested.message.equals" = "hello"
```

fails with the error

```
Failed to build test 'regex_parser_nested':
  failed to build transform 'regex_parser_nested': Invalid regular expression: regex parse error:
      ^(?P<nested.timestamp>[\w\-:\+]+) (?P<nested.level>\w+) (?P<doubly.nested.message>.*)$
                 ^
  error: invalid capture group character
```

I think we need to allow field names containing dots. A simplest option to do this is to fork the `regex` crate and add support for it there, send a PR to the upstream, and use the fork until the support for dots in capture groups in added to the upstream crate.

### PR DESCRIPTION
**Pull request by bruceg**
Closes #1812

### CODE REVIEW

File: src/transforms/regex_parser.rs [hunk 1]
```diff
@@ -12,28 +12,21 @@ use std::collections::HashMap;
...
 use string_cache::DefaultAtom as Atom;
 
-#[derive(Deserialize, Serialize, Debug)]
+#[derive(Debug, Derivative, Deserialize, Serialize)]
+#[derivative(Default)]
 #[serde(default, deny_unknown_fields)]
 pub struct RegexParserConfig {
     pub regex: String,
     pub field: Option<Atom>,
+    #[derivative(Default(value = "false"))]
```
Comment (Hoverbear) [inline src/transforms/regex_parser.rs]:
```suggestion
    #[derivative(Default(value = "true"))]
```

File: .meta/transforms/regex_parser.toml [hunk 2]
```diff
@@ -39,4 +39,23 @@ description = """\
 The Regular Expression to apply. Do not include the leading or trailing `/`.\
 """
 
+[transforms.regex_parser.options.overwrite_target]
```
Comment (binarylogic) [inline .meta/transforms/regex_parser.toml]: I don't think we need this option. Other transforms simply overwrite existing values, which I think is a fine default.

**Comment by binarylogic** [comment]
Nice work. Everything else, docs wise, looks good to me.

File: src/transforms/regex_parser.rs [hunk 3]
```diff
@@ -204,38 +224,29 @@ mod tests {
...
 
-    fn do_transform(
-        event: &str,
-        regex: &str,
-        field: Option<&str>,
-        drop_field: bool,
-        drop_failed: bool,
-        types: &[(&str, &str)],
-    ) -> Option<LogEvent> {
+    fn do_transform(event: &str, regex: &str, config: &str) -> Option<LogEvent> {
```
Comment (Hoverbear) [inline src/transforms/regex_parser.rs]: 🎉

File: src/transforms/regex_parser.rs (hunk 1 above)
Comment (bruceg) [reply src/transforms/regex_parser.rs]: This follows the lead of other parser transforms like `json_parser` that default to `false`.

File: .meta/transforms/regex_parser.toml (hunk 2 above)
Comment (bruceg) [reply .meta/transforms/regex_parser.toml]: As indicated to @Hoverbear, this mirrors the `json_parser` transform. Since it is the only other parser transform that includes the `target_field` capability, I thought it made sense to copy its behavior as well.

File: src/transforms/regex_parser.rs (hunk 1 above)
Comment (Hoverbear) [reply src/transforms/regex_parser.rs]: Please update https://github.com/timberio/vector/blob/8c252a2c32fda4317284be46b70cf2e64e13d651/.meta/transforms/regex_parser.toml#L18 then! :)

File: .meta/transforms/regex_parser.toml (hunk 2 above)
Comment (binarylogic) [reply .meta/transforms/regex_parser.toml]: Ah, I wasn't aware we had an `overwrite_target` option. Ignore my comment then.

File: src/transforms/regex_parser.rs (hunk 1 above)
Comment (bruceg) [reply src/transforms/regex_parser.rs]: That would be the default for `drop_field`, which is a different setting.

Comment (Hoverbear) [reply src/transforms/regex_parser.rs]: Yes, but in your branch:

image

image
In master:

image

https://github.com/timberio/vector/blob/9cd0ba6fca6b577c4c76956fc550496f5031175f/.meta/transforms/regex_parser.toml#L18

https://github.com/timberio/vector/blob/9cd0ba6fca6b577c4c76956fc550496f5031175f/src/transforms/regex_parser.rs#L30

**Review by lukesteensen — COMMENTED** [review]
I'm curious how people feel about the `overwrite_target` option. I'm not sure it's useful enough to warrant the additional implementation complexity, but there may be use cases I'm not thinking about.

(I could have sworn we talked about this somewhere but now I can't find it)

**Comment by binarylogic** [comment]
I'm indifferent, but I tend to agree it adds confusion to the UX as well. My opinion is not strong.

File: src/transforms/regex_parser.rs (hunk 1 above)
Comment (bruceg) [reply src/transforms/regex_parser.rs]: Ah I see it now, sorry. That was part of a lead up patch that I had forgotten about. Will fix.

**Comment by bruceg** [comment]
So where are we with `overwrite_target`? Should I leave it the same as `json_parser`, make it default to `true`, or drop it entirely?

**Comment by binarylogic** [comment]
Leave it and default it to `true`. It's fine as an advanced option. We should follow up by changing the default to `true` in the `json_parser` as well.

**Review by Hoverbear — APPROVED** [review]

**Review by binarylogic — APPROVED** [review]
Looks good!

**Comment by binarylogic** [comment]
Merging so that we can get this in `0.9.0`.
