### PR TITLE
fix: apply encoding rules in sinks

### LINKED ISSUE #3763: LogDNA sink does not honour `encoding.only_fields`
Greetings!

Thanks for all the hard work on vector, it's awesome!

I put together a simple test case:

vector.toml:
```
[sources.testlogs]
  type = "file" # required
  include = ["/testlogs/*.log"] # required

[transforms.add_fields]
  # General
  type = "add_fields" # required
  inputs = ["testlogs"] # required

  # Fields
  fields.someotherfield = "plsdontinclude"

[sinks.logdna_stag]
  type = "logdna" # required
  inputs = ["add_fields"]
  healthcheck = false
  host = "https://webhook.site/e248d113-6b92-438f-80cd-a5a81e796aa0"
  api_key = "trash" # required
  hostname = "${HOSTNAME}" # required

  encoding.only_fields = ["timestamp"]
```

I ran this and echoed to a file such that it POSTed:
```
{
  "lines": [
    {
      "file": "/testlogs/hello.log",
      "line": "test-1",
      "meta": {
        "host": "aa1688d9cc0e",
        "someotherfield": "plsdontinclude",
        "source_type": "file"
      },
      "timestamp": "2020-09-07T23:06:00.917702547Z"
    },
    ...
```

As I understand it, `someotherfield` should not be in there, because it's not in `encoding.only_fields`. From the [docs](https://vector.dev/docs/reference/sinks/logdna/#only_fields):
> Limit the sink to only encoding the specified labels.

Thanks!

### PR DESCRIPTION
**Pull request by fanatid**
Closes #3763 

I also checked all sinks and fixed Influxdb logs, Pulsar in addition to LogDNA.

/cc @jchorl

### CODE REVIEW

**Comment by binarylogic** [comment]
I'm curious how we could test for this? Even just linting a config via `vector validate` would have caught this, right?

**Comment by fanatid** [comment]
:thinking: I'm not sure that we can catch this automatically for each sink which use encoding, but for fixed here I can add tests (what would be correct I think)

**Comment by binarylogic** [comment]
I think #1735 would have helped. Which would have errored on the `encoding` option for these sinks.

**Comment by jchorl** [comment]
Thank you so much for the very quick fix!!

> I'm curious how we could test for this? Even just linting a config via `vector validate` would have caught this, right?

Agreed, this seems like the kind of bug that'll just hit the next sink type as well. Looking at the code though, the logic seems baked into the vendor-specific sink logic. `encode_event` is probably the wrong layer to execute this logic, because you need to remember to call `apply_rules`. I don't know rust well enough to know the right solution here - although I'd think something like:
1. Create a `ProcessedForEncoding` type that `apply_rules` returns
1. Make `encode_event` only accept a `ProcessedForEncoding`
1. Add a generic impl of `apply_rules`

Clients can call `apply_rules` and feed the results into `encode_event`, they'll be forced to because that's all `encode_event` will accept.

I don't know how else you'd ensure in each vendor-specific sink that a function gets called but would love ideas here.

**Comment by lukesteensen** [comment]
> Even just linting a config via `vector validate` would have caught this, right?

No. All of the configs had an `encoding` field and would parse it just fine. The problem is that they were not applying the encoding rules.

> Looking at the code though, the logic seems baked into the vendor-specific sink logic. `encode_event` is probably the wrong layer to execute this logic, because you need to remember to call `apply_rules`.

The problem is that when to apply the encoding rules is often specific to the sink. See #3715 for example.

File: src/sinks/logdna.rs [hunk 1]
```diff
@@ -101,7 +101,8 @@ impl HttpSink for LogdnaConfig {
     type Input = serde_json::Value;
     type Output = Vec<BoxedRawValue>;
 
-    fn encode_event(&self, event: Event) -> Option<Self::Input> {
+    fn encode_event(&self, mut event: Event) -> Option<Self::Input> {
+        self.encoding.apply_rules(&mut event);
```
Comment (lukesteensen) [inline src/sinks/logdna.rs:105]: Should we apply these rules after we pull off the fields below?

Comment (fanatid) [reply src/sinks/logdna.rs:105]: Good question... I think we should not because below we change fields for the sink. If we move, then it would be possible to change the already build event?
TODO: need to check all `apply_rules`.. :disappointed:

Comment (fanatid) [reply src/sinks/logdna.rs:105]: Reviewed all sinks and made changes where it was required.

**Review by bruceg — APPROVED** [review]

File: src/sinks/datadog/logs.rs [hunk 2]
```diff
@@ -79,8 +74,6 @@ fn encode_event(
     api_key: &str,
     encoding: &EncodingConfig<Encoding>,
 ) -> Option<Bytes> {
-    encoding.apply_rules(&mut event);
```
Comment (lukesteensen) [inline src/sinks/datadog/logs.rs:82]: Do we need to add this back somewhere?

File: src/sinks/gcp/stackdriver_logs.rs [hunk 3]
```diff
@@ -172,8 +171,11 @@ impl HttpSink for StackdriverSink {
             .map(remap_severity)
             .unwrap_or_else(|| 0.into());
 
+        let mut event = Event::Log(log);
+        self.config.encoding.apply_rules(&mut event);
```
Comment (lukesteensen) [inline src/sinks/gcp/stackdriver_logs.rs:175]: Do you think we should open an issue to make `apply_rules` take a `LogEvent`?

File: src/sinks/influxdb/logs.rs [hunk 4]
```diff
@@ -235,6 +240,31 @@ mod tests {
...
+        event.as_mut_log().insert("timestamp", ts());
+
+        let mut sink = create_sink(
+            "http://localhost:9999",
+            "my-token",
+            ProtocolVersion::V1,
+            "ns",
+            vec![],
+        );
+        sink.encoding.except_fields = Some(vec![Atom::from("host")]);
```
Comment (lukesteensen) [inline src/sinks/influxdb/logs.rs:256]: Are we asserting that `host` is not included in the output?

File: src/sinks/pulsar.rs [hunk 5]
```diff
@@ -225,6 +227,27 @@ mod tests {
...
+        let msg = "hello_world";
+
+        let mut evt = Event::from(msg);
+        evt.as_mut_log().insert("key", "value");
+
+        let event = encode_event(
+            evt,
+            &EncodingConfigWithDefault {
+                codec: Encoding::Text,
+                except_fields: Some(vec![Atom::from("key")]),
```
Comment (lukesteensen) [inline src/sinks/pulsar.rs:242]: I'm not sure what this is testing. Encoding to text doesn't usually include fields other than `message`, so I feel like we shouldn't even allow `except_fields` in this case.

File: src/sinks/papertrail.rs [hunk 6]
```diff
@@ -107,3 +102,33 @@ fn encode_event(
...
+        evt.as_mut_log().insert("magic", "key");
+
+        let bytes = encode_event(
+            evt,
+            0,
+            &EncodingConfig {
+                codec: Encoding::Json,
+                only_fields: None,
+                except_fields: Some(vec![Atom::from("magic")]),
+                // except_fields: None,
```
Comment (lukesteensen) [inline src/sinks/papertrail.rs:123]: Can probably clean this up.

File: src/sinks/gcp/stackdriver_logs.rs (hunk 3 above)
Comment (bruceg) [reply src/sinks/gcp/stackdriver_logs.rs:175]: Or the reverse, `fn LogEvent::apply_encoding(&mut self, encoding: &Encoding)`?

File: src/sinks/datadog/logs.rs (hunk 2 above)
Comment (bruceg) [reply src/sinks/datadog/logs.rs:82]: This one caught me too. That function calls `util::encode_event(event, encoding)` further down, which calls this, so this change just removes the double call to it.

Comment (lukesteensen) [reply src/sinks/datadog/logs.rs:82]: Aha, that makes sense.

**Review by jszwedko — APPROVED** [review]
I just focused on the `splunk_hec` sink as the CODEOWNER there. That looks good to me!

I agree it's a bit unfortunate that we need to apply this in every sink. It does seem like we are liable to miss it again in the future.

File: src/sinks/pulsar.rs (hunk 5 above)
Comment (fanatid) [reply src/sinks/pulsar.rs:242]: This is not correct test, thanks! I'll change to `Encoding::Json`.

File: src/sinks/influxdb/logs.rs (hunk 4 above)
Comment (fanatid) [reply src/sinks/influxdb/logs.rs:256]: Yes, we asserting that `host` is not included

File: src/sinks/gcp/stackdriver_logs.rs (hunk 3 above)
Comment (fanatid) [reply src/sinks/gcp/stackdriver_logs.rs:175]: Yeah, it would be nice to have any of these
