### PR TITLE
fix(codecs): deny unknown fields on transformer config

### LINKED ISSUE #13783: sink: wrong "encoding.onlyfields" option does not fail vector config validation
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector configuration check fails to detect wrong encoding.onlyfields option (encoding.only_fields is valid)

[sinks.out]
... 
type = "console"
encoding.codec = "json"
encoding.onlyfields = [ "message","aa"]

=> Vector does not give a warning that this is not correct and will output all the fields instead of the wanted fields

### Configuration

```text
[sources.in]
type = "stdin"

[sinks.out]
inputs = ["modify"]
type = "console"
encoding.codec = "json"
encoding.onlyfields = [ "message","aa"]

[transforms.modify]
type = "remap"
inputs = ["in"]
source = ''' 
 .  = parse_json!(string!(.message))
 .message="DeMessage"
'''
```

### Version

vector 0.23.0 (x86_64-apple-darwin 38c2435 2022-07-11)

### Debug Output

```text
2022-08-01T15:52:44.258064Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,kube=trace"
2022-08-01T15:52:44.258197Z  INFO vector::config::watcher: Creating configuration file watcher.
2022-08-01T15:52:44.261816Z  INFO vector::config::watcher: Watching configuration files.
2022-08-01T15:52:44.261880Z  INFO vector::app: Loading configs. paths=["debug.toml"]
2022-08-01T15:52:44.263029Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
2022-08-01T15:52:44.264361Z DEBUG vector::topology::builder: Building new source. component=in
2022-08-01T15:52:44.264806Z DEBUG vector::topology::builder: Building new transform. component=modify
2022-08-01T15:52:44.264935Z  INFO vector::sources::stdin: Capturing STDIN.
2022-08-01T15:52:44.265038Z DEBUG vector::topology::builder: Building new sink component=out
2022-08-01T15:52:44.265150Z  INFO vector::topology::running: Running healthchecks.
2022-08-01T15:52:44.265177Z DEBUG vector::topology::running: Connecting changed/added component(s).
2022-08-01T15:52:44.265199Z DEBUG vector::topology::running: Configuring outputs for source. component=in
2022-08-01T15:52:44.265210Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-08-01T15:52:44.266176Z DEBUG vector::topology::running: Configuring output for component. component=in output_id=None
2022-08-01T15:52:44.266216Z DEBUG vector::topology::running: Configuring outputs for transform. component=modify
2022-08-01T15:52:44.266235Z DEBUG vector::topology::running: Configuring output for component. component=modify output_id=None
2022-08-01T15:52:44.266254Z DEBUG vector::topology::running: Connecting inputs for transform. component=modify
2022-08-01T15:52:44.266284Z DEBUG vector::topology::running: Adding component input to fanout. component=modify fanout_id=in
2022-08-01T15:52:44.266305Z DEBUG vector::topology::running: Connecting inputs for sink. component=out
2022-08-01T15:52:44.266324Z DEBUG vector::topology::running: Adding component input to fanout. component=out fanout_id=modify
2022-08-01T15:52:44.266357Z DEBUG vector::topology::running: Spawning new source. key=in
2022-08-01T15:52:44.266401Z DEBUG vector::topology::running: Spawning new transform. key=modify
2022-08-01T15:52:44.266451Z TRACE vector::topology::running: Spawning new sink. key=out
2022-08-01T15:52:44.266452Z DEBUG source{component_kind="source" component_id=in component_type=stdin component_name=in}: vector::topology::builder: Source pump starting.
2022-08-01T15:52:44.266571Z  INFO vector: Vector has started. debug="false" version="0.23.0" arch="x86_64" build_id="38c2435 2022-07-11"
2022-08-01T15:52:44.266611Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
2022-08-01T15:52:44.267911Z TRACE vector: Beep.
```

### Example Data

{"aa":200,"cc":"Overrule","message":"DeMessage"}
 
with the wrong option (encoding.onlyfields) gives output: {"aa":200,"cc":"Overrule","message":"DeMessage"} 
expected behaviour: The vector startup should stop with an error

### Additional Context

no

### References

_No response_

### PR DESCRIPTION
**Pull request by tobz**
In #13783, a user reported that despite specifying an invalid configuration field (`onlyfields` vs `only_fields`), Vector still loaded their configuration without issue, leading to a scenario where the intended behavior (only allow specify fields) did not occur, as they believe the configuration was valid.

We've simply added the `#[serde(deny_unknown_fields)]` annotation to detect this scenario, as well as a unit test to ensure we've correctly fixed the issue. There's certainly precedent to potentially use `deny_unknown_fields` by default with an escape hatch for necessary situations, but I figured it was easy enough to fix in this isolated case.

Closes #13783.

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

File: src/codecs/encoding/transformer.rs [hunk 1]
```diff
@@ -356,4 +357,16 @@ mod tests {
         "#});
         assert!(config.is_err())
     }
+
+    #[test]
+    fn deny_unknown_fields() {
+        // We're only checking this explicitly because of our custom deserializer arrangement to
+        // make it possible to throw the exclusivity error during deserialization, to ensure that we
+        // enforce this on the top-level `Transformer`g type even though it has to be applied at the
```
Comment (neuronull) [inline src/codecs/encoding/transformer.rs:365]: Is that `g` char after `Transformer` , a typo ?

Comment (tobz) [reply src/codecs/encoding/transformer.rs]: Ah, nice catch. That was indeed a woopsie daisy.

Fixed in ad7006dba.

**Review by neuronull — APPROVED** [review]
