### PR TITLE
fix(buffers): initial write offset sometimes calculated incorrectly in disk v1

### LINKED ISSUE #11573: Disk buffer v1 doesn't calculate starting write offset based off last record's event count
As part of the work in #11454, we switched over the disk buffer implementations to utilize `EventCount`.  In order to do so, the event count of a record essentially became part of how we increment record IDs/keys.

When we first load a disk v1 buffer, we should be reading the last record, taking its key, and adding its event count to the key to figure out the next key, or write offset, that the writer should use.  We missed updating this area of the code in #11454, as it currently still increments by a hard-coded amount of one, which is valid for the previous logic but not for the new logic:

https://github.com/vectordotdev/vector/blob/2df5d1a00883c4c86a21a29d8e294dd85790fb4b/lib/vector-buffers/src/variants/disk_v1/mod.rs#L321

Like the code in `db_initial_size`, we need to decode the last record to get its event count so the offset can be correctly calculated.

### PR DESCRIPTION
**Pull request by tobz**
As part of the work in #11454, we mistakenly missed a spot when it came to ensuring we were using the event count of records when adjusting IDs and positions, specifically in calling the initial write offset for a disk v1 buffer.

This PR addresses that, and closes #11573.

### CODE REVIEW

File: lib/vector-buffers/src/variants/disk_v1/tests/mod.rs [hunk 1]
```diff
@@ -113,3 +113,88 @@ macro_rules! assert_reader_v1_delete_position {
         );
     }};
 }
+
+#[macro_export]
+macro_rules! assert_buffer_usage_metrics {
```
Comment (blt) [inline lib/vector-buffers/src/variants/disk_v1/tests/mod.rs:118]: This is some macro.

File: lib/vector-buffers/src/variants/disk_v1/mod.rs [hunk 2]
```diff
@@ -241,47 +250,85 @@ where
...
+                        "Detected undecodable record when querying initial state of buffer. Dropping record and continuing."
+                    );
+
+                    // Set our write offset, and update the last key, to compensate for the fact
+                    // this record is going away.  Also update our buffer byte size value, too.
+                    state.write_offset = Some(last_key);
+                    if state.first_key != state.last_key {
+                        // If this isn't the only record, then go back by one to get the end of the
+                        // previous record.  Otherwise, our last key shouldn't move at all.
+                        state.last_key = Some(last_key.wrapping_sub(1));
```
Comment (bruceg) [inline lib/vector-buffers/src/variants/disk_v1/mod.rs:305]: Will this still work if the previous record contains more than one event?

File: lib/vector-buffers/src/variants/disk_v1/tests/mod.rs [hunk 3]
```diff
@@ -113,3 +113,88 @@ macro_rules! assert_reader_v1_delete_position {
...
+            @asserts ($($field => $expected,)* received_event_count => $recv_events),
+            $($tail)*
+        );
+    }};
+    ($usage:expr, @asserts ($($field:ident => $expected:expr),*), recv_events => $recv_events:expr) => {{
+        assert_buffer_usage_metrics!(
+            $usage,
+            @asserts ($($field => $expected,)* received_event_count => $recv_events)
+        );
+    }};
```
Comment (bruceg) [inline lib/vector-buffers/src/variants/disk_v1/tests/mod.rs:137]: Can these (and other pairs below) be combined by eliminating the `,` and adding an empty base case?
```suggestion
    ($usage:expr, @asserts ($($field:ident => $expected:expr),*), recv_events => $recv_events:expr $($tail:tt)*) => {{
        assert_buffer_usage_metrics!(
            $usage,
            @asserts ($($field => $expected,)* received_event_count => $recv_events)
            $($tail)*
        );
    }};
```

File: lib/vector-buffers/src/variants/disk_v1/mod.rs (hunk 2 above)
Comment (tobz) [reply lib/vector-buffers/src/variants/disk_v1/mod.rs:305]: Actually, thinking this through: no, what I'm doing there doesn't make a ton of sense.  We also don't need to update `last_key`, though, since it's really just a temporary for the sake of calculating the total event count.

I'll change this section up to reflect that all we really care about is the size in events/bytes, and the read/write offset.

File: lib/vector-buffers/src/variants/disk_v1/tests/mod.rs (hunk 3 above)
Comment (tobz) [reply lib/vector-buffers/src/variants/disk_v1/tests/mod.rs:137]: It's not possible to use that specific syntax -- expressions need terminating tokens when the macro definition also allows arbitrary tokens (TTs) to come after the expression -- but I can just slim it down so that all field/expectation pairs have to be terminated with a comma, since that's trivial and not really a burden at all.

File: lib/vector-buffers/src/variants/disk_v1/mod.rs (hunk 2 above)
Comment (tobz) [reply lib/vector-buffers/src/variants/disk_v1/mod.rs]: Addressed in 6da55f3cf.

File: lib/vector-buffers/src/variants/disk_v1/tests/mod.rs (hunk 3 above)
Comment (tobz) [reply lib/vector-buffers/src/variants/disk_v1/tests/mod.rs]: Addressed in 6da55f3cf.

File: lib/vector-buffers/src/variants/disk_v1/mod.rs [hunk 4]
```diff
@@ -241,13 +249,12 @@ where
...
-    let mut byte_size = 0;
-    let mut key_count = 0;
     let mut first_key = None;
     let mut last_key = None;
+    let mut state = BufferState::default();
     for (k, v) in db.iter(ReadOptions::new()) {
-        byte_size += v.len() as u64;
-        key_count += 1;
+        state.total_bytes += v.len() as u64;
+        state.total_records += 1;
```
Comment (bruceg) [inline lib/vector-buffers/src/variants/disk_v1/mod.rs:257]: I'm not a big fan of the `mut` state struct pattern. I'd rather see individual variables and construct the resulting state at the end, which also avoids the need for a `Default` here.

**Review by bruceg — APPROVED** [review]
LGTM. I left one code smell comment below, but it's not a blocker.

**Review by blt — APPROVED** [review]

File: lib/vector-buffers/src/variants/disk_v1/mod.rs (hunk 4 above)
Comment (tobz) [reply lib/vector-buffers/src/variants/disk_v1/mod.rs:257]: I can I have no problem cleaning it up to fit that model.

For my own curiosity, though: what do you see as the downsides of the state struct being used mutably? Given that there's no way to freeze the struct, given visibility rules within the same module, it feels like the same difference regardless of how I construct it.

Comment (bruceg) [reply lib/vector-buffers/src/variants/disk_v1/mod.rs:257]: It makes no real changes for _this_ struct, as all the data is simple integers. It's more a pattern issue to avoid as a general practice:
1. The variables have needlessly longer names (trivial).
2. It uses struct internals in a non-member function (relatively trivial)
3. With other data types, there could be the overhead of extra allocations, or `Drop` on early return, or other side effects.
4. Without the struct variables, this particular loop could be reduced to a `fold` adapter on the iterator (albeit somewhat complex given the four pieces of data being folded) to eliminate mutable state.

Comment (tobz) [reply lib/vector-buffers/src/variants/disk_v1/mod.rs:257]: Yeah, OK, I buy that and appreciate the thoughtfulness of the response.

This will be good information that we can hopefully add to a style guide, in the future, if I get around to writing the RFC... 😅
