### PR TITLE
fix(splunk_hec sink): Fix handling of indexer acknowledgements config

### LINKED ISSUE #11615: `splunk_hec_logs` sink no longer accepts indexer acknowledgements options
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

After merging #11346, the indexer acknowledgements options for the `splunk_hec_logs` sink shadow the outer `acknowledgements` options, preventing the indexer acknowledgements from being enabled or configured. These outer options needed to be common across all sinks to enable the propagation to their respective connected sources. Furthermore those outer options are not marked to deny unknown fields, so configurations with indexer options will silently be accepted and ignored.

I have come up with some options, none of which I find appealing:
1. Rename the outer configuration. This will end up giving it a different name than the existing source `acknowledgements` option, which will be surprising to users.
2. Rename the inner indexer acknowledgements configuration. This will break existing configs with those options.
3. Add a function to the inner trait type and a new field to all sinks that support acknowledgements (33). This adds a lot of extra code for this naming conflict.

### Configuration

_No response_

### Version

current `master` head

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by bruceg**
This moves the `acknowledgements` configuration from `struct SinkOuter` into
the individual sinks, and exposes it through a new `fn acknowledgements` in the
`SinkConfig` trait. Most of the changes except for the core config and
splunk_hec sink are purely mechanical.

Closes #11615

### CODE REVIEW

File: src/sinks/splunk_hec/common/acknowledgements.rs [hunk 1]
```diff
@@ -26,6 +27,13 @@ pub struct HecClientAcknowledgementsConfig {
     pub query_interval: NonZeroU8,
     pub retry_limit: NonZeroU8,
     pub max_pending_acks: NonZeroU64,
+    #[serde(
+        default,
+        deserialize_with = "crate::serde::bool_or_struct",
+        flatten,
+        skip_serializing_if = "crate::serde::skip_serializing_if_default"
+    )]
+    pub inner: AcknowledgementsConfig,
```
Comment (001wwang) [inline src/sinks/splunk_hec/common/acknowledgements.rs:36]: With this added, I think we can remove/deprecate the `indexer_acknowledgements_enabled` option (replacing its use with `inner.enabled`).

**Review by wbew — COMMENTED** [review]
Nice! Just one comment on the `splunk_hec` configuration.

File: src/sinks/splunk_hec/common/acknowledgements.rs (hunk 1 above)
Comment (bruceg) [reply src/sinks/splunk_hec/common/acknowledgements.rs:36]: Oh, I thought we would want to separate the indexer acknowledgements from the end-to-end acknowledgements. I'll raise that as a follow-up issue once this is merged.

Comment (001wwang) [reply src/sinks/splunk_hec/common/acknowledgements.rs:36]: Mm, perhaps I have the wrong idea here. Currently if `indexer_acknowledgements_enabled` is `true` we integrate acknowledge based on indexer acks and if `false` we acknowledge based solely on the `200` response. What will the effect of `inner.enabled` `true/false` be?

Comment (bruceg) [reply src/sinks/splunk_hec/common/acknowledgements.rs:36]: The `AcknowledgementConfig` is not used in the sink itself. Rather it is used, when enabled, to turn on acknowledgements on all connected sources.

Comment (001wwang) [reply src/sinks/splunk_hec/common/acknowledgements.rs:36]: Aha, right -- had things mixed up conceptually. That makes sense, never mind what I said then.

**Review by wbew — APPROVED** [review]

**Review by jszwedko — APPROVED** [review]
