### PR TITLE
enhancement(config): extend environment variables interpolation syntax

### LINKED ISSUE #10420: [EnvVar Interpolation] Add support for empty string defaults
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
vector 0.18.1 (x86_64-unknown-linux-gnu c4adb60 2021-11-30)
```

### Use-cases

* Interpolation of environment variables into Vector configuration files.
* Interpolation of variables with defaults that can be empty strings, i.e. for declaring optional variables.

### Attempted Solutions

At the moment, Vector is unable to use the empty string as a default for interpolated environment variables.

Consider the following simple Vector pipeline configuration file in YAML:
```yaml
sources:
  logs:
    type: demo_logs
    format: syslog

sinks:
  http:
    type: http
    inputs:
      - logs
    uri: ${SINKS_HTTP_URI:-http://localhost:8080}
    proxy:
      enabled: ${SINKS_HTTP_PROXY_ENABLED:-true}
      http: ${SINKS_HTTP_PROXY_HTTP:-}
      https: ${SINKS_HTTP_PROXY_HTTPS:-}
      no_proxy: ${SINKS_HTTP_PROXY_NO_PROXY:-}
    encoding:
      codec: json
```

If you try to validate the above configuration, you get the following error:
```
$ vector validate vector.yaml
Failed to load ["vector.yaml"]
------------------------------
x sinks.http.proxy.no_proxy: invalid type: unit value, expected string or list of strings at line 17 column 5
```

The reason for this is because the environment variables were not interpolated to the default empty string with `${VAR:-}`, leading to the final interpolated YAML document to have a null node instead of an empty string node.

If we quote the variable that errors, we are able to force the interpolation to be of type string:
```yaml
no_proxy: '${SINKS_HTTP_PROXY_NO_PROXY:-}'
```

This time, the validation passes but there are warnings that the variables were not interpolated:
```
$ vector validate vector.yaml
Loaded with warnings ["vector.yaml"]
------------------------------------
~ Unknown env var in config. name = "SINKS_HTTP_PROXY_HTTP"
~ Unknown env var in config. name = "SINKS_HTTP_PROXY_HTTPS"
~ Unknown env var in config. name = "SINKS_HTTP_PROXY_NO_PROXY"
```

### Proposal

Other variable substitution systems such as the one in [Docker Compose files](https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution) do recognise empty strings as defaults.

I think Vector should also support this as it is a common way to make simple "optional" environment variables.

Probably the way to implement this in Vector would be to change the `+` qualifier to `*` in this regex:

https://github.com/vectordotdev/vector/blob/816d42c1e6f5718c531a12e2a71a11b6e6e8806b/src/config/vars.rs#L18

As a side note, I think implementing variable interpolation/substitution in the same way Docker Compose does it would be very handy/useful in Vector as well. In particular the syntax to specify mandatory variables:

> Similarly, the following syntax allows you to specify mandatory variables:
> ${VARIABLE:?err} exits with an error message containing err if VARIABLE is unset or empty in the environment.
> ${VARIABLE?err} exits with an error message containing err if VARIABLE is unset in the environment.

### PR DESCRIPTION
**Pull request by hhromic**
This PR improves the current environment variables interpolator to fully mimic the Docker compose syntax:

* `${VARIABLE:-default}` evaluates to `default` if `VARIABLE` is unset or empty in the environment.
* `${VARIABLE-default}` evaluates to `default` only if `VARIABLE` is unset in the environment.
* `${VARIABLE:?err}` exits with an error message containing `err` if `VARIABLE` is unset or empty in the environment.
* `${VARIABLE?err}` exits with an error message containing `err` if `VARIABLE` is unset in the environment.

**Note:** The last two cases (_exits with an error message ..._) will not show properly until #12149 is resolved.

In addition, the improved regex also allows for `default` and `err` to be empty strings, fixing the linked issue.

I was not sure where exactly to update the documentation, as there are two places with the same content (CUE content and Markdown content). So I just updated/aligned both to have the same content for now.

Closes #10420

### CODE REVIEW

File: src/config/vars.rs [hunk 1]
```diff
@@ -16,27 +21,59 @@ pub fn interpolate(input: &str, vars: &HashMap<String, String>) -> (String, Vec<
...
+                                    name, def_or_err
+                                ));
+                                ""
+                            }
+                            _ => {
+                                warnings
+                                    .push(format!("Unknown env var in config. name = {:?}", name));
+                                ""
+                            }
                         })
```
Comment (bruceg) [inline src/config/vars.rs:65]: Would this logic be more straightforward to match on the `flags` at the top level instead of mapping the value?

**Review by bruceg — COMMENTED** [review]
Thanks for this contribution, @hhromic. I have one question but otherwise it looks good to me.

File: src/config/vars.rs (hunk 1 above)
Comment (hhromic) [reply src/config/vars.rs:65]: For the record, I was also not 100% happy about this part of the code :)
I did think of matching on `flags` first, however I got a bit tangled with handling the `HashMap::get()` because of the potential item-not-found case. I will give it another thought now that I am getting more familiar with Rust.

Thanks for the feedback!

Comment (hhromic) [reply src/config/vars.rs]: Hi @bruceg, I managed to implement the code by matching on `flags` instead of mapping the var values as suggested.

The code could be cleaner with these alternatives that unfortunately are not ready in Rust:
* The ["if-let-chains" RFC](https://rust-lang.github.io/rfcs/2497-if-let-chains.html), which is still pending.
* The [`is_some_with()` method](https://doc.rust-lang.org/std/option/enum.Option.html#method.is_some_with), which is still experimental (and will be renamed to `is_some_and()`).

Anyway, the implementation I pushed now at least gets rid of the duplicated `errors.push(...)` part, which makes me happy :)  Let me know what do you think.

Comment (hhromic) [reply src/config/vars.rs]: I simplified it a bit more now by replacing the trivial `if let Some(v) = val { v } else { ... }` blocks with `.unwrap_or()` and `.unwrap_or_else()` as appropriate.

**Review by bruceg — APPROVED** [review]
I think that condition block might be a little wordier now, but it's definitely clearer what's going on, so that's a win. I'll wait to see if @JeanMertz wants to weigh in on this, but otherwise this LGTM.

File: src/config/vars.rs [hunk 2]
```diff
@@ -16,27 +21,63 @@ pub fn interpolate(input: &str, vars: &HashMap<String, String>) -> (String, Vec<
...
         \$([[:word:].]+)|
-        \$\{([[:word:].]+)(?::-([^}]+)?)?\}",
+        \$\{([[:word:].]+)(?:(:?-|:?\?)([^}]*))?\}",
     )
     .unwrap();
+
     let interpolated = re
         .replace_all(input, |caps: &Captures<'_>| {
+            let flags = caps.get(3).map(|m| m.as_str()).unwrap_or("");
+            let def_or_err = caps.get(4).map(|m| m.as_str()).unwrap_or("");
```
Comment (JeanMertz) [inline src/config/vars.rs:31]:
```suggestion
            let flags = caps.get(3).map(|m| m.as_str()).unwrap_or_default();
            let def_or_err = caps.get(4).map(|m| m.as_str()).unwrap_or_default();
```

File: src/config/vars.rs [hunk 3]
```diff
@@ -16,27 +21,63 @@ pub fn interpolate(input: &str, vars: &HashMap<String, String>) -> (String, Vec<
...
-                            warnings.push(format!("Unknown env var in config. name = {:?}", name));
+                    let val = vars.get(name).map(|v| v.as_str());
+                    match flags {
+                        ":-" => {
+                            if matches!(val, Some(v) if !v.is_empty()) {
+                                val.unwrap()
+                            } else {
+                                def_or_err
+                            }
+                        }
```
Comment (JeanMertz) [inline src/config/vars.rs:44]: It might be easier to read by moving the if-condition to the match statement, e.g.:

```rust
match flags {
    ":-" if matches!(val, Some(v) if !v.is_empty()) => val.unwrap(),
    ":-" => def_or_err

    // ...
}
```

**Review by JeanMertz — APPROVED** [review]
A few minor nits, but otherwise this LGTM 👍

File: src/config/vars.rs (hunk 2 above)
Comment (hhromic) [reply src/config/vars.rs:31]: Ah, doh, indeed `unwrap_or_default()` will resolve to `""` and is cleaner. Thanks!

File: src/config/vars.rs (hunk 3 above)
Comment (hhromic) [reply src/config/vars.rs:44]: Ah this is exactly the kind of feedback I was looking for.
I'm still a bit "fresh" with the Rust pattern matching system and totally forgot you could do that. Great suggestion!
I will apply it later and test it. Thanks!

Comment (jszwedko) [reply src/config/vars.rs:44]: I'd go a bit further and avoid the `unwrap` with something like:

```rust
                        ":?" => match val {
                            Some(v) if !v.is_empty() => v,
                            _ => {
                                errors.push(format!(
                                    "Non-empty env var required in config. name = {:?}, error = {:?}",
                                    name, def_or_err
                                ));
                                ""
                            }
                        }
```

Comment (jszwedko) [reply src/config/vars.rs:44]: Or, rather, that snippet would replace the below arm for `:?` but you could do something similar for this match arm.

**Review by jszwedko — COMMENTED** [review]
Nice work! I left a non-blocking comment about the matching. It seems like you are interested in refactoring so I'll leave this open for that, but we can merge whenever.

Thanks for expanding the test suite.

File: src/config/vars.rs (hunk 3 above)
Comment (hhromic) [reply src/config/vars.rs:44]: Thanks for the ideas @jszwedko , will take a look at these later too.

**Comment by hhromic** [comment]
> It seems like you are interested in refactoring so I'll leave this open for that, but we can merge whenever.

Yes, I would like to apply the suggestions you have given.
I'm a firm believer that less, more readable, code for the same functionality is fundamental for good software 👍.
I'll let you know when I'm happy for a final surface scanning and merging.

**Comment by hhromic** [comment]
@bruceg @JeanMertz @jszwedko thanks for the feedback and quality suggestions!
I now applied the lastest ideas and I think I'm quite happy with the end results. It should be good to go now!

**Comment by jszwedko** [comment]
Awesome, looks good. Thanks for your work on this @hhromic ! This is a nice usability enhancement for configs.
