### PR TITLE
fix(dnstap source): increase request limit for TCP dnstap source

### LINKED ISSUE #23392: Missing or throttled events with dnstap TCP source on v0.48.0
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi All,

After upgrading from v0.47.0 to v0.48.0 (without any config change), a dnstap source went from receiving around 1300 events/sec to around 130 events/sec using `mode=tcp`.  Switching back and forth between the versions without changing any config gives the same difference every time.

I found that it seems to be affected by the number of dnstap senders opening connections to the vector dnstap source.  With up to 4 servers sending it will maintain 1300 events/sec, once I add more it lowers the throughput (even though only 1 of the servers is sending most of the events).

Looking at the release notes, I'm wondering if it could be related to #23123 since there were changes made to the dnstap tcp socket.  I have tried setting the `connection_limit`, `max_connection_duration_secs`, etc. but have not found the issue.

Could I be missing some configuration for handling more connections?  Or is there a recommended limit of connections from senders before a new source (with different port) should be added?  If I can provide any further details, please let me know.

Thanks!

### Configuration

```text
dnstap:
    type: dnstap
    address: 0.0.0.0:9000
    mode: tcp
    multithreaded: true # Seems to make no difference in this case
    permit_origin:
      - 172.16.1.1/32
      - 172.16.1.2/32
      - 172.16.1.3/32
      - 172.16.1.4/32
      - 172.16.1.5/32
    keepalive:
      time_secs: 30

  blackhole:
    type: blackhole
    inputs:
      - dnstap
```

### Version

0.48.0

### Debug Output

```text
I didn't notice anything useful in the debug output, but can add it if anyone wants to see it.  However, it seems to be easily reproducible.
```

### Example Data

_No response_

### Additional Context

_No response_

### References

#23123

### PR DESCRIPTION
**Pull request by esensar**
## Summary
Uses `max_frame_handling_tasks` setting to increase the default request limit. By default, `max_frame_handling_tasks` is 1000 and since the code for this component only handles 1 event for each permit, this translates well into this usage. This greatly reduces time lost by re-acquiring permits and waiting for connections that produce no data to drop the permits.

## Vector configuration
```yaml
api:
  enabled: true
  address: "0.0.0.0:8686"

sources:
  dnstap_tcp:
    type: "dnstap"
    mode: "tcp"
    address: "0.0.0.0:59001"

sinks:
  console:
    inputs: ["dnstap_tcp"]
    type: "blackhole"
```

## How did you test this PR?
Started Vector with the above configuration, connected (THREAD COUNT - 1) dnstap clients that send no data and then connected 64 more. Observing via `vector top`, before #23123, this managed 200-300k events/sec, but it often produced errors and crashed connections. After #23123, this scenario dropped to <10k events/sec. After this fix, it is close to the original (still a bit less, but still in 200-300k events/sec range) and no errors appear. This can further be controlled with `max_frame_handling_tasks`, which is already used in this component - default is 1000, but performance can further be improved, although it doesn't make much difference if it is already higher than connection count.

## Change Type
- [x] Bug fix
- [ ] New feature
- [ ] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?
- [ ] Yes
- [x] No

## Does this PR include user facing changes?

- [x] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the `no-changelog` label to this PR.

## References

- Closes: #23392

## Notes
- Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
- Do not hesitate to use `@vectordotdev/vector` to reach out to us regarding this PR.
- Some CI checks run only after we manually approve them.
  - We recommend adding a `pre-push` hook, please see [this template](https://github.com/vectordotdev/vector/blob/master/CONTRIBUTING.md#Pre-push).
  - Alternatively, we recommend running the following locally before pushing to the remote branch:
    - `cargo fmt --all`
    - `cargo clippy --workspace --all-targets -- -D warnings`
    - `cargo nextest run --workspace` (alternatively, you can run `cargo test --all`)
- After a review is requested, please avoid force pushes to help us review incrementally.
  - Feel free to push as many commits as you want. They will be squashed into one before merging.
  - For example, you can run `git merge origin master` and `git push`.
- If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
  run `cargo vdev build licenses` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

---
>Sponsored by [Quad9](https://quad9.net/)

### CODE REVIEW

**Comment by esensar** [comment]
@jszwedko Could this get in before the release? It is a small change, but it prevents the issue that forces some users to use 0.47.0

**Comment by pront** [comment]
> @jszwedko Could this get in before the release? It is a small change, but it prevents the issue that forces some users to use 0.47.0

Hi @esensar, is it ready for review? The release is scheduled for next week but we can probably include this PR.

**Comment by esensar** [comment]
Sorry, I must have left it a draft by accident. It is ready, I will add a changelog.

**Review by pront — APPROVED** [review]

File: src/sources/util/framestream.rs [hunk 1]
```diff
@@ -451,8 +451,10 @@ pub fn build_framestream_tcp_source(
         let connection_gauge = OpenGauge::new();
         let shutdown_clone = shutdown.clone();
 
-        let request_limiter =
-            RequestLimiter::new(MAX_IN_FLIGHT_EVENTS_TARGET, crate::num_threads());
+        let request_limiter = RequestLimiter::new(
+            MAX_IN_FLIGHT_EVENTS_TARGET,
+            frame_handler.max_frame_handling_tasks() as usize,
```
Comment (pront) [inline src/sources/util/framestream.rs:456]: Nit: Ideally `max_frame_handling_tasks` would also be `usize` but u32 to usize is fine.

Comment (esensar) [reply src/sources/util/framestream.rs:456]: I could clean that up in a separate PR. It was there in the original dnstap source, so it is used in more places now - it would introduce noise into this PR.

Comment (pront) [reply src/sources/util/framestream.rs:456]: Agreed, thanks.
