### PR TITLE
fix(config): allow usage of metrics-only decoders in log sources

### LINKED ISSUE #21039: Log-only sources can't output metrics with the `influxdb` decoder
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

As discussed in #21027, log-only sources (for example, the `exec` source) should be capable of emitting metrics with a decoder that does not include logs in its output (currently, the `influxdb` decoder is the only one with this behavior).

### Configuration

```text
sources:
  file:
    type: exec
    command: ["cat", "sampling.txt"]
    decoding:
      codec: "influxdb"
    mode: streaming
sinks:
  console:
    type: console
    inputs: ["file"]
    encoding:
      codec: "json"
```

### Version

vector 0.40.0 (x86_64-unknown-linux-gnu)

### Debug Output

```text
2024-08-10T09:58:45.063500Z DEBUG vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2024-08-10T09:58:45.063519Z  INFO vector::app: Log level is enabled. level="trace"
2024-08-10T09:58:45.063538Z DEBUG vector::app: messaged="Building runtime." worker_threads=20
2024-08-10T09:58:45.064633Z  INFO vector::app: Loading configs. paths=["config.yaml"]
2024-08-10T09:58:45.066867Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
thread 'main' panicked at lib/vector-core/src/config/mod.rs:128:9:
assertion failed: ty.contains(DataType::Log)
stack backtrace:
   0:     0x6081905123a5 - <unknown>
   1:     0x60819054364b - <unknown>
   2:     0x60819050c57f - <unknown>
   3:     0x60819051217e - <unknown>
   4:     0x608190513c79 - <unknown>
   5:     0x6081905139bd - <unknown>
   6:     0x608190514113 - <unknown>
   7:     0x608190513fbb - <unknown>
   8:     0x608190512869 - <unknown>
   9:     0x608190513d27 - <unknown>
  10:     0x60818b96b9b3 - <unknown>
  11:     0x60818b96ba5c - <unknown>
  12:     0x60818f4e671b - <unknown>
  13:     0x60818bbc35d7 - <unknown>
  14:     0x60818c639b24 - <unknown>
  15:     0x60818bfaae47 - <unknown>
  16:     0x60818c55561f - <unknown>
  17:     0x60818c550ec9 - <unknown>
  18:     0x60818df6b284 - <unknown>
  19:     0x60818df8cff6 - <unknown>
  20:     0x60818df006d9 - <unknown>
  21:     0x60818c4a840f - <unknown>
  22:     0x60818d667608 - <unknown>
  23:     0x60818d667059 - <unknown>
  24:     0x60818d666d91 - <unknown>
  25:     0x60818d666c49 - <unknown>
  26:     0x60818b96f082 - <unknown>
  27:     0x60818b96f3f6 - <unknown>
  28:     0x60818b96f40c - <unknown>
  29:     0x6081905011c0 - <unknown>
  30:     0x60818b96f2d4 - <unknown>
  31:     0x76ac681a2e08 - <unknown>
  32:     0x76ac681a2ecc - __libc_start_main
  33:     0x60818b96df45 - <unknown>
  34:                0x0 - <unknown>
```

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jorgehermo9**
Closes #21039 

Now this works:
### Configuration
```yaml
sources:
  file:
    type: exec
    command: ["cat", "test.txt"]
    decoding:
      codec: "influxdb"
    mode: streaming
    streaming:
      respawn_on_exit: false
sinks:
  console:
    type: console
    inputs: ["file"]
    encoding:
      codec: "native_json"
```

### Input `test.txt`
```txt
weather,location=us-midwest temperature=82 1465839830100400200
```

### Output
```json
{"metric":{"name":"weather_temperature","tags":{"location":"us-midwest"},"timestamp":"+48420-08-12T18:35:00.400200Z","kind":"absolute","gauge":{"value":82.0}}}
```

Although, I would like to add some more tests, like for example, integration test for some source with an influxdb decoder config similar to the former. Where should I create those tests? Or isn't that needed?
It would be nice to have this kind of test so we verify that log sources with this codec can really output metrics to a metric sink and this feature doesn't get broken in a future.

### CODE REVIEW

File: lib/vector-core/src/config/mod.rs [hunk 1]
```diff
@@ -673,4 +671,18 @@ mod test {
         new_definition.assert_valid_for_event(&valid_event);
         new_definition.assert_valid_for_event(&invalid_event);
     }
+
+    #[test]
+    fn test_new_log_source_ignores_definition_with_metric_data_type() {
```
Comment (jorgehermo9) [inline lib/vector-core/src/config/mod.rs:676]: Maybe the tests naming could be improving, i'm open for suggestions on how to name & test this behavior

Comment (jszwedko) [reply lib/vector-core/src/config/mod.rs:676]: I think these tests are good 👍

**Review by jszwedko — APPROVED** [review]
Thanks for this contribution @jorgehermo9 ! And thanks for catching its lack before we officially released the influxdb codec as others would have likely ran into the panic.
