### PR TITLE
fix(docker_logs source): fix and document exclude_self logic

### LINKED ISSUE #5996: docker_logs: using exclude_containers should not disable exclude_self
### Vector Version
```
docker pull timberio/vector:nightly-2021-01-12-distroless-static
```

### Vector Configuration File
```toml
# Vector's API for introspection
[api]
enabled = true
address = "127.0.0.1:8686"

# Host-level logs
[sources.logs]
type = "docker_logs"
exclude_containers = ["docker-compose"]

# --> Add transforms here to parse, enrich, and process data

# print all events, replace this with your desired sink(s)
# https://vector.dev/docs/reference/sinks/
[sinks.out]
type = "console"
inputs = [ "logs" ]
encoding.codec = "json"
```

### Debug Output

Not going to actually run this because wow. But here's an exciting excerpt:

<details>
<summary>your eyes will hurt</summary>
<code>
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"docker\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"stream\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"stdout\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"timestamp\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"2021-01-12T09:33:25.454660119Z\\\\\\\\\\\\\\\\\\
</code>

</details>

### Expected Behavior
I get logs for containers that aren't vector and aren't docker-compose.

### Actual Behavior
I get logs for containers that are aren't vector and aren't docker-compose, but also vector.

### Additional Context
Vector is running under docker.

### References
I think the condition here is wrong:
https://github.com/timberio/vector/blob/3a51020a953d9a29b56b8fe6ab79806d49dedbd6/src/sources/docker_logs.rs#L350-L352

### PR DESCRIPTION
**Pull request by juchiast**
close #5996 

Signed-off-by: Duy Do <juchiast@gmail.com>

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
:+1: the implementation seems sensible to me. Could we add a test or two validating this behavior?

**Review by bruceg — COMMENTED** [review]
Do we have any way of testing this behavior?

**Comment by juchiast** [comment]
@jszwedko @bruceg I'm not sure how to write test for this yet. 

The booleans in this code look wrong, for example, `fn exclude_vector` claims to return true if passed container need to be excluded, but it always return true when `exclude_self == false`,
```rust
    /// True if container with the given id and image must be excluded from logging,
    /// because it's a vector instance, probably this one.
    fn exclude_vector<'a>(&self, id: &str, image: impl Into<Option<&'a str>>) -> bool {
        if self.exclude_self {
            ....
        }
        true
    }
```

The way it is used is opposite to the function's name:
```rust
                if !self.exclude_vector(id.as_str(), image.as_str()) {
                    return;
                }
```

This is wrong too: `let exclude_self = include_containers_specified && ....`, because "state of catching everything" mean `!include_containers_specified`.
```rust
        // This is to be used only if source is in state of catching everything.
        // Or in other words, if includes are used then this is not necessary.
```

**Comment by juchiast** [comment]
I've removed `exclude_self` flag, because:
- I don't see why we don't need it when `include_containers` is specified, we support prefix matches so it could still match the current vector container. 
- `exclude_vector` is simple and fast, so there is no cost in performance, especially when it is only run on start and unpause.

File: src/sources/docker_logs.rs [hunk 1]
```diff
@@ -546,23 +522,20 @@ impl DockerLogsSource {
...
+        let match_hostname = self
+            .hostname
+            .as_ref()
+            .map(|maybe_short_id| id.starts_with(maybe_short_id))
+            .unwrap_or(false);
+        let match_image = image
+            .into()
+            .map(|image| image.starts_with(VECTOR_IMAGE_NAME))
+            .unwrap_or(false);
+        match_hostname || match_image
```
Comment (bruceg) [inline src/sources/docker_logs.rs:538]: If I'm reading this right, this would exclude all containers on the local host. Did you mean `match_hostname && match_image`?

File: docs/reference/components/sources/docker_logs.cue [hunk 2]
```diff
@@ -86,6 +86,12 @@ components: sources: docker_logs: {
 				[Docker `journald` driver](\(urls.docker_logging_driver_journald))
 				drivers.
 				""",
+			"""
+				To avoid collecting logs from itself, the Docker source does not
+				collect logs from Vector containers. Please consider using the
+				[`vector` source](\(urls.vector_source)) if you want to collect logs
+				from other Vector containers.
+				""",
```
Comment (bruceg) [inline docs/reference/components/sources/docker_logs.cue:94]: Does this change in semantics make this a breaking change? If so, make sure it's marked in the title.

**Review by bruceg — CHANGES_REQUESTED** [review]
I think there's an issue with exclude_vector

File: src/sources/docker_logs.rs (hunk 1 above)
Comment (juchiast) [reply src/sources/docker_logs.rs:538]: Hi, `match_hostname` is true only if hostname is a short container ID (current vector process is inside a container, and the hostname of this cointainer matches the passed-in ID).

**Review by juchiast — COMMENTED** [review]
.

File: docs/reference/components/sources/docker_logs.cue (hunk 2 above)
Comment (juchiast) [reply docs/reference/components/sources/docker_logs.cue:94]: I don't think this behaviour was documented previously. Anyway, I've marked it.

Comment (jszwedko) [reply docs/reference/components/sources/docker_logs.cue:94]: Do you mean it will not collect logs from _any_ vector container? Or just itself?

File: src/sources/docker_logs.rs [hunk 3]
```diff
@@ -318,8 +318,6 @@ struct DockerLogsSource {
     main_recv: mpsc::UnboundedReceiver<Result<ContainerLogInfo, ContainerId>>,
     /// It may contain shortened container id.
     hostname: Option<String>,
-    /// True if self needs to be excluded
-    exclude_self: bool,
```
Comment (jszwedko) [inline src/sources/docker_logs.rs:322]: Could we leave this, but deprecate it and output a warning if it is specified? That would allow us to more smoothly transition anyone using it.

**Review by jszwedko — COMMENTED** [review]
Thanks @juchiast !

I agree that it is unlikely for users to want to ingest logs from itself via the `docker_logs` source, but I could see users wanting to ingest logs from _other_ vector containers on the host. Is this still possible after these changes?

It'd still be nice to see a test or two for this behavior once it is decided on.

File: src/sources/docker_logs.rs (hunk 3 above)
Comment (juchiast) [reply src/sources/docker_logs.rs:322]: This was not a configurable option so I don't think this is an option.

File: docs/reference/components/sources/docker_logs.cue (hunk 2 above)
Comment (juchiast) [reply docs/reference/components/sources/docker_logs.cue:94]: From any vector container. Currently, there is two filters in `exclude_vector`:
- `match_hostname`: hostname inside a container is usually a short ID of that container, so we use this info to find out which container current vector process is in. 
- `match_image`: exclude all vector images.

If `match_hostname` works well enough, we could remove `match_image`.
cc @ktff

File: src/sources/docker_logs.rs (hunk 3 above)
Comment (juchiast) [reply src/sources/docker_logs.rs:322]: Previous behaviour is: if any of the `include_*` options is set, disable `exclude_self`.

Comment (jszwedko) [reply src/sources/docker_logs.rs:322]: Ah! Yes, I see.

File: docs/reference/components/sources/docker_logs.cue (hunk 2 above)
Comment (jszwedko) [reply docs/reference/components/sources/docker_logs.cue:94]: :+1: I think that would be nice if we could remove `match_image`. I can see a case where a user is running vector as an agent on a server, in docker, to collect all docker logs and then also another `vector` instance as an aggregator, also in docker, on the same server where it'd be useful to have the agent forward the aggregator's logs.

However, it also seems like that behavior hasn't changed so I'm happy to punt on this to a separate issue if we want.

**Review by jszwedko — COMMENTED** [review]
Thanks @juchiast ! I'd still like to see some tests around this logic. I realize that is tricky though as it relies on being inside of docker in the tests, but maybe we could refactor in such a way that we could test just the logic independently.

Let me know what you think though, I realize this bit is hard to test, but I also realize that if we had had tests around it, we probably wouldn't have had the bug in the first place :smile:

File: docs/reference/components/sources/docker_logs.cue (hunk 2 above)
Comment (jszwedko) [reply docs/reference/components/sources/docker_logs.cue:94]: Also, I think we can avoid marking this change as a breaking change as it isn't changing, we just hadn't documented it.

Comment (juchiast) [reply docs/reference/components/sources/docker_logs.cue]: I'm in favour of removing `match_image` too, I've removed it.

File: src/sources/docker_logs.rs [hunk 4]
```diff
@@ -1133,6 +1090,21 @@ mod tests {
     fn generate_config() {
         crate::test_util::test_generate_config::<DockerLogsConfig>();
     }
+
+    #[test]
+    fn exclude_self() {
```
Comment (juchiast) [inline src/sources/docker_logs.rs:1095]: Added a simple test.

File: src/sources/docker_logs.rs [hunk 5]
```diff
@@ -543,26 +515,11 @@ impl DockerLogsSource {
...
-                .map(|image| image.starts_with(VECTOR_IMAGE_NAME))
-                .unwrap_or(false);
-            if hostname_hint || image_hint {
-                // This container is probably itself.
-                info!(message = "Detected self container.", id = %id);
-                return false;
-            }
-        }
-        true
+    fn exclude_self<'a>(&self, id: &str) -> bool {
```
Comment (jszwedko) [inline src/sources/docker_logs.rs:518]: Just calling attention to the failing check here. It seems like you could drop the lifetime.

File: src/sources/docker_logs.rs (hunk 4 above)
Comment (jszwedko) [reply src/sources/docker_logs.rs:1095]: Thanks! I think this is a good test.

**Review by jszwedko — COMMENTED** [review]
This looks good to me, thanks @juchiast !

I am actually wondering about which cases would cause `get_hostname()` to fail. Do you mind testing on the images we publish? I'm specifically wondering about the `distroless` image. If all of our published, supported, images support fetching the container id as the hostname, I'm content.

**Comment by ktff** [comment]
> I've removed exclude_self flag, because:
>
>  * I don't see why we don't need it when include_containers is specified, 

The way we determine which container is self can easily break, `hostname` and `image_name` can change for ordinary reasons, so we tried to reduce our relience on it to only when necessary. As a side bonus, the exclusion of self didn't interfere with include/exclude options (well with the exception of this bug). (Although it also seams the logic got a bit contrived)

That said, it's unfortunate we are adding responsibility to the user, of not interfering with the hostname, but I think it's for the better in this case.

>ingest logs from other vector containers on the host. Is this still possible after these changes?

It seams they will be ingested by default. It would be nice to mention this in a release.

Completely disabling a way to capture self logs also seams fine.

Removing `match_image` is also fine.

Although all of this depends on how reliably does Docker set `hostname` as a long enough ID. This, I'm worried about, but I agree with @jszwedko 
>  If all of our published, supported, images support fetching the container id as the hostname, I'm content.

File: src/sources/docker_logs.rs (hunk 5 above)
Comment (juchiast) [reply src/sources/docker_logs.rs]: Thanks! Removed.

**Comment by juchiast** [comment]
> I am actually wondering about which cases would cause get_hostname() to fail. 

@jszwedko `EFAULT`, `EINVAL`, `ENAMETOOLONG` are invalid argument errors, `EPERM` is for `sethostname` only. Accordingly, `get_hostname` would never fail. https://man7.org/linux/man-pages/man2/gethostname.2.html

**Comment by juchiast** [comment]
@jszwedko I can use `get_env_var` remap function to get hostname in all images `nightly-distroless-libc`, `nightly-distroless-static`, `nightly-debian`, `nightly-alpine`.

**Comment by jszwedko** [comment]
> > I am actually wondering about which cases would cause get_hostname() to fail.
> 
> @jszwedko `EFAULT`, `EINVAL`, `ENAMETOOLONG` are invalid argument errors, `EPERM` is for `sethostname` only. Accordingly, `get_hostname` would never fail. https://man7.org/linux/man-pages/man2/gethostname.2.html

Aha, thanks! I neglected we were just delegating to libc here. Thanks for testing on our images too.

**Review by jszwedko — APPROVED** [review]
Looks good!
