### PR TITLE
fix(docker_logs source): Fix HTTP and HTTPS URL

### LINKED ISSUE #4526: Containerized Vector not working with Docker source using DOCKER_HOST
### Vector Version

```
Vector is starting. version="0.10.0" git_version="v0.9.0-377-g0f0311a" released="Wed, 22 Jul 2020 20:01:29 +0000" arch="x86_64"
```

### Vector Configuration File

```toml
[sources.in]
  type = "docker" # required

[sinks.out]
  # General
  endpoint = "http://loki:3100" # required
  inputs = ["in"] # required
  type = "loki" # required

  # Labels
  labels.key = "value" # example
  labels.key = "{{ event_field }}" # example
```

### Expected Behavior

I'm seting-up Vector as a container and would like to collect docker logs from other containers and sending those to a loki instance.
I'm not going to use the unix socket to connect Vector to Docker, but I'm using the DOCKER_HOST environment variable pointing to a proxy that forward the request to Docker.
I already use successfully this proxy for other purpose on other containers.

### Actual Behavior

On Vector I get this error during start-up:

```
ERROR source{name=in type=docker}: vector::sources::docker: Listing currently running containers, failed error=Hyper error: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Other, error: "failed to lookup address information: Try again" }))
```
After this the container is killed.

Changing the entry-point of the container to "ping localhost" I can have the container running and from inside it I can successfully ping my proxy:

```
PING socket-proxy (172.29.44.2): 56 data bytes
64 bytes from 172.29.44.2: seq=0 ttl=64 time=0.379 ms
64 bytes from 172.29.44.2: seq=1 ttl=64 time=0.076 ms
```

And I can even execute API request over it:

```
wget http://socket-proxy:2475/version

{"Version":"17.09.1-ce","ApiVersion":"1.32","MinAPIVersion":"1.12","GitCommit":"0bbe3ac","GoVersion":"go1.8.3","Os":"linux","Arch":"amd64","KernelVersion":"XXX","BuildTime":"2020-05-22T06:36:01.000000000+00:00"}
```

So looks like the dns error is misleading.

### Additional Context

docker-compose:

```yaml
version: "3"

networks:
  loki:
    external:
      name: loki_loki
  socket-proxy-net:
    external:
      name: socket-proxy-net

services:
  vector:
    image: timberio/vector:latest-alpine
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
    environment:
      DOCKER_HOST : "http://socket-proxy:2475"
    networks:
      - loki
      - socket-proxy-net
```

### PR DESCRIPTION
**Pull request by juchiast**
close #4526

Documentation of Bollard suggested that passing in an URL with http:// should work, but in fact it doesn't, Bollard only trims tcp://.

### CODE REVIEW

**Comment by juchiast** [comment]
https://github.com/fussybeaver/bollard/issues/133

File: src/sources/docker_logs.rs [hunk 1]
```diff
@@ -1041,11 +1041,18 @@ fn default_certs() -> Option<DockerTlsConfig> {
     })
 }
 
-fn docker(host: Option<String>, tls: Option<DockerTlsConfig>) -> Result<Docker, DockerError> {
+fn get_authority(url: &str) -> crate::Result<String> {
+    url.parse::<Uri>()
+        .ok()
+        .and_then(|uri| uri.authority().map(<_>::to_string))
+        .ok_or_else(|| "URL has no host.".into())
```
Comment (bruceg) [inline src/sources/docker_logs.rs:1048]: How hard would it be to make this a concrete error instead of just a string?

**Review by bruceg — APPROVED** [review]
