### PR TITLE
fix(topology): Fix for issue causing stalling on shutdown for sinks configured w/ disk buffers

### LINKED ISSUE #17666: Negative Buffer Usage being reported in `Datadog` and `Prometheus`
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We had an incident today similar to [this](https://github.com/vectordotdev/vector/issues/16561). Our S3 sink buffer was reporting negative values (see the screenshots).

Screenshot 2023-06-12 at 11 42 57

Screenshot 2023-06-12 at 13 55 01

I also noticed that outgoing events dropped to 0 during this time, and our source time lag increased. 

Screenshot 2023-06-12 at 14 00 32

Screenshot 2023-06-12 at 13 59 27

We have seen this in past when a sink with a blocking buffer gets full. Even if the client stops/slows down sending events due to backpressure, the buffer usage stays the same, causing it to hang forever. 

### Configuration

```text
toml
  aws_s3_archive.toml: |-
    type = "aws_s3"
    inputs = [ "remap_archive_logs_for_datadog" ]
    key_prefix = "dt=%Y%m%d/hour=%H/"
    compression = "gzip"
    content_encoding = "none"
    bucket = "vector-logs-archive-prod-asia"
    content_type = "application/x-gzip"
    filename_extension = "json.gz"
    filename_time_format = "archive_%H%M%S.%3f0.e"

    framing.method = "newline_delimited"
    encoding.codec = "json"

    batch.max_bytes = 256000000

    buffer.type = "disk"
    buffer.max_size = 8000000000

    buffer.when_full = "block"
  datadog_logs.toml: |-
    type = "datadog_logs"
    inputs = [ "internal_logs", "drop_nginx_ingress_logs" ]
    default_api_key = "${DATADOG_API_KEY}"
    site = "datadoghq.eu"


    buffer.type = "disk"
    buffer.max_size = 36000000000

    buffer.when_full = "block"
  internal_metrics_exporter.toml: |-
    type = "prometheus_exporter"
    inputs = [ "remap_enrich_internal_metrics_with_static_tags" ]
    distributions_as_summaries = true
    address = "0.0.0.0:9598"
  nginx_ingress_logs_s3_archive.toml: |-
    # S3 Sink to archive nginx ingress logs

    type = "aws_s3"
    inputs = [ "filter_nginx_logs_for_archival" ]
    key_prefix = "dt=%Y%m%d/hour=%H/"
    compression = "gzip"
    content_encoding = "none"
    bucket = "nginx-ingress-logs-archive-prod-asia"
    content_type = "application/x-gzip"
    filename_extension = "json.gz"
    filename_time_format = "archive_%H%M%S.%3f0.e"
    region = "ap-southeast-1"

    framing.method = "newline_delimited"
    encoding.codec = "json"

    batch.max_bytes = 256000000

    buffer.type = "disk"
    buffer.max_size = 4000000000

    buffer.when_full = "drop_newest"
```
```


### Version

`vector 0.28.0`

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### LINKED ISSUE #19600: s3 sink should complete with incomplete batch at shutdown
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

if s3 sink is using batch and during shutdown batch is not full it keep waiting for batch to become full or complete.
grace period may expire earlier causing those events to be not delivered.
depending of type of buffer used it would cause loss or delayed delivery and ungraceful shutdown.

### Configuration

```text
data_dir = "/tmp/vector/data"
schema.log_namespace = false
acknowledgements.enabled = true
[api]
enabled = true
[sources.dummy_logs]
type = "http_server"
address = "0.0.0.0:443"
decoding.codec = "bytes"
tls.enabled = false
[sinks.s3]
type = "aws_s3"
bucket = "my-bucket"
batch.max_events = 100000
batch.timeout_secs = 600
inputs = ["dummy_logs"]
encoding.codec = "raw_message"
buffer.max_size = 1000000000
buffer.type = "disk"
```

### Version

35.0

### Debug Output

```text
2024-01-11T20:41:58.799877Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=info,rdkafka=info,buffers=info,lapin=info,kube=info"
2024-01-11T20:41:58.800877Z  INFO vector::app: Loading configs. paths=["vector.toml"]
2024-01-11T20:41:59.365666Z  INFO vector::topology::running: Running healthchecks.
2024-01-11T20:41:59.365865Z  INFO vector: Vector has started. debug="true" version="0.35.0" arch="x86_64" revision=""
2024-01-11T20:41:59.366167Z  INFO source{component_kind="source" component_id=dummy_logs component_type=http_server}: vector::sources::util::http::prelude: Building HTTP server. address=0.0.0.0:443
2024-01-11T20:41:59.367863Z  INFO vector::internal_events::api: API server running. address=127.0.0.1:8686 playground=http://127.0.0.1:8686/playground
2024-01-11T20:41:59.639459Z ERROR vector::topology::builder: msg="Healthcheck failed." error=Unknown status code: 301 Moved Permanently component_kind="sink" component_type="aws_s3" component_id=s3
^C2024-01-11T20:42:09.619090Z  INFO vector::signal: Signal received. signal="SIGINT"
2024-01-11T20:42:09.619180Z  INFO vector: Vector has stopped.
2024-01-11T20:42:09.620726Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="59 seconds left"
2024-01-11T20:42:14.620626Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="54 seconds left"
2024-01-11T20:42:19.621906Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="49 seconds left"
2024-01-11T20:42:24.621188Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="44 seconds left"
2024-01-11T20:42:29.621132Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="39 seconds left"
2024-01-11T20:42:34.621181Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="34 seconds left"
2024-01-11T20:42:39.621160Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="29 seconds left"
2024-01-11T20:42:44.620830Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="24 seconds left"
2024-01-11T20:42:49.620156Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="19 seconds left"
2024-01-11T20:42:54.621015Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="14 seconds left"
2024-01-11T20:42:59.620651Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="9 seconds left"
2024-01-11T20:43:04.620839Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="s3" time_remaining="4 seconds left"
2024-01-11T20:43:09.620738Z ERROR vector::topology::running: Failed to gracefully shut down in time. Killing components. components="s3"
```

### Example Data

_No response_

### Additional Context

with this config send 
1 http request  `curl -v http://localhost:443 -d "hi"`
and SIGTERM the vector. graceful shutdown stuck at closing sink.

### References

_No response_

### LINKED ISSUE #24948: Sinks configured with disk buffers cause partial stall of pipeline on config reload
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Testing with Vector 0.52 I noticed that when editing my config, if I modified the configuration of the sole sink, I observe pipeline stalls. The logs pasted will indicate that the source will error. Presumably this is because its buffer is full and it can no longer accept new requests. Furthermore I noticed this occurred only when disk buffers were enabled on the sink and the problem resolves itself after 1 iteration of `batch.timeout_secs`. So if this value is small enough the problem will actually go unnoticed. There seems to be a strange interaction between configuration reload with components that have disk buffers enabled.

### Configuration

```text
sources:
  http-server-source:
    type: "http_server"
    address: "127.0.0.1:8001"

sinks:
  amazon-s3-sink:
    inputs:
      - "http-server-source"
    type: "aws_s3"
    bucket: e2e-tests
    region: us-east-1
    encoding:
      codec: json
    buffer:
      type: disk
      max_size: 30000000000
      when_full: block
    batch:
      timeout_secs: 500
      max_bytes: 100000000
```

### Version

vector 0.52.0-custom-bc654a796a 

### Debug Output

```text
2026-03-17T16:52:33.863641Z DEBUG vector::config::watcher: Collected file change events during delay period. paths=1 delay=1s
2026-03-17T16:52:33.865309Z DEBUG vector::config::watcher: Reloaded paths.
2026-03-17T16:52:33.865326Z  INFO vector::config::watcher: Configuration file changed.
2026-03-17T16:52:33.866107Z DEBUG vector::config::loading::secret: No secret placeholder found, skipping secret resolution.
2026-03-17T16:52:33.867414Z  INFO vector::topology::running: Reloading running topology with new configuration.
2026-03-17T16:52:33.868630Z DEBUG vector::topology::running: Changing sink. component_id=amazon-s3-sink
2026-03-17T16:52:33.868664Z DEBUG vector::topology::running: Pausing component input in fanout. component_id=amazon-s3-sink fanout_id=http-server-source
2026-03-17T16:52:33.868679Z DEBUG vector::topology::running: Waiting for sink to shutdown. component_id=amazon-s3-sink
2026-03-17T16:52:33.871203Z DEBUG source{component_kind="source" component_id=http-server-source component_type=http_server}: vector_buffers::variants::disk_v2::writer: Writer marked as closed.
2026-03-17T16:52:35.026745Z DEBUG vector::utilization: component_id=amazon-s3-sink utilization=0.0079 internal_log_rate_limit=false
2026-03-17T16:52:35.026781Z DEBUG vector::utilization: component_id=datadog-internal-metrics utilization=0.0011 internal_log_rate_limit=false
2026-03-17T16:52:35.042722Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=68}:http: vector::internal_events::http_client: Internal log [Sending HTTP request.] has been suppressed 6 times.
2026-03-17T16:52:35.042760Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=68}:http: vector::internal_events::http_client: Sending HTTP request. uri=https://0-52-0-vector.agent.datadoghq.com/api/v1/series method=POST version=HTTP/1.1 headers={"dd-api-key": "<KEY>", "dd-agent-payload": "4.87.0", "content-type": "application/json", "content-encoding": "deflate", "user-agent": "Vector/0.52.0-custom-bc654a796a (aarch64-apple-darwin debug=full)", "accept-encoding": "identity"} body=[1495 bytes]
2026-03-17T16:52:35.043785Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=68}:http: hyper::client::pool: Internal log [reuse idle connection for ("https", 0-52-0-vector.agent.datadoghq.com)] has been suppressed 6 times.
2026-03-17T16:52:35.043800Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=68}:http: hyper::client::pool: reuse idle connection for ("https", 0-52-0-vector.agent.datadoghq.com)
2026-03-17T16:52:35.074258Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=68}:http: hyper::client::pool: Internal log [pooling idle connection for ("https", 0-52-0-vector.agent.datadoghq.com)] has been suppressed 6 times.
2026-03-17T16:52:35.074287Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=68}:http: hyper::client::pool: pooling idle connection for ("https", 0-52-0-vector.agent.datadoghq.com)
2026-03-17T16:52:35.074348Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=68}:http: vector::internal_events::http_client: Internal log [HTTP response.] has been suppressed 6 times.
2026-03-17T16:52:35.075356Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=68}:http: vector::internal_events::http_client: HTTP response. status=202 Accepted version=HTTP/1.1 headers={"content-type": "text/json", "content-length": "16", "date": "Tue, 17 Mar 2026 16:52:35 GMT", "x-content-type-options": "nosniff", "strict-transport-security": "max-age=31536000; includeSubDomains; preload"} body=[16 bytes]
2026-03-17T16:52:37.034687Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=69}:http: vector::internal_events::http_client: Internal log [Sending HTTP request.] is being suppressed to avoid flooding.
2026-03-17T16:52:37.034783Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=69}:http: hyper::client::pool: Internal log [reuse idle connection for ("https", 0-52-0-vector.agent.datadoghq.com)] is being suppressed to avoid flooding.
2026-03-17T16:52:37.062302Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=69}:http: hyper::client::pool: Internal log [pooling idle connection for ("https", 0-52-0-vector.agent.datadoghq.com)] is being suppressed to avoid flooding.
2026-03-17T16:52:37.062367Z DEBUG sink{component_kind="sink" component_id=datadog-internal-metrics component_type=datadog_metrics}:request{request_id=69}:http: vector::internal_events::http_client: Internal log [HTTP response.] is being suppressed to avoid flooding.
2026-03-17T16:52:40.026712Z DEBUG vector::utilization: component_id=amazon-s3-sink utilization=0.0008 internal_log_rate_limit=false
2026-03-17T16:52:40.026797Z DEBUG vector::utilization: component_id=datadog-internal-metrics utilization=0.0013 internal_log_rate_limit=false
2026-03-17T16:52:40.042306Z DEBUG hyper::proto::h1::io: Internal log [flushed 1652 bytes] has been suppressed 413 times.
2026-03-17T16:52:40.042356Z DEBUG hyper::proto::h1::io: flushed 1320 bytes
2026-03-17T16:52:40.064273Z DEBUG hyper::proto::h1::io: Internal log [parsed 9 headers] has been suppressed 302 times.
2026-03-17T16:52:40.064331Z DEBUG hyper::proto::h1::io: parsed 5 headers
2026-03-17T16:52:40.064371Z DEBUG hyper::proto::h1::conn: Internal log [incoming body is empty] has been suppressed 302 times.
2026-03-17T16:52:40.064403Z DEBUG hyper::proto::h1::conn: incoming body is content-length (16 bytes)
2026-03-17T16:52:40.064749Z DEBUG hyper::proto::h1::conn: Internal log [incoming body completed] has been suppressed 301 times.
2026-03-17T16:52:40.064776Z DEBUG hyper::proto::h1::conn: incoming body completed
2026-03-17T16:52:41.062895Z DEBUG hyper::proto::h1::io: Internal log [flushed 1652 bytes] is being suppressed to avoid flooding.
2026-03-17T16:52:41.088395Z DEBUG hyper::proto::h1::io: Internal log [parsed 9 headers] is being suppressed to avoid flooding.
2026-03-17T16:52:41.088512Z DEBUG hyper::proto::h1::conn: Internal log [incoming body is empty] is being suppressed to avoid flooding.
2026-03-17T16:52:41.088610Z DEBUG hyper::proto::h1::conn: Internal log [incoming body completed] is being suppressed to avoid flooding.
2026-03-17T16:52:43.934486Z DEBUG hyper::server::server::new_svc: connection error: connection closed before message completed
2026-03-17T16:52:43.935419Z ERROR source{component_kind="source" component_id=http-server-source component_type=http_server}:http-request{method=POST path=/}: vector_common::internal_event::component_events_dropped: Events dropped intentional=false count=100 reason="Source send cancelled."
```

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by graphcareful**
## Summary
This PR includes two fixes when sinks configured with buffers are shutdown. First issue is observed when reloading a config that contains a sink with a disk buffer. Vector will wait until `batch.timeout_secs` has completed which causes buffers to flush and unblocks the reload process. The fix for this is to send the `cancel()` signal to the sink, so it doesn't block on its buffer not being flushed downstream.

The second fix is for an issue with the same root cause. I noticed the same hang on issue of control-c with the `aws_s3` sink. I employed the same solution there in the `stop()` method - to call the `cancel()` signal early in the `stop()` method.

## Vector configuration
```
sources:
  http-server-source:
    type: "http_server"
    address: "127.0.0.1:8001"

sinks:
  amazon-s3-sink:
    inputs:
      - "http-server-source"
    type: "aws_s3"
    bucket: e2e-tests
    region: us-east-1
    encoding:
      codec: json
    buffer:
      type: disk
      max_size: 30000000000
      when_full: block
    batch:
      timeout_secs: 500
      max_bytes: 100000000
 ```

## How did you test this PR?
By using the config above and a simple HTTP traffic generator. Modifying the sink buffer and re-saving the file, looking for errors from the source.

## Change Type
- [x] Bug fix
- [ ] New feature
- [ ] Dependencies
- [ ] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?
- [ ] Yes
- [x] No

## Does this PR include user facing changes?
- [ ] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [x] No. A maintainer will apply the `no-changelog` label to this PR.

## References
- Closes: #24948 
- Closes: #17666
- Closes: #19600 

## Notes
- Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
- Do not hesitate to use `@vectordotdev/vector` to reach out to us regarding this PR.
- Some CI checks run only after we manually approve them.
  - We recommend adding a `pre-push` hook, please see [this template](https://github.com/vectordotdev/vector/blob/master/CONTRIBUTING.md#Pre-push).
  - Alternatively, we recommend running the following locally before pushing to the remote branch:
    - `make fmt`
    - `make check-clippy` (if there are failures it's possible some of them can be fixed with `make clippy-fix`)
    - `make test`
- After a review is requested, please avoid force pushes to help us review incrementally.
  - Feel free to push as many commits as you want. They will be squashed into one before merging.
  - For example, you can run `git merge origin master` and `git push`.
- If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
  run `make build-licenses` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

### CODE REVIEW

**Comment by pront** [comment]
@codex review

File: src/topology/running.rs [hunk 1]
```diff
@@ -148,6 +148,15 @@ impl RunningTopology {
     pub fn stop(self) -> impl Future<Output = ()> {
         // Update the API's health endpoint to signal shutdown
         self.running.store(false, Ordering::Relaxed);
+
+        // Signal all sinks to flush their partial batches and stop accepting
+        // input. Without this, sinks rely on the natural stream EOF which only
```
Comment (bruceg) [inline src/topology/running.rs]: The bit about "stop accepting input" makes me more than a little nervous. Could this cause problems if upstream sources send more events?

Comment (graphcareful) [reply src/topology/running.rs]: In my manual testing before this change vector would stall on shutdown. With this change it takes a few seconds but I believe that is the time it takes to complete a round trip request of the payload to S3 (was a little less than 100MB).

I believe data will still be in the channel, orphaned. This data will be lost on shutdown, however this already occurs if the 60s timeout expires. Thoughts?

Comment (graphcareful) [reply src/topology/running.rs]: In theory the best option would be to stop accepting input, drain all channels, then await until disk flushes have completed, then proceed with rest of shutdown

Comment (graphcareful) [reply src/topology/running.rs]: I'm considering dropping this commit as its not really related to the original reported issue anyway

Comment (pront) [reply src/topology/running.rs]: > I'm considering dropping this commit

I agree with this. We should keep this fix as short as possible.

**Comment by pront** [comment]
> @codex review

Hmm, unfortunately this integration failed. This fix raises some concerns which I believe are also captured by the session below.

## Codex Session
For [issue #24948](https://github.com/vectordotdev/vector/issues/24948), I’d aim for a narrower fix than PR 24949.

The issue context is: on reload, a changed sink with a disk buffer gets its fanout input Paused, then Vector waits for that sink to shut down. Because the buffer sender is still alive, the sink never sees EOF, so it only flushes its partial batch when batch.timeout_secs expires. That’s why the pipeline stalls for one batch timeout. The PR fixes the stall by canceling the sink input stream, but that changes behavior to potentially drop queued events.

### A better fix is:

During reload of changed sinks, stop using Pause for sinks we are about to wait on.
Instead, fully disconnect the old sink from fanout so it sees a real EOF and flushes immediately.
Route new traffic to the replacement sink as soon as it is ready, instead of holding the whole pipeline behind the old sink’s batch timeout.
Only wait synchronously when there is a true resource conflict.
For the disk-buffer reuse case, prefer correctness over channel reuse:
either don’t reuse the live (tx, rx) pair for disk-buffered sinks on reload, or add a real “flush current batch” control path that does not sever input.
In plain terms: the old sink should drain and exit naturally; the new sink should start taking new events; and we should stop trying to make “reuse the exact same live buffer channel” carry the whole reload design.

So my concrete recommendation would be:

#### Short-term safe fix
Don’t reuse disk-buffer channels across reload for changed sinks.
Disconnect old sink with EOF semantics, let it flush and finish, and start the new sink with a fresh buffer.
This should fix #24948 without introducing loss.

#### Longer-term better design
Add an explicit sink lifecycle signal like “flush_partial_batch_now” separate from “stop accepting input”.
Then reload/shutdown can flush partial batches without using take_until_if(tripwire) as a blunt instrument.

Why I prefer that over PR 24949:

It addresses the actual stall described in [#24948](https://github.com/vectordotdev/vector/issues/24948).
It preserves graceful semantics.
It avoids turning reload/shutdown into a lossy path.
If you want, I can sketch the exact shutdown_diff / remove_inputs changes I’d make in src/topology/running.rs.

File: lib/vector-buffers/src/variants/disk_v2/tests/acknowledgements.rs [hunk 2]
```diff
@@ -68,7 +68,8 @@ async fn ack_wakes_reader() {
             let ledger = Arc::new(ledger);
             let finalizer = Arc::clone(&ledger).spawn_finalizer();
 
-            let mut wait_for_writer = spawn(ledger.wait_for_writer());
+            let notified = ledger.writer_notified();
+            let mut wait_for_writer = spawn(notified);
```
Comment (bruceg) [inline lib/vector-buffers/src/variants/disk_v2/tests/acknowledgements.rs]: This is effectively the following, which is closer to the original code, right?
```suggestion
            let notified = spawn(ledger.writer_notified());
```

File: lib/vector-buffers/src/variants/disk_v2/ledger.rs [hunk 3]
```diff
@@ -362,12 +366,13 @@ where
...
+    /// Registers interest in writer progress, returning a future that resolves
+    /// when the writer signals.
     ///
-    /// This will occur when a record is written, or when a new data file is created.
+    /// This futures resolves record is written, or when a new data file is created.
     #[cfg_attr(test, instrument(skip(self), level = "trace"))]
-    pub async fn wait_for_writer(&self) {
-        self.writer_notify.notified().await;
+    pub fn writer_notified(&self) -> Notified<'_> {
+        self.writer_notify.notified()
```
Comment (bruceg) [inline lib/vector-buffers/src/variants/disk_v2/ledger.rs]: I don't see how this functionally changes anything, other than changing the return type from an effective `impl Future` into a concrete type. Am I missing something?

Comment (graphcareful) [reply lib/vector-buffers/src/variants/disk_v2/ledger.rs]: This allows the caller to register to be notified before checking some pre-condition to await for, avoiding any races between the await and the condition. This is more of a defensive change, the core of the bugfix is checking `is_writer_done` in `reader.rs`

Comment (bruceg) [reply lib/vector-buffers/src/variants/disk_v2/ledger.rs]: What I'm saying is that `async fn wait_for_writer(&self)` desugars to `fn wait_for_writer(&self) -> impl Future<Output = ()>` and contains a state machine that just waits on `writer_notify.notified` when it's polled (which the optimizer will simplify to just calling the original future), and the new code returns the inner future directly, which will behave the same way. I guess what I'm keying on is that the comment change seems to indicate that the behavior of this function changed, but it hasn't.

Comment (pront) [reply lib/vector-buffers/src/variants/disk_v2/ledger.rs]: We can revert the `writer_notified` change here just to keep this PR minimal.

Comment (graphcareful) [reply lib/vector-buffers/src/variants/disk_v2/ledger.rs]: > the new code returns the inner future directly, which will behave the same way

Yes, the main difference here is that `.await` isn't called within `fn wait_for_writer`, which means the future returned hasn't been yet polled on. The point of the change was to modify the interface so the caller has to decide if/when to poll.

> We can revert the writer_notified change here just to keep this PR minimal.

We could break it out into a separate one?

Comment (pront) [reply lib/vector-buffers/src/variants/disk_v2/ledger.rs]: Hi @graphcareful I want to make sure I understand correctly before making suggestions. 

There are two scenarios here:

1. This change does affect behavior (avoids a race between the condition check and the await). In this case it belongs in this PR as part of the fix. No split needed.
2. This change does not affect behavior, in which case we should just revert it.

Comment (bruceg) [reply lib/vector-buffers/src/variants/disk_v2/ledger.rs]: > Yes, the main difference here is that `.await` isn't called within `fn wait_for_writer`, which means the future returned hasn't been yet polled on.

That isn't how futures work. Nothing happens until they are polled, which always happens in the caller. An `async fn` is always just transformed into returning a future.

Comment (graphcareful) [reply lib/vector-buffers/src/variants/disk_v2/ledger.rs]: > Nothing happens until they are polled, which always happens in the caller
 
Now that the API has changed the caller now has a choice when to poll, which can be after the initial call to `writer_notified`. They can also decide not to poll by never calling `.await` on the returned `Notified`, so its not always guaranteed to always happen in the caller. This occurs in the early exit case.

Comment (graphcareful) [reply lib/vector-buffers/src/variants/disk_v2/ledger.rs]: Spoke with @pront offline, in either case this is not directly related to the core bugfix so will revert.

**Comment by pront** [comment]
@codex review this PR

**Comment by garryliu-stripe** [comment]
@graphcareful any movement in this fix?

**Comment by graphcareful** [comment]
Latest round of changes send the cancel signal to the sinks to force them to gracefully shutdown instead of pause then reconnect buffers. A bit of extra code was added to be able to wait for a sink to fully shut down, since it wasn't really possible to understand when the retain count of a buffer would go to 0 since fanout.rs performed delayed shutdown of channels in the background -- with [no way to wait](https://github.com/vectordotdev/vector/blob/master/lib/vector-core/src/fanout.rs#L321-L328) on that works completion. I had to include that after observing that during manual testing things were fine but my new unit tests failed, so something must have been racing to make things flaky.

**Review by tobz — APPROVED** [review]
Seems straightforward enough to me if it fixes the glitch. 👍🏻

File: changelog.d/24929_fix_stall_on_disk_shutdown.fix.md [hunk 4]
```diff
@@ -0,0 +1,4 @@
+Fixed issue during shutdown or restart of a sink with disk buffer configured where
```
Comment (graphcareful) [inline changelog.d/24929_fix_stall_on_disk_shutdown.fix.md]: Update this, fix no longer involves shutdown path

**Comment by pront** [comment]
@codex review

* focus on unconditional cancel() and graceful drain
* `RunningTopology::stop()` and cancels sink detach triggers

**Comment by graphcareful** [comment]
@codex review

- focus on unconditional cancel() and graceful drain
- RunningTopology::stop() and cancels sink detach triggers

File: src/topology/running.rs [hunk 5]
```diff
@@ -633,24 +649,26 @@ impl RunningTopology {
 
         for key in &sinks_to_change {
             debug!(component_id = %key, "Changing sink.");
-            if reuse_buffers.contains(key) {
+            if reuse_buffers.contains(key) || changed_disk_buffer_sinks.contains(key) {
                 self.detach_triggers
                     .remove(key)
                     .unwrap()
                     .into_inner()
                     .cancel();
```
[the remark this answers is not in the document]
Comment (graphcareful) [reply src/topology/running.rs:652]: This I'm not so sure about, will require more research to confirm/deny

[the remark this answers is not in the document]
Comment (graphcareful) [reply src/topology/running.rs:652]: Here's my thoughts on this:

> Because sink input is wrapped in take_until_if(tripwire), cancellation stops consumption immediately

Yes consumption is stopped but not abruptly, the stream will [flush partial batches](https://github.com/vectordotdev/vector/blob/master/lib/vector-stream/src/partitioned_batcher.rs#L285-L290)

> so queued records are not gracefully drained

In this specific case where we are calling cancel on a disk buffer sink, it is guaranteed that all queued records are gracefully drained because the stream will not end until the [buffer has been emptied](https://github.com/vectordotdev/vector/blob/master/lib/vector-buffers/src/variants/disk_v2/reader.rs#L970-L985)

File: changelog.d/24929_fix_stall_on_disk_shutdown.fix.md [hunk 6]
```diff
@@ -0,0 +1,4 @@
+Fixed issue during in-situ reload of a sink with disk buffer configured where
```
Comment (pront) [inline changelog.d/24929_fix_stall_on_disk_shutdown.fix.md]: There are a few typos here, please revise this changelog. Worth mentioning the shutdown fix here as well.

**Review by pront — COMMENTED** [review]
I tested this locally and the results look very promising: https://gist.github.com/pront/104ac344ab28d24614c1c4ab6572d79e

One concern, the two new unit tests in `reload.rs` prove the reload doesn't deadlock, but they don't send any data
through the disk buffer before triggering the reload. 

I would be more confident in merging this if we added an integration test that exercises the full path: 

```
source → disk buffer → S3 batch → drain on reload → new buffer → S3 delivery resumes
```

The infrastructure already exists:

- `tests/integration/aws/config/compose.yaml` — LocalStack with S3
- `src/sinks/aws_s3/integration_tests.rs` — scaffolding already implemented

Suggested test:

1. Use the config from PR description
2. Send events to the source
3. Check S3 (LocalStack) for the events
4. Change the disk buffer `max_size` and trigger a config reload (same as the `-w` file watcher would). Fail the test if the reload doesn't complete within 5 seconds.
5. Send more events post-reload
6. Assert all events are present in S3

File: src/topology/running.rs [hunk 7]
```diff
@@ -635,24 +651,26 @@ impl RunningTopology {
...
```
[the remark this answers is not in the document]
Comment (pront) [reply src/topology/running.rs:652]: duplicate of https://github.com/vectordotdev/vector/pull/24949#discussion_r3047284559

File: src/topology/running.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (pront) [reply src/topology/running.rs:652]: I _think_ the key distinction here is between records already pulled into the sink's batching pipeline and records still unread in the disk buffer. 

The replacement sink [recreates the disk buffer under the same component key and data directory](https://github.com/vectordotdev/vector/blob/79c27c329/lib/vector-buffers/src/config.rs#L315-L320), unread records remain durable on disk and are picked up by the new buffer instance. And unacknowledged in-flight reads are replayed via the ledger rather than lost. The guarantee comes from disk buffer durability, not from the old reader draining to completion.

**Comment by garryliu-stripe** [comment]
@pront @graphcareful are we able to move forward with this fix? Or is there anything I can help with (i.e. manual testing) to push this forward? 

We generate vector config somewhat dynamically on each host so this deadlock issue actually impose a great risk in our systems

**Comment by graphcareful** [comment]
Hi @garryliu-stripe I am going to add another test and should be good to merge

File: src/topology/running.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (graphcareful) [reply src/topology/running.rs:652]: > The replacement sink [recreates the disk buffer under the same component key and data directory](https://github.com/vectordotdev/vector/blob/79c27c329/lib/vector-buffers/src/config.rs#L315-L320)

Yes the concern isn't that there would be data loss because the files are on disk, but rather that ungraceful drain will cause later replay of events that may have already been sent over the wire. Therefore the user could observe duplicate events in their final destination during a graceful reload event. 

> And unacknowledged in-flight reads are replayed via the ledger rather than lost.

Yup, however this should only happen during ungraceful shutdown. This is also why I modified some of my previous solutions too, to address this.

File: src/topology/builder.rs [hunk 8]
```diff
@@ -884,30 +884,46 @@ async fn run_source_output_pump(
...
+    loop {
+        tokio::select! {
+            biased;
+            // Process control messages (e.g. Remove/Pause) even when the source
+            // is idle, so that config reloads can proceed without waiting for the
+            // next event.
+            alive = fanout.recv_control_message(), if control_channel_open => {
+                if !alive {
+                    control_channel_open = false;
+                }
```
Comment (bruceg) [inline src/topology/builder.rs]: nit: I think this can boil down to just:
```suggestion
                control_channel_open = alive;
```

File: src/sinks/aws_s3/integration_tests.rs [hunk 9]
```diff
@@ -616,10 +701,10 @@ async fn client() -> S3Client {
     .unwrap()
 }
 
-fn config(bucket: &str, batch_size: usize) -> S3SinkConfig {
+fn config(bucket: &str, batch_size: usize, timeout_secs: f64) -> S3SinkConfig {
     let mut batch = BatchConfig::default();
     batch.max_events = Some(batch_size);
-    batch.timeout_secs = Some(5.0);
+    batch.timeout_secs = Some(timeout_secs);
```
Comment (bruceg) [inline src/sinks/aws_s3/integration_tests.rs:717]: nit: Could consider combining these to avoid the `mut`:
```
    let batch = BatchConfig {
        max_events: Some(batch_size),
        timeout_secs: Some(timeout_secs),
        ...BatchConfig::default()
    };
```

File: src/topology/test/reload.rs [hunk 10]
```diff
@@ -320,6 +319,138 @@ async fn topology_reload_component() {
...
+    // config edit) must not stall the reload. Previously, the detach trigger was
+    // only cancelled for sinks whose buffers were being reused, so sinks with
+    // changed disk buffer configs would never have their input stream terminated,
+    // causing the reload to hang indefinitely.
+    test_util::trace_init();
+
+    let (_guard, address) = next_addr();
+
+    let data_dir = temp_dir();
+    std::fs::create_dir(&data_dir).unwrap();
```
Comment (bruceg) [inline src/topology/test/reload.rs:334]: I'd prefer to see the use of something like `tempfile::temp_dir()` which will handle both creation and cleanup.

Actually, I'm not seeing any cleanup at all here. Do these temporary directories and any files within them get removed?

**Review by bruceg — CHANGES_REQUESTED** [review]
The tests give better confidence that this resolves the bug, though I do have a doubt about test cleanup. I'd also like to see commentary on if the codex review comments are valid or not as they sound like serious consistency issues.

File: src/topology/running.rs [hunk 11]
```diff
@@ -628,24 +644,26 @@ impl RunningTopology {
...
```
[the remark this answers is not in the document]
Comment (graphcareful) [reply src/topology/running.rs:652]: @bruceg to explain I think theres a few paths to consider here:
1. Disk -> Disk (data dir unchanged)
  - The on disk buffer files continue to exist at their expected path(s), upon reload of the new sink those events that were flowing through the topology would have landed in the disk buffer. Any events that were dequeued by the old sink were flushed on call to close (explained [here](https://github.com/vectordotdev/vector/pull/24949#discussion_r3047284559)). Any that didn't get a chance to be read will be read off the disk buffer as the new sink continues from last good offset.
2. Disk -> Disk (data dir changed)
  - This [cannot be done](https://github.com/vectordotdev/vector/blob/master/src/topology/running.rs#L288-L293) any config where globals are modified are rejected from inflight reloads 
3. Disk -> Memory: 
  - Any in flight data will be written to the disk buffer but it will lay there dormant, only to ever be read again if the mode was switched back to disk. 
  - Could be considered a way for data loss to occur, if user never switches back to disk mode or renames the sink.
  - However this could be considered to be consistent with existing durability semantics.

**Comment by pront** [comment]
> The tests give better confidence that this resolves the bug, though I do have a doubt about test cleanup. I'd also like to see commentary on if the codex review comments are valid or not as they sound like serious consistency issues.

Thank you for the review. I will come back for a final review after @bruceg approves this PR.

File: src/sinks/aws_s3/integration_tests.rs (hunk 9 above)
Comment (graphcareful) [reply src/sinks/aws_s3/integration_tests.rs:717]: Unfortunately fails to compile due to private fields, however I have removed the `mut` from the other instances of configs in this file.

File: src/topology/test/reload.rs (hunk 10 above)
Comment (graphcareful) [reply src/topology/test/reload.rs:334]: Will change, they previously wrote to /tmp which gets cleared periodically depending on OS

**Review by bruceg — APPROVED** [review]

**Comment by pront** [comment]
What do we think about the open codex comments? 

* https://github.com/vectordotdev/vector/pull/24949#discussion_r3102772200
* https://github.com/vectordotdev/vector/pull/24949#discussion_r3102875801

**Comment by graphcareful** [comment]
> What do we think about the open codex comments?

@pront there were 3 codex comments referring to the same underlying issue, I replied to one of them [here](https://github.com/vectordotdev/vector/pull/24949#discussion_r3112967573)

**Review by pront — APPROVED** [review]

File: src/topology/running.rs [hunk 12]
```diff
@@ -628,24 +644,26 @@ impl RunningTopology {
 
         for key in &sinks_to_change {
             debug!(component_id = %key, "Changing sink.");
-            if reuse_buffers.contains(key) {
+            if reuse_buffers.contains(key) || changed_disk_buffer_sinks.contains(key) {
```
[the remark this answers is not in the document]
Comment (pront) [reply src/topology/running.rs:647]: https://github.com/vectordotdev/vector/pull/24949#discussion_r3112967573

File: src/topology/running.rs [hunk 13]
```diff
@@ -635,24 +651,26 @@ impl RunningTopology {
...
```
[the remark this answers is not in the document]
Comment (pront) [reply src/topology/running.rs:647]: https://github.com/vectordotdev/vector/pull/24949#discussion_r3112967573
