### PR TITLE
fix(core): don't show warning about max allocation groups if tracing not enabled

### LINKED ISSUE #18480: Warning is raised for `Maximum number of registrable allocation group IDs reached` even when `allocation-tracing` is off
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

If you have more than 128 components in your configuration, Vector will issue the warning:

```
"Maximum number of registrable allocation group IDs reached (128). Allocations for component 'xxxxxxx_sink' will be attributed to the root allocation group.","target":"vector::internal_telemetry::allocations"}
```

This warning is only relevant if you are passing `allocation-tracing`. For normal usage, the allocation groups are not used.

The warning should only be raised when you want to trace allocations to prevent confusion.

### Configuration

```text
*a configuration with 129 components*
```

### Version

v0.32.1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by tobz**
This PR ensures that allocation groups are not created/attached to components unless allocation tracing itself is enabled at runtime. Prior to this PR, it would always create/attach them so long as allocation tracing support itself was compiled in. This has the side effect of emitting warnings about exhausting allocation group IDs for configurations with many components (> 128) even when allocation tracing wasn't being used.

We've also made the log message emit at the warning level, rather than the info level, to highlight this fact more prominently.

Fixes #18480.

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Makes sense! Thanks for picking this up.

File: src/internal_telemetry/allocations/mod.rs [hunk 1]
```diff
@@ -21,12 +21,17 @@ pub(crate) use self::allocator::{
...
 const NUM_GROUPS: usize = 128;
+
 // Allocations are not tracked during startup.
 // We use the Relaxed ordering for both stores and loads of this atomic as no other threads exist when
 // this code is running, and all future threads will have a happens-after relationship with
 // this thread -- the main thread -- ensuring that they see the latest value of TRACK_ALLOCATIONS.
 pub static TRACK_ALLOCATIONS: AtomicBool = AtomicBool::new(false);
 
+pub fn is_allocation_tracing_enabled() -> bool {
+    TRACK_ALLOCATIONS.load(Ordering::Acquire)
```
Comment (bruceg) [inline src/internal_telemetry/allocations/mod.rs:32]: Can this not be `Relaxed` as described above?

**Review by bruceg — APPROVED** [review]
