### PR TITLE
fix: Switch to `futures-0.3` channels

### LINKED ISSUE #6043: Investigate performance regression from tokio channel upgrade
It appears that https://github.com/timberio/vector/pull/5868 may have introduced a performance regression. We should investigate and/or decide if it is worth the trade-off.

Specifically, I saw performance regress for the test-harness real_world_1_performance/default benchmark of around 7%:

```
--------------------------------------------------------------------------------
Test Comparison
Test name: real_world_1_performance
Test configuration: default
Subject: vector
Versions: dev-43325a343d4cf0f5156ec14575d00fa2c28bb50c dev-401a9a3d7eeae4891df17eecd920b533b2ee76a1
--------------------------------------------------------------------------------
Metric          | dev-401a9a3d7eeae4891df17ee... | dev-43325a343d4cf0f5156ec14...
----------------|--------------------------------|-------------------------------
Test count      | 1                              | 1                             
Duration (avg)  | 62s                            | 62s                           
Duration (max)  | 62s                            | 62s                           
CPU sys (max)   | 3 (+20%)                       | 2.5 W                         
CPU usr (max)   | 99.5 W                         | 99.5 W                        
Load 1m (avg)   | 1.6 W                          | 1.8 (+13%)                    
Mem used (max)  | 313.1 MiB (+2%)                | 305.1 MiB W                   
Disk read (avg) | 809.7 kib/s W                  | 806 kib/s (0%)                
Disk read (sum) | 49 MiB (+0%)                   | 48.8 MiB W                    
Disk writ (sum) | 80.8 MiB (+0%)                 | 80.7 MiB W                    
Net recv (avg)  | 6.4 MiB/s W                    | 5.9 MiB/s (-7%)               
Net recv (sum)  | 398.3 MiB W                    | 366.9 MiB (-7%)               
Net send (sum)  | 257.2 MiB                      | 238.3 MiB                     
TCP estab (avg) | 599                            | 599                           
TCP syn (avg)   | 0                              | 0                             
TCP close (avg) | 0                              | 0                             
--------------------------------------------------------------------------------
W = winner
vector = dev-401a9a3d7eeae4891df17eecd920b533b2ee76a1
vector = dev-43325a343d4cf0f5156ec14575d00fa2c28bb50c
```

In criterion, I see a regression in some of the topology benchmarks, but an improvement in others:

```
group                            before                                 after
-----                            ------                                 ---
complex/complex                  1.00       2.1±0.02s        ? B/sec    1.13       2.4±0.02s        ? B/sec
interconnected/interconnected    1.23    76.6±22.69ms    24.9 MB/sec    1.00    62.5±17.22ms    30.5 MB/sec
pipe/pipe_big_lines              1.07    164.4±2.59ms   116.0 MB/sec    1.00    153.4±1.95ms   124.3 MB/sec
pipe/pipe_multiple_writers       1.00     37.9±0.21ms     2.5 MB/sec    1.04     39.3±0.28ms     2.4 MB/sec
pipe/pipe_simple                 1.00     35.7±0.05ms    26.7 MB/sec    1.00     35.8±0.19ms    26.7 MB/sec
pipe/pipe_small_lines            1.01     27.9±0.03ms   350.1 KB/sec    1.00     27.6±0.17ms   354.3 KB/sec
transforms/transforms            1.00     60.7±0.16ms    17.3 MB/sec    1.05     63.9±0.07ms    16.4 MB/sec
```

Here `complex/complex`, `transforms/transforms`, `pipe/pipe_simple`, and `pipe/pipe_multiple_writers` show a regression, but the others show an improvement.

### PR DESCRIPTION
**Pull request by ktff**
Closes #6043 

Replaces `tokio-0.2` channels introduced in #5868 with `futures-0.3` channels.

### Todo
- [x] Run `test-harness` benches. Currently I'm failing to do so https://github.com/timberio/vector-test-harness/issues/67 
- [x] Benches that guided this were done on a local computer, let's see what will the benches show here.
- [x] Investigate if are indeed hitting a race in the `futures` channels when shutting down ~~https://github.com/rust-lang/futures-rs/issues/909, fortunately there is PR that fixes it https://github.com/rust-lang/futures-rs/pull/2304~~. `timely_shutdown_lua_timer` is failing consistently. (EDIT: nope, it was just a regular bug)

### OpenQuestions
- [x] Should we also replace, or at least try to replace guided by benchmarks, other usages of `tokio` channels with `future3` channels? (EDIT: Nope, better to leave that for a future issue)

### CODE REVIEW

**Comment by lukesteensen** [comment]
> Should we also replace, or at least try to replace guided by benchmarks, other usages of `tokio` channels with `future3` channels?

I think this can be driven by benchmarks and profiling. I would not go ahead and spend the time to change everything everywhere without good evidence that performance improves meaningfully.

**Review by lukesteensen — APPROVED** [review]
So far this looks reasonable to me!

**Comment by ktff** [comment]
>  I would not go ahead and spend the time to change everything everywhere without good evidence that performance improves meaningfully.

True, then we'll postpone that to a different issue where it will be easier to bench the difference.

File: src/transforms/util/runtime_transform.rs [hunk 1]
```diff
@@ -81,6 +81,7 @@ where
         Box::pin(
             input_rx
                 .map(Message::Process)
+                .fuse()
```
Comment (ktff) [inline src/transforms/util/runtime_transform.rs:84]: Fixes a bug where if no events are sent before shutting down this, then `into_future` will poll this and get `None` which it will pass with the rest of the stream which will be polled again later therefor breaking the stream contract of not calling it after first `None`.

**Comment by jszwedko** [comment]
I was able to run the test harness against these changes and the latest nightly.

Specifically for the real world performance test mentioned in #6043 it looks like this is an improvement:

```
--------------------------------------------------------------------------------
Test Comparison
Test name: real_world_1_performance
Test configuration: default
Subject: vector
Versions: dev-56a30078b6f5c29f61650d9733c0873f35c749a2 nightly/2021-02-01
--------------------------------------------------------------------------------
Metric          | dev-56a30078b6f5c29f61650d9... | nightly/2021-02-01
----------------|--------------------------------|-------------------
Test count      | 1                              | 2                 
Duration (avg)  | 61s                            | 61.5s             
Duration (max)  | 61s                            | 62s               
CPU sys (max)   | 1.5 W                          | 1.8 (+16%)        
CPU usr (max)   | 100 (+0%)                      | 99.5 W            
Load 1m (avg)   | 1.8 (+19%)                     | 1.5 W             
Mem used (max)  | 325.3 MiB (+3%)                | 315.3 MiB W       
Disk read (avg) | 434.6 kib/s (-2%)              | 446.4 kib/s W     
Disk read (sum) | 25.9 MiB W                     | 26.9 MiB (+3%)    
Disk writ (sum) | 277.6 MiB (+554%)              | 42.4 MiB W        
Net recv (avg)  | 6.7 MiB/s W                    | 6.3 MiB/s (-5%)   
Net recv (sum)  | 407.6 MiB W                    | 389.7 MiB (-4%)   
Net send (sum)  | 261.5 MiB                      | 248.1 MiB         
TCP estab (avg) | 603                            | 597               
TCP syn (avg)   | 0                              | 0                 
TCP close (avg) | 0                              | 0                 
--------------------------------------------------------------------------------
W = winner
vector = dev-56a30078b6f5c29f61650d9733c0873f35c749a2
vector = nightly/2021-02-01
```

However I do see some less favorable results for other configurations, for example:

```
--------------------------------------------------------------------------------
Test Comparison
Test name: real_world_1_performance
Test configuration: high_concurrency
Subject: vector
Versions: dev-56a30078b6f5c29f61650d9733c0873f35c749a2 nightly/2021-02-01
--------------------------------------------------------------------------------
Metric          | dev-56a30078b6f5c29f61650d9... | nightly/2021-02-01
----------------|--------------------------------|-------------------
Test count      | 5                              | 2                 
Duration (avg)  | 63.2s                          | 62s               
Duration (max)  | 66s                            | 62s               
CPU sys (max)   | 2.4 W                          | 2.6 (+5%)         
CPU usr (max)   | 28.5 W                         | 32.8 (+15%)       
Load 1m (avg)   | 4.2 W                          | 4.7 (+13%)        
Mem used (max)  | 687.8 MiB (+5%)                | 654.2 MiB W       
Disk read (avg) | 879.7 kib/s W                  | 681.2 kib/s (-22%)
Disk read (sum) | 54 MiB (+31%)                  | 41.2 MiB W        
Disk writ (sum) | 114.2 MiB (+29%)               | 88.1 MiB W        
Net recv (avg)  | 13.9 MiB/s (-22%)              | 18 MiB/s W        
Net recv (sum)  | 876.4 MiB (-21%)               | 1.1 gib W         
Net send (sum)  | 566.4 MiB                      | 722.1 MiB         
TCP estab (avg) | 607.4                          | 602.5             
TCP syn (avg)   | 0                              | 8.5               
TCP close (avg) | 0                              | 0                 
--------------------------------------------------------------------------------
W = winner
vector = dev-56a30078b6f5c29f61650d9733c0873f35c749a2
vector = nightly/2021-02-01
```

My confidence in the test harness is lower than it has been though. I think #6274 will help here.

Full test harness results: https://gist.github.com/jszwedko/9f4236899a0df1450d698f08d86a20bb

I'll try running the criterion benches.

**Comment by jszwedko** [comment]
I keep the criterion ones are already in CI :smile: 

For the topology benches I see:

```
2021-01-29T18:03:48.8351489Z pipe/pipe_simple                                                                                     38.998 ms  -3.2001%     24.455 MiB/s    +3.3059%           0.00  none
2021-01-29T18:03:48.8352485Z pipe/pipe_small_lines                                                                                31.661 ms  -1.6706%     308.45 KiB/s    +1.6989%           0.00  none
2021-01-29T18:03:48.8353287Z pipe/pipe_big_lines                                                                                  156.54 ms  -3.6279%     121.85 MiB/s    +3.7645%           0.00  none
2021-01-29T18:03:48.8354086Z pipe/pipe_multiple_writers                                                                           41.732 ms  -4.7469%     2.2852 MiB/s    +4.9835%           0.00  none
2021-01-29T18:03:48.8354975Z interconnected/interconnected                                                                        64.958 ms  -8.4663%     29.363 MiB/s    +9.2494%           0.02  none
2021-01-29T18:03:48.8355858Z transforms/transforms                                                                                77.984 ms  -1.4718%     13.452 MiB/s    +1.4938%           0.00  none
2021-01-29T18:03:48.8356683Z complex/complex                                                                                      3.0303 s   -5.6531%     unknown         unknown            0.00  none
```

Which does show some improvement, though not more than our noise threshold for those tests (20%). The fact that the improvement is consistent across all of them does give me some confidence though. Given that, I'm fine with this change going in. Hopefully #6274 will illuminate more.

File: src/topology/builder.rs [hunk 2]
```diff
@@ -56,7 +53,7 @@ pub async fn build_pieces(
         .iter()
         .filter(|(name, _)| diff.sources.contains_new(&name))
     {
-        let (tx, rx) = mpsc::channel(1000);
+        let (tx, rx) = tokio::sync::mpsc::channel(1000);
```
Comment (jszwedko) [inline src/topology/builder.rs:56]: Do you mean to keep this on a tokio channel?

Comment (ktff) [reply src/topology/builder.rs:56]: It is intentional. The idea is to restrict the change to what was originally changed in #5868 so to bench against that and avoid improvement/regression of other things to mess with the results.

Comment (jszwedko) [reply src/topology/builder.rs:56]: Ah gotcha :+1:

**Comment by ktff** [comment]
@jszwedko 
>  The fact that the improvement is consistent across all of them does give me some confidence though.

Indeed, in criterion it's more or less consistent, even all of 15 `topology/tcp_socket` benches are showing improvement, but the test harness is somewhat inconclusive, `nightly` seams better overall, but `dev` shows a persistent 2-3% improvement in net recv. Let's wait for #6274 to see what it will show. 

Looking at this results, my main worry is, that since `futures` channels relies more on allocations, that it's faster in criterion benches since it doesn't have to clean up after itself/has more free clean memory/etc during the bench, but that's not true during test harness so it's slower or on par there.

**Comment by jszwedko** [comment]
I merged in master so what the benches look like.

**Comment by ktff** [comment]
Now we are talking 

```
2021-02-04T22:08:55.7594172Z Benchmarking real_world_1/topology: Analyzing
2021-02-04T22:08:57.1529661Z real_world_1/topology   time:   [3.4942 s 3.4978 s 3.5015 s]
2021-02-04T22:08:57.1530289Z                         thrpt:  [28.559 Kelem/s 28.590 Kelem/s 28.619 Kelem/s]
2021-02-04T22:08:57.1530983Z                  change:
2021-02-04T22:08:57.1532055Z                         time:   [-9.8741% -9.7432% -9.6084%] (p = 0.00 < 0.05)
2021-02-04T22:08:57.1532589Z                         thrpt:  [+10.630% +10.795% +10.956%]
```

The new benchmark shows consistent 10% improvement, so I'll run this one more time for good measure since it's a new bench and then we can go ahead in merging this.

cc @jszwedko

**Comment by jszwedko** [comment]
Nice! :tada:
