### PR TITLE
fix(config): Implement `Serialize`/`Display` for `OwnedPath`

### LINKED ISSUE #12256: `lookup::lookup_v2::OwnedPath::serialize` not implemented
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Since updating from 0.20.11 to 0.21.0, vector now crashes on startup with:

```
2022-04-18T09:43:47.551748Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-04-18T09:43:47.551944Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.toml"]
thread 'main' panicked at 'not yet implemented', /project/lib/lookup/src/lookup_v2/mod.rs:30:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: <lookup::lookup_v2::OwnedPath as serde::ser::Serialize>::serialize
   4: serde::ser::impls::<impl serde::ser::Serialize for &T>::serialize
   5: serde::ser::impls::<impl serde::ser::Serialize for &T>::serialize
   6: <T as erased_serde::ser::Serialize>::erased_serialize
   7: core::ops::function::FnOnce::call_once
   8: <T as erased_serde::ser::Serialize>::erased_serialize
   9: <erased_serde::ser::erase::Serializer<T> as erased_serde::ser::Serializer>::erased_serialize_some
  10: <T as erased_serde::ser::Serialize>::erased_serialize
  11: <serde_json::ser::Compound<W,F> as serde::ser::SerializeStruct>::serialize_field
  12: core::ops::function::FnOnce::call_once
  13: <T as erased_serde::ser::Serialize>::erased_serialize
  14: core::ops::function::FnOnce::call_once
  15: <T as erased_serde::ser::Serialize>::erased_serialize
  16: vector::config::builder::_::<impl serde::ser::Serialize for vector::config::builder::ConfigBuilderHash>::serialize
  17: vector::config::builder::ConfigBuilder::sha256_hash
  18: vector::config::compiler::compile
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: vector::app::Application::prepare_from_opts::{{closure}}
  21: vector::app::Application::prepare_from_opts
  22: vector::app::Application::prepare
  23: vector::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

A `vector.toml` that reproduces this issue is attached.
Notably, if I remove the `encoding.only_fields` property of the http sink, vector starts up without panicking.

### Configuration

```text
[sources.journal]
type = "journald"

[sinks.out]
type = "http"
uri = "https://localhost/"
inputs = ["journal"]
encoding.codec = "ndjson"
# Removing this line makes the panic go away:
encoding.only_fields = ["message", "timestamp", "host", "systemd_unit", "file"]
```

### Version

vector 0.21.0 (x86_64-unknown-linux-gnu c1edb89 2022-04-14)

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

#11759 introduced this `todo!`, with some discussion about whether it's possible to hit this panic.

### PR DESCRIPTION
**Pull request by pablosichert**
Fixes #12256.

### CODE REVIEW

File: lib/lookup/src/lookup_v2/mod.rs [hunk 1]
```diff
@@ -22,12 +25,11 @@ impl<'de> Deserialize<'de> for OwnedPath {
...
 
 impl Serialize for OwnedPath {
-    fn serialize<S>(&self, _serializer: S) -> Result<S::Ok, S::Error>
+    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
     where
         S: Serializer,
     {
-        // TODO: Implement canonical way to serialize segments.
-        todo!()
+        serializer.serialize_str(&format!("{}", self))
```
Comment (JeanMertz) [inline lib/lookup/src/lookup_v2/mod.rs:32]:
```suggestion
        serializer.serialize_str(&self.to_string())
```

File: lib/lookup/src/lookup_v2/mod.rs [hunk 2]
```diff
@@ -220,3 +261,56 @@ impl<'a> From<BorrowedSegment<'a>> for OwnedSegment {
...
+            ("foo[", ".foo.<invalid>"),
+            ("foo$", ".<invalid>"),
+            (r#""$peci@l chars""#, r#"."$peci@l chars""#),
+            (".foo.foo bar", ".foo.<invalid>"),
+            (r#".foo."foo bar".bar"#, r#".foo."foo bar".bar"#),
+            ("[1]", "[1]"),
+            ("[42]", "[42]"),
+            (".[42]", ".<invalid>"),
+            ("[42].foo", "[42].foo"),
+            ("[42]foo", "[42].foo"), // TODO: Review, shouldn't this be invalid?
```
Comment (JeanMertz) [inline lib/lookup/src/lookup_v2/mod.rs:298]: Agreed, good to file as separate issue.

File: lib/lookup/src/lookup_v2/mod.rs [hunk 3]
```diff
@@ -186,6 +200,33 @@ impl<'a, 'b: 'a> From<&'b OwnedSegment> for BorrowedSegment<'a> {
     }
 }
 
+impl Display for OwnedSegment {
+    fn fmt(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
+        match self {
+            OwnedSegment::Field(field) => {
+                static UNESCAPED_PATTERN: Lazy<Regex> =
+                    Lazy::new(|| Regex::new(r"^[A-Za-z_0-9@]*$").unwrap());
```
Comment (JeanMertz) [inline lib/lookup/src/lookup_v2/mod.rs:208]: This seems somewhat brittle.

I would expect the `OwnedSegment` (or `Field`?) types to encode whether the segment needs to be escaped. Either through enum variants, or a flag in a struct somewhere.

File: lib/lookup/src/lookup_v2/mod.rs [hunk 4]
```diff
@@ -186,6 +200,33 @@ impl<'a, 'b: 'a> From<&'b OwnedSegment> for BorrowedSegment<'a> {
...
+                        string.push(c);
+                    }
+                    string.push('"');
+                    write!(formatter, ".{}", string)
+                } else {
+                    write!(formatter, ".{}", field)
+                }
+            }
+            OwnedSegment::Index(index) => write!(formatter, "[{}]", index),
+            OwnedSegment::Invalid => write!(formatter, ".<invalid>"),
```
Comment (pablosichert) [inline lib/lookup/src/lookup_v2/mod.rs:225]: I'm not sure why the `Invalid` variant is a thing, and why we don't fail when building a `OwnedSegment` instead.

As long as the variant exists though, I opted to choose the string `.<invalid>` which will again produce a `Invalid` variant when being parsed.

File: lib/lookup/src/lookup_v2/mod.rs [hunk 5]
```diff
@@ -220,3 +261,56 @@ impl<'a> From<BorrowedSegment<'a>> for OwnedSegment {
...
+            ("", ".<invalid>"),
+            (".", "."),
+            ("]", ".<invalid>"),
+            ("]foo", ".<invalid>"),
+            ("..", ".<invalid>"),
+            ("...", ".<invalid>"),
+            ("f", ".f"),
+            (".f", ".f"),
+            (".[", ".<invalid>"),
+            ("f.", ".f"), // TODO: Review, shouldn't this be invalid?
```
[the remark this answers is not in the document]
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs:281]: I copied most of these assertions from the tests in `jit.rs`

https://github.com/vectordotdev/vector/blob/c41e3e95b4052691012a71cf67a7f92271b98591/lib/lookup/src/lookup_v2/jit.rs#L198-L291

and was surprised to find these in there. If these are confirmed to be invalid, I'll leave them out of this PR and file an issue to remove/fix them for `jit.rs` then

File: lib/lookup/src/lookup_v2/mod.rs (hunk 3 above)
Comment (fuchsnj) [reply lib/lookup/src/lookup_v2/mod.rs:208]: If this is implemented by adding the data do `OwnedSegment` or `Field` and then looking it up, just be _very_ careful about how it's implemented. The parser / iterating over the segments is a _very_ hot path and performance is critical. The `Display` path is hopefully not performance sensitive, so I would prefer to defer calculations to it when possible.

File: lib/lookup/src/lookup_v2/mod.rs (hunk 2 above)
Comment (fuchsnj) [reply lib/lookup/src/lookup_v2/mod.rs]: Not sure I agree with this one. `[42]foo` is not ambiguous what it represents, and can easily be parsed. It is also currently supported in VRL.

File: lib/lookup/src/lookup_v2/mod.rs (hunk 3 above)
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: Implemented in 13a88eeefc6242a38fd22cf9ec839b06f586776b. It figures out if the quote is needed and bubbles that information up. Adding that state should not have any performance impact as far as I'm aware

Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: (Since it's doing equality checks on the character for `"` or `\` in match branches before, that might now even have any performance impact, depending on the code that the compiler generates for this switch.)

File: lib/lookup/src/lookup_v2/mod.rs (hunk 2 above)
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: That's funny. Then we probably should not break backwards compatibility here?

File: lib/lookup/src/lookup_v2/mod.rs [hunk 6]
```diff
@@ -220,3 +261,57 @@ impl<'a> From<BorrowedSegment<'a>> for OwnedSegment {
...
+    #[test]
+    fn owned_path_display() {
+        let test_cases = [
+            ("", ".<invalid>"),
+            (".", "."),
+            ("]", ".<invalid>"),
+            ("]foo", ".<invalid>"),
+            ("..", ".<invalid>"),
+            ("...", ".<invalid>"),
+            ("f", ".f"),
```
Comment (fuchsnj) [inline lib/lookup/src/lookup_v2/mod.rs:275]: These are the same thing. A leading `.` means it's part of the event vs a local. This isn't used in VRL today, but it eventually will be and should match.

File: lib/lookup/src/lookup_v2/mod.rs (hunk 2 above)
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: Is that supported since VRL uses the same lookup code now, or has that also been supported pre `0.21`?

Comment (fuchsnj) [reply lib/lookup/src/lookup_v2/mod.rs]: It has been supported in VRL since at least 0.19.0, and probably much longer

File: lib/lookup/src/lookup_v2/mod.rs (hunk 3 above)
Comment (fuchsnj) [reply lib/lookup/src/lookup_v2/mod.rs]: there are some benches in `lib/lookup/benches/lookup.rs` if you want to run that and compare to before this change. Your changes seem reasonable, but I'd prefer to double check since this is used so often.

Comment (JeanMertz) [reply lib/lookup/src/lookup_v2/mod.rs]: Looks good to me @pablosichert 👍 

One suggestion, similar to what we did in VRL, you might want to lower the "requires quoting" variant into a `Field` enum.

This means you'd keep `Field`, `Index`, and `Invalid` for `OwnedSegment`, but `Field` now takes a `Field` type instead of `String`, which is an enum over `Quoted` and `Regular` or something similar.

e.g.:

```rust
enum OwnedSegment {
	Field(Field)
	...
}

enum Field {
	Quoted(String),
	Regular(String),
}
```

File: lib/lookup/src/lookup_v2/mod.rs (hunk 2 above)
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: Thanks for confirming 👍

Comment (JeanMertz) [reply lib/lookup/src/lookup_v2/mod.rs]: It has, but it's a bug. We will definitely fix this at some point, but we don't need to do that here, I agree.

File: lib/lookup/src/lookup_v2/mod.rs (hunk 3 above)
Comment (fuchsnj) [reply lib/lookup/src/lookup_v2/mod.rs]: I really don't like this change. Quoting is purely a visual thing, and adding it into the data of a "field" is unnecessary. It will make specifying paths in the future more difficult too. For example, if in code you want to specify to place something in metadata, (using a macro I've implemented in a current PR), it would look like `path!("metadata", "foo")`. This should generate a static array of `BorrowedSegment`, which is trivial before this change. With this change, we would either need a function to determine if any of those fields need to be quoted, or the user need to supply it which is really error prone. If we need a function to determine if something is quoted, then we can just use that in the `Display` implementation and not complicate the `Field` values.
Similarly, the `BorrowedSegment::field()` function is not assuming the field is _not_ quoted, and there's no alternative for a quoted alternative.

File: lib/lookup/src/lookup_v2/mod.rs [hunk 7]
```diff
@@ -22,12 +22,42 @@ impl<'de> Deserialize<'de> for OwnedPath {
...
+            let path = self
+                .segments
+                .iter()
+                .map(|segment| match segment {
+                    OwnedSegment::Field(field) => {
+                        let needs_quotes = field
+                            .chars()
+                            .any(|c| !matches!(c, 'A'..='Z' | 'a'..='z' | '_' | '0'..='9' | '@'));
+                        if needs_quotes {
+                            let mut string = String::new();
```
Comment (fuchsnj) [inline lib/lookup/src/lookup_v2/mod.rs:41]: why not `String::with_capacity(field.as_bytes().len())`?

**Review by fuchsnj — APPROVED** [review]

File: lib/lookup/src/lookup_v2/mod.rs (hunk 7 above)
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: Also just noticed this when reviewing my own code 😄 That was a clunky leftofer from some refactoring. Went with a slightly different approach in a8d18d2450bff6db7bf0a010af68419467d2c347, but same idea

File: lib/lookup/src/lookup_v2/mod.rs (hunk 3 above)
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: I had the pain of going through all the issues that @fuchsnj mentioned in my approach in d5655ef3f896f2f0799ae79ff17ddd684c011581...

Ideally I'd really like to have the escape information without any additional processing from within `Serialize`, but both the runtime cost and carefullness that instantiating `Segments` all over codebase would require really doesn't seem worth the cost

File: lib/lookup/src/lookup_v2/mod.rs [hunk 8]
```diff
@@ -22,12 +22,45 @@ impl<'de> Deserialize<'de> for OwnedPath {
...
+                .segments
+                .iter()
+                .map(|segment| match segment {
+                    OwnedSegment::Field(field) => {
+                        let needs_quotes = field
+                            .chars()
+                            .any(|c| !matches!(c, 'A'..='Z' | 'a'..='z' | '_' | '0'..='9' | '@'));
+                        if needs_quotes {
+                            let mut string = String::from(r#".""#);
+                            string.reserve(field.as_bytes().len() + 1);
```
Comment (jszwedko) [inline lib/lookup/src/lookup_v2/mod.rs:42]: Not a big deal since this isn't likely to be on a hot path, but it seems like you could have less allocations by doing `String::with_capacity` and then push on the `."`?

Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs:42]: Yeah that seems reasonable. The `push` is likely way cheaper than the first (albeit small) allocation

Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: Applied your suggestion in 5a06ba592bd783dd26baabb1f083e2973a828770

File: lib/lookup/src/lookup_v2/mod.rs (hunk 7 above)
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: 5a06ba592bd783dd26baabb1f083e2973a828770 looks better now and is also what you suggested 😄

File: lib/lookup/src/lookup_v2/mod.rs (hunk 3 above)
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: This doesn't really change the concerns about maintainability, but at least this is not using a regex any more: 1bfbe232ac6cde4d7f01a270bc3473ab0e11a4b3

**Review by jszwedko — APPROVED** [review]
Looks good! I played around with it locally using `vector config`.

File: lib/lookup/src/lookup_v2/mod.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: Opened #12326 to address this

File: lib/lookup/src/lookup_v2/mod.rs (hunk 2 above)
Comment (pablosichert) [reply lib/lookup/src/lookup_v2/mod.rs]: Also mentioned this case in #12326

**Review by jszwedko — APPROVED** [review]
Looks good. For others, I was chatting with Pablo and we realized that the paths shouldn't be serialized with leading `.`s because the are not specified that way in the configuration file (where they are deserialized from).

For example:

```toml
encoding.only_fields = ["foo.bar"]
```

Should be serialized that way rather than:

```toml
encoding.only_fields = [".foo.bar"]
```

**Comment by pablosichert** [comment]
Requesting another round of reviews since we decided that paths should be normalized without a leading `.` (this is consistent with how we communicate e.g. the `include_only` feature in our docs).

Eventually, prefixing paths in configs with `.` should be deprecated, therefore we don't include any tests that have a path with leading `.` as input (since they would pass today, but shouldn't).

**Comment by JeanMertz** [comment]
> Is this what we want long term? I would have thought the leading `.` would be desired so it matches the docs/usage of VRL?

That was my assumption as well.

**Comment by jszwedko** [comment]
> 
> > Is this what we want long term? I would have thought the leading `.` would be desired so it matches the docs/usage of VRL?
> 
> That was my assumption as well.

We haven't made this change, as far as I know. We still document that paths, when used in configuration like `encoding.only_fields`, `sample` transform's `key_field`, etc., do not have a leading `.`. I think we should unify this in the future, but for now, we should maintain compatibility.

File: lib/lookup/src/lookup_v2/mod.rs [hunk 9]
```diff
@@ -22,12 +22,52 @@ impl<'de> Deserialize<'de> for OwnedPath {
...
+                        }
+                    }
+                    OwnedSegment::Index(index) => format!("[{}]", index),
+                    OwnedSegment::Invalid => {
+                        (if i == 0 { "<invalid>" } else { ".<invalid>" }).to_owned()
+                    }
+                })
+                .collect::<Vec<_>>()
+                .join("");
+            serializer.serialize_str(&path)
```
[the remark this answers is not in the document]
Comment (jszwedko) [reply lib/lookup/src/lookup_v2/mod.rs:69]: Yeah, that's a good point. I'll make that change since Pablo is out today.

**Comment by spencergilbert** [comment]
> We haven't made this change, as far as I know. We still document that paths, when used in configuration like `encoding.only_fields`, `sample` transform's `key_field`, etc., do not have a leading `.`. I think we should unify this in the future, but for now, we should maintain compatibility.

Fair - I read the issue as "we now accept leading `.` and raw"

File: lib/lookup/src/lookup_v2/mod.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (jszwedko) [reply lib/lookup/src/lookup_v2/mod.rs:69]: Yeah, we just discovered that while talking through it in stand-up too 😅 We'll leave it as-is.

**Review by fuchsnj — APPROVED** [review]
