### PR TITLE
fix(buffers): update buffer metrics correctly + disk_v2 warning

### LINKED ISSUE #10426: bug(buffers): disk buffers v1/v2 no longer reports events being read out
After merging #10379, both the disk buffers v1 and disk buffers v2 no longer seems to report `buffer_received_events_total`, whereas both the in-memory v1 and in-memory v2 buffer do.

### PR DESCRIPTION
**Pull request by tobz**
This PR accomplishes two main things:
- fixes the usage of `BufferUsageHandle` for both `BufferSender`/`BufferReceiver` and in internally instrumented cases (i.e. the disk buffer v1 code)
- adds a warning message when using `disk_v2`

The warning message is mostly meant to discourage people from using `disk_v2` since it's not ready for prime time yet while still allowing it to be used during testing, soak testing, etc, without a bunch of feature flag changes that slow down the development cycle.

I hand-checked the output of `memory`, `memory_v2`, and `disk_v1`, in terms of metrics, going to Datadog, and all of them report both sent/received metrics and in the right order (i.e. received represents events into the buffer, and sent represents events out of the buffer).

Closes #10426.

### CODE REVIEW

File: src/app.rs [hunk 1]
```diff
@@ -81,6 +82,7 @@ impl Application {
                     format!("file_source={}", level),
                     "tower_limit=trace".to_owned(),
                     format!("rdkafka={}", level),
+                    format!("buffers={}", level),
```
Comment (tobz) [inline src/app.rs:85]: A note: I checked the `buffers` crate and there are no logs at the info level, only debug/trace and the new addition of a warning message in this PR.. so the effective default behavior will be the users only see the new message we've added here if they sleuth out the new `disk_v2` buffer type and configure it.

File: lib/vector-core/buffers/src/disk_v2/ledger.rs [hunk 2]
```diff
@@ -364,12 +367,26 @@ impl Ledger {
     /// Tracks the statistics of a successful write.
     pub fn track_write(&self, record_size: u64) {
         self.state().increment_records(record_size);
+
+        // A 4GB record should not be possible to write, at all.
+        let record_size = record_size
+            .try_into()
+            .expect("record size didn't fit into usize; is this a 32-bit platform?");
```
Comment (jszwedko) [inline lib/vector-core/buffers/src/disk_v2/ledger.rs:374]: Notably we do provide builds for armv7 which is 32-bit. Would it make sense to flag out the disk buffers for that build? I believe we did previously do that for leveldb.

Alternatively, instead of `usize` could we just use a `u64` for `record_size`?

**Review by jszwedko — COMMENTED** [review]
Just one comment about usize vs u64; otherwise looks good to me!

File: lib/vector-core/buffers/src/disk_v2/ledger.rs (hunk 2 above)
Comment (tobz) [reply lib/vector-core/buffers/src/disk_v2/ledger.rs:374]: I specifically use `usize` for _most_ byte-related things because most stdlib APIs use `usize` as the parameter for anything size-related: number of bytes written by `Write::write`, any `len()` method on containers, etc.

Might just be easier to flag it off for those platforms, yeah.

**Review by 001wwang — APPROVED** [review]

File: lib/vector-core/buffers/src/disk_v2/ledger.rs (hunk 2 above)
Comment (jszwedko) [reply lib/vector-core/buffers/src/disk_v2/ledger.rs:374]: I might be missing something, but it seems like we are converting from `u64` into `usize` here only to convert back to `u64` when publishing the metric via `counter!`. In that case, just using `u64`s all the way through would seemingly make sense to me.

Comment (tobz) [reply lib/vector-core/buffers/src/disk_v2/ledger.rs]: Addressed in d472e49.

I ended up not feature flagging the buffers, because thinking through where and when we used `usize` vs `u64`, my conclusion is that we have the right safeguards/fallible conversions in place in the sense of that we start from `usize` and go to `u64`, and then go back from `u64` to `usize`, so we'll fail loudly if that constraint is somehow violated, but as the design stands... it shouldn't actually ever be violated.

**Review by jszwedko — APPROVED** [review]
Looks good! Thanks for swapping out the `usize`s.
