### PR TITLE
enhancement(prometheus_exporter sink): expire metrics

### LINKED ISSUE #5867: prometheus_scrape source or prometheus_exporter sink does not expire values
I'm not sure if the issue here is with the sink or the source, but a user in discord brought up that the last successful scrape value for a metric scraped by the `prometheus_scrape` source was being returned even after the node went away.

https://discord.com/channels/742820443487993987/746070591097798688/796088208386818148

### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)
```

### Vector Configuration File

```toml
[sources.prometheus]
type = "prometheus_scrape"
endpoints = ["http://localhost:9100/metrics"]

[sinks.out]
type = "prometheus_exporter"
inputs = ["prometheus"]
address = "0.0.0.0:9598" # required
```

### Debug Output
```
Jan 05 19:02:36.557  INFO vector::app: Log level is enabled. level="vector=info,codec=info,file_source=info,tower_limit=trace,rdkafka=info"
Jan 05 19:02:36.557  INFO vector::app: Loading configs. path=[("in.toml", None)]
Jan 05 19:02:36.559  INFO vector::topology: Running healthchecks.
Jan 05 19:02:36.559  INFO vector::topology: Starting source. name="prometheus"
Jan 05 19:02:36.559  INFO vector::topology: Starting sink. name="out"
Jan 05 19:02:36.559  INFO vector::topology::builder: Healthcheck: Passed.
Jan 05 19:02:36.559  INFO vector: Vector has started. version="0.11.1" git_version="v0.11.1" released="Thu, 17 Dec 2020 17:03:52 +0000" arch="x86_64"
Jan 05 19:02:36.559  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
Jan 05 19:03:06.568 ERROR source{component_kind="source" component_name=prometheus component_type=prometheus_scrape}: vector::internal_events::prometheus: HTTP request processing error. url=http://localhost:9100/metrics error=CallRequest { source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }
```

### Expected Behavior

`curl`ing the `prometheus_exporter` endpoint after the `prometheus_scrape` source fails to pull metrics should result in those metrics not being returned anymore; otherwise they are stale.

### Actual Behavior

The `prometheus_exporter` endpoint continues to return the last scraped value.

### Reproduce

* Start `node_exporter` (https://prometheus.io/docs/guides/node-exporter/)
* Start `vector` with above config
* `curl localhost:9598/metrics` and note the metrics are there
* Stop the `node_exporter`
* Wait for vector to output a scrape error
* `curl localhost:9598/metrics` and note that the metrics are still there

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #5867

### CODE REVIEW

File: src/sinks/prometheus/exporter.rs [hunk 1]
```diff
@@ -304,32 +310,47 @@ impl StreamSink for PrometheusExporter {
...
-                            metric.zero();
+                    .map(|(mut entry, metadata)| {
+                        if metadata.is_incremental_set {
+                            entry.0.zero();
                         }
-                        (MetricEntry(metric), is_incremental_set)
+                        (entry, metadata)
+                    })
+                    .filter(|(_metric, metadata)| {
+                        metadata.updated_at.elapsed().as_secs() < self.config.flush_period_secs
```
Comment (bruceg) [inline src/sinks/prometheus/exporter.rs:320]: This could use an `Instant::now` computed outside of the filter and `start.duration_since(metadata.updated_at).as_secs()` here.

**Review by bruceg — APPROVED** [review]
Logic looks good. I have an optimization suggestion below for the filter loop.
