### PR TITLE
fix(networking): Rework auto concurrency backpressure logic

### LINKED ISSUE #3424: Handle explicit backpressure in auto-concurrency layer
The auto-concurrency layer detects backpressure based on RTT timing increases or retriable errors. Additional logic should be added to handle explicit backpressure notifications such has HTTP 429 responses.

This will proceed by either adding a method to `RetryLogic` to indicate the backpressure status of either a response or error or, if possible, by adding a new trait implemented by all responses and errors indicating the same:
```rust
pub trait IsBackPressure {
  fn is_back_pressure(&self) -> bool;
}
```

### PR DESCRIPTION
**Pull request by bruceg**
Previously, all responses were marked as not being backpressure. This
changes that logic to:

1. Treat RetryAction::Retry responses as backpressure

2. Only use the RTT values from RetryAction::Successful responses

Signed-off-by: Bruce Guenter <bruce@timber.io>

Closes #3424

### CODE REVIEW

File: src/sinks/util/auto_concurrency/controller.rs [hunk 1]
```diff
@@ -229,8 +229,14 @@ where
         start: Instant,
         response: &Result<L::Response, crate::Error>,
     ) {
-        let is_back_pressure = match response {
-            Ok(_) => false,
+        // It would be better to avoid generating the string in Retry(_)
+        // just to throw it away here, but it's probably not worth the
+        // effort.
+        let response = response
```
Comment (jszwedko) [inline src/sinks/util/auto_concurrency/controller.rs:235]: Should this variable be called something like `retry_status`? It doesn't seem to represent the `response` anymore after being mapped which confused me initially.

**Review by jszwedko — APPROVED** [review]
This looks good! Are there tests for this behavior?

I reran the concurrency tests and it seems to be handling 429s and 503s well now.

The "drop connections over 10 concurrent" test seems to achieve optimal behavior, but I still would have, naively, expected it to more closely match the 429/503 graphs.

all

File: src/sinks/util/auto_concurrency/controller.rs (hunk 1 above)
Comment (bruceg) [reply src/sinks/util/auto_concurrency/controller.rs:235]: Sure, I'll rename.

Comment (bruceg) [reply src/sinks/util/auto_concurrency/controller.rs:235]: > This looks good! Are there tests for this behavior?

Not yet. I'll see about adding that to #3802 

> I reran the concurrency tests and it seems to be handling 429s and 503s well now.

Yay! One step closer. I will say the throughput graphs look a bit ugly, but eyeballing the average looks like it's about right. It would be good to get some numbers on the average for those two, as they still have some surprisingly deep dips.

**Comment by jszwedko** [comment]
> Yay! One step closer. I will say the throughput graphs look a bit ugly, but eyeballing the average looks like it's about right. It would be good to get some numbers on the average for those two, as they still have some surprisingly deep dips.

Agreed, I opened https://github.com/timberio/http_test_server/issues/5 to see about adding that.

@jamtur01 @binarylogic Is it ok to put those issues over there? Or should I open them in the vector repo.

**Comment by jamtur01** [comment]
Over there seems fine.
