### PR TITLE
fix(metrics): Rework the metrics batch buffer

### LINKED ISSUE #5589: Metrics batch buffer does not pass through a single counter
While writing test cases for #5227, I discovered that the metrics batch buffer does not pass through single counter values. All of the internal tests contain multiple values for the same counter, and they pass, but trying to send a single counter disappears.

I wrote up a test case (along with some other refactoring) on this branch: https://github.com/timberio/vector/tree/fix-metric-batch-buffer

### LINKED ISSUE #5700: Metrics batch buffer mixes multiple concerns
The metrics batch buffer is designed to aggregate identical metrics to increase the effective size of the buffer and reduce transmission costs, However, as indicated in https://github.com/timberio/vector/issues/5589#issuecomment-750381902, it has conflicting requirements for doing so:

1. Some sinks, notably the Prometheus sinks, require absolute metrics, and would want incremental metrics converted to absolute where possible.
2. Other sinks, notably Datadog metrics, require incremental metrics, and would want absolute metrics converted to incremental where possible.

Obviously one buffer cannot satisfy both requirements.

These concerns need to be split up such that sinks that require conversion can do so as required. This leads to two possible designs:

1. Three separate metrics batch buffers, which integrate the conversion of metrics with their aggregation. This is likely most efficient for the buffer but worst for code complexity, and so I think we would prefer…
2. A much simplified metrics batch buffer combined with either a pre-process or post-process layer that will do the required conversion specific to the sink.

### LINKED ISSUE #5894: Increase metrics test coverage for absolute metrics
As part of investigating #5698, @bruceg noted that our test coverage for absolute metrics was non-existent for a variety of metics sinks:

> Our current tests only produce relative metrics, and only gauges too IIRC. This one only affects counters, and possibly only absolute ones.

We should be testing all supported metrics types in all sinks to verify that they do not regress like they did in #5698.

### PR DESCRIPTION
**Pull request by bruceg**
The core of this change however is to split the metric normalization logic out of the metrics batch buffer and attach it to the sinks, since there are differing requirements for most of the sinks.

This is a pretty large change to the metrics batch buffer system. A large chunk of the lines changed are relatively simple moves or re-indentation.

I am unsure if the normalization logic for Influxdb metrics sink is actually correct, but it should be the same effective behavior as what it used to do, so it shouldn't introduce any problems.

Closes #5589 

Signed-off-by: Bruce Guenter <bruce@timber.io>

### CODE REVIEW

File: src/sinks/aws_cloudwatch_metrics.rs [hunk 1]
```diff
@@ -166,51 +170,58 @@ impl CloudWatchMetricsSvc {
...
     }
 }
 
+struct AwsCloudwatchMetricNormalize;
+
+impl MetricNormalize for AwsCloudwatchMetricNormalize {
+    fn apply_state(state: &mut MetricSet, metric: Metric) -> Option<Metric> {
+        match &metric.data.value {
+            MetricValue::Gauge { .. } => state.make_absolute(metric),
+            _ => state.make_incremental(metric),
```
Comment (lukesteensen) [inline src/sinks/aws_cloudwatch_metrics.rs:220]: Is it semantically correct to just change the metric kind like this? I would expect that the kind limit which metrics we can pass to a given sink, not that we can just adjust the kind to match what the sink expects. If we can just change it then it seems like there's no point in tracking the kind in the first place.

Comment (bruceg) [reply src/sinks/aws_cloudwatch_metrics.rs:220]: There is more to `make_absolute` and `make_incremental` here than just flipping the `kind` bit. The former uses the state information to accumulate the value of incremental metrics, starting from a zero value, to produce an absolute total. The latter uses a previous absolute value to calculate a delta.

Comment (lukesteensen) [reply src/sinks/aws_cloudwatch_metrics.rs:220]: Ah! I misread, sorry about that.

**Review by lukesteensen — APPROVED** [review]
Looks good to me!

**Comment by lukesteensen** [comment]
A little hard to tell from the interleaved output, but it looks like `test sinks::datadog::logs::tests::smoke_json` may have failed and could be related.

**Comment by bruceg** [comment]
> A little hard to tell from the interleaved output, but it looks like `test sinks::datadog::logs::tests::smoke_json` may have failed and could be related.

I confirm that is the right test that is failing, but only on Windows. It is suspicious that it is only failing on this PR and not master, but I don't see how it is related. AFAICT there are no metrics involved in the code paths of that test. Also, the base64 data reported in the errors decodes to binary noise (it's not UTF-16 neither), and is not found in the code. I don't have access to a Windows test system so I don't see how to proceed other than trying to push additional debug output and watching the CI reports.

File: src/sinks/util/buffer/metrics.rs [hunk 2]
```diff
@@ -281,6 +182,134 @@ impl Batch for MetricBuffer {
...
+    }
+
+    /// Convert the absolute metric into an incremental by calculating
+    /// the increment from the last saved absolute state.
+    fn absolute_to_incremental(&mut self, metric: Metric) -> Option<Metric> {
+        let mut entry = MetricEntry(metric);
+        match self.0.get(&entry) {
+            Some(reference) => {
+                // From the stored reference value, emit an increment
+                entry.data.value.subtract(&reference.data.value);
```
Comment (tustvold) [inline src/sinks/util/buffer/metrics.rs:266]: Shouldn't this store the new value for the absolute metric?

File: src/sinks/util/buffer/metrics.rs [hunk 3]
```diff
@@ -281,6 +182,134 @@ impl Batch for MetricBuffer {
...
+            }
+            None => entry.clone(),
+        };
+        self.0.replace(new_entry);
+        Some(entry.0)
+    }
+
+    /// Produce a fresh state by cloning all the absolute references and
+    /// updating them with any increment previously emitted in this batch.
+    fn fresh(&self, metrics: &Self) -> Self {
```
Comment (tustvold) [inline src/sinks/util/buffer/metrics.rs:295]: I'm a little bit confused as to what this method is doing, although I could be misunderstanding something. As far as I can tell:

The only user of MetricSet is MetricsBuffer which on receiving a metric, feeds this into MetricNormalize::apply_state with a state MetricSet. Any result it will store in a separate `self.metrics` replacing any prior contents. There are four options depending on what it is receiving and what it outputs

**1. Absolute to Absolute**

Doesn't touch state, propagated directly into self.metrics

**2. Absolute to Incremental**

The first Absolute metric is recorded in the state, with future increments computed from this by `absolute_to_incremental` and stored in self.metrics

**3. Incremental to Incremental**

Accumulates incremental metrics within state with `aggregate_incremental`, storing the accumulated total in self.metrics

**4. Incremental to Absolute**

Accumulates absolute value within state, storing the accumulated total in self.metrics

I think the purpose is for the next buffer as created by `fresh` to handle case 2. correctly. Case 1. doesn't touch the state and case 3. is excluded by the filter. Case 4, however, I think is incorrect because entry.data.value.add doesn't check that the metric being added is actually incremental - `metric.data.add` would work I think (this seems like a fairly fun foot-gun that I've actually removed in the branch in which I'm working on #6045)

It is also perhaps worth noting that whilst BatchSink calls fresh via fresh_replace, PartitionBatchSink, as used by prometheus_remote_write, does not and just calls finish and drops the buffer. I think this will break this component.

**Comment by tustvold** [comment]
I'm just spit-balling here, and feel free to ignore me, especially if I'm completely misunderstanding how this component works, but I wonder if it might be simpler to delegate kind-conversion to the sinks? The use of `fresh` to propagate state between subsequent buffers was surprising to me, and seems to be imposing some constraints on correct usage of the Batch trait, which currently aren't upheld by PartitionBatchSink.

Without the kind-conversion the buffer does not need to keep a separate state map, as absolute metrics can just replace old values, and incremental metrics can just be summed.

Something similar to MetricsSet, perhaps type parameterised by MetricNormalize, could then be used within the sinks to avoid duplicating the aggregation logic. This would potentially have an added benefit for sinks where metrics already need to be grouped by MetricName, such as both Prometheus sinks, as this aggregator component could expose the indexed data instead of flattening to a Vec<Metric>. In future it would also be extensible for Sinks to perform more advanced type conversion, for example, converting Histograms to Datadog distribution metrics.

File: src/sinks/util/buffer/metrics.rs (hunk 3 above)
Comment (bruceg) [reply src/sinks/util/buffer/metrics.rs:295]: The purpose of this method is to handle all four cases.

I am not seeing the issue you are describing with case 4. It is true that `MetricValue::add` does not check the metric kind, as that is a separate field, but hashing and comparison on the `MetricEntry` does apply that field, which is why I do that dance with `.into_incremental()` and `.into_absolute()`.

So, when converting an incremental metric to absolute, `incremental_to_absolute` stores the current accumulated value of the incremental metric in the state set, and emits an absolute metric into the metrics set with the same value. When a fresh state set is produced, those accumulated absolute values are cloned, but the update step does not do anything with the emitted absolute metrics, as the `metrics.get` call will not return them.

Your observation about `PartitionBatchSink` is a good insight, and likely explains the problem we saw in #5916 caused by `BatchSink` being replaced by `PartitionBatchSink`. As that is somewhat unrelated to this work, I will open up a new issue for it.

Comment (bruceg) [reply src/sinks/util/buffer/metrics.rs:295]: Ref: https://github.com/timberio/vector/issues/6062#issuecomment-771009689

**Comment by bruceg** [comment]
> I wonder if it might be simpler to delegate kind-conversion to the sinks?

This was the idea behind parameterizing the `MetricsBuffer`, at least to delegate the semantics of the normalization/conversion to the sinks. I see what you are saying about delegating the state itself to the sinks, though. The idea has merit, and could lead to some good simplifications for both `MetricsBuffer` (by eliminating the state buffer) and `trait Batch`. However, it may complicate the batch sink interface, as it requires adding a new mapping layer between the source events and the batch sink. I'll put up a new issue to discuss this aspect.

> Without the kind-conversion the buffer does not need to keep a separate state map, as absolute metrics can just replace old values, and incremental metrics can just be summed.

I originally had the buffer logic as you describe, with incremental metrics adding to the state instead of replacing it, but had some issues with some of the metric handling. However, looking at the current code, I see no reason not to move back to this logic.

File: src/sinks/util/buffer/metrics.rs (hunk 3 above)
Comment (tustvold) [reply src/sinks/util/buffer/metrics.rs:295]: >  but hashing and comparison on the MetricEntry does apply that field, 

You are quite right, I missed this subtlety of the implementation. As you say, whilst the absolute value stored by 4. will get past the filter it will not find a corresponding incremental metric within `metrics`. :+1:

File: src/event/metric.rs [hunk 4]
```diff
@@ -257,11 +257,23 @@ impl Metric {
         self
     }
 
-    /// Create a new Metric from this with all the data but marked as absolute.
-    pub fn to_absolute(&self) -> Self {
+    pub fn into_parts(self) -> (MetricSeries, MetricData) {
```
Comment (pablosichert) [inline src/event/metric.rs:260]: Why is this method needed when the caller can do

```rust
let Metric { series, data } = metric;
```

since the fields are (currently?) public. A simple text-search on this PR also doesn't show any usage of the `into_parts` method.

Comment (bruceg) [reply src/event/metric.rs:260]: I think I added that early on with the expectation it would be useful, but obviously never found a use. I'll drop it.

File: src/event/metric.rs [hunk 5]
```diff
@@ -347,49 +359,130 @@ impl Metric {
...
     /// Update this MetricData by adding the value from another.
     pub fn update(&mut self, other: &Self) {
-        match (&mut self.value, &other.value) {
-            (MetricValue::Counter { ref mut value }, MetricValue::Counter { value: value2 }) => {
+        self.value.add(&other.value)
+    }
+
+    /// Add the data from the other metric to this one. The `other` must
+    /// be relative and contain the same value type as this one.
+    pub fn add(&mut self, other: &Self) {
```
Comment (pablosichert) [inline src/event/metric.rs:398]: Would it make sense to return a `Result` type here? Currently it silently does nothing if the other type is not `::Incremental`, which could lead to bugs that are hard to track down.

File: src/event/metric.rs [hunk 6]
```diff
@@ -408,62 +501,119 @@ impl MetricData {
...
+                        .all(|(b1, b2)| b1.upper_limit == b2.upper_limit)
+                {
+                    for (b1, b2) in quantiles.iter_mut().zip(quantiles2) {
+                        b1.value += b2.value;
+                    }
+                    *count += count2;
+                    *sum += sum2;
+                }
+            }
             _ => {}
```
Comment (pablosichert) [inline src/event/metric.rs:529]: Same question as above, regarding silently aborting.

File: src/event/metric.rs [hunk 7]
```diff
@@ -408,62 +501,119 @@ impl MetricData {
...
+                    for (b1, b2) in quantiles.iter_mut().zip(quantiles2) {
+                        b1.value -= b2.value;
+                    }
+                    *count -= count2;
+                    *sum -= sum2;
                 }
-                *count = 0;
-                *sum = 0.0;
             }
+            _ => {}
```
Comment (pablosichert) [inline src/event/metric.rs:616]: And here.

File: src/sinks/prometheus/exporter.rs [hunk 8]
```diff
@@ -476,12 +477,12 @@ mod tests {
         let map = &sink.metrics.read().unwrap().map;
 
         assert_eq!(
-            map.get_full(&MetricEntry(m1)).unwrap().1 .0.data.value,
```
Comment (pablosichert) [inline src/sinks/prometheus/exporter.rs:479]: Wondering how that space in ` .0` ever passed the formatting checks? 😄

File: src/sinks/sematext/metrics.rs [hunk 9]
```diff
@@ -176,6 +177,21 @@ impl Service<Vec<Metric>> for SematextMetricsService {
...
 
+struct SematextMetricNormalize;
+
+impl MetricNormalize for SematextMetricNormalize {
+    fn apply_state(state: &mut MetricSet, metric: Metric) -> Option<Metric> {
+        match &metric.data.value {
+            MetricValue::Gauge { .. } => state.make_absolute(metric),
+            MetricValue::Counter { .. } => state.make_incremental(metric),
+            _ => {
+                emit!(SematextMetricsInvalidMetricReceived { metric: &metric });
```
Comment (pablosichert) [inline src/sinks/sematext/metrics.rs:188]: Why are the other implementations of `MetricNormalize` able to handle this case, what's the difference here?

File: src/sinks/util/buffer/metrics.rs [hunk 10]
```diff
@@ -281,6 +197,102 @@ impl Batch for MetricBuffer {
     }
 }
 
+/// The metrics state trait abstracts how data point normalization is
+/// done.  Normalisation is required to make sure Sources and Sinks are
```
Comment (pablosichert) [inline src/sinks/util/buffer/metrics.rs:201]: Nit: Remove double space.

File: src/sinks/util/buffer/metrics.rs [hunk 11]
```diff
@@ -281,6 +197,102 @@ impl Batch for MetricBuffer {
...
+    /// application uptime.
+    fn incremental_to_absolute(&mut self, metric: Metric) -> Option<Metric> {
+        let mut entry = MetricEntry(metric.into_absolute());
+        let mut existing = self.0.take(&entry).unwrap_or_else(|| {
+            // Start from zero value if the entry is not found.
+            MetricEntry(entry.zero())
+        });
+        existing.data.value.add(&entry.data.value);
+        entry.data.value = existing.data.value.clone();
+        self.0.insert(existing);
```
Comment (pablosichert) [inline src/sinks/util/buffer/metrics.rs:270]: Would the following be the same?

```suggestion
        entry.data.value.add(&existing.data.value);
        self.0.insert(entry);
```

**Review by pablosichert — APPROVED** [review]
Admittedly, I haven't fully worked into the details of what the bigger implications are for these changes.

However, apart from the suggestions I left, the code looks good.

File: src/event/metric.rs (hunk 5 above)
Comment (bruceg) [reply src/event/metric.rs:398]: This calling interface is copied from the previous implementation. I opted not to change it. I agree it is less than ideal, and we should open an issue to improve this. The callers I was working with ensure the metric kind and type are valid before calling.

File: src/sinks/prometheus/exporter.rs (hunk 8 above)
Comment (bruceg) [reply src/sinks/prometheus/exporter.rs:479]: It's stranger than that. When I was working with that, if I deleted the space, `rustfmt` inserted it.

File: src/sinks/sematext/metrics.rs (hunk 9 above)
Comment (bruceg) [reply src/sinks/sematext/metrics.rs:188]: The other types of metrics are invalid for Sematext. By dropping them in normalize, we don't have to handle them in the buffer or when creating the request. That logic was moved from `fn encode_events`.

File: src/sinks/util/buffer/metrics.rs (hunk 11 above)
Comment (bruceg) [reply src/sinks/util/buffer/metrics.rs:270]: Nope, because `insert` takes ownership of `entry`, and it is returned in the next line.

File: src/sinks/util/buffer/metrics.rs (hunk 10 above)
Comment (bruceg) [reply src/sinks/util/buffer/metrics.rs:201]: Done

File: src/event/metric.rs (hunk 5 above)
Comment (bruceg) [reply src/event/metric.rs:394]: Moved to https://github.com/timberio/vector/issues/6329
