### PR TITLE
fix(reduce transform): Fix flush not occuring when events arrive in high rate

### LINKED ISSUE #16145: Flush never occurs in high frequency events when starts_when and ends_when are not defined
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I current reduce transform, in case both `starts_when` and `ends_when` are not defined, aggregation continues on and on, without flushing as long as events arrive in rate that is faster than the rate of expire_ms between events.

For example, if we want to group by user, but keep getting events in rate faster than 1/minute, then flush will never occur.

### Configuration

```text
[transforms.group_by_user]
  type = "reduce"
  inputs = ["user_log_events"]
  group_by = ["org_id", "user_id"]
  expire_after_ms = 60000
```

### Version

0.27.0

### Reproduction:

Create a configuration file `/tmp/vector.toml`:

```toml
[sources.userpackets]
type = "stdin"
max_length = 1_024

[transforms.jsonize]
type = "remap"
inputs = ["userpackets"]
source = """
  . |= object!(parse_json!(.message))
  del(.message)
"""

[transforms.rrr]
type = "reduce"
inputs = ["jsonize"]
group_by = ["user"]
expire_after_ms = 10_000

[sinks.print]
inputs = ["rrr"]
type = "console"
encoding.codec = "json"
```

Create log generation script, `gen_log.py`:
```python
#!/usr/bin/env python3

import random
import json
import time


def main():
    while True:
        u = random.randint(2, 5)
        d = {
            "user": f"usr-{u}",
            "pkts": random.randint(0, 9) + 100 ** (u-1)
        }
        print(json.dumps(d), flush=True)
        time.sleep(0.4)


main()
```

Run the Vector docker:
```bash
chmod +x gen_log.py
./gen_log.py | docker run --rm -i -v /tmp/vector.toml:/etc/vector/vector.toml timberio/vector:latest-alpine
```

#### Expected behavior
The generated log lines should appear in a reduced manner ever 10 seconds.

#### Observed behavior
The generated log lines never appear.

### PR DESCRIPTION
**Pull request by tomers**
Fixes flush not occuring when events arrive in high frequency (in rate faster then `expire_after` between events).
Fixes #16145.

### CODE REVIEW

File: src/transforms/reduce/mod.rs [hunk 1]
```diff
@@ -264,7 +269,9 @@ impl ReduceState {
             }
         }
         self.events += 1;
-        self.stale_since = Instant::now();
+        if !force_periodic_flush {
```
Comment (davidhuie-dd) [inline src/transforms/reduce/mod.rs:272]: I think we'll want to set `stale_since` here if `expire_after` has passed. Otherwise, we'll be flushing every single new event immediately after we've flushed the first batch of discriminants. In other words, we want to reset back to the start of the reducing state.

Comment (davidhuie-dd) [reply src/transforms/reduce/mod.rs:272]: Actually, after thinking about this some, I think we can do better. `force_periodic_flush` kind of implies that forcing a flush is a feature or an action that we seek out to do with this function, but this behavior should be implicit. Here's an alternative, perhaps more clear way to do this:

What do you think about introducing a new `Instant`, say `self.last_flushed_at`, which we'll use for tracking the time since the last flush? This would allow us to keep `add_event` intact, only changing these `flush_into` lines: https://github.com/vectordotdev/vector/blob/master/src/transforms/reduce/mod.rs#L330

To this:
```
            if t.stale_since.elapsed() >= self.expire_after {
                flush_discriminants.push(k.clone());
            } else if t.last_flushed_at.elapsed() >= self.expire_after {
                flush_discriminants.push(k.clone());
                t.last_flushed_at = Instant::now();
            }
```

That should be the correct behavior around accounting for subsequent batches of discriminants, which the proposed solution doesn't account for.

**Review by davidhuie-dd — CHANGES_REQUESTED** [review]
I agree that we need a fix here, and I provided an alternative to explore. We'll also need some unit testing of this behavior since it's subtle.

File: src/transforms/reduce/mod.rs (hunk 1 above)
Comment (tomers) [reply src/transforms/reduce/mod.rs]: Thanks @davidhuie-dd. I took your suggestion, and it looks much better now! I'l try to add unit test myself, however I could use some help with that :-).

Comment (davidhuie-dd) [reply src/transforms/reduce/mod.rs]: The implementation looks good! Regarding the unit test, we should be able to add VRL that demonstrates the issue, like this: https://github.com/vectordotdev/vector/blob/master/src/transforms/reduce/mod.rs#L819

I'm not 100% sure how we can make time pass, but there's probably an example in the code that we can use.

Comment (tomers) [reply src/transforms/reduce/mod.rs]: @davidhuie-dd , I run `make test SCOPE=reduce` and it takes ~20 minutes to build and run, even after a small change to the test code. It takes 9 seconds on re-run, but then on every change it builds absolutely everything. Is there a faster way to iteratively modify. build and run tests?

Comment (jszwedko) [reply src/transforms/reduce/mod.rs]: Hey @tomers ! Yeah there are some tips here for iterating more quickly: https://github.com/vectordotdev/vector/blob/master/docs/DEVELOPING.md#tips-and-tricks

In your case, in particular, I think it'll go a lot faster if you do `cargo test --no-default-features --features transforms-reduce reduce` which will only build that component.

File: src/transforms/reduce/mod.rs [hunk 2]
```diff
@@ -885,4 +891,48 @@ merge_strategies.bar = "concat"
         })
         .await;
     }
+
+    #[tokio::test]
+    async fn last_flush_at() {
+        let reduce_config = toml::from_str::<ReduceConfig>(indoc! {r#"
+                group_by = ["user_id"]
+                expire_after_ms = 100
```
Comment (davidhuie-dd) [inline src/transforms/reduce/mod.rs:899]: Can we make this 1ms? Just to ensure that the chances of this test fails due to a race condition is low.

Comment (tomers) [reply src/transforms/reduce/mod.rs:902]: This would not be the right thing to do.

In the test we set events to expire after 100ms, and we periodically submit events every 50ms.
Setting expiry to be less than the event submission period would mean that each event expire on his own, before next event shows. This does not reproduce the issue, and it means that this test will pass even without the fix in the codebase.

We test which events arrived after 220ms. Setting expiration to be greater than this value means that no event should expire at the point where we test which events arrived, thus the test will fail.
So overall we must keep`expire_after_ms` in the range `(100,220)`.
We can of course lower all values, e.g. divide them all by a factor of 10 - (5,10,22) instead of (50,100,220), however in that case code execution time might come into effect, so I made a compromise between having a stable test and having it execute in a very short  time.

As a side note, I would like to say that although this test looks as if it should be done in a second, it seems to take much longer. I haven't research that yet, and could use other's help with that.

Comment (davidhuie-dd) [reply src/transforms/reduce/mod.rs:901]: Alright, this looks good to me then.

**Review by davidhuie-dd — APPROVED** [review]

**Comment by davidhuie-dd** [comment]
@tomers looks like the test might've failed in other environments. maybe we need to play with the times?

**Review by davidhuie-dd — APPROVED** [review]

**Comment by tomers** [comment]
@davidhuie-dd can you please approve latest changes? thanks

**Review by fuchsnj — APPROVED** [review]
This makes sense to me. Thanks!
