### PR TITLE
fix(filter transform): Increment dropped events metric on each drop

### LINKED ISSUE #14622: Filter component not reporting events_discarded_total
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Here are three graphs of metrics on a `filter` component.

Screen Shot 2022-09-28 at 14 10 00

Here are the queries behind these graphs:

```
sum:vector.component_received_events_total{component_name:hot_shots_error_filter}.as_count()
sum:vector.component_sent_events_total{component_name:hot_shots_error_filter}.as_count()
sum:vector.events_discarded_total{component_name:hot_shots_error_filter}.as_count()
```

It is unexpected that the `events_discarded_total` graph is showing `0` because this component is clearly filtering things. The first graph has millions while the second has thousands.

I would have expected that metric to be emitted such that summing it with the `component_sent_events_total` metric would yield approximately `component_received_events_total`.

### Configuration

```text
[transforms.hot_shots_error_filter]
  type = "filter"
  inputs = [ "message_string" ]
  condition = '.hot_shots_error'
```

### Version

0.24.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

I considered this: https://github.com/vectordotdev/vector/issues/14464 but since the metric isn't being produced with any tags, this is not the same.

### PR DESCRIPTION
**Pull request by bruceg**
The core fix here is pretty simple, just register the dropped event metric and then increment it on each drop. All the other changes fall out from setting up that registered internal event.

Closes #14622

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Tested locally against my config sample in the linked issue:

```shell
❯ xh :9598/metrics | rg discard
# HELP vector_component_discarded_events_total component_discarded_events_total
# TYPE vector_component_discarded_events_total counter
vector_component_discarded_events_total{host="COMP-J44M27KKWV",intentional="true"} 17 1664560441592
# HELP vector_events_discarded_total events_discarded_total
# TYPE vector_events_discarded_total counter
vector_events_discarded_total{host="COMP-J44M27KKWV"} 17 1664560441592
```

**Review by lukesteensen — APPROVED** [review]

File: lib/vector-common/src/internal_event/mod.rs [hunk 1]
```diff
@@ -95,8 +95,13 @@ pub fn register<E: RegisterInternalEvent>(event: E) -> E::Handle {
 
 pub type Registered<T> = <T as RegisterInternalEvent>::Handle;
 
+#[derive(Clone, Copy)]
 pub struct ByteSize(pub usize);
 
+#[derive(Clone, Copy)]
+pub struct Count(pub usize);
```
Comment (neuronull) [inline lib/vector-common/src/internal_event/mod.rs:102]: Just curious- since the data needs to be cast to `u64` , is it `usize` chosen in the data structure here so that there are fewer overall casts?
Curious because in `ComponentEventsDropped` I used a `u64` with the opposite logic- keeping the type in the data structure consistent with what it will be used as.
Is there is a convention / guideline here?

**Review by neuronull — APPROVED** [review]

File: lib/vector-common/src/internal_event/mod.rs (hunk 1 above)
Comment (bruceg) [reply lib/vector-common/src/internal_event/mod.rs:102]: I made the choice to avoid casts in the users of these data types, centralizing the casts into internal events. Any value that is constrained by the memory size (byte sizes, number of elements, etc) will fit into a `usize`, and `usize` will fit into `u64` on all known architectures that we target or plan to target, so it's safe on all counts to just coerce. The reverse is not true if we ever had to coerce away from `u64` to `usize` as that could be 32-bit.

Comment (bruceg) [reply lib/vector-common/src/internal_event/mod.rs:102]: FWIW I started down the path of converting all users of this new type to use `usize` in the internal events, but decided that would be out of scope for this work.

Comment (neuronull) [reply lib/vector-common/src/internal_event/mod.rs:102]: :+1: Makes sense. Thanks for the context.
