### PR TITLE
fix(buffers): correctly handle partial writes in reader seek during initialization

### LINKED ISSUE #16525: Unrecoverable issue: "Last written record was unable to be deserialized. Corruption likely."
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

This issue most likely happened after an un-graceful shutdown of the kubernetes node vector was running on.
Now the pod keeps crashing will following errors:
```023-02-21T10:51:45.658120Z ERROR vector_buffers::variants::disk_v2::writer: Last written record was unable to be deserialized. Corruption likely. reason="invalid data : check failed for struct member payload: subtree pointer out of bounds: ptr 0x7ff00a60da58 not in range 0x7ff00374f000..0x7ff0059ffa00"  ``` 

```2023-02-21T10:51:57.324468Z ERROR vector::topology: Configuration error. error=Sink "eventhub_sink": error occurred when building buffer: failed to build individual stage 0: failed to seek to position where reader left off: failed to deserialize encoded record from buffer: invalid data: check failed for struct member payload: subtree pointer out of bounds: ptr 0x7ff00a6340d8 not in range 0x7ff00a64f280..0x7ff00a650880````

### Configuration

```text
sources:
    vector_source:
      type: vector
      address: 0.0.0.0:9000
      version: "2"
  sinks:
    eventhub_sink:
      type: kafka
      buffer:
        type: "disk"
        max_size: 536870912
      inputs:
        - vector_source
      encoding: 
        codec: json
      bootstrap_servers: "${EVENTHUB_NAMESPACE}.servicebus.windows.net:9093"
      topic: topic-name
      sasl:
        enabled: true
        mechanism: "PLAIN"
        username: "$$ConnectionString"
        password: "${EVENTHUB_CONNECTION_STRING}"
      healthcheck: true
      compression: none
      message_timeout_ms: 0
      librdkafka_options:
        "security.protocol": sasl_ssl
        "socket.keepalive.enable": "true"
        "metadata.max.age.ms": "180000"
        "request.timeout.ms": "30000"
        "partitioner": "consistent_random"
```

### Version

0.27.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by tobz**
## Context

In some cases, a buffer can fail to reopen after Vector has been stopped in an impromptu fashion, due to a partially-written record that causes the reader to loop endlessly, waiting for data that can't possibly arrive.

Fixes #16525, #16463, and #16231.

## Solution

In this PR, we've simply piggybacked on some existing logic in the reader -- logic which decides whether or not it should keep waiting for data or should return that there wasn't enough data -- in order to avoid endlessly looping during the buffer initialization phase.

This ensures that when we indicate that the read should be "finalized" -- either the writer is done or we're still getting the buffer initialized -- and there's either not enough data to read the length delimiter, or there's not as many bytes as the length delimiter indicates there should be... we properly return an error indicating a partial write.

Additionally, we've tweaked the reader initialization logic to properly ignore these errors, and other non-I/O-based errors, as they should not be bubbled up to the user, as the errors may have come from previously-processed records _or_ will be correctly handled during the next read _after_ the buffer is initialized.

## Testing

A new unit test is included that exercises this behavior, and I approached it in the TDD style or writing it first, observing that it failed, and then fixing it.

### CODE REVIEW

**Review by bruceg — APPROVED** [review]

File: lib/vector-buffers/src/variants/disk_v2/tests/initialization.rs [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+            let data_file_path = ledger.get_current_writer_data_file_path();
+            drop(reader);
+            drop(writer);
+            drop(ledger);
+
+            // Open the data file and drop the last eight bytes of the record, which will ensure
+            // that there is less data available to read than the number of bytes indicated by the
+            // record's length delimiter.
+            let initial_len = first_bytes_written as u64;
+            let target_len = initial_len - 8;
```
Comment (spencergilbert) [inline lib/vector-buffers/src/variants/disk_v2/tests/initialization.rs:69]: I can't think of any, but could there be a case where `8` doesn't trigger this condition - should it be `arbitrary`?

**Review by spencergilbert — APPROVED** [review]
Only question was a likely, _no_, so this lgtm.

File: lib/vector-buffers/src/variants/disk_v2/tests/initialization.rs (hunk 1 above)
Comment (tobz) [reply lib/vector-buffers/src/variants/disk_v2/tests/initialization.rs:69]: In this case, all that matters is that we remove a portion of the actual record payload, so that the amount of bytes encoded in the length delimiter is greater than the number of bytes available to read after it.
