### PR TITLE
fix(setup): Fix get_gnu_musl_glibc function

### LINKED ISSUE #10740: Install script installs wrong version on Alpine Linux
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As the title says, running the install command as found here: https://vector.dev/docs/setup/installation/

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash
```

results in the wrong version being installed on my Alpine Linux 3.15 system..

```
# curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash
                                   __   __  __
                                   \ \ / / / /
                                    \ V / / /
                                     \_/  \/

                                   V E C T O R
                                    Installer


--------------------------------------------------------------------------------
Website: https://vector.dev
Docs: https://vector.dev/docs/
Community: https://vector.dev/community/
--------------------------------------------------------------------------------

>>> We'll be installing Vector via a pre-built archive at https://packages.timber.io/vector/0.19.0/
>>> Ready to proceed? (y/n)

>>> y

--------------------------------------------------------------------------------

musl libc (x86_64)
Version 1.2.2
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
>>> Unknown architecture from ldd: 
>>> Downloading Vector via https://packages.timber.io/vector/0.19.0/vector-0.19.0-x86_64-unknown-linux-gnu.tar.gz ✓
>>> Unpacking archive to /root/.vector ... ✓
>>> Adding Vector path to /root/.zprofile>>> Adding Vector path to /root/.profile ✓
>>> Install succeeded! 🚀
>>> To start Vector:

    vector --config ~/.vector/config/vector.toml

>>> More information at https://vector.dev/docs/
```

I expect it's an issue with either the script calling alpine's ldd incorrectly, or parsing its output incorrectly.  But I could be wrong.

### Vector Version

```
0.19.0
```

### Expected Behavior

Download and install vector-0.19.0-x86_64-unknown-linux-musl.tar.gz

### Actual Behavior

Downloaded and installed vector-0.19.0-x86_64-unknown-linux-gnu.tar.gz

### Additional Context

```
# uname -vr
5.15.12-0-lts #1-Alpine SMP Fri, 31 Dec 2021 13:23:07 +0000

# cat /etc/alpine-release 
3.15.0

# ldd --version
musl libc (x86_64)
Version 1.2.2
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
```

### Workaround

Download and install vector-0.19.0-x86_64-unknown-linux-musl.tar.gz manually.

### PR DESCRIPTION
**Pull request by spencergilbert**
Signed-off-by: Spencer Gilbert <spencer.gilbert@datadoghq.com>

Closes #10740

This fixes the case on Alpine where the `ldd --version` output is on STDERR, as well as Ubuntu where "GNU" is not included in the `ldd --version` output.
Also included is a minor change to fix linebreaks when adding Vector to the user's path.

Before:

```bash
>>> Unpacking archive to /root/.vector ... ✓
>>> Adding Vector path to /root/.zprofile>>> Adding Vector path to /root/.profile ✓
>>> Install succeeded! 🚀
```

After:

```bash
>>> Unpacking archive to /root/.vector ... ✓
>>> Adding Vector path to /root/.zprofile  ✓
>>> Adding Vector path to /root/.profile  ✓
>>> Install succeeded! 🚀
```

Ubuntu 20.04.3

```bash
ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

### CODE REVIEW

**Review by binarylogic — APPROVED** [review]

File: distribution/install.sh [hunk 1]
```diff
@@ -209,26 +210,18 @@ add_to_path() {
...
   need_cmd awk
   # Detect both gnu and musl
-  # Also detect glibc versions older than 2.18 and return musl for these
-  # Required until we address https://github.com/timberio/vector/issues/5412.
   local _ldd_version
   local _glibc_version
-  _ldd_version=$(ldd --version)
-  if [[ $_ldd_version =~ "GNU" ]]; then
-    _glibc_version=$(echo "$_ldd_version" | awk '/ldd/{print $NF}')
-    if [ 1 -eq "$(echo "${_glibc_version} < 2.18" | bc)" ]; then
```
Comment (jszwedko) [inline distribution/install.sh:222]: I noticed we dropped this check. The associated issue is closed, but are we aware of the minimum libc version we currently require? It could be good to still include the check but update the minimum libc version.

Comment (spencergilbert) [reply distribution/install.sh:222]: Ah, I'm not - @silversupreme had just noticed that the issue had been closed a while back. I'm not entirely sure how to verify this?

Comment (jszwedko) [reply distribution/install.sh:222]: This script seems to work pretty well: https://gist.github.com/fasterthanlime/17e002a8f5e0f189861c

The `x86_64-unknown-linux-gnu` build seems to require 2.14. We'd want to check `aarch64-unknown-linux-gnu` and `armv7-unknown-linux-gnueabihf` too. This could even be something we do in CI to enforce it.

Comment (jszwedko) [reply distribution/install.sh:222]: I'm fine with this being a follow-up but would suggest we replace the conservative check we have now until we can figure out the new min supported version.

**Review by jszwedko — APPROVED** [review]
