### PR TITLE
fix!(codecs): Use '\0' delimiter as default stream decode framer

### LINKED ISSUE #20768: GELF decoder's default framer with TCP input does not match the encoder's default
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

As discussed in #18008, the GELF encoder was using newline delimited but graylog expected it to be '\0' delimited (https://go2docs.graylog.org/5-0/getting_in_log_data/gelf.html)

Reviewing the code, it seems that the GELF decoder is still using the newline delimiter as default in TCP inputs
https://github.com/vectordotdev/vector/blob/3de6f0b8175c8a08da1974d6b6e9634075244a06/src/sources/socket/mod.rs#L123
https://github.com/vectordotdev/vector/blob/3de6f0b8175c8a08da1974d6b6e9634075244a06/lib/codecs/src/decoding/mod.rs#L337

Should this be changed to match the encoder's default and read streaming gelf with the '\0' delimiter? 

### Configuration

_No response_

### Version

0.40.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

#18008

### PR DESCRIPTION
**Pull request by jorgehermo9**
Closes #20768.

I think that in my local environment some test fail but has nothing to do with the changes I did. Could you trigger them here and if its fails too in the CI I review what could happen?

Thanks

### CODE REVIEW

File: lib/codecs/src/decoding/framing/character_delimited.rs [hunk 1]
```diff
@@ -53,7 +59,7 @@ pub struct CharacterDelimitedDecoderOptions {
 
 impl CharacterDelimitedDecoderOptions {
     /// Create a `CharacterDelimitedDecoderOptions` with a delimiter and optional max_length.
-    pub fn new(delimiter: u8, max_length: Option<usize>) -> Self {
+    pub const fn new(delimiter: u8, max_length: Option<usize>) -> Self {
```
Comment (jorgehermo9) [inline lib/codecs/src/decoding/framing/character_delimited.rs:62]: Noticed this and didn't hurt

File: lib/codecs/src/encoding/mod.rs [hunk 2]
```diff
@@ -362,12 +362,14 @@ impl SerializerConfig {
                 FramingConfig::LengthDelimited(LengthDelimitedEncoderConfig::default())
             }
             SerializerConfig::Csv(_)
-            | SerializerConfig::Gelf
             | SerializerConfig::Json(_)
             | SerializerConfig::Logfmt
             | SerializerConfig::NativeJson
             | SerializerConfig::RawMessage
             | SerializerConfig::Text(_) => FramingConfig::NewlineDelimited,
+            SerializerConfig::Gelf => {
```
Comment (jorgehermo9) [inline lib/codecs/src/encoding/mod.rs:370]: In order to be consistent with the `default_stream_framing` of the `DeserializerConfig`. Noticed that this change was missing in #18008. Changed it here, but tell me if you want this PR to not do anything out of scope from #20768.

File: src/codecs/decoding/decoder.rs [hunk 3]
```diff
@@ -138,4 +138,33 @@ mod tests {
         let event = next.unwrap().0.pop().unwrap().into_log();
         assert_eq!(event.get("bar").unwrap(), &Value::from(2));
     }
+
+    #[tokio::test]
+    async fn gelf_streaming_decoding() {
```
Comment (jorgehermo9) [inline src/codecs/decoding/decoder.rs:143]: Added this test, I don't know if its correct to place it here. Didn't find anywhere else to place it.

I'm new in this project and can't find some modules easily. 
Maybe this test is more of an integration test, but couldn't find any related in the root `/tests` directory. I'm missing something?

It would be nice to have something like a TCP socket integration test where we test this same behavior...As the `default_stream_framing` is also called in https://github.com/vectordotdev/vector/blob/e982f6679e9d1526d856efa462e728774b52cf34/src/sources/socket/mod.rs#L123.

I thought of adding a similar test like this in https://github.com/vectordotdev/vector/blob/e982f6679e9d1526d856efa462e728774b52cf34/src/sources/socket/mod.rs#L391, what do you think?
In that case, I would create a TCP config setting only `decoding = DeserializerConfig::from(GelfDeserializerConfig)`(and leaving the framing as None in that config) and see how the TCP initialization takes the default framer.

What are your thoughts of all of this?

**Comment by jorgehermo9** [comment]
Please, note that this is a breaking change as we are changing the default framing. 

Maybe someone configured a source to send '\n' delimited gelf messages and left the vector config as the default, asumming that it would be correct.

In my opinion, we should adhere to the stardard and go ahead with this "breaking change"

File: lib/codecs/src/encoding/mod.rs (hunk 2 above)
Comment (jszwedko) [reply lib/codecs/src/encoding/mod.rs:370]: Huh, yeah, this does seem like an oversight. I'm trying to understand the impact of it though since the original PR did seem to resolve the issue for people 🤔

**Review by jszwedko — COMMENTED** [review]
Thanks for this fix @jorgehermo9!

Do you mind adding a changelog fragment? See https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md

I think the test you added is ok. I'd actually be content with just testing the the default is set correctly without testing that it actually decode with the default config and `\0` delimited input since the character delimited codec is tested separately. If anything, you could add a test to `lib/codecs/src/decoding/framing/character_delimited.rs` that tests `\0` works as a delimiter, but I don't think it is strictly necessary.

**Comment by jorgehermo9** [comment]
Thanks for the review! I'll submit the changes asap.

> I'd actually be content with just testing the the default is set correctly without testing that it actually decode with the default config and \0 delimited input since the character delimited codec is tested separately

Right, I will narrow the scope of that test, no problem. It seemed too simple for me to just test that, but it doesn't have sense to test the \0 framing there...

File: lib/codecs/src/decoding/mod.rs [hunk 4]
```diff
@@ -334,14 +334,16 @@ impl DeserializerConfig {
...
-            | DeserializerConfig::Gelf(_)
             | DeserializerConfig::NativeJson(_) => {
                 FramingConfig::NewlineDelimited(Default::default())
             }
             DeserializerConfig::Protobuf(_) => FramingConfig::Bytes,
             #[cfg(feature = "syslog")]
             DeserializerConfig::Syslog(_) => FramingConfig::NewlineDelimited(Default::default()),
             DeserializerConfig::Vrl(_) => FramingConfig::Bytes,
+            DeserializerConfig::Gelf(_) => {
+                FramingConfig::CharacterDelimited(CharacterDelimitedDecoderConfig::new(0))
```
Comment (jorgehermo9) [inline lib/codecs/src/decoding/mod.rs:345]: I was thinking about this these days... I think that GELF Http maybe uses newline delimiter? I can't find anything related to streaming gelf in Http here https://go2docs.graylog.org/5-0/getting_in_log_data/gelf.html, but maybe someone will rely on that for http sources also and this will be a breaking change in those cases too, not only with TCP.

If you are ok with that, I will include that breaking changes and the "fix" (manually setting the newline delimiter in `framing.method`) in the changelog fragment

Comment (jszwedko) [reply lib/codecs/src/decoding/mod.rs:345]: Interesting, I haven't heard of anyone using GELF over HTTP, but it seems plausible. TCP seems to be the dominant transport so I think it makes sense to configure the defaults to work well with that.

File: lib/codecs/src/encoding/mod.rs (hunk 2 above)
Comment (jorgehermo9) [reply lib/codecs/src/encoding/mod.rs:370]: It seems that the changed struct was `EncodingConfigWithFraming` (#18419).

It seems that a few places relies on `EncodingConfigWithFraming` to get this default behaviour, and other places uses this method `SerializerConfig::default_stream_framing`. For example, see this line https://github.com/vectordotdev/vector/blob/67a5e4682138721575b22369cf5ba629cd86ce55/src/components/validation/resources/mod.rs#L113
Where we can see its relying on `SerializerConfig::default_stream_framing` in order to get the default framing for a given encoder.

There are a lot of sinks that relies on `EncodingConfigWithFraming` having a Option<FramingConfig> in order to calculate that default (https://github.com/search?q=repo%3Avectordotdev%2Fvector%20EncodingConfigWithFraming&type=code) https://github.com/vectordotdev/vector/blob/67a5e4682138721575b22369cf5ba629cd86ce55/src/codecs/encoding/config.rs#L110

**Comment by jorgehermo9** [comment]
Hi @jszwedko, I'm sorry for addressing the changes that late. I simplified that test and moved it to another file.

Could you trigger the CI and see if everything works ok?

File: changelog.d/20768-default_gelf_stream_framing.breaking.md [hunk 5]
```diff
@@ -0,0 +1,31 @@
+Now the GELF codec with stream-based sources uses null byte (`\0`) by default as messages delimiter instead of newline (`\n`) character.
```
Comment (jszwedko) [inline changelog.d/20768-default_gelf_stream_framing.breaking.md:1]:
```suggestion
Now the GELF codec with stream-based sources uses null byte (`\0`) by default as messages delimiter instead of newline (`\n`) character. This better matches GELF server behavior.
```

File: changelog.d/20768-default_gelf_stream_framing.breaking.md [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+
+### Configuration changes
+
+In order to maintain the previous behavior, you must set the `framing.method` option to the `character_delimited` method and the `framing.character_delimited.delimiter` option to `\n` when using GELF codec with stream-based sources.
+
+### Example configuration change for socket source
```
Comment (jszwedko) [inline changelog.d/20768-default_gelf_stream_framing.breaking.md:7]: Awesome, thanks for including the example for using the previous default.

Small nit that we try to use YAML rather than TOML as the default these days.

File: lib/codecs/src/encoding/mod.rs (hunk 2 above)
Comment (jszwedko) [reply lib/codecs/src/encoding/mod.rs:370]: Aha, gotcha, thanks for looking into that.

**Review by jszwedko — APPROVED** [review]
Awesome, thanks again for this change @jorgehermo9 !

File: changelog.d/20768-default_gelf_stream_framing.breaking.md (hunk 6 above)
Comment (jorgehermo9) [reply changelog.d/20768-default_gelf_stream_framing.breaking.md:7]: Done!

**Review by jszwedko — APPROVED** [review]
Thanks again for this!

**Comment by jorgehermo9** [comment]
Thank you very much for your prompt review!
