### PR TITLE
fix (aws service): use http client so we can use openssl tls.

### LINKED ISSUE #19879: aws_s3 Source Failing to assume_role After Update to 0.36.0
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We just updated our Vector deployment to use version 0.36.0, and suddenly a pipeline of ours which is utilizing the `aws_s3` source with an `assume_role` which grants it access to an SQS queue and S3 bucket stopped being able to access messages in the SQS queue. This pipeline has been running without issue for 4 months on previous Vector versions (the latest we've used before this was 0.35.0), so it seems like a change introduced in 0.35.1 or later has caused the problem.

Our other pipelines that don't rely on an assume_role are still working just fine with the newest version, which leads us to believe that something has changed with the way that:  auth: assume_role:  works in the aws_s3 source. Does anyone have any ideas? We have a hunch it could be related to this change in 0.35.1, but aren't sure: https://github.com/vectordotdev/vector/commit/c2cc94a262ecf39798009d29751d59cc97baa0c5#diff-d6eef19144b594971c40fce6c9e73777c346036e50277c3874a665ce31bccfb8 

Debug logs show an issue we've never seen before re: environment variables, which seems like the culprit: `environment variable not set (CredentialsNotLoaded(CredentialsNotLoaded { source: "environment variable not set" }))`

### Configuration

```text
our_source_name:
    type: aws_s3
    compression: auto
    region: eu-central-1
    sqs:
      delete_message: true
      queue_url: source_sqs_queue_url
    auth:
      assume_role: assume_role_arn
      region: "us-east-1"
```
```


### Version

vector 0.36.0

### Debug Output

```text
2024-02-14T21:56:29.202231Z DEBUG assume_role:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: loaded credentials provider=WebIdentityToken
2024-02-14T21:56:29.202336Z DEBUG assume_role: aws_config::sts::assume_role: retrieving assumed credentials
2024-02-14T21:56:29.202384Z DEBUG assume_role:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider in chain did not provide credentials provider=Environment context=the credential provider was not enabled: environment variable not set (CredentialsNotLoaded(CredentialsNotLoaded { source: "environment variable not set" }))
2024-02-14T21:56:29.202401Z DEBUG assume_role:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider in chain did not provide credentials provider=Profile context=the credential provider was not enabled: No profiles were defined (CredentialsNotLoaded(CredentialsNotLoaded { source: NoProfilesDefined }))
```

### Example Data

_No response_

### Additional Context

Here are the error logs we're seeing related to this issue: ```vector::internal_events::aws_sqs: Failed to fetch SQS events. error=dispatch failure error_code="failed_fetching_sqs_events" error_type="request_failed" stage="receiving" internal_log_rate_limit=true```

### References

_No response_

### PR DESCRIPTION
**Pull request by StephenWakely**
Fixes #19879 

The assume role authentication wasn't using the http client, so when it needed to use TLS it was raising an error. Prior to the AWS crate upgrade it was using OpenSSL by default so TLS was built in. V1 of the crates use RustTLS, which we are avoiding, so we turn this feature off and rely on setting up the HTTP client ourselves.

I haven't been able to reproduce the exact error that was reported, but I'm fairly certain it's related. I will shortly have a custom build available for testing if someone want to check that this fixes the issue in their environment.

### CODE REVIEW

File: src/aws/auth.rs [hunk 1]
```diff
@@ -266,8 +267,20 @@ impl AwsAuthentication {
...
+                let connector = HyperClientBuilder::new().build(tls_connector);
+                let config = SdkConfig::builder()
+                    .http_client(connector)
+                    .region(auth_region.clone())
+                    .time_source(SystemTimeSource::new())
+                    .build();
+
+                let mut builder = AssumeRoleProviderBuilder::new(assume_role)
+                    .region(auth_region.clone())
+                    .configure(&config);
```
Comment (jszwedko) [inline src/aws/auth.rs:283]: Do we need to add this to the `AwsAuthentication::Default ` arm too? The default credential provider can also assume role using STS based on environment variable configuration (`$AWS_ROLE_ARN`).

**Review by jszwedko — COMMENTED** [review]
Just one question, otherwise this looks good to me to fix the panic you saw. I'd feel better if we saw the exact same issue users saw but I agree with building a custom build to see if one of them can verify.

File: src/aws/auth.rs (hunk 1 above)
Comment (StephenWakely) [reply src/aws/auth.rs]: Good catch. I've refactored the code into a separate function so all uses do the same thing.

**Comment by StephenWakely** [comment]
I wasn't able to reproduce the exact error message reported in the original issue, but I was able to get an error. Have tested this PR in EKS and it now works.

In the process I stumbled across a separate issue #19959 which I will now look into.

**Comment by StephenWakely** [comment]
For the curious, the error message I was getting is:

```
2024-02-27T16:07:00.973034Z  INFO vector::app: Log level is enabled. level="info"
2024-02-27T16:07:00.973676Z  INFO vector::app: Loading configs. paths=["/etc/vector"]
2024-02-27T16:07:00.975737Z  INFO source{component_kind="source" component_id=kubernetes_logs component_type=kubernetes_logs}: vector::sources::kubernetes_logs: Obtained Kubernetes Node name to collect logs for (self). self_node_name="ip-192-168-41-216.ec2.internal"
2024-02-27T16:07:00.990585Z  INFO source{component_kind="source" component_id=kubernetes_logs component_type=kubernetes_logs}: vector::sources::kubernetes_logs: Excluding matching files. exclude_paths=["**/*.gz", "**/*.tmp"]
2024-02-27T16:07:01.064456Z  WARN sink{component_kind="sink" component_id=s3 component_type=aws_s3}:load_region{provider=ImdsRegionProvider { client: Client { operation: Operation { service_name: "imds", operation_name: "get", runtime_plugins: RuntimePlugins { client_plugins: [SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_identity_cache_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: Some(Tracked { _origin: "default_identity_cache_plugin", value: SharedIdentityCache(LazyCache { partitions: CachePartitions { partitions: RwLock { data: {}, poisoned: false, .. }, buffer_time: 10s }, load_timeout: 5s, buffer_time: 10s, buffer_time_jitter_fraction: 0x7f873baa4450, default_expiration: 900s }) }), identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_retry_config", items: [TypeErasedBox[!Clone]:Set(RetryConfig { mode: Standard, max_attempts: 1, initial_backoff: 1s, max_backoff: 20s, reconnect_mode: ReconnectOnTransientError, use_static_exponential_base: false }), TypeErasedBox[!Clone]:Set(RetryPartition { name: "imds" })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_retry_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: Some(Tracked { _origin: "default_retry_config_plugin", value: SharedRetryStrategy(StandardRetryStrategy { retry_permit: Mutex { data: None, poisoned: false, .. } }) }), time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_retry_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_sleep_impl_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: Some(Tracked { _origin: "default_sleep_impl_plugin", value: SharedAsyncSleep(TokioSleep) }), config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_time_source_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: Some(Tracked { _origin: "default_time_source_plugin", value: SharedTimeSource(SystemTimeSource) }), sleep_impl: None, config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_timeout_config", items: [TypeErasedBox[!Clone]:Set(TimeoutConfig { connect_timeout: None, read_timeout: None, operation_timeout: None, operation_attempt_timeout: None })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_timeout_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_timeout_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_stalled_stream_protection_config", items: [TypeErasedBox[!Clone]:Set(StalledStreamProtectionConfig { is_enabled: true, grace_period: 5s })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_stalled_stream_protection_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_stalled_stream_protection_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "operation", items: [TypeErasedBox[!Clone]:Set(SharedResponseDeserializer(FnDeserializer)), TypeErasedBox[!Clone]:Set(SharedRequestSerializer(FnSerializer))] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "operation", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [Tracked { _origin: "operation", value: SharedInterceptor { interceptor: ConnectionPoisoningInterceptor } }], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [] }), order: None }), SharedRuntimePlugin(ImdsCommonRuntimePlugin { config: FrozenLayer(Layer { name: "ImdsCommonRuntimePlugin", items: [TypeErasedBox[!Clone]:Set(AwsUserAgent { sdk_metadata: SdkMetadata { name: "rust", version: "1.1.4" }, api_metadata: ApiMetadata { service_id: "imds", version: "1.0.1" }, os_metadata: OsMetadata { os_family: Linux, version: None }, language_metadata: LanguageMetadata { lang: "rust", version: "1.75.0", extras: AdditionalMetadataList([]) }, exec_env_metadata: None, feature_metadata: [], config_metadata: [], framework_metadata: [], app_name: None }), TypeErasedBox[!Clone]:Set(EndpointResolverParams(TypeErasedBox[!Clone]:())), TypeErasedBox[!Clone]:Set(RetryConfig { mode: Standard, max_attempts: 4, initial_backoff: 1s, max_backoff: 20s, reconnect_mode: ReconnectOnTransientError, use_static_exponential_base: false }), TypeErasedBox[!Clone]:Set(SensitiveOutput), TypeErasedBox[!Clone]:Set(TimeoutConfig { connect_timeout: Some(1s), read_timeout: Some(1s), operation_timeout: None, operation_attempt_timeout: None }), TypeErasedBox[!Clone]:Set(AuthSchemeOptionResolverParams(TypeErasedBox[!Clone]:()))] }), components: RuntimeComponentsBuilder { builder_name: "ImdsCommonRuntimePlugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedEndpointResolver(ImdsEndpointResolver { endpoint_source: Env(ProviderConfig { env: Env(Real), fs: Fs(Real), time_source: SharedTimeSource(SystemTimeSource), http_client: None, sleep_impl: Some(SharedAsyncSleep(TokioSleep)), region: None, use_fips: None, use_dual_stack: None, profile_name_override: None }), mode_override: None }) }), auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedInterceptor { interceptor: UserAgentInterceptor } }], retry_classifiers: [Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedRetryClassifier(ImdsResponseRetryClassifier) }], retry_strategy: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedRetryStrategy(StandardRetryStrategy { retry_permit: Mutex { data: None, poisoned: false, .. } }) }), time_source: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedTimeSource(SystemTimeSource) }), sleep_impl: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedAsyncSleep(TokioSleep) }), config_validators: [] } }), SharedRuntimePlugin(TokenRuntimePlugin { components: RuntimeComponentsBuilder { builder_name: "TokenRuntimePlugin", auth_scheme_option_resolver: Some(Tracked { _origin: "TokenRuntimePlugin", value: SharedAuthSchemeOptionResolver(StaticAuthSchemeOptionResolver { auth_scheme_options: [AuthSchemeId { scheme_id: "x-aws-ec2-metadata-token" }] }) }), http_client: None, endpoint_resolver: None, auth_schemes: [Tracked { _origin: "TokenRuntimePlugin", value: SharedAuthScheme(TokenAuthScheme { signer: TokenSigner }) }], identity_cache: Some(Tracked { _origin: "TokenRuntimePlugin", value: SharedIdentityCache(NoCache) }), identity_resolvers: Some({AuthSchemeId { scheme_id: "x-aws-ec2-metadata-token" }: Tracked { _origin: "TokenRuntimePlugin", value: SharedIdentityResolver { inner: TokenResolver { inner: TokenResolverInner { cache: ExpiringCache { buffer_time: 120s, value: RwLock { data: OnceCell { value: None } }, _phantom: PhantomData<aws_config::imds::client::error::ImdsError> }, refresh: Operation { service_name: "imds", operation_name: "get-token", runtime_plugins: RuntimePlugins { client_plugins: [SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_identity_cache_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: Some(Tracked { _origin: "default_identity_cache_plugin", value: SharedIdentityCache(LazyCache { partitions: CachePartitions { partitions: RwLock { data: {}, poisoned: false, .. }, buffer_time: 10s }, load_timeout: 5s, buffer_time: 10s, buffer_time_jitter_fraction: 0x7f873baa4450, default_expiration: 900s }) }), identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_retry_config", items: [TypeErasedBox[!Clone]:Set(RetryConfig { mode: Standard, max_attempts: 1, initial_backoff: 1s, max_backoff: 20s, reconnect_mode: ReconnectOnTransientError, use_static_exponential_base: false }), TypeErasedBox[!Clone]:Set(RetryPartition { name: "imds" })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_retry_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: Some(Tracked { _origin: "default_retry_config_plugin", value: SharedRetryStrategy(StandardRetryStrategy { retry_permit: Mutex { data: None, poisoned: false, .. } }) }), time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_retry_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_sleep_impl_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: Some(Tracked { _origin: "default_sleep_impl_plugin", value: SharedAsyncSleep(TokioSleep) }), config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_time_source_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: Some(Tracked { _origin: "default_time_source_plugin", value: SharedTimeSource(SystemTimeSource) }), sleep_impl: None, config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_timeout_config", items: [TypeErasedBox[!Clone]:Set(TimeoutConfig { connect_timeout: None, read_timeout: None, operation_timeout: None, operation_attempt_timeout: None })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_timeout_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_timeout_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_stalled_stream_protection_config", items: [TypeErasedBox[!Clone]:Set(StalledStreamProtectionConfig { is_enabled: true, grace_period: 5s })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_stalled_stream_protection_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_stalled_stream_protection_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "operation", items: [TypeErasedBox[!Clone]:Set(SharedRequestSerializer(FnSerializer)), TypeErasedBox[!Clone]:Set(SharedResponseDeserializer(FnDeserializer)), TypeErasedBox[!Clone]:Set(AuthSchemeOptionResolverParams(TypeErasedBox[!Clone]:()))] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "operation", auth_scheme_option_resolver: Some(Tracked { _origin: "operation", value: SharedAuthSchemeOptionResolver(StaticAuthSchemeOptionResolver { auth_scheme_options: [AuthSchemeId { scheme_id: "no_auth" }] }) }), http_client: None, endpoint_resolver: None, auth_schemes: [Tracked { _origin: "operation", value: SharedAuthScheme(NoAuthScheme { signer: NoAuthSigner }) }], identity_cache: Some(Tracked { _origin: "operation", value: SharedIdentityCache(NoCache) }), identity_resolvers: Some({AuthSchemeId { scheme_id: "no_auth" }: Tracked { _origin: "operation", value: SharedIdentityResolver { inner: NoAuthIdentityResolver, cache_partition: IdentityCachePartition(5) } }}), interceptors: [Tracked { _origin: "operation", value: SharedInterceptor { interceptor: ConnectionPoisoningInterceptor } }], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [] }), order: None }), SharedRuntimePlugin(ImdsCommonRuntimePlugin { config: FrozenLayer(Layer { name: "ImdsCommonRuntimePlugin", items: [TypeErasedBox[!Clone]:Set(AwsUserAgent { sdk_metadata: SdkMetadata { name: "rust", version: "1.1.4" }, api_metadata: ApiMetadata { service_id: "imds", version: "1.0.1" }, os_metadata: OsMetadata { os_family: Linux, version: None }, language_metadata: LanguageMetadata { lang: "rust", version: "1.75.0", extras: AdditionalMetadataList([]) }, exec_env_metadata: None, feature_metadata: [], config_metadata: [], framework_metadata: [], app_name: None }), TypeErasedBox[!Clone]:Set(EndpointResolverParams(TypeErasedBox[!Clone]:())), TypeErasedBox[!Clone]:Set(RetryConfig { mode: Standard, max_attempts: 4, initial_backoff: 1s, max_backoff: 20s, reconnect_mode: ReconnectOnTransientError, use_static_exponential_base: false }), TypeErasedBox[!Clone]:Set(SensitiveOutput), TypeErasedBox[!Clone]:Set(TimeoutConfig { connect_timeout: Some(1s), read_timeout: Some(1s), operation_timeout: None, operation_attempt_timeout: None }), TypeErasedBox[!Clone]:Set(AuthSchemeOptionResolverParams(TypeErasedBox[!Clone]:()))] }), components: RuntimeComponentsBuilder { builder_name: "ImdsCommonRuntimePlugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedEndpointResolver(ImdsEndpointResolver { endpoint_source: Env(ProviderConfig { env: Env(Real), fs: Fs(Real), time_source: SharedTimeSource(SystemTimeSource), http_client: None, sleep_impl: Some(SharedAsyncSleep(TokioSleep)), region: None, use_fips: None, use_dual_stack: None, profile_name_override: None }), mode_override: None }) }), auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedInterceptor { interceptor: UserAgentInterceptor } }], retry_classifiers: [Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedRetryClassifier(ImdsResponseRetryClassifier) }], retry_strategy: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedRetryStrategy(StandardRetryStrategy { retry_permit: Mutex { data: None, poisoned: false, .. } }) }), time_source: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedTimeSource(SystemTimeSource) }), sleep_impl: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedAsyncSleep(TokioSleep) }), config_validators: [] } })], operation_plugins: [] }, _phantom: PhantomData<((), aws_config::imds::client::token::TtlToken, aws_config::imds::client::error::TokenError)> } } }, cache_partition: IdentityCachePartition(6) } }}), interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [] } })], operation_plugins: [] }, _phantom: PhantomData<(alloc::string::String, aws_config::imds::client::SensitiveString, aws_config::imds::client::error::InnerImdsError)> } }, env: Env(Real) }}: aws_config::imds::region: failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: No HTTP client was available to send this request. Enable the `rustls` crate feature or configure a HTTP client to fix this. (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: "No HTTP client was available to send this request. Enable the `rustls` crate feature or configure a HTTP client to fix this.", connection: Unknown } }) }))
2024-02-27T16:07:01.065607Z  WARN sink{component_kind="sink" component_id=s3 component_type=aws_s3}:load_region{provider=ImdsRegionProvider { client: Client { operation: Operation { service_name: "imds", operation_name: "get", runtime_plugins: RuntimePlugins { client_plugins: [SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_identity_cache_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: Some(Tracked { _origin: "default_identity_cache_plugin", value: SharedIdentityCache(LazyCache { partitions: CachePartitions { partitions: RwLock { data: {}, poisoned: false, .. }, buffer_time: 10s }, load_timeout: 5s, buffer_time: 10s, buffer_time_jitter_fraction: 0x7f873baa4450, default_expiration: 900s }) }), identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_retry_config", items: [TypeErasedBox[!Clone]:Set(RetryConfig { mode: Standard, max_attempts: 1, initial_backoff: 1s, max_backoff: 20s, reconnect_mode: ReconnectOnTransientError, use_static_exponential_base: false }), TypeErasedBox[!Clone]:Set(RetryPartition { name: "imds" })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_retry_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: Some(Tracked { _origin: "default_retry_config_plugin", value: SharedRetryStrategy(StandardRetryStrategy { retry_permit: Mutex { data: None, poisoned: false, .. } }) }), time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_retry_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_sleep_impl_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: Some(Tracked { _origin: "default_sleep_impl_plugin", value: SharedAsyncSleep(TokioSleep) }), config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_time_source_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: Some(Tracked { _origin: "default_time_source_plugin", value: SharedTimeSource(SystemTimeSource) }), sleep_impl: None, config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_timeout_config", items: [TypeErasedBox[!Clone]:Set(TimeoutConfig { connect_timeout: None, read_timeout: None, operation_timeout: None, operation_attempt_timeout: None })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_timeout_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_timeout_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_stalled_stream_protection_config", items: [TypeErasedBox[!Clone]:Set(StalledStreamProtectionConfig { is_enabled: true, grace_period: 5s })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_stalled_stream_protection_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_stalled_stream_protection_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "operation", items: [TypeErasedBox[!Clone]:Set(SharedResponseDeserializer(FnDeserializer)), TypeErasedBox[!Clone]:Set(SharedRequestSerializer(FnSerializer))] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "operation", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [Tracked { _origin: "operation", value: SharedInterceptor { interceptor: ConnectionPoisoningInterceptor } }], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [] }), order: None }), SharedRuntimePlugin(ImdsCommonRuntimePlugin { config: FrozenLayer(Layer { name: "ImdsCommonRuntimePlugin", items: [TypeErasedBox[!Clone]:Set(AwsUserAgent { sdk_metadata: SdkMetadata { name: "rust", version: "1.1.4" }, api_metadata: ApiMetadata { service_id: "imds", version: "1.0.1" }, os_metadata: OsMetadata { os_family: Linux, version: None }, language_metadata: LanguageMetadata { lang: "rust", version: "1.75.0", extras: AdditionalMetadataList([]) }, exec_env_metadata: None, feature_metadata: [], config_metadata: [], framework_metadata: [], app_name: None }), TypeErasedBox[!Clone]:Set(EndpointResolverParams(TypeErasedBox[!Clone]:())), TypeErasedBox[!Clone]:Set(RetryConfig { mode: Standard, max_attempts: 4, initial_backoff: 1s, max_backoff: 20s, reconnect_mode: ReconnectOnTransientError, use_static_exponential_base: false }), TypeErasedBox[!Clone]:Set(SensitiveOutput), TypeErasedBox[!Clone]:Set(TimeoutConfig { connect_timeout: Some(1s), read_timeout: Some(1s), operation_timeout: None, operation_attempt_timeout: None }), TypeErasedBox[!Clone]:Set(AuthSchemeOptionResolverParams(TypeErasedBox[!Clone]:()))] }), components: RuntimeComponentsBuilder { builder_name: "ImdsCommonRuntimePlugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedEndpointResolver(ImdsEndpointResolver { endpoint_source: Env(ProviderConfig { env: Env(Real), fs: Fs(Real), time_source: SharedTimeSource(SystemTimeSource), http_client: None, sleep_impl: Some(SharedAsyncSleep(TokioSleep)), region: None, use_fips: None, use_dual_stack: None, profile_name_override: None }), mode_override: None }) }), auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedInterceptor { interceptor: UserAgentInterceptor } }], retry_classifiers: [Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedRetryClassifier(ImdsResponseRetryClassifier) }], retry_strategy: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedRetryStrategy(StandardRetryStrategy { retry_permit: Mutex { data: None, poisoned: false, .. } }) }), time_source: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedTimeSource(SystemTimeSource) }), sleep_impl: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedAsyncSleep(TokioSleep) }), config_validators: [] } }), SharedRuntimePlugin(TokenRuntimePlugin { components: RuntimeComponentsBuilder { builder_name: "TokenRuntimePlugin", auth_scheme_option_resolver: Some(Tracked { _origin: "TokenRuntimePlugin", value: SharedAuthSchemeOptionResolver(StaticAuthSchemeOptionResolver { auth_scheme_options: [AuthSchemeId { scheme_id: "x-aws-ec2-metadata-token" }] }) }), http_client: None, endpoint_resolver: None, auth_schemes: [Tracked { _origin: "TokenRuntimePlugin", value: SharedAuthScheme(TokenAuthScheme { signer: TokenSigner }) }], identity_cache: Some(Tracked { _origin: "TokenRuntimePlugin", value: SharedIdentityCache(NoCache) }), identity_resolvers: Some({AuthSchemeId { scheme_id: "x-aws-ec2-metadata-token" }: Tracked { _origin: "TokenRuntimePlugin", value: SharedIdentityResolver { inner: TokenResolver { inner: TokenResolverInner { cache: ExpiringCache { buffer_time: 120s, value: RwLock { data: OnceCell { value: None } }, _phantom: PhantomData<aws_config::imds::client::error::ImdsError> }, refresh: Operation { service_name: "imds", operation_name: "get-token", runtime_plugins: RuntimePlugins { client_plugins: [SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_identity_cache_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: Some(Tracked { _origin: "default_identity_cache_plugin", value: SharedIdentityCache(LazyCache { partitions: CachePartitions { partitions: RwLock { data: {}, poisoned: false, .. }, buffer_time: 10s }, load_timeout: 5s, buffer_time: 10s, buffer_time_jitter_fraction: 0x7f873baa4450, default_expiration: 900s }) }), identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_retry_config", items: [TypeErasedBox[!Clone]:Set(RetryConfig { mode: Standard, max_attempts: 1, initial_backoff: 1s, max_backoff: 20s, reconnect_mode: ReconnectOnTransientError, use_static_exponential_base: false }), TypeErasedBox[!Clone]:Set(RetryPartition { name: "imds" })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_retry_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: Some(Tracked { _origin: "default_retry_config_plugin", value: SharedRetryStrategy(StandardRetryStrategy { retry_permit: Mutex { data: None, poisoned: false, .. } }) }), time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_retry_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_sleep_impl_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: Some(Tracked { _origin: "default_sleep_impl_plugin", value: SharedAsyncSleep(TokioSleep) }), config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: None, runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_time_source_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: Some(Tracked { _origin: "default_time_source_plugin", value: SharedTimeSource(SystemTimeSource) }), sleep_impl: None, config_validators: [] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_timeout_config", items: [TypeErasedBox[!Clone]:Set(TimeoutConfig { connect_timeout: None, read_timeout: None, operation_timeout: None, operation_attempt_timeout: None })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_timeout_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_timeout_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "default_stalled_stream_protection_config", items: [TypeErasedBox[!Clone]:Set(StalledStreamProtectionConfig { is_enabled: true, grace_period: 5s })] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "default_stalled_stream_protection_config_plugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: None, auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [Tracked { _origin: "default_stalled_stream_protection_config_plugin", value: SharedConfigValidator { inner: StaticFn } }] }), order: Some(Defaults) }), SharedRuntimePlugin(StaticRuntimePlugin { config: Some(FrozenLayer(Layer { name: "operation", items: [TypeErasedBox[!Clone]:Set(SharedRequestSerializer(FnSerializer)), TypeErasedBox[!Clone]:Set(SharedResponseDeserializer(FnDeserializer)), TypeErasedBox[!Clone]:Set(AuthSchemeOptionResolverParams(TypeErasedBox[!Clone]:()))] })), runtime_components: Some(RuntimeComponentsBuilder { builder_name: "operation", auth_scheme_option_resolver: Some(Tracked { _origin: "operation", value: SharedAuthSchemeOptionResolver(StaticAuthSchemeOptionResolver { auth_scheme_options: [AuthSchemeId { scheme_id: "no_auth" }] }) }), http_client: None, endpoint_resolver: None, auth_schemes: [Tracked { _origin: "operation", value: SharedAuthScheme(NoAuthScheme { signer: NoAuthSigner }) }], identity_cache: Some(Tracked { _origin: "operation", value: SharedIdentityCache(NoCache) }), identity_resolvers: Some({AuthSchemeId { scheme_id: "no_auth" }: Tracked { _origin: "operation", value: SharedIdentityResolver { inner: NoAuthIdentityResolver, cache_partition: IdentityCachePartition(7) } }}), interceptors: [Tracked { _origin: "operation", value: SharedInterceptor { interceptor: ConnectionPoisoningInterceptor } }], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [] }), order: None }), SharedRuntimePlugin(ImdsCommonRuntimePlugin { config: FrozenLayer(Layer { name: "ImdsCommonRuntimePlugin", items: [TypeErasedBox[!Clone]:Set(AwsUserAgent { sdk_metadata: SdkMetadata { name: "rust", version: "1.1.4" }, api_metadata: ApiMetadata { service_id: "imds", version: "1.0.1" }, os_metadata: OsMetadata { os_family: Linux, version: None }, language_metadata: LanguageMetadata { lang: "rust", version: "1.75.0", extras: AdditionalMetadataList([]) }, exec_env_metadata: None, feature_metadata: [], config_metadata: [], framework_metadata: [], app_name: None }), TypeErasedBox[!Clone]:Set(EndpointResolverParams(TypeErasedBox[!Clone]:())), TypeErasedBox[!Clone]:Set(RetryConfig { mode: Standard, max_attempts: 4, initial_backoff: 1s, max_backoff: 20s, reconnect_mode: ReconnectOnTransientError, use_static_exponential_base: false }), TypeErasedBox[!Clone]:Set(SensitiveOutput), TypeErasedBox[!Clone]:Set(TimeoutConfig { connect_timeout: Some(1s), read_timeout: Some(1s), operation_timeout: None, operation_attempt_timeout: None }), TypeErasedBox[!Clone]:Set(AuthSchemeOptionResolverParams(TypeErasedBox[!Clone]:()))] }), components: RuntimeComponentsBuilder { builder_name: "ImdsCommonRuntimePlugin", auth_scheme_option_resolver: None, http_client: None, endpoint_resolver: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedEndpointResolver(ImdsEndpointResolver { endpoint_source: Env(ProviderConfig { env: Env(Real), fs: Fs(Real), time_source: SharedTimeSource(SystemTimeSource), http_client: None, sleep_impl: Some(SharedAsyncSleep(TokioSleep)), region: None, use_fips: None, use_dual_stack: None, profile_name_override: None }), mode_override: None }) }), auth_schemes: [], identity_cache: None, identity_resolvers: None, interceptors: [Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedInterceptor { interceptor: UserAgentInterceptor } }], retry_classifiers: [Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedRetryClassifier(ImdsResponseRetryClassifier) }], retry_strategy: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedRetryStrategy(StandardRetryStrategy { retry_permit: Mutex { data: None, poisoned: false, .. } }) }), time_source: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedTimeSource(SystemTimeSource) }), sleep_impl: Some(Tracked { _origin: "ImdsCommonRuntimePlugin", value: SharedAsyncSleep(TokioSleep) }), config_validators: [] } })], operation_plugins: [] }, _phantom: PhantomData<((), aws_config::imds::client::token::TtlToken, aws_config::imds::client::error::TokenError)> } } }, cache_partition: IdentityCachePartition(8) } }}), interceptors: [], retry_classifiers: [], retry_strategy: None, time_source: None, sleep_impl: None, config_validators: [] } })], operation_plugins: [] }, _phantom: PhantomData<(alloc::string::String, aws_config::imds::client::SensitiveString, aws_config::imds::client::error::InnerImdsError)> } }, env: Env(Real) }}: aws_config::imds::region: failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: No HTTP client was available to send this request. Enable the `rustls` crate feature or configure a HTTP client to fix this. (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: "No HTTP client was available to send this request. Enable the `rustls` crate feature or configure a HTTP client to fix this.", connection: Unknown } }) }))
2024-02-27T16:07:01.075376Z  INFO vector::topology::running: Running healthchecks.
2024-02-27T16:07:01.075487Z  INFO vector: Vector has started. debug="false" version="0.36.0" arch="x86_64" revision="a5e48bb 2024-02-13 14:43:11.911392615"
2024-02-27T16:07:01.075506Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
2024-02-27T16:07:01.076641Z  INFO source{component_kind="source" component_id=kubernetes_logs component_type=kubernetes_logs}:file_server: file_source::checkpointer: Loaded checkpoint data.
2024-02-27T16:07:01.078247Z ERROR vector::topology::builder: msg="Healthcheck failed." error=dispatch failure component_kind="sink" component_type="aws_s3" component_id=s3
```

File: src/aws/mod.rs [hunk 2]
```diff
@@ -3,6 +3,7 @@ pub mod auth;
 pub mod region;
 
 pub use auth::{AwsAuthentication, ImdsAuthentication};
+// use aws_config::{meta::region::ProvideRegion, retry::RetryConfig, Region, SdkConfig};
```
Comment (bruceg) [inline src/aws/mod.rs:6]: Can this be removed instead of commented out?

File: src/aws/mod.rs [hunk 3]
```diff
@@ -94,6 +96,24 @@ fn check_response(res: &HttpResponse) -> bool {
         || (status.is_client_error() && re.is_match(response_body.as_ref()))
 }
 
+/// Creates the http connector that has been configured to use the given proxy and TLS settings.
+/// All AWS requests should use this connector as the aws crates by default use RustTLS which we
+/// have turned off as we want to consistently use openssl.
+fn connector(
+    proxy: &ProxyConfig,
+    tls_options: &Option<TlsConfig>,
+) -> crate::Result<SharedHttpClient> {
```
Comment (bruceg) [inline src/aws/mod.rs:105]: Will this function ever be useful from outside of Vector, or is it effectively "exported" by think like the client builder that is already `pub`?

File: Cargo.toml [hunk 4]
```diff
@@ -181,6 +181,7 @@ aws-sdk-cloudwatchlogs = { version = "1.3.0", default-features = false, features
 aws-sdk-elasticsearch = { version = "1.3.0", default-features = false, features = ["behavior-version-latest"], optional = true }
 aws-sdk-firehose = { version = "1.3.0", default-features = false, features = ["behavior-version-latest"], optional = true }
 aws-sdk-kinesis = { version = "1.3.0", default-features = false, features = ["behavior-version-latest"], optional = true }
+aws-sdk-sts = { version = "1.3.0", default-features = false, features = ["behavior-version-latest"], optional = true }
```
Comment (bruceg) [inline Cargo.toml:184]: I didn't see anything in this PR that is using `aws_sdk_sds` directly. Is this added just to add the feature flag, or is this a remnant of an intermediate step?

Comment (StephenWakely) [reply Cargo.toml:184]: It needs the feature flag, and if I recall the error only occurs at runtime when you select a specific combination of authentication mechanisms. I'll spend a moment trying to replicate it - but for safety I think it's probably worth keeping it there.

File: src/aws/mod.rs (hunk 3 above)
Comment (StephenWakely) [reply src/aws/mod.rs:105]: It's only really useful for use with the AWS crates. Would this be useful it OPW? I can make it `pub` if so.

**Review by jszwedko — APPROVED** [review]
I'm still a little angsty that we haven't seen the exact same logs the user ran into, but these changes make sense to me and do definitely fix a bug. I'd say we can merge this and then let's build a custom build to ask one of the issue reporters to try to make sure it fixes it for them before we cut a 0.36.1 release.

File: src/aws/mod.rs (hunk 3 above)
Comment (bruceg) [reply src/aws/mod.rs:104]: That was what I was wondering. I don't _know_ we'll need it, so just leave it for now.

**Review by bruceg — APPROVED** [review]

**Comment by jszwedko** [comment]
@StephenWakely I missed this before, but this should have had a changelog entry explaining the fix. I'll add one.

**Comment by rfum** [comment]
@StephenWakely @jszwedko has this pr included in v0.36.1 release?

**Comment by jszwedko** [comment]
> @StephenWakely @jszwedko has this pr included in v0.36.1 release?

Yep!
