### PR TITLE
fix(gelf encoder): gelf encoder timestamp handling

### LINKED ISSUE #15362: Gelf codec encoder send timestamp as integer but graylog expects float
### Vector Version
vector 0.26.0 (x86_64-unknown-linux-musl 5d610b6 2022-11-25)

### Example Data
For example, my test message:
```
{
  "host": "host",
  "short_message": "short message",
  "timestamp": "2022-11-25T13:10:56.962200925Z",
  "version": "1.1"
}
```

### Problem
As part of https://github.com/vectordotdev/vector/issues/4868 , PR https://github.com/vectordotdev/vector/pull/13333 submitted GELF encoding support.

I want to send logs contains timestamp field to graylog using encondig.gelf. 

To send this timestamp in graylog i need to do one of the following:
1.  Configure encoder parameter in socket sink
`encoding.timestamp_format: "unix"`
2. Parse timestamp field with vrl: 
```
  transforms:
    gelf:
      type: remap
      inputs: ["kubernetes_logs"]
      source: |-
        .timestamp = to_unix_timestamp!(.timestamp)
```

In this cases logs sends correctly, but **without milliseconds**:
-   Stdout: ` "timestamp": 1669381856,`
-   Graylog shows this filed:  `timestamp: 2022-11-25T13:10:56.000Z `

**I don't want to lose milliseconds** and i tried vrl parsings:
1. `.timestamp = to_unix_timestamp!(.timestamp, unit: "milliseconds")`
In this case graylog can't recognize and skipping logs.
2. `.timestamp = to_float(to_timestamp!(.timestamp))` - it must be true way, but it fails.
In this case i get vector ERRORs:
`2022-11-28T10:57:11.468111Z ERROR sink{component_kind="sink" component_id=gelf_out component_type=socket component_name=gelf_out}: vector::internal_events::codecs: Failed serializing frame. error=LogEvent contains a value with an invalid type. field = "timestamp" type = "float" expected type = "timestamp or integer" error_type="encoder_failed" stage="sending" internal_log_rate_limit=true `

### What's Happening
Gelf docs: https://docs.graylog.org/docs/gelf
**Quote** gelf docs : _**"timestamp - number with optional decimal places for milliseconds"**_ - I.e float.

Sending to graylog ` "timestamp": 1669381856.123,` - works correctly
And graylog shows this field `timestamp: 2022-11-25T13:10:56.123Z `

But encoder check this field as int:
https://github.com/vectordotdev/vector/blob/d2f2ff3a667f7e027754d156fe4b1e369038fdf5/lib/codecs/src/encoding/format/gelf.rs#L178-L181

I think it's necessary to chage is_integer() to is_float() or just add is_float() 

### Expected Behavior
When i parse timestamp as float encoder.gelf not fails.

### PR DESCRIPTION
**Pull request by scMarkus**
This fixes #15362 

Currently using the socket sink with gelf encoding to sent to Graylog needs to have `sinks.*.encoding.timestamp_format=unix` configured but this drops sub second information from the timestamp field. The expected behavior of the gelf encoder would be to conform to the [gelf protocol](https://archivedocs.graylog.org/en/latest/pages/gelf.html) using floating point unix timestamps to encode millisecond precision as decimals.

Since Rfc3339 timestamps are not accepted bey Graylog the suggested solution is to always coerces the timestamp field to a numeric type making the `timestamp_format` config not needed. 

@neuronull suggestions are welcome

### CODE REVIEW

File: lib/codecs/src/encoding/format/gelf.rs [hunk 1]
```diff
@@ -165,6 +167,19 @@ fn coerce_field_names_and_values(
                     if !(value.is_timestamp() || value.is_integer()) {
                         err_invalid_type(field, "timestamp or integer", value.kind_str())?;
                     }
+
+                    // timestamp to gelf compatible f64 (milliseconds as decimal)
+                    if let Value::Timestamp(ts) = value {
+                        if ts.timestamp_subsec_millis() > 0 {
+                            *value = Value::Float(
+                                NotNan::new(ts.timestamp_millis() as f64 / 1000.0).unwrap(),
```
Comment (neuronull) [inline lib/codecs/src/encoding/format/gelf.rs:175]: Not sure it would save that much but it strikes me that you could get the timestamp in milliseconds once and do the check with arithmetic operations on that without a separate function call.

Non-blocking

File: lib/codecs/src/encoding/format/gelf.rs [hunk 2]
```diff
@@ -165,6 +167,19 @@ fn coerce_field_names_and_values(
                     if !(value.is_timestamp() || value.is_integer()) {
                         err_invalid_type(field, "timestamp or integer", value.kind_str())?;
                     }
+
+                    // timestamp to gelf compatible f64 (milliseconds as decimal)
```
Comment (neuronull) [inline lib/codecs/src/encoding/format/gelf.rs:171]:
```suggestion
                    // convert a `Value::Timestamp` to a GELF specified timestamp where milliseconds are represented by the fractional part of a float.
```

File: lib/codecs/src/encoding/format/gelf.rs [hunk 3]
```diff
@@ -322,6 +338,47 @@ mod tests {
...
+                SHORT_MESSAGE => "Some message",
+                HOST => "example.org",
+                TIMESTAMP => dt,
+            };
+
+            let jsn = do_serialize(true, event_fields).unwrap();
+            assert_eq!(true, jsn.get(TIMESTAMP).unwrap().is_f64());
+            assert_eq!(
+                jsn.get(TIMESTAMP).unwrap().as_f64().unwrap(),
+                dt.timestamp_millis() as f64 / 1000.0
```
Comment (neuronull) [inline lib/codecs/src/encoding/format/gelf.rs:358]: It might be a good idea to use a fixed expected value rather than using the same logic in the test as is used in the source.

File: lib/codecs/src/encoding/format/gelf.rs [hunk 4]
```diff
@@ -322,6 +338,47 @@ mod tests {
...
+                SHORT_MESSAGE => "Some message",
+                HOST => "example.org",
+                TIMESTAMP => dt,
+            };
+
+            let jsn = do_serialize(true, event_fields).unwrap();
+            assert_eq!(true, jsn.get(TIMESTAMP).unwrap().is_i64());
+            assert_eq!(
+                jsn.get(TIMESTAMP).unwrap().as_f64().unwrap(),
+                (dt.timestamp_millis() as f64 / 1000.0)
```
Comment (neuronull) [inline lib/codecs/src/encoding/format/gelf.rs:377]: Seems like we should be getting that as an integer and expecting an integer as well.

**Review by neuronull — CHANGES_REQUESTED** [review]
At a high level this looks good. I have some suggestions though.

File: lib/codecs/src/encoding/format/gelf.rs (hunk 4 above)
Comment (scMarkus) [reply lib/codecs/src/encoding/format/gelf.rs:377]: For this one I would argue that getting as int could potentially be a hard cut off of decimal places (which I have not tested). But I agree that since there is an explicit check if the value is an int beforehand it makes this thinking way overengineered.

File: lib/codecs/src/encoding/format/gelf.rs (hunk 1 above)
Comment (scMarkus) [reply lib/codecs/src/encoding/format/gelf.rs:175]: Sounds absolutely reasonable to me. Thx for pointing that out.

File: lib/codecs/src/encoding/format/gelf.rs (hunk 3 above)
Comment (scMarkus) [reply lib/codecs/src/encoding/format/gelf.rs:358]: Agreed

**Review by neuronull — APPROVED** [review]
The edits look good to me, thanks for making those.

I'll approve and kick off CI

**Comment by neuronull** [comment]
@scMarkus  it looks like there is a clippy lint failing in CI.

It's a good idea to run locally 

`make check-clippy`, `make check`, `make check-fmt` , as these will be run in CI.

further reading: https://github.com/vectordotdev/vector/blob/master/docs/DEVELOPING.md#bring-your-own-toolbox

**Comment by scMarkus** [comment]
@neuronull obviously I ran all the tests but not all the checks. I am very sorry.

Sadly there are still some checks failing. If i read the output correctly it is about `make check-component-docs` which does finish successfully for me locally?

**Comment by scMarkus** [comment]
In that case thanks again for the review an suggestions.  If nothing else is concerning you I am looking forward to a merge and the next release of `vector` :).

**Comment by neuronull** [comment]
All green. Thanks for the contribution @scMarkus !
