### PR TITLE
enhancement(vrl): Support optional user-provided message with abort expression

### LINKED ISSUE #10686: Structured error messages from VRL
With the additional of `reroute_dropped` to the remap transform, users have the ability to do further processing of events that fail or are aborted during normal processing. To make that processing simpler, it would be helpful to have more structured data about the cause of the failure available to downstream components:

- [ ] Ability to pass an optional message to `abort`
- [x] Have the existing user-provided message from `assert` and `assert_eq` be passed as its own field rather than interpolated into a system message (#10914)

### PR DESCRIPTION
**Pull request by wbew**
Closes #10686 

This PR adds the ability to include a user-specified message when using the `abort` expression. The syntax is 
```
abort {some expression resolving to string here}

# example

abort "your message here"
```
The message will appear in diagnostic prints.
- The `remap` transform will attach the abort message (if present) to a dropped event's metadata when relevant

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
I'm fine with this but should get another ✅ from someone with more experience in VRL

**Review by JeanMertz — COMMENTED** [review]
Hey @001wwang we discussed this during check-in yesterday.

Would you be okay by changing this to support any expression that infallibly resolves to a string? That would allow people to dynamically construct the abort message based on the event payload.

I'd be happy to chat and/or screen share to help get this through.

Alternatively, I'm also happy to merge this, and have that work happen in a follow-up PR.

File: lib/vrl/parser/src/ast.rs [hunk 1]
```diff
@@ -1077,6 +1077,31 @@ impl fmt::Debug for Not {
     }
 }
 
+// -----------------------------------------------------------------------------
+// abort
+// -----------------------------------------------------------------------------
+
+#[derive(Clone, PartialEq)]
+pub struct Abort {
+    pub message: Option<String>,
```
[the remark this answers is not in the document]
Comment (001wwang) [reply lib/vrl/parser/src/ast.rs:1086]: Sure thing, happy to try updating that in this PR. I'll give it a shot and let you know if I run into any blockers. Thanks!

File: lib/vrl/compiler/src/expression/abort.rs [hunk 2]
```diff
@@ -1,24 +1,72 @@
...
+                    span,
+                    message: Some(Box::new(expr)),
+                })
+            }
+        } else {
+            Ok(Self {
+                span,
+                message: None,
+            })
+        }
```
Comment (JeanMertz) [inline lib/vrl/compiler/src/expression/abort.rs:47]: nit: this could be a `match` expression.

File: lib/vrl/compiler/src/expression/abort.rs [hunk 3]
```diff
@@ -1,24 +1,72 @@
...
 
 impl Expression for Abort {
-    fn resolve(&self, _: &mut Context) -> Resolved {
-        Err(ExpressionError::Abort { span: self.span })
+    fn resolve(&self, ctx: &mut Context) -> Resolved {
+        let message = if let Some(expr) = &self.message {
+            Some(expr.resolve(ctx)?.try_bytes_utf8_lossy()?.to_string())
+        } else {
+            None
+        };
```
Comment (JeanMertz) [inline lib/vrl/compiler/src/expression/abort.rs:64]: nit:

```suggestion
        let message = self
            .message
            .map(|expr| Ok(expr.resolve(ctx)?.try_bytes_utf8_lossy()?.to_string())
            .transpose()?;
```

File: lib/vrl/compiler/src/expression/abort.rs [hunk 4]
```diff
@@ -1,24 +1,72 @@
...
+            if type_def.is_fallible() {
+                Err(Error {
+                    variant: ErrorVariant::FallibleExpr,
+                    expr_span,
+                })
+            } else if !type_def.is_bytes() {
+                Err(Error {
+                    variant: ErrorVariant::NonString(type_def.kind()),
+                    expr_span,
+                })
```
Comment (JeanMertz) [inline lib/vrl/compiler/src/expression/abort.rs:35]: We have a `value::Error::Expected` variant that covers this, and unifies the returned error.

File: lib/vrl/compiler/src/expression/abort.rs [hunk 5]
```diff
@@ -1,24 +1,72 @@
...
+                Ok(Self {
+                    span,
+                    message: Some(Box::new(expr)),
+                })
+            }
+        } else {
+            Ok(Self {
+                span,
+                message: None,
+            })
```
Comment (JeanMertz) [inline lib/vrl/compiler/src/expression/abort.rs:46]: nit: instead of duplicating this twice, have the error-variants return early, and move this to the end of the function implementation.

File: lib/vrl/compiler/src/expression/abort.rs [hunk 6]
```diff
@@ -31,3 +79,80 @@ impl fmt::Display for Abort {
...
+    }
+}
+
+impl DiagnosticError for Error {
+    fn code(&self) -> usize {
+        use ErrorVariant::*;
+
+        match self.variant {
+            NonString(_) => 300,
+            FallibleExpr => 630,
```
Comment (JeanMertz) [inline lib/vrl/compiler/src/expression/abort.rs:117]: The first one can be removed if we use `value::Error::Expected`, the second one would have to be documented in our errors page (check our `cue` docs).

File: lib/vrl/parser/src/ast.rs [hunk 7]
```diff
@@ -1077,6 +1077,31 @@ impl fmt::Debug for Not {
...
+    pub message: Option<Box<Node<Expr>>>,
+}
+
+impl fmt::Display for Abort {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        if let Some(message) = self.message.as_ref() {
+            write!(f, "abort: {}", message)
+        } else {
+            write!(f, "abort")
+        }
```
Comment (JeanMertz) [inline lib/vrl/parser/src/ast.rs:1095]: nit:

```suggestion
        f.write_str(self.message.as_ref()
            .map(|m| format!("abort: {}", m))
            .unwrap_or_else(|| "abort".to_owned()))
```

(but I'll concede that I can't say either is "better")

**Review by JeanMertz — APPROVED** [review]
Sweet!

Left a remark about updating the Cue docs, an error message we need to update, and a few (TIOLI) nits, but other than that this LGTM.

File: lib/vrl/compiler/src/expression/abort.rs (hunk 6 above)
Comment (JeanMertz) [reply lib/vrl/compiler/src/expression/abort.rs]: Hmm, yeah I think we should create a new one, given that that one explicitly talks about function arguments, which this is not. It could potentially confuse users into thinking `abort` is a function call, and they can treat it as such, which they can not.

**Review by JeanMertz — CHANGES_REQUESTED** [review]
One more remark, with my apologies for going back-and-forth on this.

File: lib/vrl/tests/tests/diagnostics/abort_with_non_string_message.vrl [hunk 8]
```diff
@@ -0,0 +1,6 @@
+# result:
+#
+# error[E300]: expected "string", got "object"
+#  = see language documentation at https://vrl.dev
```
[the remark this answers is not in the document]
Comment (001wwang) [reply lib/vrl/tests/tests/diagnostics/abort_with_non_string_message.vrl:4]: No worries, sounds good. I'll revert back to the previous behavior. Thanks for considering it more!

File: lib/vrl/compiler/src/expression/abort.rs (hunk 6 above)
Comment (001wwang) [reply lib/vrl/compiler/src/expression/abort.rs]: What is the protocol for creating a new error code? Not sure if I missed a README, but I can't quite tell what the pattern is for a new code. Would I make it `631`?

Comment (001wwang) [reply lib/vrl/compiler/src/expression/abort.rs]: Answered this over chat with Jean -- we'll proceed with `631` as the new error code. In general, error codes will likely be overhauled with a more formal pattern/process in the future.

Comment (001wwang) [reply lib/vrl/compiler/src/expression/abort.rs]: Added in 678d5aa

**Review by JeanMertz — APPROVED** [review]
Sweet 👌
