### PR TITLE
fix(core): Add deny_unknown_fields to TlsEnableableConfig

### LINKED ISSUE #23145: tls.enable is not valid. validator and vector think it's valid without error message.
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hi team,
This should throw an error. However it doesn't. 
```
tls:
  enable: true 
```

The valid one is 
```
tls:
  enabled: true
```

### Configuration

```text

```

### Version

vector 0.45.0 (x86_64-unknown-linux-gnu 063cabb 2025-02-24 14:52:02.810034614)

### Debug Output

```text

```

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by thomasqueirozb**
## Summary

Add deny_unknown_fields to TlsEnableableConfig so vector will not run when unused/invalid args are supplied

## Change Type
- [x] Bug fix
- [ ] New feature
- [ ] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?
- [x] Yes
- [ ] No

## How did you test this PR?

`cargo nextest run`

image

## Does this PR include user facing changes?

- [x] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the "no-changelog" label to this PR.

## Notes
- Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
- Do not hesitate to use `@vectordotdev/vector` to reach out to us regarding this PR.
- The CI checks run only after we manually approve them.
  - We recommend adding a `pre-push` hook, please see [this template](https://github.com/vectordotdev/vector/blob/master/CONTRIBUTING.md#Pre-push).
  - Alternatively, we recommend running the following locally before pushing to the remote branch:
    - `cargo fmt --all`
    - `cargo clippy --workspace --all-targets -- -D warnings`
    - `cargo nextest run --workspace` (alternatively, you can run `cargo test --all`)
    - `./scripts/check_changelog_fragments.sh`
- After a review is requested, please avoid force pushes to help us review incrementally.
  - Feel free to push as many commits as you want. They will be squashed into one before merging.
  - For example, you can run `git merge origin master` and `git push`.
- If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
  run `cargo vdev build licenses` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

## References

Fixes #23145

### CODE REVIEW

File: changelog.d/23187_tls_enableable_config_deny_unknown_fields.fix.md [hunk 1]
```diff
@@ -0,0 +1,3 @@
+Add deny_unknown_fields to TlsEnableableConfig so vector will not run when unused/invalid args are supplied
```
Comment (pront) [inline changelog.d/23187_tls_enableable_config_deny_unknown_fields.fix.md]:
```suggestion
Unknown fields in the `tls` config are now rejected so these fields now need to be removed  for Vector to start successfully.
```

File: changelog.d/23187_tls_enableable_config_deny_unknown_fields.fix.md [hunk 2]
```diff
@@ -0,0 +1,3 @@
+Unknown fields in the `tls` config are now rejected so these fields now need to be removed  for Vector to start successfully.
```
Comment (thomasqueirozb) [inline changelog.d/23187_tls_enableable_config_deny_unknown_fields.fix.md]:
```suggestion
Unknown fields in the `tls` config are now rejected so these fields now need to be removed for Vector to start successfully.
```
