### PR TITLE
fix(file source): Remove known small files based on remove_after_secs

### LINKED ISSUE #22762: File Source Doesn't Delete Empty Files After `remove_after_secs`
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We use Vector to collect log files generated by a third-party program, which sometimes creates empty files. As a result, Vector logs messages like `"Currently ignoring file too small to fingerprint."` However, since no additional content is written to these files, Vector neither processes nor removes them, leaving them behind.  

In `./lib/file-source/src/file_server.rs`, the `get_fingerprint_or_log_error` function handles empty files by recording them in `known_small_file`, but these records are never cleaned up.  

https://github.com/vectordotdev/vector/blob/8bc821f992207e2f6b5372cb7e9fc17aed0de62b/lib/file-source/src/file_server.rs#L179-L184

It would be beneficial to track the read timestamp in `known_small_file` and honor the `remove_after_secs` configuration to clean up outdated files accordingly.

### Configuration

```text

```

### Version

0.41.0

### Debug Output

```text

```

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by linw1995**
Remove known small files based on remove_after_secs.

## Change Type
- [x] Bug fix
- [ ] New feature
- [ ] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?
- [ ] Yes
- [x] No

## How did you test this PR?

This test checks whether Vector properly removes empty log files after the configured `remove_after_secs` timeout.

#### Configuration

```yaml
data_dir: ./data

sources:
  in:
    type: "file"
    include:
      - ./log/**/*.log
    remove_after_secs: 60

sinks:
  out:
    inputs: ["in"]
    type: "console"
    encoding:
      codec: "text"
```

Use the above config to start a Vector instance.

#### Steps

```sh
# Create an empty log file
touch ./log/emptyfile.log

# Create another file that will receive data later
touch ./log/file.log

# Wait 10 seconds
sleep 10s

# Append a single log line to file.log
echo "single line" >> ./log/file.log

# Wait 30 more seconds
sleep 30s

# Append another line
echo "single line" >> ./log/file.log
```

#### Expected Behavior

- `emptyfile.log` should be deleted after 60 seconds since it remains empty.
- `file.log` should **not** be deleted immediately, because it receives data during the interval and becomes fingerprintable.

#### Observed Vector Logs

```text
2025-04-18T16:17:47.016459Z  WARN source{component_kind="source" component_id=in component_type=file}:file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. file=log/emptyfile.log
2025-04-18T16:17:47.016606Z  WARN source{component_kind="source" component_id=in component_type=file}:file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. file=log/file.log
2025-04-18T16:17:57.269562Z  INFO source{component_kind="source" component_id=in component_type=file}:file_server: vector::internal_events::file::source: Found new file to watch. file=log/file.log
single line
single line
2025-04-18T16:18:48.601732Z  INFO source{component_kind="source" component_id=in component_type=file}:file_server: vector::internal_events::file::source: File deleted. file=log/emptyfile.log
2025-04-18T16:19:46.045848Z  INFO source{component_kind="source" component_id=in component_type=file}:file_server: vector::internal_events::file::source: File deleted. file=log/file.log
2025-04-18T16:19:46.045917Z  INFO source{component_kind="source" component_id=in component_type=file}:file_server: vector::internal_events::file::source: Stopped watching file. file=log/file.log reached_eof="true"
```

#### Conclusion

Vector removes empty files as expected. However, files that start empty and receive data *later* are still deleted if they are not updated frequently enough to maintain activity within the `remove_after_secs` window. This behavior may vary depending on how quickly the file becomes fingerprintable.

## Does this PR include user facing changes?

- [X] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the "no-changelog" label to this PR.

## Notes
- Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
- Do not hesitate to use `@vectordotdev/vector` to reach out to us regarding this PR.
- The CI checks run only after we manually approve them. To minimize round-trips see the following local checks:
  - `make check-all` is a good command to run locally. This check is
    defined [here](https://github.com/vectordotdev/vector/blob/1ef01aeeef592c21d32ba4d663e199f0608f615b/Makefile#L450-L454). Some of these
    checks might not be relevant to your PR. For Rust changes, at the very least you should run:
    - `cargo fmt --all`
    - `cargo clippy --workspace --all-targets -- -D warnings`
    - `cargo nextest run --workspace` (alternatively, you can run `cargo test --all`)
- After a review is requested, please avoid force pushes to help us review incrementally.
  - Feel free to push as many commits as you want. They will be squashed into one before merging.
  - For example, you can run `git merge origin master` and `git push`.
- If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
  run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

## References

- Closes: #22762

### CODE REVIEW

File: changelog.d/22786_remove_empty_file_after_secs.fix.md [hunk 1]
```diff
@@ -0,0 +1,3 @@
+Remove known small files based on remove_after_secs.
```
Comment (pront) [inline changelog.d/22786_remove_empty_file_after_secs.fix.md:1]:
```suggestion
Fixed `file` source bug where known small files were not deleted after the specified `remove_after_secs`.
```

File: lib/file-source/src/file_server.rs [hunk 2]
```diff
@@ -230,6 +230,29 @@ where
                 stats.record("discovery", start.elapsed());
             }
 
+            // Cleanup the known_small_files
```
Comment (pront) [inline lib/file-source/src/file_server.rs:233]: How will this behave if the small file is populated with data to the point we can produce a fingerprint?

Comment (linw1995) [reply lib/file-source/src/file_server.rs:233]: Ah good point — totally didn’t think about that case at all.

File: lib/file-source/src/fingerprinter.rs [hunk 3]
```diff
@@ -211,21 +212,30 @@ impl Fingerprinter {
                     self.get_fingerprint_of_file(path, buffer).map(Some)
                 }
             })
-            .map_err(|error| match error.kind() {
-                io::ErrorKind::UnexpectedEof => {
-                    if !known_small_files.contains(path) {
-                        emitter.emit_file_checksum_failed(path);
-                        known_small_files.insert(path.to_path_buf());
+            .inspect(|_| {
```
Comment (pront) [inline lib/file-source/src/fingerprinter.rs:215]: Did you test this? Does the file survive after it gets larger?

Comment (linw1995) [reply lib/file-source/src/fingerprinter.rs:215]: Yes, I did. The file survives once it gets large enough. I’ve also updated the description with the test steps—hopefully that provides enough context for this change. Let me know if you'd like more details, and thanks for reviewing!

**Review by pront — APPROVED** [review]
Thanks @linw1995
