### PR TITLE
fix: Incorrect Log Level Message

### LINKED ISSUE #5084: Incorrect Log Level Message
### Vector Version

```
vector 0.11.0 (gb8f83d7 x86_64-unknown-linux-musl 2020-11-16) running on Docker
```

### Vector Configuration File

```bash
docker run \
  --network host \
  -v /etc/vector/vector.toml:/etc/vector/vector.toml:ro \
  --env LOG=debug \
  --restart always \
  timberio/vector:nightly-alpine
```

### Expected Behavior

Docker logs should indicate correct log level. e.g. debug 

### Actual Behavior

Docker logs indicate debug level as "info"

### Example Data

```
Nov 17 18:18:27.375  INFO vector::app: Log level is enabled. level=**"info"**
```

### Additional Context

https://discord.com/channels/742820443487993987/746070591097798688/778324625439588433

### PR DESCRIPTION
**Pull request by juchiast**
`level` was log-level from CLI options, therefore it did not take into account environment variables configuration.

close #5084

Signed-off-by: Duy Do <juchiast@gmail.com>

### CODE REVIEW

File: src/app.rs [hunk 1]
```diff
@@ -51,26 +51,22 @@ impl Application {
...
+            level => [
+                format!("vector={}", level),
+                format!("codec={}", level),
+                format!("file_source={}", level),
+                "tower_limit=trace".to_owned(),
+                format!("rdkafka={}", level),
+            ]
+            .join(","),
+        });
+
```
Comment (fanatid) [inline src/app.rs:65]: I think I miss something but isn't this code looks the same as it was? What is the difference?

Comment (juchiast) [reply src/app.rs:65]: The difference is `level` and `levels`.

Comment (fanatid) [reply src/app.rs:65]: Thanks. I opened the whole file and found that we log `level` later while applying`levels`. Now it's clear.

**Review by fanatid — APPROVED** [review]
