### PR TITLE
enhancement(loki sink): Partition HTTP requests to loki by stream & re-enable concurrency

### LINKED ISSUE #6041: Partition HTTP requests to loki by stream for improved throughput
Broken off from https://github.com/timberio/vector/pull/5973#issuecomment-757992069

Right now users are limited to only sending one HTTP request at a time to Loki due to the ordering requirements Loki has around streams which result in possible failures when requests are issued in parallel for a given stream. This constrains the throughput vector is able to achieve.

https://github.com/timberio/vector/pull/5973 improves this situation by letting users modify the behavior on failure by, for example, rewriting the timestamps but I think it would be advantageous to modify the `loki` sink to batch partition HTTP requests by stream to increase throughput by allowing multiple HTTP requests for different streams to be issued simultaneously.

### LINKED ISSUE #6932: Allow setting higher concurrency for `loki` sink
Requested by user: https://github.com/timberio/vector/issues/6041#issuecomment-810202085

> @jszwedko As part of #5973, the `request.concurrency` configuration was disabled as a workaround to eliminate out-of-order issues. Although this eliminates out-of-order issues in Loki, it also reduces overall throughput. You made a review comment stating:
> 
> > Instead of hard-coding to 1, maybe we could still let users set it if they really know what they are doing, but output a warning?
> 
> I would preference this to be a warning instead of a hard-coded value. Perhaps this should be included as part of the documentation rather than limiting the performance of vector?
> 
> In addition, [there is progress in Loki](https://github.com/grafana/loki/issues/1544) to provide some leniency around out-of-order log submissions.
> 
> Is there a chance we could get `request.concurrency` re-enabled with a warning and/or documentation for users who may not understand the implications of increasing this value?

We should still do https://github.com/timberio/vector/issues/6041 too, but this would be an easier fix to unblock users that are able to manage the higher concurrency.

### PR DESCRIPTION
**Pull request by ktff**
Closes #6041
Closes #6932

This PR adds partitioning of requests by stream, on top of the already partitioning by tenant. To enable this, inner struct `PartitionBatchSink` is also extended with ability to order requests per partition. This ordering guarantee could maybe be useful as a configurable option on some other sinks.

As a side effect, to test this, concurrency in the sink is also re-enabled.

### CODE REVIEW

File: src/sinks/util/sink.rs [hunk 1]
```diff
@@ -254,9 +260,15 @@ where
...
             lingers: HashMap::new(),
+            in_flight: None,
             closing: false,
         }
     }
+
+    /// Enforces per partition ordering of request.
+    pub fn ordered(&mut self) {
+        self.in_flight = Some(HashMap::new());
+    }
```
Comment (bruceg) [inline src/sinks/util/sink.rs:271]: I'm not particularly excited about having this behavior dynamically turned on at run time. How hard would it be to create a `struct OrderedPartitionBatchSink` as a wrapper around `PartitionBatchSink`, providing the ordering guarantee in  the outer layer?

File: src/sinks/util/sink.rs [hunk 2]
```diff
@@ -325,35 +337,45 @@ where
...
+                    this.lingers.remove(partition);
 
                     let batch_size = batch.num_items();
                     let (batch, finalizers) = batch.finish();
-                    tokio::spawn(self.service.call(batch, batch_size, finalizers));
+                    let future = tokio::spawn(this.service.call(batch, batch_size, finalizers));
+
+                    this.in_flight.as_mut().map(|map| {
+                        map.insert(partition.clone(), future.map(|_| ()).fuse().boxed())
+                    });
```
Comment (bruceg) [inline src/sinks/util/sink.rs:378]: I'm surprised clippy doesn't want you to change this to `if let Some(map) = this.in_flight.as_mut() {…`

File: src/sinks/util/sink.rs [hunk 3]
```diff
@@ -364,6 +386,26 @@ where
...
+                        if !this.partitions.contains_key(partition)
+                            && matches!(req.poll_unpin(cx), Poll::Ready(()))
+                        {
+                            remove.push(partition.clone());
+                        }
+                    }
+
+                    for partition in remove {
+                        in_flight.remove(&partition);
+                    }
```
Comment (bruceg) [inline src/sinks/util/sink.rs:405]: Could this be accomplished with `retain` to avoid the clones, something like:
```suggestion
                    in_flight.retain(|partition, req| {
                        this.partitions.contains_key(partition)
                            || !matches!(req.poll_unpin(cx), Poll::Ready(()))
                    });
```

File: src/sinks/loki.rs [hunk 4]
```diff
@@ -243,6 +240,11 @@ impl HttpSink for LokiSink {
             labels = vec![("agent".to_string(), "vector".to_string())]
         }
 
+        let key = PartitionKey {
+            tenant_id,
+            labels: labels.clone(),
```
[the remark this answers is not in the document]
Comment (ktff) [reply src/sinks/loki.rs:245]: >Is there any way to avoid this clone, 

From what I see, multiple layers would need to be changed to fetch and pass `labels` without cloning it. 

> o cheaply turn the labels into a form

Besides wrapping it in `Arc`, we could just hash them. This partitioning is for performance reason so on hash collision we can send multiple streams in the same request. `LokiBuffer` already has that ability, so just removing simplifications from this PR would be sufficient. This looks like a good way.

File: src/sinks/loki.rs [hunk 5]
```diff
@@ -786,6 +788,33 @@ mod integration_tests {
...
+                log_schema().timestamp_key(),
+                base + Duration::seconds(i as i64),
+            );
+        }
+
+        // So, since all of the events are of the same partition, and if there is concurrency,
+        // then if ordering inside paritions isn't upheld, the big line events will take longer
+        // time to flush than small line events so loki will receive smaller ones before large
+        // ones hence out of order events.
+        test_out_of_order_events(OutOfOrderAction::Drop, batch_size, events.clone(), events).await;
```
[the remark this answers is not in the document]
Comment (ktff) [reply src/sinks/loki.rs:815]: It is. 

>  Is there any way to provoke out of order events without racing

Not really. There are two more ways to provoke them:
* Fail requests and force them to retry. 
   * This isn't quite testing what it needs too since retry logic can correct this.
   * A mock loki server which we can configure to fail requests would be needed.
* Stall the start of the server so that requests pile up. 
   * This is yet again racy.  

What we can do is to increase the number of events to increase the chance of out of order event happening.

File: src/sinks/util/sink.rs (hunk 1 above)
Comment (ktff) [reply src/sinks/util/sink.rs:271]: Nope. It can't be a layer above, nor a layer bellow. We can either separate this layer into separate pieces or raise ordering guarantee to type level like `ServiceLogic` is. `OrderingLogic`

File: src/sinks/util/sink.rs (hunk 2 above)
Comment (ktff) [reply src/sinks/util/sink.rs:378]: It probably gave up.

File: src/sinks/loki.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (bruceg) [reply src/sinks/loki.rs:251]: Right. I was thinking of even just joining them all together into a single string, so it was reduced to one allocation, but a suitable hash would be ideal. However, that is likely better for follow-up work.

**Review by bruceg — APPROVED** [review]

**Comment by jszwedko** [comment]
@ktff It'd be nice to merge this on Monday if we can to get it into the next release. I see it approved but just want to make sure you didn't want to make any other tweaks. Nice work on re-enabling concurrency here; it'll make a lot of people happy.

File: src/sinks/loki.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (ktff) [reply src/sinks/loki.rs:251]: Good idea, a single string will be cloned in no time.

**Comment by wgb1990** [comment]
@ktff Vector I use for aggregator mode, so there may be more streams, which will eventually lead to the backlog of events in the buffer.

**Comment by wgb1990** [comment]
@ktff Hi Partitioning through convection is not suitable for the role of aggregator, because there will be a large number of label combinations in the aggregator, which eventually leads to the slow sending of Loki. In my case, the final events are stacked in the buffer.

**Comment by ktff** [comment]
@wgb1990 by buffer if I assume you mean batch. Events shouldn't be in batch more than `batch.timeout_secs`, where default value is 1 sec. If you are still seeing events being in batch for a longer period of time, open a issue for it since that would be a bug.

> which eventually leads to the slow sending of Loki

If on the other hand you mean that throughput is low because you have a large number of streams but only a few events per stream per second, true, the older solution would be better for that use case. That is doable, so in that case open a feature issue with your use case. I imagine it could be done with a simple enum option or something more dynamic.

**Comment by wgb1990** [comment]
@ktff #8998
