### PR TITLE
fix(config): Make config watcher recursive.

### LINKED ISSUE #20547: --watch-config hot reloading is not working with config namespacing
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Using the automatic-namespacing scenario, and after successfully starting with the command "vector -C /etc/vector -w", if you edit the configuration in the sources, transforms, and sinks directories and find that hot reloading is not working

[https://vector.dev/docs/reference/configuration/#automatic-namespacing](url)

### Configuration

_No response_

### Version

0.38.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by iFurySt**
Close #20547, this problem is that the watcher doesn't watch dir recursively.

This easily changes the watcher to watch dir recursively. While this may not be the best solution, considering that `config::watcher::spawn_thread` is currently only used for watching config. IMHO, it seems intuitive to watch paths recursively.

Please let me know if you have any concerns about potential implications for users to upgrade the version.

### CODE REVIEW

File: src/config/watcher.rs [hunk 1]
```diff
@@ -127,7 +127,11 @@ fn create_watcher(
 #[cfg(unix)]
 fn add_paths(watcher: &mut RecommendedWatcher, config_paths: &[PathBuf]) -> Result<(), Error> {
     for path in config_paths {
-        watcher.watch(path, RecursiveMode::NonRecursive)?;
+        if path.is_dir() {
+            watcher.watch(path, RecursiveMode::Recursive)?;
+        } else {
+            watcher.watch(path, RecursiveMode::NonRecursive)?;
+        }
```
Comment (jszwedko) [inline src/config/watcher.rs:134]:
```suggestion
        watcher.watch(path, RecursiveMode::Recursive)?;
```

Looking at https://docs.rs/notify/latest/notify/trait.Watcher.html#tymethod.watch it looks like the `RecursiveMode` parameter is only used if the path is a directory and ignored if it is a file so I think we can just always set it.

**Review by jszwedko — COMMENTED** [review]
Good catch, thanks @iFurySt !

Could we add:

- A changelog fragment describing the change? See https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md
- A test? You can see one at the bottom of `watcher.rs` to use as an example

**Comment by iFurySt** [comment]
Of course, let me handle it

**Comment by iFurySt** [comment]
image

Xnip2024-08-08_12-14-24

@jszwedko All requested changes were done. The unit tests passed on my machine. Feel free to review it again when you have time.

**Review by jszwedko — APPROVED** [review]
Perfect, thank you for this contribution!

**Comment by jszwedko** [comment]
I think this just needs a `cargo fmt`.

**Comment by iFurySt** [comment]
@jszwedko Sorry for that, I've fixed it. It looks like the `md` checking failed rather than rust files. Unfortunately, the `cargo fmt` (or `make fmt`) can't fix the markdown fmt.

Xnip2024-08-09_10-12-18

**Comment by jszwedko** [comment]
> @jszwedko Sorry for that, I've fixed it. It looks like the `md` checking failed rather than rust files. Unfortunately, the `cargo fmt` (or `make fmt`) can't fix the markdown fmt.
> 
> Xnip2024-08-09_10-12-18

Ah, yes, the markdown lint errors have to be fixed manually. I see you did so. Thank you!
