### PR TITLE
fix(config)!: require encoding for console and file sinks

### LINKED ISSUE #1031: [Help] coercer transform
Hi team, I did [coercer transform guide](https://docs.vector.dev/usage/configuration/transforms/coercer) but result not the same.
I use timberio/vector:latest-debian docker image
(Vector is starting. version="0.4.0-dev" git_version="v0.5.0")
1. vector.toml
```
# TCP request
[sources.in]
  # REQUIRED - General
  type = "tcp" # must be: tcp

  # OPTIONAL - General
  address = "0.0.0.0:9000" # no default
  max_length = 102400 # default, bytes
  shutdown_timeout_secs = 30 # default, seconds

  # OPTIONAL - Context
  host_key = "host" # default

[transforms.coercer_transforms]
  inputs = ["in"]
  type = "coercer"
  
  [transforms.coercer_transforms.types]
    bytes_in = "int"
    bytes_out = "int"
    timestamp = "timestamp|%m/%d/%Y:%H:%M:%S %z"
    status = "int"

[sinks.out]
  inputs = ["coercer_transforms"]
  type = "console"
  encoding = "text"
  healthcheck = true
```
2. Result 
```
{
  "bytes_in": "5667",
  "bytes_out": "20574",
  "host": "5.86.210.12",
  "message": "GET /embrace/supply-chains/dynamic/vertical",
  "status": "201",
  "timestamp": "19/06/2019:17:20:49 -0400",
  "user_id": "zieme4647"
}
```
3. Expected
```
{
  "bytes_in": 5667,
  "bytes_out": 20574,
  "host": "5.86.210.12",
  "message": "GET /embrace/supply-chains/dynamic/vertical",
  "status": 201,
  "timestamp": <19/06/2019:17:20:49 -0400>,
  "user_id": "zieme4647"
}
```
So, how I do the same result in the above guide. Thanks

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #1031 

There were a handful of small-ish issues preventing things from working the way our [coercer guide](https://docs.vector.dev/usage/configuration/transforms/coercer#examples) claims they should:

1. The example timestamp format string didn't match the example data
2. We weren't logging the failure to convert types from (1) at a level that's visible by default
3. We forgot the console and file sinks when fixing #806, so even when (1) and (2) were addressed the console sink wouldn't output the event
4. There were a couple of typos in the config metadata that gave them incorrect docs

This is a breaking change for both the console and file sinks, since the `encoding` field is no longer optional.

## Upgrade guide

1. If you're using the `console` sink add the `encoding` option:

    ```toml
    [sinks.print]
      type = "console"
      encoding = "json" # or text
    ```

2. If you're using the `file` sink add the `encoding` option:

    ```toml
    [sinks.file_out]
      type = "file"
      encoding = "ndjson" # or text
    ```

### CODE REVIEW

File: src/sinks/console.rs [hunk 1]
```diff
@@ -29,7 +29,7 @@ impl Default for Target {
 pub struct ConsoleSinkConfig {
     #[serde(default)]
     pub target: Target,
-    pub encoding: Option<Encoding>,
+    pub encoding: Encoding,
```
Comment (binarylogic) [inline src/sinks/console.rs]: @LucioFranco shouldn't this have been resolved in https://github.com/timberio/vector/pull/894? I assume we just missed this? Making sure this wasn't intentional.

File: src/transforms/coercer.rs [hunk 2]
```diff
@@ -42,10 +42,11 @@ impl Transform for Coercer {
                 match conv.convert(value) {
                     Ok(converted) => log.insert_explicit(field.into(), converted),
                     Err(error) => {
-                        debug!(
+                        warn!(
```
Comment (binarylogic) [inline src/transforms/coercer.rs]: 👍 I believe this transform was merged before we had rate limiting. Unfortunately, https://github.com/timberio/vector/issues/628 didn't cover this transform. I'll do another pass to make sure we're not missing anything new.

**Review by binarylogic — APPROVED** [review]
This all looks great! Thanks for fixing.

**Comment by lukesteensen** [comment]
@binarylogic do you know why the semantic PR check is still pending? I thought I did it right...

**Comment by binarylogic** [comment]
It's the `!`. I opened https://github.com/probot/semantic-pull-requests/issues/73.

File: src/sinks/console.rs (hunk 1 above)
Comment (LucioFranco) [reply src/sinks/console.rs]: I believe I discussed this with you or luke but the reason this sink allows a null encoding is that it makes sense here to auto change how logs are printed since this is a debug sink. Happy to go the other way but for me this one actually made sense to dynamically choose since the downstream service is a human instead of a machine that might expect an encoding.

**Review by LucioFranco — APPROVED** [review]
I added a comment about encoding in console but I'm happy either way.

File: src/sinks/console.rs (hunk 1 above)
Comment (binarylogic) [reply src/sinks/console.rs]: I don't remember having that conversation. Do you have this documented anywhere? It should be in Github or Slack somewhere, correct?

**Comment by binarylogic** [comment]
Anything holding this up from merging? I would merge regardless of the semantic check for now.

File: src/sinks/console.rs (hunk 1 above)
Comment (lukesteensen) [reply src/sinks/console.rs]: I'd have been ok with leaving it, but I only noticed this because the logic was complex enough that we skipped an entire case and weren't outputting anything at all. That convinced me we should simplify.
