### PR TITLE
fix(syslog source): emit received events/bytes metrics for UDP mode

### LINKED ISSUE #15687: Syslog source has no received events metrics when the mode is UDP
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm using Syslog source in UDP mode with internal metrics turned on. It turns out that the received events related metrics of the source like component_received_event_bytes_total and component_received_event_total are missing.

FYI, using Syslog source in TCP mode do have those received events related metrics.

### Configuration

```text
{
  "type": "syslog",
  "address": "0.0.0.0:514",
  "mode": "udp",
  "tls": {
    "enabled": false
  }
}
```

### Version

vector 0.26.0 (x86_64-apple-darwin c6b5bc2 2022-12-05)

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by sghall**
## Summary
- Fixes missing “received” metrics for the syslog source in UDP mode. Closes #15687.
- Aligns UDP behavior with TCP and the Component Spec.

## Motivation
- In UDP mode, the syslog source did not emit:
  - component_received_events_total
  - component_received_event_bytes_total
  - component_received_bytes_total
- This made observability inconsistent and broke component compliance checks.

## Changes
- src/sources/syslog.rs:
  - Emit SocketEventsReceived for UDP with event count and estimated JSON size.
  - Emit SocketBytesReceived for UDP with the datagram byte size.
- Tests:
  - Add test_udp_syslog using the compliance harness to assert:
    - component_received_events_total
    - component_received_event_bytes_total
    - component_received_bytes_total (tagged)
    - component_sent_events_total
    - component_sent_event_bytes_total

## Testing
- Focused:
  - cargo test -p vector test_udp_syslog
  - cargo test -p vector 'sources::syslog::test::'

## Related
- Issue: Syslog source has no received events metrics when the mode is UDP (#15687)
- Thanks for the report and context.

## Change Type
- [X] Bug fix
- [ ] New feature
- [ ] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?
- [ ] Yes
- [X] No

## Does this PR include user facing changes?

- [X] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the `no-changelog` label to this PR.

## Notes
- Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
- Do not hesitate to use `@vectordotdev/vector` to reach out to us regarding this PR.
- Some CI checks run only after we manually approve them.
  - We recommend adding a `pre-push` hook, please see [this template](https://github.com/vectordotdev/vector/blob/master/CONTRIBUTING.md#Pre-push).
  - Alternatively, we recommend running the following locally before pushing to the remote branch:
    - `make fmt`
    - `make check-clippy` (if there are failures it's possible some of them can be fixed with `make clippy-fix`)
    - `make test`
- After a review is requested, please avoid force pushes to help us review incrementally.
  - Feel free to push as many commits as you want. They will be squashed into one before merging.
  - For example, you can run `git merge origin master` and `git push`.
- If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
  run `make build-licenses` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

### CODE REVIEW

File: src/sources/syslog.rs [hunk 1]
```diff
@@ -355,7 +359,17 @@ pub fn udp(
...
-                    Ok(((mut events, _byte_size), received_from)) => {
+                    Ok(((mut events, byte_size), received_from)) => {
+                        emit!(SocketBytesReceived {
+                            mode: SocketMode::Udp,
+                            byte_size,
+                        });
+                        let count = events.len();
+                        emit!(SocketEventsReceived {
+                            mode: SocketMode::Udp,
+                            byte_size: events.estimated_json_encoded_size_of(),
```
Comment (thomasqueirozb) [inline src/sources/syslog.rs:370]: Using `events.estimated_json_encoded_size_of()` is misleading and will over report size. I think `byte_size` should be used here directly.

File: src/sources/syslog.rs [hunk 2]
```diff
@@ -355,7 +359,17 @@ pub fn udp(
             let host_key = host_key.clone();
             async move {
                 match frame {
-                    Ok(((mut events, _byte_size), received_from)) => {
+                    Ok(((mut events, byte_size), received_from)) => {
+                        emit!(SocketBytesReceived {
+                            mode: SocketMode::Udp,
+                            byte_size,
+                        });
```
Comment (thomasqueirozb) [inline src/sources/syslog.rs]:
```suggestion
```

I don't think we want to emit this event. `SocketBytesReceived` is only used in the `statsd` source. `SocketEventsReceived` should be sufficient here

File: src/sources/syslog.rs [hunk 3]
```diff
@@ -355,7 +359,17 @@ pub fn udp(
...
+                        let count = events.len();
+                        emit!(SocketEventsReceived {
```
Comment (thomasqueirozb) [inline src/sources/syslog.rs:368]: Not sure if this is being emitted in the right place. I'll double check what the tcp implementation does later on my second pass on this PR once the other comments are addressed

**Comment by emilychendd** [comment]
I have read the CLA Document and I hereby sign the CLA

File: src/sources/syslog.rs (hunk 1 above)
Comment (pront) [reply src/sources/syslog.rs:370]: Noticed that `estimated_json_encoded_size_of` is what [other SocketEventsReceived emitters use](https://github.com/search?q=repo%3Avectordotdev%2Fvector%20SocketEventsReceived%20%7B&type=code), it's the established pattern. Switching to `byte_size` raises the question, are existing usages incorrect or should we use `estimated_json_encoded_size_of` here too? 

I’m currently on a leave and thus will not dig into this further, perhaps @jszwedko can help verify this 🙏

Comment (thomasqueirozb) [reply src/sources/syslog.rs:370]: Very interesting point. I think this should be changed and existing usages are incorrect. I don't think this should be addressed in this PR though and we should use `events.estimated_json_encoded_size_of()` in here.

File: src/sources/syslog.rs [hunk 4]
```diff
@@ -353,9 +358,17 @@ pub fn udp(
...
+            let bytes_received = bytes_received.clone();
             async move {
                 match frame {
-                    Ok(((mut events, _byte_size), received_from)) => {
+                    Ok(((mut events, byte_size), received_from)) => {
+                        let count = events.len();
+                        bytes_received.emit(ByteSize(byte_size));
+                        emit!(SocketEventsReceived {
+                            mode: SocketMode::Udp,
+                            byte_size: byte_size.into(),
```
Comment (thomasqueirozb) [inline src/sources/syslog.rs]:
```suggestion
                            byte_size: events.estimated_json_encoded_size_of(),
```

Maintains consistency with other usages as per [pront's comment](https://github.com/vectordotdev/vector/pull/24296#discussion_r2579392167)
