### PR TITLE
fix(sinks): Fix broken handling of adaptive_concurrency defaults

### LINKED ISSUE #8167: Defaults not working properly in `adaptive_concurrency` settings
When setting any one the `adaptive_concurrency` settings, the remainder default to zeros (the type default) instead of the normal value (struct default). This is due to the serde attributes being incorrect. In order to actually use these settings, all need to be configured or else adaptive concurrency will not behave correctly.

### PR DESCRIPTION
**Pull request by bruceg**
The serde defaults for `struct AdaptiveConcurrencySettings` were using
the type-level defaults if any of the settings were configured, leading
to broken behavior unless all of them were configured.

Closes #8167 

Signed-off-by: Bruce Guenter <bruce.guenter@datadoghq.com>

### CODE REVIEW

File: src/sinks/util/adaptive_concurrency/mod.rs [hunk 1]
```diff
@@ -21,24 +21,32 @@ pub(self) fn instant_now() -> std::time::Instant {
...
 // values are the best balances found between competing outcomes.
-#[derive(Clone, Copy, Debug, Derivative, Deserialize, Serialize)]
-#[derivative(Default)]
+#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
 pub struct AdaptiveConcurrencySettings {
     // This value maintained high concurrency without holding it too
     // high under adverse conditions.
-    #[serde(default)]
-    #[derivative(Default(value = "0.9"))]
+    #[serde(default = "default_decrease_ratio")]
```
Comment (jszwedko) [inline src/sinks/util/adaptive_concurrency/mod.rs:28]: Ah I see. Could this also be resolved by leaving the `derivative(Default)`s here, removing the field level `serde(default)`s and adding `serde(default)` to the struct? Mostly just for my own edification.

**Review by jszwedko — APPROVED** [review]

File: src/sinks/util/adaptive_concurrency/mod.rs (hunk 1 above)
Comment (bruceg) [reply src/sinks/util/adaptive_concurrency/mod.rs:28]: I don't actually know. I'll play around with it in the playground.

Comment (bruceg) [reply src/sinks/util/adaptive_concurrency/mod.rs:28]: I couldn't get any combination of defaults to produce this effect except for having explicit values in the `serde(default)` clauses.

Comment (jszwedko) [reply src/sinks/util/adaptive_concurrency/mod.rs:28]: Hmm, I was curious because I thought it should work and this _seems_ to work:

```rust
use derivative::Derivative;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Derivative, Deserialize, Serialize)]
#[derivative(Default)]
#[serde(default)]
struct AdaptiveConcurrencySettings {
    // This value maintained high concurrency without holding it too
    // high under adverse conditions.
    #[derivative(Default(value = "0.9"))]
    decrease_ratio: f64,

    // This value achieved the best balance between quick response and
    // stability.
    #[derivative(Default(value = "0.7"))]
    ewma_alpha: f64,

    // This value avoided changing concurrency too aggressively when
    // there is fluctuation in the RTT measurements.
    #[derivative(Default(value = "0.05"))]
    rtt_threshold_ratio: f64,
}

fn main() {
    let settings: AdaptiveConcurrencySettings = serde_json::from_str("{}").unwrap();
    dbg!(&settings);
}
```

I may be missing something though.

Comment (bruceg) [reply src/sinks/util/adaptive_concurrency/mod.rs:28]: Ha, you're right, and that's sooo much better, thanks.

**Review by JeanMertz — APPROVED** [review]
Awesome. Good find.
