### PR TITLE
fix(codecs): use nanosecond-precision timestamps in `influxdb` decoder

### LINKED ISSUE #21041: `influxdb` codec uses wrong timestamp precision
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

It seems that the influxdb decoder uses timestamp in microseconds-precision https://github.com/vectordotdev/vector/blob/7be4be622fb1e4308266d90aa1c244be636ffb8a/lib/codecs/src/decoding/format/influxdb.rs#L138 while the [line protocol documentation](https://docs.influxdata.com/influxdb/v1/write_protocols/line_protocol_tutorial/#timestamp) states that the timestamp should be expressed in nanosecond-precision 

An influxdb message like this: 

```
weather,location=us-midwest temperature=82 1465839830100400200
``` 

Is currently parsed into:
```json
{"name":"weather_temperature","tags":{"location":"us-midwest"},"timestamp":"+48420-08-12T18:35:00.400200Z","kind":"absolute","gauge":{"value":82.0}}
```

Which shows an invalid timestamp, as `1465839830100400200` in nanosecond-precision is  `2016-06-13T17:43:50.100400200Z` and not `+48420-08-12T18:35:00.400200Z`

### Configuration

_No response_

### Version

vector 0.40.0 (x86_64-unknown-linux-gnu)

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jorgehermo9**
Closes #21041

This is technically a breaking change, but I wouldn't classify it as one (note the `.fix` in the changelog and not `.breaking`)

### CODE REVIEW

File: lib/codecs/src/decoding/format/influxdb.rs [hunk 1]
```diff
@@ -168,9 +167,11 @@ mod tests {
     #[test]
     fn deserialize_success() {
         let deser = InfluxdbDeserializer::new(true);
-        let buffer = Bytes::from(
-            "cpu,host=A,region=west usage_system=64i,usage_user=10i 1590488773254420000",
-        );
+        let now = chrono::Utc::now();
```
Comment (jorgehermo9) [inline lib/codecs/src/decoding/format/influxdb.rs:170]: Refactored this a little bit, If you prefer how it was before, I could just change `DateTime::from_timestamp_micros` to `DateTime::from_timestamp_nanos` in this test

Comment (jszwedko) [reply lib/codecs/src/decoding/format/influxdb.rs:170]: I personally prefer the hardcoded input, but it's not a big deal 👍

**Review by jszwedko — APPROVED** [review]
Good catch!
