### PR TITLE
fix(kafka source): Flush commits on rebalance events

### LINKED ISSUE #9587: Kafka backwards offset reset when acknowledgments are enabled.
### Vector Version

```
vector --version
vector 0.17.0 (x86_64-unknown-linux-gnu 3d34cde 2021-10-08)
```

### Vector Configuration File

```yaml
timezone: UTC
api:
  enabled: true
  address: 127.0.0.1:8686
sources:
  kafka_in:
    type: kafka
    acknowledgements: true
    auto_offset_reset: earliest
    commit_interval_ms: 1000
    bootstrap_servers: ${bootstrap_server}
    group_id: offset-reset-vector-test
    topics:
      - ${topic}
    librdkafka_options:
      'enable.auto.commit': 'true'
    tls:
      enabled: true
      ca_file: /etc/vector/kafka/ca.pem
      crt_file: /etc/vector/kafka/crt.pem
      key_file: /etc/vector/kafka/key.pem
  vector-metrics:
    type: internal_metrics
    scrape_interval_secs: 2
transforms:
  parse_json:
    type: remap
    inputs:
      - kafka_in
    source: |-
      . = parse_json!(.message)
sinks:
  prom:
    type: prometheus_exporter
    inputs:
      - vector-metrics
    address: 0.0.0.0:9500
  vector-sink:
    type: vector
    inputs:
      - parse_json
    address: http://vector_sink:9000/
    version: "2"
    batch:
      max_events: 6000
      timeout_secs: 5
    request:
      concurrency: "adaptive"
```

### Debug Output

N/A

### Expected Behavior

Kafka Offset should not reset and spike down when acknowledgments are enabled and when the number of vector kafka consumers in a kafka group scales down or up.

### Actual Behavior

Kafka Offset resets and goes backward, by an unexpected amount. 

### Example Data
Left side of the graph depicts the behavior when acknowledgments are enabled, right side shows it when acknowledgments are disabled. 

kafka_offset_reset
On the screenshot above you can see the consumer group lag, whose delta should in reality be either 0 (no one is consuming) or <0 when there are consumers. Note that various spikes in delta changes that are <0 are when i was adding and removing vector instances to reproduce the issue.

The following screenshot shows the actual current offset and the drop on one of the partitions(blue), yellow partition is there solely to showcase the expected behavior.
kafka_offset_drop

### Additional  Context
We’re running vector in the following setup kafka -> vector-set1 -> vector-set2 -> sink. Where vector-set1 uses same kafka consumer group and dynamically scales up or down in a stateful set in kubernetes. 
We’re seeing weird behavior when the number of vector instances in the set1 group gets changed and `acknowledgments` are on.  It seems like the offset for the topic/partition on those events randomly drops(or to put in another way consumer lag for the topic/partition spikes) and it does so for a value that’s way too high for it to be considered as a part of “stored offset just didn’t get committed for the interval specified”.
I am however unable to reproduce the same behavior when acknowledgments are off.
Leading me to believe that there might be something weird going on, within either the finalizer or the way that messages get passed into it.
https://github.com/vectordotdev/vector/blob/v0.17.0/src/sources/kafka.rs#L158-L160

### References

https://github.com/vectordotdev/vector/pull/7787
https://vector.dev/releases/0.15.0/

### PR DESCRIPTION
**Pull request by bruceg**
If a Kafka cluster rebalances, this consumer could end up pulling data
from a different partition, in which case commits caused by
acknowledgements will acknowledging the wrong offsets. To handle this,
simply flush (drop) all the outstanding finalizers and start over.

This should fix #9587 and #10398

This currently has no integration tests. I am still thinking about how to exercise the new code paths, but wanted to get this out to ensure the basic approach is sane.

### CODE REVIEW

**Comment by blt** [comment]
I buy the basic approach here, FYI.

File: src/sources/kafka.rs [hunk 1]
```diff
@@ -346,14 +357,34 @@ fn create_consumer(
...
+    }
+}
+
+impl ConsumerContext for CustomContext {
+    fn post_rebalance(&self, _rebalance: &Rebalance) {
+        if let Some(finalizer) = self.finalizer.get() {
+            finalizer.flush();
+        }
+    }
+}
```
Comment (jszwedko) [inline src/sources/kafka.rs:386]: 👍 this _should_ work but I'm wondering if we could make it slightly more efficient by only dropping the finalizers for partitions we aren't the consumer of anymore? If that's complicated, I'm ok with this change as-is; it just may result in additional duplication in sinks.

Comment (bruceg) [reply src/sources/kafka.rs:386]: I thought about that, yes. I think it's doable, but could get complicated due to which piece has what data. I also had some doubts if doing that would still leave a hole due to the scenario outlined in https://github.com/vectordotdev/vector/issues/9587#issuecomment-946850281, where we end up getting the same partition again but the offsets aren't valid any more. Of course, then we should receive more than one rebalance event, so we should have dropped the finalizers anyways.

This may also only be relevant in a peculiar set of circumstances, since the next acknowledged batch of data ends up marking everything before it as done. As such, it would only matter during the time until the next piece of data for the partition is sent and acknowledged.

Comment (jszwedko) [reply src/sources/kafka.rs:386]: Yeah, I can see how it would be complicated to track. This is a definite step forward so I'm fine with it as-is.

**Review by jszwedko — COMMENTED** [review]
👍 the general approach here makes sense to me.

**Comment by bruceg** [comment]
@tobz The testing changes I mentioned are in eb9744f. Right now both connect, and both pull down the same 100 events. The resulting offset varies somewhere between 98 and 200 depending on the timing delay I put into the pipeline, despite the messages logged to stderr showing the numbers 0-99. If I use `collect_ready` instead of `collect_n`, no events are pulled out of the pipeline, which makes sense because it's only driving the pipeline with the collect that causes the delays to actually wait. I've tried so many different things I can no longer see a path to actually getting this tested.

**Comment by bruceg** [comment]
I tracked down the rdkafka bug: https://github.com/fede1024/rust-rdkafka/issues/416

File: Cargo.toml [hunk 2]
```diff
@@ -271,7 +271,7 @@ postgres-openssl = { version = "0.5.0", default-features = false, features = ["r
 pulsar = { version = "4.1", default-features = false, features = ["tokio-runtime"], optional = true }
 rand = { version = "0.8.4", default-features = false, features = ["small_rng"] }
 rand_distr = { version = "0.4.2", default-features = false }
-rdkafka = { version = "0.27.0", default-features = false, features = ["tokio", "libz", "ssl", "zstd"], optional = true }
+rdkafka = { git = "https://github.com/fede1024/rust-rdkafka", rev = "7a2355f03c9aee8d4544e89bc4b0b0b6b96826e0", default-features = false, features = ["tokio", "libz", "ssl", "zstd"], optional = true }
```
Comment (tobz) [inline Cargo.toml:274]: This is a commit from upstream that fixes a segfault, if I remember correctly, but hasn't yet been released?

File: src/sources/kafka.rs [hunk 3]
```diff
@@ -352,14 +361,36 @@ fn create_consumer(
...
+
+impl ConsumerContext for CustomContext {
+    fn post_rebalance(&self, rebalance: &Rebalance) {
+        if matches!(rebalance, Rebalance::Revoke(_)) {
+            if let Some(finalizer) = self.finalizer.get() {
+                finalizer.flush();
+            }
+        }
```
Comment (tobz) [inline src/sources/kafka.rs:390]: The one thing I don't remember from when I was poking at the unit test you wrote for this behavior is whether or not all consumers have their partitions revoked and then re-assigned during a rebalance event, or if only the revocations necessary to balance the partitions will occur.

If it's the latter, then we might actually be breaking finalization for messages in partition that we haven't had revoked from us.

**Review by tobz — COMMENTED** [review]
Overall, it looks pretty good... I mostly just have a question of how rebalances are specified/documented on the Kafka side, as it could have big implications for what guarantees we can provide on the Vector side during a rebalance.

File: Cargo.toml (hunk 2 above)
Comment (bruceg) [reply Cargo.toml:274]: Correct

File: src/sources/kafka.rs (hunk 3 above)
Comment (bruceg) [reply src/sources/kafka.rs:390]: It is the latter, based on my experiments in testing. You are correct, we do not minimize which finalizations we drop from the queue. However, given streaming data from Kafka, the next acknowledged new piece of data will correctly re-set the offset. I'm a little nervous to make this effort any more complex given our difficulty testing it ourselves.

Comment (jszwedko) [reply src/sources/kafka.rs:390]: 👍 I think the end result is some event duplication which is better than loss. We should make an issue just to track following up on this though.

Comment (tobz) [reply src/sources/kafka.rs:390]: Totally understand about wanting to limit complexity.

I think I would quibble over the "next acknowledged new piece of data" bit, though.  Here's how I'm thinking about this:

- a consumer is processing two partition, and has two outstanding/in-flight messages, one from each partition
- a rebalance happens, and the consumer loses one partition, but resets all in-flight finalizers
- this is fine for the partition that it actually lost
- the consumer pulls the next message from the partition it still has, and the finalizer runs and updates the offset for that partition
- this happens _before_ the previous message for that partition is finalized: either due to latency or due to the actual message failing to process

Am I wrong or are we not effectively telling Kafka that all the messages we had yet to acknowledge on the partitions we still control are now acknowledged?

File: scripts/setup_integration/kafka_integration_env.sh [hunk 4]
```diff
@@ -26,7 +26,7 @@ start_podman () {
   podman run -d --pod=vector-test-integration-kafka --name vector_zookeeper $ZOOKEEPER
    # pinned to 2.6.0 due to https://github.com/wurstmeister/kafka-docker/issues/669
   podman run -d --pod=vector-test-integration-kafka -e KAFKA_BROKER_ID=1 \
-	 -e KAFKA_ZOOKEEPER_CONNECT=vector_zookeeper:2181 -e KAFKA_LISTENERS=PLAINTEXT://:9091,SSL://:9092,SASL_PLAINTEXT://:9093 \
+	 -e KAFKA_ZOOKEEPER_CONNECT=localhost:2181 -e KAFKA_LISTENERS=PLAINTEXT://:9091,SSL://:9092,SASL_PLAINTEXT://:9093 \
```
Comment (jszwedko) [inline scripts/setup_integration/kafka_integration_env.sh:29]: Did you mean to keep this diff? This will also change with #10817

Comment (bruceg) [reply scripts/setup_integration/kafka_integration_env.sh:29]: Yes, this was required to get podman running the Kafka image. Yes, it will change with #10817, but I think that PR will have other conflicts with this one in the test code as well.

File: src/sources/kafka.rs (hunk 3 above)
Comment (bruceg) [reply src/sources/kafka.rs:390]: I agree with your timeline, but there is one missing step: Vector is killed before that previous message is finalized. *Then* that unfinalized message is lost.

I agree this is worth correcting. However, given that the approach in this PR is an improvement to the current state, has been in review state for over a month, and the corrections to resolve this could be non-trivial, I would prefer to complete this PR as-is and add another issue to fix the above correctness hole.

Comment (tobz) [reply src/sources/kafka.rs:390]: Oh, absolutely.  I mostly just wanted to make sure we were on the same page, or correct my thinking if it was in error, since we're already reviewing this code and might as well get it as solid as we reasonably can. :)

+1 to a follow-up issue.

**Review by tobz — APPROVED** [review]

**Comment by bruceg** [comment]
Ok, so this works for Linux (and macOS apparently), but fails to link on ARM64 and Windows due to openssl symbol issues. This is undoubtedly due to the update to the rdkafka crate, but that's required to fix a crash issues that this would otherwise trigger. Any suggestions for how to resolve this?

**Comment by jszwedko** [comment]
Ah, yeah, seemingly those are the same failures we saw on https://github.com/vectordotdev/vector/pull/10302. I think someone will need to dig in to see what we need to do to upgrade. Do you want to do that? Or we could tap someone else?

**Review by bvujanic — APPROVED** [review]

**Comment by jszwedko** [comment]
Just noting that this is still unfortunately blocked by the rdkafka upgrade 😢 https://github.com/vectordotdev/vector/pull/10302

**Comment by udleinati** [comment]
Hello Guys, I just lost some events on production due to this issue. It means that I'm eager to see it in the next release :)

**Comment by jches** [comment]
Hi everyone! Thanks for addressing this bug -- Is this fix still blocked? I am testing a new vector deployment on a high volume kafka topic. and believe I have hit this a few times during testing; would be happy to help test this if needed!

**Comment by bruceg** [comment]
We have merged support for a relevant version of rdkafka (#10302), but there still appear to be some linking issues on the less common platforms. It probably will need to be re-merged after #14135 lands, so there is a little work to do yet.

**Comment by jszwedko** [comment]
@neuronull the build failures here look a lot like the OpenSSL build failures we resolved before when upgrading rdkafka. Does anything jump out to you?

**Comment by neuronull** [comment]
> @neuronull the build failures here look a lot like the OpenSSL build failures we resolved before when upgrading rdkafka. Does anything jump out to you?

It does look very similar.
I tried to dig up the exact build failures we saw before, but I'm not finding them.
But I can say, it was during the linking stage, and it was the `ENGINE` feature set that the linking failed on.

At the moment not able to think of why this might be coming up again.
Just glancing at the changes here it looks like the rust-rdkafka version is changed. I wonder if that might impact anything :thought_balloon:

**Comment by bruceg** [comment]
This is an old PR that might be fixed by simply merging in current `master` branch. However, the sources for the `kafka` source have diverted significantly since the last merge, so that merge will be non-trivial.

File: Cargo.toml [hunk 5]
```diff
@@ -287,7 +287,7 @@ postgres-openssl = { version = "0.5.0", default-features = false, features = ["r
 pulsar = { version = "4.1.3", default-features = false, features = ["tokio-runtime", "auth-oauth2"], optional = true }
 rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
 rand_distr = { version = "0.4.3", default-features = false }
-rdkafka = { version = "0.28.0", default-features = false, features = ["tokio", "libz", "ssl", "zstd"], optional = true }
+rdkafka = { git = "https://github.com/fede1024/rust-rdkafka", tag = "v0.29.0", default-features = false, features = ["tokio", "libz", "ssl", "zstd"], optional = true }
```
Comment (jszwedko) [inline Cargo.toml:290]: It's odd that they tagged it but didn't release it to crates.io 🤔

File: src/sinks/kafka/request_builder.rs [hunk 6]
```diff
@@ -88,7 +88,10 @@ fn get_headers(event: &Event, headers_key: &Option<String>) -> Option<OwnedHeade
                         let mut owned_headers = OwnedHeaders::new_with_capacity(headers_map.len());
                         for (key, value) in headers_map {
                             if let Value::Bytes(value_bytes) = value {
-                                owned_headers = owned_headers.add(key, value_bytes.as_ref());
+                                owned_headers = owned_headers.insert(Header {
+                                    key,
+                                    value: Some(value_bytes.as_ref()),
+                                });
```
Comment (jszwedko) [inline src/sinks/kafka/request_builder.rs:94]: What is the difference here? Or was it just an API change to the crate?

**Review by jszwedko — APPROVED** [review]
Approach still looks good to me. It's unfortunate that we can't test it. Tagging @tobz for re-review too.

File: Cargo.toml (hunk 5 above)
Comment (jszwedko) [reply Cargo.toml:290]: Left a comment over here asking if that was intentional: https://github.com/fede1024/rust-rdkafka/issues/478#issuecomment-1275425106

**Comment by jches** [comment]
> Approach still looks good to me. It's unfortunate that we can't test it.

I've been watching this one since we saw this bug manifest pretty regularly when we first started testing vector. We've been running a patched version of Vector where we cherry-picked this branch over, and I can at least confirm that we haven't seen the backwards offset reset since applying this patch (although we also took steps to reduce the number of group rebalances that were happening).

The approach seems good, though I agree with one of the discussions above suggesting a follow-up to correct the problem of flushing acknowledgements for partitions that are _not_ revoked during a rebalance.

File: src/sinks/kafka/request_builder.rs (hunk 6 above)
Comment (bruceg) [reply src/sinks/kafka/request_builder.rs:94]: It's an API change in the upstream crate.

**Comment by bruceg** [comment]
Thanks for the note @jches, I'll be sure to add a follow-up issue once this is merged.
