### PR TITLE
fix(kafka source): fix acknowledgement handling during shutdown and rebalance events

### LINKED ISSUE #14761: Kafka source not processing pending acknowledgements at shutdown
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When running a kafka source with acknowledgements enabled on the sink, I've noticed some messages being processed twice when vector is restarted. On shutdown, the acknowledgement stream isn't being drained before the process exits, so any messages that were consumed and acknowledged, but whose ack wasn't processed, get duplicated when vector starts up again.

Running the config below, it's easy to recreate this:

1. Start vector
2. Produce a large number of messages
3. Shortly after producing messages, terminate vector
4. Restart vector

Comparing the `blackhole` sink logs shows more messages processed than were produced.

```bash
# Produce 10,000 messages then kill vector
❯ kcat -b $broker -P -t testTopic1 -K : -l <(for i in $(seq 1 10000); do echo "${i}:{\"value\": ${i}}"; done);  sleep 0.1; pkill vector
```

Logs:

```
2022-10-07T04:34:08.450213Z  INFO vector::sinks::blackhole::sink: Total events collected events=0 raw_bytes_collected=0
2022-10-07T04:34:09.451049Z  INFO vector::sinks::blackhole::sink: Total events collected events=0 raw_bytes_collected=0
2022-10-07T04:34:10.450242Z  INFO vector::sinks::blackhole::sink: Total events collected events=4329 raw_bytes_collected=3604950
2022-10-07T04:34:10.504935Z  INFO vector: Vector has stopped.
2022-10-07T04:34:10.505154Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="devnull, testTopic1" time_remaining="59 seconds left"
2022-10-07T04:34:10.544353Z  INFO vector::sinks::blackhole::sink: Total events collected events=9031 raw_bytes_collected=7521716


❯ KAFKA_ADDRS=10.2.22.139:9092 VECTOR_API_PORT=8687 vector -c kafka2blackhole.toml
2022-10-07T04:34:51.798202Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-10-07T04:34:51.798509Z  INFO vector::app: Loading configs. paths=["kafka2blackhole.toml"]
2022-10-07T04:34:51.806936Z  INFO vector::topology::running: Running healthchecks.
2022-10-07T04:34:51.807383Z  INFO vector: Vector has started. debug="false" version="0.24.1" arch="x86_64" build_id="8935681 2022-09-12"
2022-10-07T04:34:51.807497Z  INFO vector::internal_events::api: API server running. address=0.0.0.0:8687 playground=off
2022-10-07T04:34:51.807707Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-10-07T04:34:51.809614Z  INFO vector::sinks::blackhole::sink: Total events collected events=0 raw_bytes_collected=0
2022-10-07T04:34:52.809293Z  INFO vector::sinks::blackhole::sink: Total events collected events=0 raw_bytes_collected=0
2022-10-07T04:34:53.809251Z  INFO vector::sinks::blackhole::sink: Total events collected events=0 raw_bytes_collected=0
2022-10-07T04:34:54.809671Z  INFO vector::sinks::blackhole::sink: Total events collected events=0 raw_bytes_collected=0
2022-10-07T04:34:55.809451Z  INFO vector::sinks::blackhole::sink: Total events collected events=1007 raw_bytes_collected=838832
2022-10-07T04:34:56.809269Z  INFO vector::sinks::blackhole::sink: Total events collected events=1007 raw_bytes_collected=838832
```

Out of 10,000 messages produced, `9,031 + 1007 = 10,038` were processed.

### Configuration

```text
[sources.testTopic1]
type = "kafka"
bootstrap_servers = "${KAFKA_ADDRS}"
group_id = "group1"
topics = [ "testTopic1" ]
decoding = { codec = "json" }

[sinks.devnull]
type = "blackhole"
inputs      = [ "*" ]
acknowledgements = { enabled = true }
```

### Version

vector 0.24.1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

Maybe related to https://github.com/vectordotdev/vector/issues/11405

### PR DESCRIPTION
**Pull request by jches**
This adds some integration tests and a fix for the kafka source to fully drain acknowledgements during consumer group rebalancing and at shutdown, and should close #14761 

Prior related work: https://github.com/vectordotdev/vector/pull/16928

### Overview 

I discussed this a bit over in https://github.com/vectordotdev/vector/discussions/16827, the implementation here essentially follows that outline:

- Run a separate task to handle acknowledgements (additionally, handle acknowledgements for separate kafka partitions on separate streams, for cleaner handling when rebalancing partition assignments)
- Add coordination between the kafka client task and acknowledgement task, so that at rebalance and shutdown time, we have the best possible chance of processing all pending acknowledgements

Here is a visual representation of what I'm going for:

[](https://mermaid.live/edit#pako:eNp1kluPmzAQhf_KyE9blaDEZJOAVnlaqa-V-tZSrSYwgAXYrG32FuW_d4Ds5qL0BaEZn8_njGcvMpOTSISj5550Ro8KS4ttqgE6tF5lqkPtocaixutiS85hSU8eXX3dw6z-qsMkn223388lCZTW9B1Y2mGDfDc8oHOq1C0xQOnCbCe1Np7AqrLyYIqJlcCPUascd1_5MCCkorPEHpQuT8xUgPPo6Rbp0szJRoZNs-MADnaNyWrwFdd6awdbp0znao72GXgAvZiaTdz96RYBdDKAMAz_BlzXOX28mN5BVqH-NmE-dbMLRm6RM3WsGNKMXgpjJzTl06S9MtrdynXCPJqhBQ2x8YpnRW8ZsXwINI4RHIdgDHjVkun9laXt9nJEoyvW3-XWdP_JczEWJhyfKzNtq_yTKQpH_uj6xhRnx-M_rRmdvipfnb2MCERLtkWV88ruB0oqOEzLz5zwb04F9o1PRaoPfBR7b36960wk3vYUiL7LeROOGy6SAhvHVV5XkezFm0gWq3C5iDfRchGt4pXcxIF4F4mU61Dey9U85m8s4_UhEB_GMGARRvfLjYwiOY9WG7mey5H2e2wOVx7-AUdIJk0)

A few oddities come up around how `rdkafka`, and particularly the rebalance handlers work in async code. The `pre_rebalance` hook is called internally by the kafka client while polling for new messages on the message stream, so that task (and the rebalance process itself) will be blocked until it returns. That callback handler isn't async, so it can't yield or receive on async channels, and must run on a `spawn_blocking` thread. The task handling acknowledgements can be async and can run as a normal `tokio::spawn` task. 

This just has implications for what can be used to coordinate between the two:

- the message task (on which rebalance hooks run) can _send_ messages on a tokio mpsc channel to the acknowledgement task, but must use an `Unbounded` channel since sending on a bounded tokio channel requires an async context. Overlapping rebalance events will not happen, so this unbounded channel should never have more than 1 message on it.
- the message task can receive on a `std::sync::mpsc::sync_channel`. This uses a bound size 0, to act as a rendezvous channel, so the acknowledgement task can signal when acks have drained (or when a timeout is reached).

I also found that to properly test this, the source needed to be able to "consume until the end of the partition(s)" rather than "consume a specified number of messages". This is enabled by the `enable.partition.eof` flag, which I've enabled as an option (gated by `cfg(test)` in a couple places where it's needed outside of the actual test module). 

### Testing locally

When running these tests locally, I've found it is easiest to use an existing kafka topic pre-populated with, say 100k messages (for some reason, the way the tests write messages in to kafka is very slow; I haven't looked into why that is, yet). For the automated runs in CI we may need to tune the number of messages or the timings, since this is essentially testing a race condition, it can be a bit performance-dependent. I've put in assertions to avoid a false "pass" (where the first consumer takes in all the messages before shutdown, for example). I've had no trouble triggering the bug when running the tests against a pre-populated topic.

Here is how I've set this up locally:

```bash
❯ kcat -b $BROKER_ADDR -P -t TestTopic -K : -l <(for i in $(seq 1 100000); do echo "${i}:{\"value\": ${i}}"; done);
```

...then running the tests, targeting that topic through environment variables. This can be a bit finicky with regard to timings, so `KAFKA_SHUTDOWN_DELAY` controls how long to run the first consumer before shutting down (for the drain at shutdown test), and `KAFKA_CONSUMER_DELAY` controls the time between starting new consumers during the rebalancing test.

```bash
❯ KAFKA_SEND_COUNT=0 \
  KAFKA_EXPECT_COUNT=100000 \
  KAFKA_TEST_TOPIC=TestTopic \
  KAFKA_CONSUMER_DELAY=5000 \
  KAFKA_SHUTDOWN_DELAY=5000 \
  KAFKA_HOST=$BROKER_ADDR \
  KAFKA_PORT=9092 \
    cargo test --lib --no-default-features -F sources-kafka -F kafka-integration-tests drains_acknowledgement
```

### Additional testing / notes

- The first pass I made at this used `StreamMap` from the tokio library for combining the partition-specific streams. The StreamMap [docs note potential performance issues](https://docs.rs/tokio-stream/latest/tokio_stream/struct.StreamMap.html#implementation) when used with a large number of streams, and indeed, when testing against a topic with 400 partitions this was significantly slower. So I refactored using forwarding tasks and channels, which need a bit more bookkeeping but scales much better
- There are some test failures around how `assert_source_compliance` works, and I believe it's related to some thread-local variables used to collect data from `emit!` macros. I've not dug deeply into this yet and might need help there

### CODE REVIEW

**Comment by jches** [comment]
Hey @jszwedko! I had left this as a draft intending to look at the failing `assert_source_compliance` tests in more detail before requesting a review. I didn't end up having time this week, but I might jump in to discord next week and ask around if I need more help there.

**Comment by dsmith3197** [comment]
HI @jches, I just wanted to let you know this is on my radar and I'll get you a review soon.

**Comment by jches** [comment]
Thanks for taking the time to look this over @dsmith3197! Yeah, I think your hunch might be right; I will look into the stream per topic-partition design and come back soon with more thoughts and/or an implementation, and everything moved to the top level :) I will leave the restructuring into separate files for a separate PR, just to keep the diff clear here but big +1 to that from me.

**Comment by jches** [comment]
OK, finally had time to get back to this! I was unsure at first whether [split_partition_queue](https://docs.rs/rdkafka/0.33.2/rdkafka/consumer/struct.StreamConsumer.html#method.split_partition_queue) would work for this, since the docs note that there may still be messages received on the main consumer, _but_ if we make sure to split off the partition queues as soon as a partition is assigned, that's not a problem. 

I'm much happier with this version, there are waaay fewer "gotchas" / edge cases in here, and the bookkeeping is a lot simpler thanks to messages and acknowledgements for a partition being handled on the same task, none of the `ForwardedAck` stuff from the initial draft is needed anymore.

**Comment by dsmith3197** [comment]
> OK, finally had time to get back to this! I was unsure at first whether [split_partition_queue](https://docs.rs/rdkafka/0.33.2/rdkafka/consumer/struct.StreamConsumer.html#method.split_partition_queue) would work for this, since the docs note that there may still be messages received on the main consumer, _but_ if we make sure to split off the partition queues as soon as a partition is assigned, that's not a problem.
> 
> I'm much happier with this version, there are waaay fewer "gotchas" / edge cases in here, and the bookkeeping is a lot simpler thanks to messages and acknowledgements for a partition being handled on the same task, none of the `ForwardedAck` stuff from the initial draft is needed anymore.

Great to hear! I'm excited to take a look through this. I should be able to give this a review by next week.

File: src/sources/kafka.rs [hunk 1]
```diff
@@ -374,105 +390,406 @@ impl SourceConfig for KafkaSourceConfig {
...
+    pub fn revoke_partition(&mut self, tp: TopicPartition) {
+        self.expect_drain.insert(tp);
+    }
+
+    pub fn observed_last_ack(&mut self, tp: TopicPartition) {
+        self.observed_drain.insert(tp);
+    }
+
+    pub fn is_drain_complete(&self) -> bool {
+        self.observed_drain == self.expect_drain
```
Comment (dsmith3197) [inline src/sources/kafka.rs:575]: I worry that we can enter a state where we block indefinitely (during rebalance) because `observed_drain` contains elements not in `expect_drain`.  As of now, this might only occur if a consumer tasks ends early due to receiving an EOF signal. However, there *could* be other cases in the future. To make this a more robust check, should we change the logic to check if `expect_drain` is a subset of `observed_drain`? This would also mean that in `clear()`, we would clear `expect_drain` and then remove its elements from `observed_drain`, rather than clearing `observed_drain`. What do you think?

File: src/sources/kafka.rs [hunk 2]
```diff
@@ -374,105 +390,406 @@ impl SourceConfig for KafkaSourceConfig {
...
+
+                // Signal the client task that at least one partition has completed
+                _ = drain_signal.as_ref().map(|sig| _ = sig.send(()) );
+
+                if partition_state.is_drain_complete() {
+                    debug!("All expected partitions have drained.");
+                    partition_state.clear();
+                    // Signal the client task that all partitions that are expected to drain have completed
+                    drain_signal.take();
+                }
```
Comment (dsmith3197) [inline src/sources/kafka.rs:628]: In conjunction with the suggestion for `is_drain_complete`, we should add a check here to verify that there is an active drain in progress.
```suggestion
                if drain_signal.is_some() && partition_state.is_drain_complete() {
                    debug!("All expected partitions have drained.");
                    partition_state.clear();
                    // Signal the client task that all partitions that are expected to drain have completed
                    drain_signal.take();
                }
```

File: src/sources/kafka.rs [hunk 3]
```diff
@@ -374,105 +390,406 @@ impl SourceConfig for KafkaSourceConfig {
...
+            tokio::select! {
+                _ = &mut shutdown => {
+                    consumer.context().shutdown();
+                    break
+                },
+
+                _ = &mut eof => {
+                    consumer.context().shutdown();
+                    break
+                },
```
Comment (dsmith3197) [inline src/sources/kafka.rs:744]: I believe we will only want to select on `_ = &mut eof` if the feature is enabled. Otherwise, the channel sender is dropped after the source is built, which would then trigger a shutdown, right? We can accomplish this with `futures::future::OptionFuture`.

```suggestion
fn drive_kafka_consumer(
    consumer: Arc<StreamConsumer<KafkaSourceContext>>,
    mut shutdown: ShutdownSignal,
    eof: Option<tokio::sync::oneshot::Receiver<()>>,
) {
    Handle::current().block_on(async move {
        let mut eof: OptionFuture<_> = eof.into();
        let mut stream = consumer.stream();
        loop {
            tokio::select! {
                _ = &mut shutdown => {
                    consumer.context().shutdown();
                    break
                },

                Some(_) = &mut eof => {
                    consumer.context().shutdown();
                    break
                },
```

File: src/sources/kafka.rs [hunk 4]
```diff
@@ -374,105 +390,406 @@ impl SourceConfig for KafkaSourceConfig {
...
+
+    let (callback_sender, callback_rx) = mpsc::unbounded_channel();
+    consumer
+        .context()
+        .callbacks
+        .set(callback_sender)
+        .expect("Error setting up consumer callback channel.");
+
+    // EOF signal allowing the coordination task to tell the kafka client task when all partitions have reached EOF
+    let (eof_tx, eof_rx) = tokio::sync::oneshot::channel::<()>();
```
Comment (dsmith3197) [inline src/sources/kafka.rs:417]: In conjunction with the comment for `drive_kafka_consumer`:
```suggestion
    let (eof_tx, eof_rx) = if eof {
        let (tx, rx) = tokio::sync::oneshot::channel::<()>();
        (Some(tx), Some(rx))
    } else {
        (None, None)
    };
```

**Review by dsmith3197 — CHANGES_REQUESTED** [review]
This looks great overall! Thanks for taking the time to re-architect the solution :)

File: src/sources/kafka.rs (hunk 1 above)
Comment (dsmith3197) [reply src/sources/kafka.rs]: I don't have any other cases in mind as of now but I prefer to write defensive code to make things easier down the line 🙂

File: src/sources/kafka.rs [hunk 5]
```diff
@@ -370,105 +388,415 @@ impl SourceConfig for KafkaSourceConfig {
...
+                        if let Some(end) = end_signals.remove(&tp) {
+                            let _ = end.send(());
+                        }
+                        debug!("Revoking partition {}:{}", &tp.0, tp.1);
+                        partition_state.revoke_partition(tp);
+                    }
+
+                    if partition_state.is_drain_complete() {
+                        partition_state.clear();
+                        drop(drain);
```
Comment (jches) [inline src/sources/kafka.rs:676]: I'm still not _quite_ satisfied with how this draining state is tracked via two separate vars (a signal, and a deadline future). It sets up some pitfalls, for example this check is meant to detect when the partition tasks have already exited, and immediately proceed with the rebalance -- but the drain deadline is still set even if this check passes. We could get a spurious warning log when that deadline is reached, in this case. I'd like to package these two bits of state together in a struct or something to avoid pitfalls like this, though.

That said, I think this specific check can actually be removed, since partition task completion is now detected on another branch of this same `select!` (in a previous iteration it was detected on a different task, I believe, so this is a leftover bit of code) -- it may be the case that tasks have ended already when this check runs, but that fact will not have been registered in `partition_state` yet.

File: src/sources/kafka.rs [hunk 6]
```diff
@@ -374,105 +390,406 @@ impl SourceConfig for KafkaSourceConfig {
...
+                        });
+                    }
+
+                    drain_deadline = tokio::spawn(revoke_timeout(max_drain_ms));
+                    if partition_state.is_drain_complete() {
+                        partition_state.clear();
+                        drop(drain);
+                    } else if drain_signal.replace(drain).is_some() {
+                        debug!("Kafka consumer shutting down mid-rebalance.");
+                    }
```
[the remark this answers is not in the document]
Comment (jches) [reply src/sources/kafka.rs:703]: In looking closer at the drain signal handling, in the shutdown-during-rebalance case, there's a chance that a shutdown signal mid-rebalance could cause a rebalance to move ahead while there are actually still pending acknowledgements for the revoked partitions, when a `Some` returned by this `replace()` call is dropped. To deal with this case correctly we'd probably need to hold on to both the rebalance and shutdown drain signals, and just drop them both when all partitions are done.

However..thanks to the fact that the `drive_kafka_consumer` task is handling shutdown signals _and_ the kafka rebalance callbacks, I believe it's actually impossible (at least in the current implementation) to reach this state -- a shutdown signal will always be handled before or after the rebalance handlers are complete, and will not happen while in the "draining revoked partitions" state.

**Comment by jches** [comment]
OK, excuse the additional bit of churn on approach here :D just a bit more cleanup. With thinking through what can happen in each of the different states, I realized it was possible to make all these assumptions explicit in the code.

So I updated the drain signal/deadline and expected/observed drain tracking so that the draining and consuming states, and the transitions between them, are explicit using enums. It looks a lot more "rusty" here now, and it should be clearer what state the consumer is in, where the boundaries are, and where transitions happen. There is no need to track draining partitions, if no draining is expected, for example. Entering the draining state creates the drain deadline future, and the transitions _out_ of the draining state consume the drain deadline, replacing it with a `None` OptionFuture, so there shouldn't be any way to mix that up.  Hopefully it makes sense..let me know what you think or if there are improvements I missed.

The other thing to address is the integration tests added here, which appear to failing because of the checks in place to prevent a false pass (e.g. asserting that more than 0 messages were consumed both before and after a shutdown or rebalance). I've found it easiest to reproduce the original issue using a topic pre-populated with say, 500k messages. Is there a way to run a script before these integration tests, that would set up a topic for this purpose? `kcat` tends to be able to produce that many messages very fast, while the code that produces messages in these integration tests is very slow (I haven't looked into why it's so much slower, yet...)

**Review by dsmith3197 — COMMENTED** [review]
The code looks good to me overall. I think the state machine makes it easier to reason about the code, so thank you for introducing that!

I haven't had a chance to look too closely at the tests yet. I agree that it is important to test this behavior but worry that the tests might be too flakely / non-deterministic to include in CI..  With regards to your question on the producer performance, have you tried tuning the batch size?

cc/ @bruceg for a second review

File: src/sources/kafka.rs [hunk 7]
```diff
@@ -460,10 +490,48 @@ struct KafkaPartitionState {
     /// can complete before we get a rebalance callback, so "observed complete" (based on seeing the end of the stream)
     /// and "expect to complete" (based on seeing a rebalance callback with revoked partition info) are tracked separately.
     observed_drain: HashSet<TopicPartition>,
```
[the remark this answers is not in the document]
Comment (jches) [reply src/sources/kafka.rs:492]: I've been going back and forth on this question tbh. It's a case that can only happen in that "reached end of partition" mode, because that is the only condition where the consumer tasks will exit without also being added to the "expected drain" set. The comment on this field is still technically correct, but really reflects an earlier iteration where the callback handler closed the finalizer stream _before_ sending the rebalance callback, so observing a drained partition prior to populating it in the "expected to drain" set was a regular occurrence.

Since this EOF mode is only used in the tests, I'm a little hesitant to add code for it that would always be enabled. However, the "worst case" scenario is something like:

1. the consumer is in "exit at EOF" mode
2. and one or more partitions finish, while others are still being consumed
3. a rebalance starts and some of the already-done partitions are being revoked

The drain deadline would take effect in this case, since the already-finished tasks can no longer be observed. So, it won't deadlock, but the rebalance will likely take longer than it otherwise would.

There are a couple ways to address this: 

- explicitly track a set of partitions that end during the consuming phase on the `Consuming` struct, and pass that along to the `Draining` struct
- Or, when populating the set of partitions expected to drain, only add the partitions that had an entry in `end_signals`

I'm inclined to take latter approach, since it should solve this case without adding any overhead (although, it shouldn't be too expensive to explicitly tracking these, either -- mostly it would mean allocating another `Set` that is rarely, if ever, used).

[the remark this answers is not in the document]
Comment (jches) [reply src/sources/kafka.rs:492]: OK. there's a case to be made here that `observed_drain` is not needed at all anymore: removing entries from `expect_drain` as tasks complete, and checking if that set is empty, is enough to detect the end of the draining phase now. The guarantees that come with 1) handling callbacks and the partition task completions on the same task, and 2) keeping the ack stream and message reading for a given partition together in the same task, and only exiting after all acks are drained, mean that this should be safe.

In fact...thinking through the case where the deadline kicks in and some tasks get forcibly ended, that is a scenario that _could_ end up adding partitions to `observed_drain` during the consuming phase, and keeping that state could be a problem. An [aborted task _may_ still return `Ok`](https://docs.rs/tokio/latest/tokio/task/struct.AbortHandle.html#method.abort) after being aborted, and if that happens, the following could play out:

1. The state machine is in the consuming phase after aborting the previous drain due to timeout
2. One of the partition consumer tasks is seen to complete, and added to the `observed_drain` set
4. Partitions are assigned, including the one we just observed complete (this may happen before or after 2, so clearing `observed_drain` during assignment doesn't help)
5. Later, another rebalance is initiated and this partition is revoked again. Now the draining phase is at risk of completing before this partition is actually finished the second time

To correctly track "observed drain" through the consuming phase, we would need to introduce something like a generation counter to prevent this being a problem. However, for now I think we can actually remove `observed_drain` safely, provided `expect_drain` is only populated with partitions that are known to still have a running (or complete but not yet observed via `join_next`) task.

[the remark this answers is not in the document]
Comment (dsmith3197) [reply src/sources/kafka.rs]: Very true, I agree with your assessment. Thanks for thinking through that and the detailed explanation!

**Review by dsmith3197 — CHANGES_REQUESTED** [review]
I took a look at the tests and was able to improve the speed of the producer significantly by using `FuturesUnordered`. The tests take ~12 seconds each on my machine. Let's see how it'll work in CI after we commit the changes.

File: src/sources/kafka.rs [hunk 8]
```diff
@@ -943,32 +1538,49 @@ mod integration_test {
...
+                    }));
+                producer.send(record, Timeout::Never).await
+            })
+            .collect::<Vec<_>>();
+
+        for res in writes {
+            if let Err(error) = res.await {
                 panic!("Cannot send event to Kafka: {:?}", error);
             }
         }
```
[the remark this answers is not in the document]
Comment (jches) [reply src/sources/kafka.rs:1570]: Oh awesome! I literally have a `TODO` comment here in my editor to try using `FuturesUnordered`, but hadn't had time to get to it yet. Thanks for this, I'll get it added to the branch tonight

File: src/sources/kafka.rs [hunk 9]
```diff
@@ -1228,20 +1847,20 @@ mod integration_test {
...
-            spawn_kafka(tx, config.clone(), true, LogNamespace::Legacy);
+            spawn_kafka(tx, config.clone(), true, false, LogNamespace::Legacy);
         let events1 = tokio::spawn(collect_n(rx1, NEVENTS));
 
         sleep(Duration::from_secs(1)).await;
 
         let (tx, rx2) = delay_pipeline(2, Duration::from_millis(DELAY), EventStatus::Delivered);
         let (trigger_shutdown2, shutdown_done2) =
-            spawn_kafka(tx, config, true, LogNamespace::Legacy);
+            spawn_kafka(tx, config, true, true, LogNamespace::Legacy);
```
[the remark this answers is not in the document]
Comment (jches) [reply src/sources/kafka.rs:1863]: No, good catch...looks like this test case will consume specific number of events, so this should be false.

**Comment by jches** [comment]
Running the integration tests with 250k messages and 2-second delay works fine on my setup (takes about 30 seconds). I increased the number of partitions to 6, since with 2, one of the 3 consumers in the test sometimes doesn't get any partitions assigned.

**Comment by dsmith3197** [comment]
> Running the integration tests with 250k messages and 2-second delay works fine on my setup (takes about 30 seconds). I increased the number of partitions to 6, since with 2, one of the 3 consumers in the test sometimes doesn't get any partitions assigned.

Integration tests pass! They take around 40 seconds. We could probably reduce the number of messages more. Let's try 125k?

File: src/sources/kafka.rs [hunk 10]
```diff
@@ -370,105 +390,556 @@ impl SourceConfig for KafkaSourceConfig {
...
+        let session_timeout_ms = config.session_timeout_ms;
+        let consumer_state =
+            ConsumerStateInner::<Consuming>::new(config, decoder, out, log_namespace);
+        tokio::spawn(async move {
+            let _enter = span.enter();
+            coordinate_kafka_callbacks(
+                consumer,
+                callback_rx,
+                consumer_state,
+                session_timeout_ms,
```
Comment (dsmith3197) [inline src/sources/kafka.rs:436]: I think the drain deadline needs to be less than `session_timeout_ms`. Otherwise, the Kafka broker will presume the client dead when we hit the deadline, right?

**Comment by jches** [comment]
> Integration tests pass! They take around 40 seconds. We could probably reduce the number of messages more. Let's try 125k?

We can go smaller, however if we set this _too_ small, there's a risk that it wouldn't successfully demonstrate the bug. Looking back at my earlier notes, I was initially testing with around 100k messages, and that reliably demonstrated it, so this should be fine and should shave a handful of seconds off the build time.

File: src/sources/kafka.rs (hunk 10 above)
Comment (jches) [reply src/sources/kafka.rs:436]: Yes, that is true; ideally the drain timeout should be a bit shorter to avoid the client getting excluded from the group. 

Without adding any new configuration fields, something like using some percentage of `session_timeout_ms`, e.g. half rounded to the nearest ms, or using `session_timeout_ms - commit_interval_ms`  (assuming the commit interval is less than the session timeout) might be sensible.

I can also see adding a `drain_timeout_ms` configuration option with either a static default or a default based on the session_timeout_ms value. What do you think?

Comment (dsmith3197) [reply src/sources/kafka.rs:436]: I think it would be best to add a `drain_timeout_ms` configuration option with the default being half of `session_timeout_ms` rounded to the nearest ms. This way we can advise uses to tune that parameter if they are seeing undesirable behavior.

Comment (jches) [reply src/sources/kafka.rs]: Sounds good. I didn't see an obvious way to use the serde macros/default functions to initialize this based on a sibling config field, so I made it an `Option<u64>` and calculate the default when setting up this task if `None`. 

Should this emit a warning (or error?) if the drain timeout is set equal or higher than the session timeout?

Comment (dsmith3197) [reply src/sources/kafka.rs]: Looks good. I think we should validate the compute drain timeout value and return an error in the build function if it is >= the session timeout, as it is an invariant we should enforce.

**Review by dsmith3197 — APPROVED** [review]
Looks good to me 🎉

Can you run `make generate-component-docs` to update the website documentation with the new config option?

**Review by estherk15 — APPROVED** [review]

**Comment by yjagdale** [comment]
@jszwedko - Any timelines for this one?

**Comment by jszwedko** [comment]
@bruceg wants to give this one a review too but we'll get it merged in soon. Certainly by the next release (v0.34.0).

File: src/sources/kafka.rs [hunk 11]
```diff
@@ -370,105 +411,559 @@ impl SourceConfig for KafkaSourceConfig {
...
+        .set(callback_sender)
+        .expect("Error setting up consumer callback channel.");
+
+    // EOF signal allowing the coordination task to tell the kafka client task when all partitions have reached EOF
+    let (eof_tx, eof_rx) = if eof {
+        let (tx, rx) = oneshot::channel::<()>();
+        (Some(tx), Some(rx))
+    } else {
+        (None, None)
+    };
```
Comment (bruceg) [inline src/sources/kafka.rs:443]: FWIW Due to a recent change to the `Option` type, it can now `unzip` tuples:
```suggestion
    let (eof_tx, eof_rx) = eof.then(|| oneshot::channel::<()>()).unzip();
```

File: src/sources/kafka.rs [hunk 12]
```diff
@@ -370,105 +411,559 @@ impl SourceConfig for KafkaSourceConfig {
...
+
+    let coordination_task = {
+        let span = span.clone();
+        let consumer = Arc::clone(&consumer);
+        let drain_timeout_ms = match config.drain_timeout_ms {
+            Some(d) => Duration::from_millis(d),
+            None => config.session_timeout_ms / 2,
+        };
```
Comment (bruceg) [inline src/sources/kafka.rs:451]: Also FWIW We also have `Option::map_or`
```suggestion
        let drain_timeout_ms = config.drain_timeout_ms.map_or(config.session_timeout_ms / 2, Duration::from_millis);
```

File: src/sources/kafka.rs [hunk 13]
```diff
@@ -370,105 +411,559 @@ impl SourceConfig for KafkaSourceConfig {
...
+        })
+    };
+
+    _ = tokio::join!(client_task, coordination_task);
+    consumer.context().commit_consumer_state();
+
+    Ok(())
+}
+
+/// ConsumerStateInner implements a small struct/enum-based state machine.
```
Comment (bruceg) [inline src/sources/kafka.rs:481]: This is very nice!

File: src/sources/kafka.rs [hunk 14]
```diff
@@ -370,105 +411,559 @@ impl SourceConfig for KafkaSourceConfig {
...
-            biased;
-            _ = &mut shutdown => break,
-            entry = ack_stream.next() => if let Some((status, entry)) = entry {
-                if status == BatchStatus::Delivered {
-                    if let Err(error) =
-                        consumer.store_offset(&entry.topic, entry.partition, entry.offset)
-                    {
-                        emit!(KafkaOffsetUpdateError { error });
+impl<C> ConsumerStateInner<C> {
+    pub fn complete(self, _deadline: OptionDeadline) -> (OptionDeadline, ConsumerState) {
```
Comment (bruceg) [inline src/sources/kafka.rs:543]: I'm not clear what the point of this parameter is if it's always thrown away.

Also, a lot of these methods are marked as `pub`, but I don't see them used outside of this module. Was there a problem with not having the `pub` marker?

File: src/sources/kafka.rs [hunk 15]
```diff
@@ -370,105 +411,559 @@ impl SourceConfig for KafkaSourceConfig {
...
+        &self,
+        join_set: &mut JoinSet<(TopicPartition, PartitionConsumerStatus)>,
+        tp: TopicPartition,
+        consumer: Arc<StreamConsumer<KafkaSourceContext>>,
+        p: StreamPartitionQueue<KafkaSourceContext>,
+        acknowledgements: bool,
+        exit_eof: bool,
+    ) -> (oneshot::Sender<()>, tokio::task::AbortHandle) {
+        // TODO there's probably a better way to pass the keys() config around than cloning the entire config object? But they are tied to the lifetime of the config object, so..this avoids lifetime messes for now
+        let conf = self.config.clone();
```
Comment (bruceg) [inline src/sources/kafka.rs:586]: Could you clone just the keys and use a reference to that? Maybe with `self.config.keys().cloned().collect::<Vec<_>>()` if needed?

File: src/sources/kafka.rs [hunk 16]
```diff
@@ -370,105 +411,559 @@ impl SourceConfig for KafkaSourceConfig {
...
+            // task will end when it reaches the end of ack_stream
+            let mut finalizer = Some(finalizer);
+
+            let mut status = PartitionConsumerStatus::NormalExit;
+
+            loop {
+                tokio::select!(
+                    _ = &mut end_signal, if finalizer.is_some() => {
+                        finalizer.take();
+                    },
```
Comment (bruceg) [inline src/sources/kafka.rs:608]: I think this can avoid the `is_some`, since `take` on a `None` is a no-op:
```suggestion
                    _ = &mut end_signal => {
                        finalizer.take();
                    },
```

File: src/sources/kafka.rs [hunk 17]
```diff
@@ -370,105 +411,559 @@ impl SourceConfig for KafkaSourceConfig {
...
+        // so we should still add it to the "expect to drain" set
+        _ = end_signal.send(());
+        self.consumer_state.expect_drain.insert(tp);
+    }
+
+    /// Add the given TopicPartition to the set of known "drained" partitions,
+    /// i.e. the consumer has drained the acknowledgement channel. A signal is
+    /// sent on the signal channel, indicating to the client that offsets may be committed
+    pub fn partition_drained(&mut self, tp: TopicPartition) {
+        _ = self.consumer_state.signal.send(());
```
Comment (bruceg) [inline src/sources/kafka.rs:694]: It might be nice to add a note about why we can safely ignore this return value.

File: src/sources/kafka.rs [hunk 18]
```diff
@@ -370,105 +411,559 @@ impl SourceConfig for KafkaSourceConfig {
...
+                    // PartitionConsumerStatus differentiates between a task that exited after
+                    // being signaled to end, and one that reached the end of its partition and
+                    // was configured to exit. After the last such task ends, we signal the kafka
+                    // driver task to shut down the main consumer too. Note this is only used in tests.
+                    PartitionConsumerStatus::PartitionEOF if exit_eof && partition_consumers.is_empty() => {
+                        debug!("All partitions have exited or reached EOF.");
+                        let _ = eof.take().map(|e| e.send(()));
+                    },
+                    _ => {}
                 }
```
Comment (bruceg) [inline src/sources/kafka.rs:794]: While I like matches, this should probably just be an `if status == PartitionConsumerStatus::PartitionEOF && exit_eof && partition_consumers.is_empty()` (or an `if matches!(status, …)` if it can't be compared directly).

File: src/sources/kafka.rs [hunk 19]
```diff
@@ -370,105 +411,559 @@ impl SourceConfig for KafkaSourceConfig {
...
-                    emit!(KafkaBytesReceived {
-                        byte_size: msg.payload_len(),
-                        protocol: "tcp",
-                        topic: msg.topic(),
-                        partition: msg.partition(),
-                    });
+            Some(callback) = callbacks.recv() => match callback {
+                KafkaCallback::PartitionsAssigned(mut assigned_partitions, done) => match consumer_state {
+                    ConsumerState::Complete(_) => unreachable!("Partition assignment received after completion."),
+                    ConsumerState::Draining(_) => error!("Partition assignment received while draining revoked partitions, invalid assignment?"),
```
Comment (bruceg) [inline src/sources/kafka.rs:799]:
```suggestion
                    ConsumerState::Draining(_) => error!("Partition assignment received while draining revoked partitions, maybe an invalid assignment."),
```

File: src/sources/kafka.rs [hunk 20]
```diff
@@ -370,105 +411,559 @@ impl SourceConfig for KafkaSourceConfig {
...
+                    ConsumerState::Consuming(ref consumer_state) => {
+                        let acks = consumer.context().acknowledgements;
+                        for tp in assigned_partitions.drain(0..) {
+                            let topic = tp.0.as_str();
+                            let partition = tp.1;
+                            // It _should_ be impossible for this expect() to panic, since we receive the topic/partition pair from the rebalance callback
+                            let pq = consumer.split_partition_queue(topic, partition).expect("Failed to get partition queue: invalid topic or partition.");
```
Comment (bruceg) [inline src/sources/kafka.rs:806]: Would it be safer to use `if let Some(pq) = consumer.split_partition_queue(topic, partition) { … }` to avoid the panic, since we don't control that part of the code?

File: src/sources/kafka.rs [hunk 21]
```diff
@@ -720,32 +1219,138 @@ fn create_consumer(config: &KafkaSourceConfig) -> crate::Result<StreamConsumer<C
...
+            tpl.elements()
+                .iter()
+                .map(|tp| (tp.topic().into(), tp.partition()))
+                .collect(),
+            send,
+        ));
+
+        while rendezvous.recv().is_ok() {
+            // no-op: wait for partition assignment handler to complete
+        }
```
Comment (bruceg) [inline src/sources/kafka.rs:1291]: This appears to be a spin loop. Should the function be `async` to allow waiting on `recv` instead?

File: src/sources/kafka.rs [hunk 22]
```diff
@@ -720,32 +1219,138 @@ fn create_consumer(config: &KafkaSourceConfig) -> crate::Result<StreamConsumer<C
...
+            tpl.elements()
+                .iter()
+                .map(|tp| (tp.topic().into(), tp.partition()))
+                .collect(),
+            send,
+        ));
+
+        while rendezvous.recv().is_ok() {
+            self.commit_consumer_state();
+        }
```
Comment (bruceg) [inline src/sources/kafka.rs:1316]: Ditto above

File: src/sources/kafka.rs [hunk 23]
```diff
@@ -720,32 +1219,138 @@ fn create_consumer(config: &KafkaSourceConfig) -> crate::Result<StreamConsumer<C
...
+    ShuttingDown(SyncSender<()>),
+}
+
+struct KafkaSourceContext {
+    acknowledgements: bool,
     stats: kafka::KafkaStatisticsContext,
-    finalizer: OnceLock<Arc<OrderedFinalizer<FinalizerEntry>>>,
+
+    /// A callback channel used to coordinate between the main consumer task and the acknowledgement task
+    callbacks: OnceLock<UnboundedSender<KafkaCallback>>,
```
Comment (bruceg) [inline src/sources/kafka.rs:1243]: I see what's going on with `consumer` that needs a lock, but could this one be set up without the lock?

File: src/sources/kafka.rs [hunk 24]
```diff
@@ -720,32 +1219,138 @@ fn create_consumer(config: &KafkaSourceConfig) -> crate::Result<StreamConsumer<C
...
+
+    /// Emit a PartitionsAssigned callback with the topic-partitions to be consumed,
+    /// and block until confirmation is received that a stream and consumer for
+    /// each topic-partition has been set up. This function blocks until the
+    /// rendezvous channel sender is dropped by the callback handler.
+    fn consume_partitions(&self, tpl: &TopicPartitionList) {
+        let callbacks = self
+            .callbacks
+            .get()
+            .expect("Callbacks handler was not initialized.");
```
Comment (bruceg) [inline src/sources/kafka.rs:1278]: If this is necessary (ref my question above), I recommend wrapping this pattern in an extra method to avoid the duplication.

**Review by bruceg — COMMENTED** [review]
This looks very good. I have some code comments below, mostly minor but I see a couple of issues that I would like at least clarification on.

File: src/sources/kafka.rs (hunk 20 above)
Comment (jches) [reply src/sources/kafka.rs:798]: Yeah, we can emit a warning log in case this ever returns `None`

**Review by jches — COMMENTED** [review]
Thanks for the review and feedback @bruceg! I've merged a few of your suggestions and responded to most of the questions you had. I'll address the remaining suggestions and get those changes committed in the next day or so.

File: src/sources/kafka.rs (hunk 15 above)
Comment (jches) [reply src/sources/kafka.rs:589]: This didn't work, I think because the `Keys` struct here doesn't implement `Iterator` which would give us that `cloned()` method?
The best I've come up with is similar though: if we make the `Keys` struct own its members, instead of containing references, then each of the key paths from the config gets cloned for each consumed partition. That is a bit better than cloning the entire config object for each. I think it is possible to set up the lifetimes in such a way that these clones aren't needed, but I haven't been able to get my head around it so far.

**Comment by jches** [comment]
@bruceg just an fyi, this is ready for another look when you have time (I never know what github's behavior is going to be on the re-request review button, since I've seen it dismiss other reviews in the past)

**Review by bruceg — APPROVED** [review]

**Comment by jszwedko** [comment]
Thanks for this contribution @jches !

**Comment by jches** [comment]
Thanks everyone for the reviews and feedback :tada: 

> @[github-merge-queue](https://github.com/apps/github-merge-queue) github-merge-queue bot removed this pull request from the [merge queue](https://github.com/vectordotdev/vector/queue/master) due to no response for status checks Oct 11, 2023

Is this normal? I didn't see any failed checks..do I need to pull changes from master into my branch to get a clean merge?

**Comment by dsmith3197** [comment]
> Is this normal? I didn't see any failed checks..do I need to pull changes from master into my branch to get a clean merge?

No, that shouldn't of happened. I added it to the merge queue again.

**Comment by jches** [comment]
Removed from the queue again - is it just a "retry until success" kind of thing?  :zany_face: 
This branch is quite a few commits behind master, but shouldn't have any conflicts.

**Comment by jszwedko** [comment]
Apologies @jches ! You are hitting an issue with the Mac CI runners that should be fixed by https://github.com/vectordotdev/vector/pull/18823. Once that goes in, this PR should be able to make it in.

**Comment by jches** [comment]
ah I see, thanks for the update :+1:
