### PR TITLE
enhancement(kafka sink): Better tracing/tests on rdkafka options.

### LINKED ISSUE #5601: Restore default `kafka` sink batch settings
See https://github.com/timberio/vector/pull/5010#issuecomment-748157786

### LINKED ISSUE #5602: Kafka batch configuration error
Reported from a user:

```
buffer.max_bytes = 100000
```

Produces:

```
{"timestamp":"Dec 18 15:21:04.264","level":"ERROR","message":"Configuration error.","error":"Sink \"common-kafka\": creating kafka producer failed: Client config error: No such configuration property: \"batch.size\" batch.size 100000","target":"vector::topology"}
```

Looks like vector translates its own parameter to the librdkafka one but it fails for some reason.

### PR DESCRIPTION
**Pull request by Hoverbear**
Helps users better understand interactions like the one featured in #5601. This is on `debug` level, so users would need verbose mode.

# Why this wasn't a bug

This should have resolved to a bunch of `None`s.

https://github.com/timberio/vector/blob/507caed13f75973a435fe6b27417795c2eaee421/src/sinks/util/batch.rs#L18-L25

If that's the case, these should have never been set:

https://github.com/timberio/vector/blob/507caed13f75973a435fe6b27417795c2eaee421/src/sinks/kafka.rs#L146-L186

Which means that #5010 was not related.

# What we're doing

This adds debug level tracing to whenever Vector sets an rdkafka option in the sink, and tracing messages when healthchecks are started and completed (to monitor config creation and lifecycle).

The `to_rdkafka` function now takes an argument which determines if it adds producer specific arguments to the config.

# Related issues.

#5602 - This will help users see that their options are being set, however #3372 still applies.

### CODE REVIEW

**Review by lukesteensen — APPROVED** [review]

File: src/sinks/kafka.rs [hunk 1]
```diff
@@ -332,7 +363,8 @@ impl Sink<Event> for KafkaSink {
 }
 
 async fn healthcheck(config: KafkaSinkConfig) -> crate::Result<()> {
-    let client = config.to_rdkafka().unwrap();
+    trace!("Healthcheck started.");
```
Comment (binarylogic) [inline src/sinks/kafka.rs:366]: Are these logs common? Is it strange to have them for the `kafka` sink and nothing else?
