### PR TITLE
fix(kubernetes_logs source): Handle all outcomes in reflector's select!

### LINKED ISSUE #12245: Thread 'vector-worker' panicked at 'all branches are disabled and there is no else branch'
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We upgraded to 0.21 on our K8S cluster and I can see this error in vector's agent logs.

```sh
thread 'vector-worker' panicked at 'all branches are disabled and there is no else branch', src/kubernetes/reflector.rs:26:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Configuration

```yaml
data_dir: /vector-data-dir
api:
  enabled: false
  address: '0.0.0.0:8686'
  playground: true
log_schema:
  host_key: host
  message_key: message
  source_type_key: source_type
  timestamp_key: timestamp
sources:
  kubernetes_logs:
    type: kubernetes_logs
  internal_metrics:
    type: internal_metrics
sinks:
  prom_exporter:
    type: prometheus_exporter
    inputs: [internal_metrics]
    address: 0.0.0.0:9090
  loki:
    type: loki
    inputs:
      - kubernetes_remove_label_istio
    endpoint: 'XXXXXXXXXXXXXXXX'
    tls:
      ca_file: /etc/vector/ca.crt
    encoding:
      codec: json
    labels:
      env: XXXXXXXXXXX
      k8s_pod_namespace: '{{ kubernetes.pod_namespace }}'
      k8s_pod_name: '{{ kubernetes.pod_name }}'
      k8s_container_name: '{{ kubernetes.container_name }}'
transforms:
  kubernetes_remove_label_istio:
    type: remove_fields
    inputs:
      - kubernetes_logs
    fields:
      - kubernetes.pod_labels.app
      - kubernetes.pod_labels.istio
```

### Version

0.21

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by spencergilbert**
- fix(kubernetes_logs source): Handle every arm from reflector's select! and include logging
- Update Tiltfile

Closes #12245

### CODE REVIEW

**Comment by spencergilbert** [comment]
👀 just noticed some logging in the k8s path_provider is _super wonky_ on TRACE, I may fix that here as well

File: src/kubernetes/reflector.rs [hunk 1]
```diff
@@ -24,26 +24,53 @@ pub async fn custom_reflector<K, W>(
...
-                store.apply_watcher_event(&event.into_inner())
+            result = delay_queue.next(), if !delay_queue.is_empty() => {
+                match result {
+                    Some(Ok(event)) => {
+                        trace!("Processing Deleted event.");
+                        store.apply_watcher_event(&event.into_inner());
+                    },
+                    Some(Err(error)) => {
+                        warn!(message = "DelayQueue stream got an error.", error = ?error);
+                    },
```
Comment (jszwedko) [inline src/kubernetes/reflector.rs:66]: I'm still really wondering about when this would happen 🤔  I can't figure out why the stream implementation would be yielding `Result`s.

File: src/kubernetes/reflector.rs [hunk 2]
```diff
@@ -24,26 +24,53 @@ pub async fn custom_reflector<K, W>(
...
                 }
             }
-            // When the Deleted event expires from the queue pass it to the store
-            Some(Ok(event)) = delay_queue.next() => {
-                store.apply_watcher_event(&event.into_inner())
+            result = delay_queue.next(), if !delay_queue.is_empty() => {
+                match result {
+                    Some(Ok(event)) => {
+                        trace!("Processing Deleted event.");
```
Comment (jszwedko) [inline src/kubernetes/reflector.rs:61]:
```suggestion
                        trace!(message = "Processing Deleted event.", ?event);
```

Could be useful for debugging. Same for the above trace messages.

File: src/kubernetes/reflector.rs (hunk 1 above)
Comment (spencergilbert) [reply src/kubernetes/reflector.rs:66]: Same! But figure worst case we can log it and keep going 😅

File: src/kubernetes/reflector.rs [hunk 3]
```diff
@@ -24,26 +24,53 @@ pub async fn custom_reflector<K, W>(
...
+                            }
+                        }
+                    },
+                    Some(Err(error)) => {
+                        warn!(message = "Watcher stream got an error.", error = ?error);
+                    },
+                    None => {
+                        info!("Watcher stream has terminated.");
+                        break;
+                    },
```
Comment (jszwedko) [inline src/kubernetes/reflector.rs:55]: Theoretically this should never happen because the watcher stream never yields `None`:

https://docs.rs/kube-runtime/0.71.0/src/kube_runtime/watcher.rs.html#234-237

I'd be ok with doing `unreachable("watcher stream never ends")`.

Otherwise do you know what would happen if this `break` is hit? Does Vector shutdown? Something else?

File: Tiltfile [hunk 4]
```diff
@@ -18,10 +18,9 @@ helm_resource(
     image_deps=['timberio/vector'],
     image_keys=[('image.repository', 'image.tag')],
     flags=[
-        '--devel',
```
Comment (spencergilbert) [inline Tiltfile:21]: We stopped needing the pre-released chart as of 0.9, IIRC

File: src/kubernetes/reflector.rs [hunk 5]
```diff
@@ -24,26 +24,53 @@ pub async fn custom_reflector<K, W>(
...
                 }
             }
-            // When the Deleted event expires from the queue pass it to the store
-            Some(Ok(event)) = delay_queue.next() => {
-                store.apply_watcher_event(&event.into_inner())
+            result = delay_queue.next(), if !delay_queue.is_empty() => {
```
Comment (jszwedko) [inline src/kubernetes/reflector.rs:58]: I would drop this conditional otherwise it makes the `select` arms in-exhaustive which is what led to the bug this is fixing. Instead have the `None` arm below just do nothing.

File: src/sources/kubernetes_logs/k8s_paths_provider.rs [hunk 6]
```diff
@@ -45,7 +45,7 @@ impl PathsProvider for K8sPathsProvider {
             // filter out pods where we haven't fetched the namespace metadata yet
             // they will be picked up on a later run
             .filter(|pod| {
-                trace!(message = "Verifying Namespace metadata for pod.", pod = ?pod);
+                trace!(message = "Verifying Namespace metadata for pod.", pod = ?pod.metadata.name);
```
Comment (spencergilbert) [inline src/sources/kubernetes_logs/k8s_paths_provider.rs:48]: This, and the `trace!` below would print the _entire_ pod resource, which is a rather enormous struct - this just prints `Some("<podname>")`.

**Review by jszwedko — COMMENTED** [review]
Nice! Just a few comments.

File: src/kubernetes/reflector.rs (hunk 5 above)
Comment (spencergilbert) [reply src/kubernetes/reflector.rs:58]: I don't think the arms are non-exhaustive with this precondition, as I still included the `None` outcome that happens if the queue is empty - just logged that we shouldn't have reached that outcome.

However, this was @lukesteensen's suggestion on not just constantly polling the delay queue when it's empty.

File: src/kubernetes/reflector.rs [hunk 7]
```diff
@@ -24,26 +24,53 @@ pub async fn custom_reflector<K, W>(
...
+                            // Clear all delayed events on `Restarted` events
+                            watcher::Event::Restarted(_) => {
+                                trace!("Processing Restarted event.");
+                                delay_queue.clear();
+                                store.apply_watcher_event(&event);
+                            }
+                        }
+                    },
+                    Some(Err(error)) => {
+                        warn!(message = "Watcher stream got an error.", error = ?error);
```
Comment (jszwedko) [inline src/kubernetes/reflector.rs:50]:
```suggestion
                        warn!(message = "Watcher stream got an error. Retrying.", error = ?error);
```

File: src/kubernetes/reflector.rs (hunk 3 above)
Comment (spencergilbert) [reply src/kubernetes/reflector.rs:55]: Vector shouldn't stop, it would stop looping here and stop updating our cache - this was another "correctness" arm, and I can see `unreachable` as acceptable as well. Deferring to y'all here, interested in what you think @lukesteensen.

File: src/kubernetes/reflector.rs (hunk 7 above)
Comment (spencergilbert) [reply src/kubernetes/reflector.rs:50]: I definitely intended to write the message like that, and then I think I went "it's warn, obviously it's fine" 😅

File: src/kubernetes/reflector.rs (hunk 1 above)
Comment (jszwedko) [reply src/kubernetes/reflector.rs:66]: Mmm, I see this is actually fixed in newer versions of `tokio-util`: https://github.com/tokio-rs/tokio/commit/cf38ba627abb0d44ae7e7dc0659ddd51866e9efa

It also looks like @tobz approved it 😂 https://github.com/tokio-rs/tokio/pull/4241

It seems like it previously never returned an `Err`. I'd be ok with making this `unrechable()` too, with a comment.

File: src/kubernetes/reflector.rs (hunk 5 above)
Comment (jszwedko) [reply src/kubernetes/reflector.rs:58]: Yeah, thinking through this more, it should be ok. If the queue is empty, this arm will be disabled, and Tokio will wait on the other arm, i.e. for an event from the watcher.

It does make the below `None` arm unreachable and so, again, I might use `unreachable` there 😄

**Comment by spencergilbert** [comment]
Noting that the trace logging here is incredibly verbose:
image

File: src/kubernetes/reflector.rs (hunk 3 above)
Comment (jszwedko) [reply src/kubernetes/reflector.rs]: Gotcha, yeah, I think since the implementation never actually returns `None` I'd prefer to mark it `unreachable`. If they start returning `None` there then we would need to deal with it by either:

* Stopping Vector
* Restarting the watcher

I think simply ceasing to update the cache will confuse users.

File: src/kubernetes/reflector.rs [hunk 8]
```diff
@@ -16,34 +16,64 @@ pub async fn custom_reflector<K, W>(
...
+                            }
+                        }
+                    },
+                    Some(Err(error)) => {
+                        warn!(message = "Watcher Stream received an error. Retrying.", ?error);
+                    },
+                    // The watcher stream should never yield `None`
+                    // https://docs.rs/kube-runtime/0.71.0/src/kube_runtime/watcher.rs.html#234-237
+                    None => {
+                        unreachable!("a watcher Xtream never ends");
```
Comment (jszwedko) [inline src/kubernetes/reflector.rs:55]:
```suggestion
                        unreachable!("a watcher Stream never ends");
```

**Review by jszwedko — APPROVED** [review]
Looks good! I appreciate the detailed comments about the different states. I think we should wait for @lukesteensen to take a look too.

File: src/kubernetes/reflector.rs (hunk 3 above)
Comment (lukesteensen) [reply src/kubernetes/reflector.rs]: I guess it depends if we consider never returning `None` part of the API contract or just an implementation detail. I could imagine an API where these streams are expected to last as long as the underlying resource and then finish, but I don't know enough about the subject to really say.

**Review by lukesteensen — APPROVED** [review]

File: src/kubernetes/reflector.rs (hunk 3 above)
Comment (jszwedko) [reply src/kubernetes/reflector.rs]: Yeah, [`watch_object`](https://docs.rs/kube-runtime/0.71.0/src/kube_runtime/watcher.rs.html#247-272) behaves that way (returns `None` when the object is deleted). Not returning `None` isn't explicitly mentioned in the function documentation for `watcher`. We could guard against it, but I think that would mean doing one of the options I mentioned above: either shutting down Vector or restarting the watcher.
