### PR TITLE
fix(datadog_logs sink): retry HTTP requests and improve datadog sink error handling consistency

### LINKED ISSUE #12859: The `datadog_logs` does not retry requests due to aborted connections
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

A user reported an issue where they observed the `datadog_logs` sink not retrying requests due to aborted connections:

```
2022-05-24T01:38:11.479014Z ERROR sink{component_kind="sink" component_id=datadog_all component_type=datadog_logs component_name=datadog_all}:request{request_id=11606}:http: vector::internal_events::http_client: HTTP error. error=connection closed before message completed error_type="request_failed" stage="processing"
2022-05-24T01:38:11.479063Z ERROR sink{component_kind="sink" component_id=datadog_all component_type=datadog_logs component_name=datadog_all}:request{request_id=11606}: vector::sinks::util::retries: Non-retriable error; dropping the request. error=Failed to make HTTP(S) request: Failed to make HTTP(S) request: connection closed before message completed
```

Here we can see the error is marked as non-retriable, but we _should_ be retrying requests that are closed abruptly.

We should double check the other Datadog sinks here as well for this issue.

We have https://github.com/vectordotdev/vector/issues/12850 which is for `datadog_metrics`, but it is considered retriable there.

### Configuration

_No response_

### Version

vector 0.20.1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

* https://github.com/vectordotdev/vector/issues/10870

### PR DESCRIPTION
**Pull request by neuronull**
Closes #12859

- Some `HttpError`s for datadog_logs sink are now retry-able.
- Added a unit test to validate the retry behavior.
- Conformed datadog_metrics sink to have the same error reporting approach as datadog_logs sink.

**Note**: Now that the two sinks have similar error reporting behavior, there is a little bit more repeated code. I stopped from more refactoring to pull out common code into the `sinks/datadog/mod.rs` as I wasn't sure how far we wanted to take it... For example the RetryLogic implementations are almost the same. And the Service's `call()` function have some commonalities. I'm generally a fan of reducing as much redundant code as possible but I realize it may not be desirable in all scenarios.

### CODE REVIEW

File: src/sinks/datadog/logs/service.rs [hunk 1]
```diff
@@ -23,27 +22,27 @@ use vector_core::{
...
+            ApiError::BadRequest | ApiError::PayloadTooLarge => false,
             // This retry logic will be expanded further, but specifically retrying unauthorized
-            // requests for now. I verified using `curl` that `403` is the respose code for this.
+            // requests and lower level HttpErrorsfor now.
+            // I verified using `curl` that `403` is the respose code for this.
             //
             // https://github.com/vectordotdev/vector/issues/10870
             // https://github.com/vectordotdev/vector/issues/12220
-            LogApiError::ServerError | LogApiError::Forbidden => true,
+            ApiError::HttpError { .. } | ApiError::ServerError | ApiError::Forbidden => true,
```
Comment (fuchsnj) [inline src/sinks/datadog/logs/service.rs:45]: I don't think we would want _all_ `ApiError::HttpError` cases to be retried. For example, `HttpError::BuildRequest` is a permanent error that will never work.

**Comment by binarylogic** [comment]
Agree with sharing code. I'm also curious about this behavior across other HTTP-based sinks? We should be retrying these errors for all sinks.

File: src/sinks/datadog/logs/service.rs (hunk 1 above)
Comment (neuronull) [reply src/sinks/datadog/logs/service.rs:45]: I believe the type of error reported in the issue is `HttpError::CallRequest` (The error text seems to come from the hyper crate).
Last Friday I had concerns that all HttpError retries would be too broad :)  I had discussion  with @jszwedko  about it , he mentioned retrying any `HttpError` would be good but, perhaps he had not seen all the variants of `HttpError` ...
@fuchsnj  , would you recommend retrying any type of error here besides `HttpError::CallRequest` ?

**Comment by jszwedko** [comment]
> Agree with sharing code. I'm also curious about this behavior across other HTTP-based sinks? We should be retrying these errors for all sinks.

Agreed. We could take a similar tact as we have for the AWS components where they all have custom retry behavior but then fallback to shared retry logic: https://github.com/vectordotdev/vector/blob/f6f38d08bd75ded69109a009ddc023e74525eb7b/src/aws/mod.rs#L36-L73

**Comment by neuronull** [comment]
> I'm also curious about this behavior across other HTTP-based sinks? We should be retrying these errors for all sinks.

It looks like a lot of them (splunk_hec_metrics , splunk_hec_logs, clickhouse, influxdb, sematext, prometheus) use the generic `HttpRetryLogic` , which retries everything...

Some others which don't use HttpRetryLogic:

- elasticsearch: retries everything
- loki: retries all http::HttpError
- gcs_common retries everything , in fact it has a comment to merge with HttpRetryLogic
- azure blob retries only server errors or too many request errors

That's not an exhaustive analysis but, it seems that many of the sinks retry all HttpErrors , rather than being selective, as was suggested in the comments here in this PR ...

Perhaps `HttpRetryLogic` should not be retrying everything (instead adopting something like what is in this PR) and should all the http based sinks be using the `HttpRetryLogic` (at least for `http::HttpError`s ?

File: src/sinks/datadog/logs/service.rs (hunk 1 above)
Comment (neuronull) [reply src/sinks/datadog/logs/service.rs]: Addressed in latest commit.

**Comment by neuronull** [comment]
> > I'm also curious about this behavior across other HTTP-based sinks? We should be retrying these errors for all sinks.

> That's not an exhaustive analysis but, it seems that many of the sinks retry all HttpErrors , rather than being selective, as was suggested in the comments here in this PR ...
> 
> Perhaps `HttpRetryLogic` should not be retrying everything (instead adopting something like what is in this PR) and should all the http based sinks be using the `HttpRetryLogic` (at least for `http::HttpError`s) ?

Sounds like outside the scope of this issue. Jesse has referenced this in #10870 .

File: src/sinks/datadog/metrics/service.rs [hunk 2]
```diff
@@ -189,21 +189,45 @@ impl Service<DatadogMetricsRequest> for DatadogMetricsService {
...
+                            status_code: parts.status,
+                            body,
+                            batch_size,
+                            byte_size,
+                            raw_byte_size,
+                            protocol,
+                        })
+                    }
+                    StatusCode::PAYLOAD_TOO_LARGE => Err(DatadogApiError::PayloadTooLarge),
+                    _ => Err(DatadogApiError::ServerError),
```
Comment (tobz) [inline src/sinks/datadog/metrics/service.rs:227]: This should probably boil down to a method on `DatadogApiError` called `from_status` or something, that returns an `Option<DatadogApiError>` so that you can do something like:

```rust
match DatadogApiError::from_status(response.status()) {
    Some(err) => Err(err),
    None => {
        let (parts, body) = response.into_parts();
        ...
    },
}
```

Otherwise we're using a common error type that could theoretically map different status codes to different error variants, which doesn't feel like it fits the goal of a common error type.

Comment (tobz) [reply src/sinks/datadog/metrics/service.rs:227]: Alternatively, you could write a method called `from_result` that takes an `http::Response` and has a return value of `Result<http::Response, DatadogApiError>` and then you just roll up all the above into that method... basically only returning `Ok(response)` if you got OK/Accepted, and `Err(...)` otherwise.

File: src/sinks/datadog/mod.rs [hunk 3]
```diff
@@ -46,3 +47,47 @@ async fn healthcheck(
...
+        // https://github.com/vectordotdev/vector/issues/10870
+        // https://github.com/vectordotdev/vector/issues/12220
+        DatadogApiError::HttpError {
+            error: HttpError::CallRequest { .. },
+        }
+        | DatadogApiError::HttpError {
+            error: HttpError::BuildTlsConnector { .. },
+        }
+        | DatadogApiError::HttpError {
+            error: HttpError::MakeHttpsConnector { .. },
```
Comment (tobz) [inline src/sinks/datadog/mod.rs:88]: It strikes me that we may want a way to have `HttpError` report whether it is retriable or not, and then we proxy to that.

It also strikes me that we might want this as an inherent method on `DatadogApiError` itself rather than a free function, since doing the above for `HttpError` would start to get confusing from a `use ...::http::is_retriable_error, ...::datadog::is_retriable_error` standpoint.

**Review by tobz — CHANGES_REQUESTED** [review]
Good incremental change/cleanup, just a few comments.

File: src/sinks/datadog/metrics/service.rs (hunk 2 above)
Comment (neuronull) [reply src/sinks/datadog/metrics/service.rs]: Makes sense, went with the second approach.

File: src/sinks/datadog/logs/service.rs [hunk 4]
```diff
@@ -178,36 +154,16 @@ impl Service<LogApiRequest> for LogApiService {
...
-                            protocol,
-                        }),
-                        StatusCode::PAYLOAD_TOO_LARGE => Err(LogApiError::PayloadTooLarge),
-                        _ => Err(LogApiError::ServerError),
-                    }
-                }
-                Err(error) => Err(LogApiError::HttpError { error }),
-            }
+            let result = client.call(http_request).in_current_span().await;
+            DatadogApiError::from_result(result)?;
```
Comment (tobz) [inline src/sinks/datadog/logs/service.rs:158]: Admittedly, this is obviously the most concise way to check if it's an error but also, it's weird because it doesn't end up doing anything with the return of `from_result`... I wish `Result<T, E>` had something equivalent to `and_then` that gave you the full `Result<T, E>`, not just methods for either the `T` or `E`... then this could be composed in a much cleaner way.

Either way, not a blocker.

**Review by tobz — APPROVED** [review]
Looks good to me. Left some non-blocking nits.

**Review by spencergilbert — APPROVED** [review]

**Review by jszwedko — APPROVED** [review]
Looks good! I agree with Toby's comments including that none are blocking.

**Review by bruceg — APPROVED** [review]

File: src/sinks/datadog/logs/service.rs (hunk 4 above)
Comment (neuronull) [reply src/sinks/datadog/logs/service.rs:158]: I'll take Jesse's suggestion below for this , but keep it called "from_result" , because the other usage of the function is not mapping it and the "from" in "from_result" is based on the consistent input, whereas the caller may choose to map it or not.

**Review by jszwedko — APPROVED** [review]
Nice work!
