### PR TITLE
fix(prometheus_exporter sink): distributions should not grow unbounded over time

### LINKED ISSUE #10635: bug(prometheus_exporter sink): distributions are not transformed into aggregated histograms/summaries
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Vector Version

```
vector 0.18.1 (x86_64-unknown-linux-musl c4adb60 2021-11-30)
```

### Vector Configuration File

```toml

data_dir = "/data/vector"


[sources.vector_source]
type = "vector"
address = "0.0.0.0:9000"
version = "2"


[sinks.prometheus_exporter]
  type = "prometheus_exporter"
  inputs = [ "vector_source" ]
  address = "0.0.0.0:9598"
  default_namespace = "nginx"
```

### Debug Output

not done yet, will do.

### Expected Behavior

runs normally for hours and days

### Actual Behavior

the response time of exporter will be greater and greater, from initially <1s to over 10s and finally prometheus cannot scrape it anymore. The memory usage is also increasing , from 200M to over 1000M

### Example Data

will append it later

### Additional Context

this service is run inside a container, dont know if there's any existing issue.

### References

* https://vector.dev/docs/reference/configuration/sinks/prometheus_exporter/#memory-usage

### PR DESCRIPTION
**Pull request by tobz**
An issue was reported in #10635 where a user experienced unbounded memory growth of Vector when using the `prometheus_exporter` sink.  This turned out to be due to the fact that they emit distributions from a `log_to_metric` transform, which lead to all of the distribution samples being stored (and aggregated together) as long as that metric series was live in the sink.

In this PR, we've changed a lot of things, but the core of our change is to utilize the `MetricNormalize` machinery to concisely handle the concerns of converting distributions to aggregated forms (aggregated histograms and sketches, specifically) which solves the memory growth issue.  We've also had to rework some of the code to make it more palatable to use for this PR, because the Prometheus exporter sink has a non-typical model compared to other sinks.

One change in this PR unrelated to the bugfix is that we no longer simply zero out sets when they expire, but we remove them entirely.  Practically speaking, sets were the only metric where "expiration" meant that we zeroed out the metric to allow it to continue to be emitted but with a zero value.  Other metric types were removed entirely, so we would simply stop emitting them.

Practically, it makes sense, but all non-set metrics would appear to stop being reported until a new value came in, where they would then appear to snap back into existence... while sets would authoritatively drop to 0 until they were updated.  While I'm not sure whether removing metrics or zeroing/clearing them is the right choice, I opted to at least make them all exhibit consistent expiration behavior.

Fixes #10635.

Signed-off-by: Toby Lawrence <toby@nuclearfurnace.com>

### CODE REVIEW

**Comment by spencergilbert** [comment]
> Practically, it makes sense, but all non-set metrics would appear to stop being reported until a new value came in, where they would then appear to snap back into existence... while sets would authoritatively drop to 0 until they were updated. While I'm not sure whether removing metrics or zeroing/clearing them is the right choice, I opted to at least make them all exhibit consistent expiration behavior.

This doesn't change the user facing behavior, right?

File: lib/vector-core/src/metrics/ddsketch.rs [hunk 1]
```diff
@@ -644,7 +649,11 @@ impl AgentDDSketch {
             .or(Some(f64::NAN))
     }
 
-    pub fn merge(&mut self, other: AgentDDSketch) {
+    pub fn merge(&mut self, other: &AgentDDSketch) -> bool {
```
Comment (spencergilbert) [inline lib/vector-core/src/metrics/ddsketch.rs:652]: `merge` returning a `bool` feels weird to me, since the function name implies an action - not a "check".

File: src/sinks/prometheus/exporter.rs [hunk 2]
```diff
@@ -160,39 +179,160 @@ impl SinkConfig for PrometheusCompatConfig {
...
+                                samples_to_buckets(samples.iter(), &self.buckets);
+
+                            MetricValue::AggregatedHistogram {
+                                buckets,
+                                count,
+                                sum,
+                            }
+                        }
+                    }
+                    _ => unreachable!(),
```
Comment (spencergilbert) [inline src/sinks/prometheus/exporter.rs:305]: Do we normally leave comments as to why this unreachable?

**Review by spencergilbert — COMMENTED** [review]
Left a few comments/questions - though I don't feel I have enough understanding of the code here to give an approval. Mostly curious if we're introducing any breaking changes for users

File: lib/vector-core/src/metrics/ddsketch.rs (hunk 1 above)
Comment (tobz) [reply lib/vector-core/src/metrics/ddsketch.rs:652]: This is true, and a `Result` would probably better.

File: src/sinks/prometheus/exporter.rs (hunk 2 above)
Comment (tobz) [reply src/sinks/prometheus/exporter.rs:305]: Eh, I guess 50-50?  In this case, we know for a fact the value is `MetricValue::Distribution` because we just immutably pattern matched it above.

**Comment by tobz** [comment]
> This doesn't change the user facing behavior, right?

Answer first: it does in fact change the user-facing behavior of sets.

Prior to this PR, when a set expires (represented by a gauge, the value being the number of unique values in the set) its value would snap to 0 after we cleared it.  Now, it will simply stop being reported.

On a graph, this would look like a data of value N at some arbitrary time, and then when the set gets a value again, an interpolated line would snap between that last value N and whatever the new value is.

This is what happens for everything that isn't a set already, hence my comment about this being a change that at least brings sets in line with the behavior of other expired metric types.

File: lib/vector-core/src/metrics/ddsketch.rs (hunk 1 above)
Comment (tobz) [reply lib/vector-core/src/metrics/ddsketch.rs]: Addressed in 1021d2416.

File: src/sources/statsd/mod.rs [hunk 3]
```diff
@@ -321,131 +311,72 @@ mod test {
...
 
-        // Give some time for the topology to start
-        sleep(Duration::from_millis(100)).await;
+        // Wait like 250ms to give the sink time to start running and become ready to handle
+        // traffic.
+        //
+        // TODO: It'd be neat if we could make `ShutdownSignal` track when it was polled at least once,
+        // and then surface that (via one of the related types, maybe) somehow so we could use it as
+        // a signal for "the sink is ready, it's polled the shutdown future at least once, which
+        // means it's trying to accept connections, etc" and would be far more deterministic than this.
```
Comment (bruceg) [inline src/sources/statsd/mod.rs:336]: This makes a lot of sense. 👍🏻

File: src/sinks/prometheus/exporter.rs [hunk 4]
```diff
@@ -160,39 +179,160 @@ impl SinkConfig for PrometheusCompatConfig {
...
+impl MetricMetadata {
+    pub fn new(should_clear: bool) -> Self {
+        Self {
+            should_clear,
+            last_updated: Instant::now(),
+        }
+    }
+
+    pub fn has_expired(&self, timeout: Duration) -> bool {
+        self.last_updated.elapsed() > timeout
```
Comment (bruceg) [inline src/sinks/prometheus/exporter.rs:202]: I recommend avoiding using `.elapsed` in loop contexts, as it issues a `gettimeofday` (or equivalent) syscall via `Instant::now` on each call. You could pass in `last_flush` when it is called below, and possibly pre-calculate the expiry time instead of storing the last update and subtracting.

File: src/sinks/prometheus/exporter.rs [hunk 5]
```diff
@@ -160,39 +179,160 @@ impl SinkConfig for PrometheusCompatConfig {
...
+// Specifically, though, we do _not_ include the actual metric value.  This type is used
+// specifically to look up the entry in a map for a metric in the sense of "get the metric whose
+// name is X and type is Y and has these tags".
+#[derive(Clone, Debug)]
+struct MetricRef(
+    MetricSeries,
+    MetricKind,
+    Discriminant<MetricValue>,
+    Option<Vec<f64>>,
+);
```
Comment (bruceg) [inline src/sinks/prometheus/exporter.rs:220]: Using a tuple struct with more than one or two elements can get confusing. I recommend naming the fields here.

File: src/sinks/prometheus/exporter.rs [hunk 6]
```diff
@@ -160,39 +179,160 @@ impl SinkConfig for PrometheusCompatConfig {
...
+                let (series, data, metadata) = metric.into_parts();
+                let (ts, kind, value) = data.into_parts();
+
+                let new_value = match value {
+                    MetricValue::Distribution { samples, .. } => {
+                        if self.distributions_as_summaries {
+                            // We use a sketch when in summary mode because they're actually able to be
+                            // merged and provide correct output, unlike the aggregated summaries that
+                            // we handle from _sources_ like Prometheus.  The collector code already
+                            // renders sketches as an aggregated summary to begin with, so we're gucci.
```
Comment (bruceg) [inline src/sinks/prometheus/exporter.rs:285]: "we're gucci"?

File: src/sinks/prometheus/exporter.rs [hunk 7]
```diff
@@ -160,39 +179,160 @@ impl SinkConfig for PrometheusCompatConfig {
...
+                            let (buckets, count, sum) =
+                                samples_to_buckets(samples.iter(), &self.buckets);
+
+                            MetricValue::AggregatedHistogram {
+                                buckets,
+                                count,
+                                sum,
+                            }
+                        }
+                    }
```
Comment (bruceg) [inline src/sinks/prometheus/exporter.rs:304]: This almost looks like it should be a method or pair of methods on `MetricValue`, ie `distribution_to_sketch` and `distribution_to_histogram` possibly with a `distribution_to_something(as_summary: bool)` wrapper.

File: src/sinks/prometheus/exporter.rs [hunk 8]
```diff
@@ -302,175 +434,93 @@ impl PrometheusExporter {
...
+                        *data = normalized;
+                        metadata.last_updated = Instant::now();
+                    }
+                    None => {
+                        // We specifically clear sets when they expire rather than totally delete
+                        // them, and this flag is how we know to do that.
+                        let should_clear = matches!(normalized.value(), MetricValue::Set { .. });
+                        metrics.insert(metric_ref, (normalized, MetricMetadata::new(should_clear)));
+                    }
+                }
```
Comment (bruceg) [inline src/sinks/prometheus/exporter.rs:466]: Can this be simplified with the `entry` interface? ie `metrics.entry(metric_ref).and_modify(…).or_insert_with(…)`

File: src/sinks/prometheus/exporter.rs [hunk 9]
```diff
@@ -302,175 +434,93 @@ impl PrometheusExporter {
...
-                        } else {
-                            warn!(message = "Metric changed type, dropping old value.", series = %entry.series());
+            // If we've exceed our flush interval, go through all of the metrics we're currently
+            // tracking and remove any which have exceeded the the flush interval in terms of not
+            // having been updated within that long of a time.
+            //
+            // TODO: Can we be smarter about this? As is, we might wait up to 2x the flush period to
+            // remove an expired metric depending on how things line up.  It'd be cool to _check_
+            // for expired metrics more often, but we also don't want to check _way_ too often, like
+            // every second, since then we're constantly iterating through every metric, etc etc.
```
Comment (bruceg) [inline src/sinks/prometheus/exporter.rs:476]: Probably can be smarter, the question is if it's worth the added complexity.

File: src/sinks/prometheus/exporter.rs [hunk 10]
```diff
@@ -302,175 +434,93 @@ impl PrometheusExporter {
...
+                    .collect::<Vec<_>>();
+
+                for (metric_ref, metadata) in metrics_to_expire {
+                    if metadata.should_clear {
+                        if let Some((metric, _)) = metrics.get_mut(&metric_ref) {
+                            metric.data_mut().value_mut().zero();
                         }
+                    } else {
+                        metrics.remove(&metric_ref);
                     }
```
Comment (bruceg) [inline src/sinks/prometheus/exporter.rs:497]: Can this be rewritten using the `retain` interface to avoid creating the temporary `metrics_to_expire`?

File: src/sinks/prometheus/exporter.rs (hunk 8 above)
Comment (tobz) [reply src/sinks/prometheus/exporter.rs:466]: I tried that at first, but it involves an extra clone because you have to move the metric into both the `and_modify` closure and the `or_insert_with` closure.

I swore there was a way to avoid this, but I guess it's really only doable for the key via `.entry(..)`.

File: src/sinks/prometheus/exporter.rs (hunk 10 above)
Comment (tobz) [reply src/sinks/prometheus/exporter.rs:497]: We'd still have to iterate over the unretained metrics to see if we needed to zero them out, so I think it's a wash either way.

What we really need is for `HashMap::drain_filter` to be stabilized so we can capture the expired metrics and then be able to use them to do the "should we clear this metric?" logic.

File: src/sinks/prometheus/exporter.rs (hunk 7 above)
Comment (tobz) [reply src/sinks/prometheus/exporter.rs:304]: I definitely agree that they should be methods somewhere other than directly in the exporter, since it's fairly generic code.

I can try throwing them on `MetricValue` and seeing how that looks.

File: src/test_util/metrics.rs [hunk 11]
```diff
@@ -0,0 +1,214 @@
...
+use crate::sinks::util::buffer::metrics::{MetricNormalize, MetricSet};
+
+type SplitMetrics = HashMap<MetricSeries, (MetricData, EventMetadata)>;
+
+#[derive(Default)]
+struct PassthroughNormalizer;
+
+impl MetricNormalize for PassthroughNormalizer {
+    fn apply_state(&mut self, state: &mut MetricSet, metric: Metric) -> Option<Metric> {
+        state.make_absolute(metric)
```
[the remark this answers is not in the document]
Comment (tobz) [reply src/test_util/metrics.rs:19]: You're right.  I removed `PassthroughNormalizer` and move `AbsoluteMetricNormalizer`/`IncrementalMetricNormalizer` up into this file instead.

File: src/sinks/util/buffer/metrics.rs [hunk 12]
```diff
@@ -91,21 +91,36 @@ impl Batch for MetricsBuffer {
...
     }
+}
 
+impl<N> MetricNormalizer<N> {
+    pub fn from_inner(inner: N) -> Self {
+        Self {
+            state: MetricSet::default(),
+            inner,
+        }
+    }
```
[the remark this answers is not in the document]
Comment (tobz) [reply src/sinks/util/buffer/metrics.rs]: You're definitely right, and I've gone and converted this to a `From` implementation.

File: lib/vector-core/src/event/metric.rs [hunk 13]
```diff
@@ -981,7 +1059,36 @@ impl Display for Metric {
             MetricKind::Incremental => '+',
         };
         write!(fmt, "{} {} ", &self.series, kind)?;
-        match &self.data.value {
+        write!(fmt, "{}", &self.data.value)
```
[the remark this answers is not in the document]
Comment (tobz) [reply lib/vector-core/src/event/metric.rs:1062]: I believe you are indeed correct, so I've gone ahead and swapped to that, and also have done the same for `self.series` since it has a dedicated `Display` implementation now.

File: lib/vector-core/src/event/metric.rs [hunk 14]
```diff
@@ -726,6 +779,24 @@ impl MetricData {
...
+            kind,
+            value,
+        }
+    }
+
+    /// Consumes this `MetricData` and returns its individual parts.
+    pub fn into_parts(self) -> (Option<DateTime<Utc>>, MetricKind, MetricValue) {
+        (self.timestamp, self.kind, self.value)
+    }
+
```
[the remark this answers is not in the document]
Comment (tobz) [reply lib/vector-core/src/event/metric.rs:799]: Necessary? No.  This is my personal bias coming through: I strongly dislike the structure destructing pattern because `cargo fmt` usually ends up stratifying it across multiple lines, and renaming fields can become very verbose.  Dedicated `from_*`/`into_*` methods allow for a more succinct bit of code.

Now that I come to think of it, I also dislike `pub` fields because it makes encapsulation harder..

I could peruse the codebase to see if there's a slant we typically take -- structure destructing vs `from_*`/`into_*` -- since, if anything, I should really be going off our existing style.

File: src/sinks/prometheus/exporter.rs (hunk 4 above)
Comment (tobz) [reply src/sinks/prometheus/exporter.rs:202]: It's worth pointing out that on the vast majority of systems, these clock calls (`clock_gettime`, in this case, since we're dealing with `Instant` and not `SystemTime`) will be vDSO accelerated: 15-25 nanosecond per call, more or less.

That said, though, your suggestion is still a viable lil' performance improvement that's easy to do, so I'll do that.

File: src/sinks/prometheus/exporter.rs (hunk 5 above)
Comment (tobz) [reply src/sinks/prometheus/exporter.rs:220]: Yep, I can get behind that sentiment.

I've gone ahead and named struct-ified it.

File: src/sinks/prometheus/exporter.rs (hunk 6 above)
Comment (tobz) [reply src/sinks/prometheus/exporter.rs:285]: There I go again, treating code comments like Slack. :D

I've gone ahead and made the language a bit more plain/straightforward.

File: src/sinks/prometheus/exporter.rs (hunk 8 above)
Comment (bruceg) [reply src/sinks/prometheus/exporter.rs:466]: Yeah, I think I was looking more at the key and less at the rest.

File: src/sinks/prometheus/exporter.rs (hunk 4 above)
Comment (bruceg) [reply src/sinks/prometheus/exporter.rs:202]: Hmm, criterion says otherwise, despite the cycle counts being close:
```
rust-timeit --use 'std::time::Instant' --setup 'let ref1 = Instant::now(); let ref2 = Instant::now();' 'ref1.elapsed()' 'ref2.duration_since(ref1)'

`ref1.elapsed()`        time:   [1.1380 us 1.1407 us 1.1436 us]                              
`ref2.duration_since(ref1)`                                                                             
                        time:   [4.1161 ns 4.1651 ns 4.2423 ns]

`ref1.elapsed()`        time:   [3615.5721 cycles 3621.3010 cycles 3627.0069 cycles]         
`ref2.duration_since(ref1)`                                                                             
                        time:   [11.9903 cycles 12.0031 cycles 12.0168 cycles]

```

File: lib/vector-core/src/event/metric.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (bruceg) [reply lib/vector-core/src/event/metric.rs:799]: On the other hand, destructuring retains the names while `from_parts`/`into_parts` only has argument/tuple positioning (just like the tuple structs I mentioned elsewhere). I do agree about the encapsulation issue, so 🤷🏻

File: src/sinks/prometheus/exporter.rs (hunk 4 above)
Comment (tobz) [reply src/sinks/prometheus/exporter.rs:202]: This is where it can be tricky, on a per-system basis, but on my local Ubuntu server:

```
toby@consigliere:~$ cat /sys/devices/system/clocksource/clocksource0/current_clocksource
tsc

toby@consigliere:~$ rust-timeit --use 'std::time::Instant' --setup 'let ref1 = Instant::now(); let ref2 = Instant::now();' 'ref1.elapsed()' 'ref2.duration_since(ref1)'
...

`ref1.elapsed()`            time:   [31.101 ns 31.151 ns 31.193 ns]
`ref2.duration_since(ref1)` time:   [4.1393 ns 4.1411 ns 4.1434 ns]
```

Overall, yeah, there are definitely cases where it can be unexpectedly slow.  My comment wasn't meant to be a catch-all, but on a production server, I would expect the kernel tunables to be set such that the results on that server match what I saw running the above code.

Said another way: we shouldn't _always_ be scared of time, but to your point, it doesn't hurt to try and amortize the cost where it can be done without affecting the output/behavior.

Comment (bruceg) [reply src/sinks/prometheus/exporter.rs:202]: Hmm, interesting, my system is using `hpet` instead of the TSC, probably because the TSC was marked as unstable.

Comment (tobz) [reply src/sinks/prometheus/exporter.rs:202]: Yeah, it's tricky.  This is one of the main reasons I wrote `quanta`. 😂

File: src/sinks/prometheus/exporter.rs (hunk 7 above)
Comment (tobz) [reply src/sinks/prometheus/exporter.rs]: Addressed in `91155f808` by moving these to `MetricValue` directly, as fallible conversions.

File: lib/vector-core/src/event/metric.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (tobz) [reply lib/vector-core/src/event/metric.rs:846]: Proposal: I leave the above changes as-is, _but_ I create a new issue for defining an RFC where we adopt a style guide, which would codify patterns for scenarios like these that we want to enforce.

I'm not necessarily against the style you propose, and would be happy to propose it as a default in the hypothetical RFC/style guide, but it seems worth codifying/agreeing upon it officially if we care enough to bring it up in code reviews.

Does this seem like an amenable resolution of this comment, in your eyes?

[the remark this answers is not in the document]
Comment (tobz) [reply lib/vector-core/src/event/metric.rs:846]: @bruceg Proposal: I leave the above changes as-is, _but_ I create a new issue for defining an RFC where we adopt a style guide, which would codify patterns for scenarios like these that we want to enforce.

I'm not necessarily against the style you propose, and would be happy to propose it as a default in the hypothetical RFC/style guide, but it seems worth codifying/agreeing upon it officially if we care enough to bring it up in code reviews.

Does this seem like an amenable resolution of this comment, in your eyes?

File: src/sources/prometheus/remote_write.rs [hunk 15]
```diff
@@ -248,10 +248,17 @@ mod integration_tests {
...
+    const PROMETHEUS_RECEIVE_ADDRESS: &str = "127.0.0.1:9102";
 
     #[tokio::test]
     async fn receive_something() {
+        // TODO: This test depends on the single instance of Prometheus that we spin up for
+        // integration tests both scraping an endpoint and then also remote writing that stuff to
+        // this remote write source.  This makes sense from a "test the actual behavior" standpoint
+        // but it feels a little fragile.
+        //
+        // It could be nice to split tup the Prometheus integration tests in the future, or
```
Comment (bruceg) [inline src/sources/prometheus/remote_write.rs:260]: Nit: "split tup"?

**Review by bruceg — APPROVED** [review]
Looks good. I left a suggestion for your consideration.

File: lib/vector-core/src/event/metric.rs [hunk 16]
```diff
@@ -223,6 +224,53 @@ impl MetricValue {
...
+    /// Converts a distribution to an aggregated histogram.
+    ///
+    /// Histogram bucket bounds are based on `buckets`, where the value is the upper bound of the
+    /// bucket.  Samples will be thus be ordered in a "less than" fashion: if the given sample is
+    /// less than or equal to a given bucket's upper bound, it will be counted towards that bucket
+    /// at the given sample rate.
+    ///
+    /// If this `MetricValue` is not a distribution, then `None` is returned.  Otherwise,
+    /// `Some(MetricValue::AggregatedHistogram)` is returned.
+    pub fn distribution_to_agg_histogram(self, buckets: &[f64]) -> Option<MetricValue> {
```
[the remark this answers is not in the document]
Comment (tobz) [reply lib/vector-core/src/event/metric.rs]: Yeah, that's fair: we don't actually consume/take ownership of the distribution samples anyways since they have to be transformed one way or another.

Switched these to take `&self` in 9a08c0198, which required no other changes, surprisingly.

File: src/sources/prometheus/remote_write.rs (hunk 15 above)
Comment (tobz) [reply src/sources/prometheus/remote_write.rs]: Good catch.  Addressed in 9a08c0198.
