### PR TITLE
fix(vector sink): Add DataLoss error code as non-retryable

### LINKED ISSUE #17895: Vector source/sink not propagating non-retryable failures
### Discussed in https://github.com/vectordotdev/vector/discussions/17873

<div type='discussions-op-text'>

<sup>Originally posted by **sbalmos** July  5, 2023</sup>
I'm still trying to quantify exactly what the bug is, but it seems like the vector source/sink does not propagate back up non-retryable delivery failures from the end sink. In my setup, I have a Vector instance as a sort of post office delivery multiplexer, reading from Kafka and distributing to one or more exporter Vector instances, connected via the vector sink.

```
                            / -> (vector sink) -> (vector source) Exporter 1 -> http sink
Kafka -> (kafka source) Mux | -> (vector sink) -> (vector source) Exporter 2 -> loki sink
                            \ -> (vector sink) -> (vector source) Exporter 3 -> splunk_hec_logs sink
```

In exporters where some failures are non-retryable (e.g. HTTP sink with non-retryable errors like 400), it seems as if at the exporter level the event is appropriately dropped. However, this drop action apparently does not communicate back a hard failure acknowledgement or similar signal through the vector protocol, back to the Mux instance. The vector sink retry on the Mux instance apparently sees a delivery failure (or rather lack of acknowledgement) and repeatedly tries to retry delivery of the message to the exporter. This continues ad nauseam until the retry count is exceeded or (more likely) the exporter's vector sink buffer on the Mux is filled - which then has a follow-on bad behavior of stopping the whole mux in its tracks, stopping delivery of all messages to all destination exporters.</div>

### PR DESCRIPTION
**Pull request by sbalmos**
Fixes #17895 as discussed in #17873. The Vector source propagates downstream non-retryable errors as either DataLoss or Internal GRPC error codes. However, these error codes are not treated as non-retryable by the corresponding upstream Vector sink, leading to a delivery retry loop.

(update): Only treating DataLoss as non-retryable. As explained by @dsmith3197 in a commit review - Internal errors occur when At least one event in the batch had a transient error in delivery and DataLoss errors occur when At least one event in the batch had a permanent failure or rejection, with Internal taking precedence over Dataloss. With that in mind, we'll want to retry for Internal, but not DataLoss.

### CODE REVIEW

File: src/sinks/vector/config.rs [hunk 1]
```diff
@@ -253,6 +253,8 @@ impl RetryLogic for VectorGrpcRetryLogic {
                     | OutOfRange
                     | Unimplemented
                     | Unauthenticated
+                    | Internal
+                    | DataLoss
```
Comment (dsmith3197) [inline src/sinks/vector/config.rs:257]: `Internal` errors occur when `At least one event in the batch had a transient error in delivery` and `DataLoss` errors occur when `At least one event in the batch had a permanent failure or rejection`, with `Internal` taking precedence over `Dataloss`.

https://github.com/vectordotdev/vector/blob/a141d2b163aa487a15c278096c24a57849b53d8a/lib/vector-common/src/finalization.rs#L283

With that in mind, we'll want to retry for `Internal`, but not `DataLoss`.

```suggestion
                    | DataLoss
```

**Review by dsmith3197 — CHANGES_REQUESTED** [review]

**Review by dsmith3197 — APPROVED** [review]
Thank you for the contribution!
