### PR TITLE
fix(aws_cloudwatch_logs sink): Drop excessive large events

### LINKED ISSUE #2742: Drop records that exceed 256 bytes in the `aws_cloudwatch_logs` sink
AWS CloudWatch Logs has a [record limit of `256kb`](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html). We should drop any encoded records that exceed this size and add a rate-limited warning log message.

### PR DESCRIPTION
**Pull request by bruceg**
AWS CloudWatch Logs has a fixed maximum event size of 256KiB. This
modifies the sink to drop all events that exceed that size once encoded
and generate an error.

Signed-off-by: Bruce Guenter <bruce@timber.io>

Closes #2742

### CODE REVIEW

**Comment by bruceg** [comment]
I left this as hard coded, as there is I didn't see a good reason to let the user break it, but I am open to adding a tunable for this.

File: src/sinks/aws_cloudwatch_logs/mod.rs [hunk 1]
```diff
@@ -262,25 +267,25 @@ impl CloudwatchLogsSvc {
...
+            Encoding::Text => log
+                .get(&event::log_schema().message_key())
+                .map(|v| v.to_string_lossy())
+                .unwrap_or_else(|| "".into()),
+        };
+
+        match message.len() {
+            length if length <= MAX_MESSAGE_SIZE => Some(InputLogEvent { message, timestamp }),
+            length => {
+                error!(message = "Message exceeds CloudWatch maximum size", %length);
```
Comment (Hoverbear) [inline src/sinks/aws_cloudwatch_logs/mod.rs:287]: Might consider rate limiting this?

File: src/sinks/aws_cloudwatch_logs/mod.rs [hunk 2]
```diff
@@ -37,6 +37,11 @@ use tower::{
     Service, ServiceBuilder, ServiceExt,
 };
 
+// Estimated maximum size of InputLogEvent with an empty message
```
Comment (Hoverbear) [inline src/sinks/aws_cloudwatch_logs/mod.rs:40]: Is there a reasoning for this number? (I think it's fine)

File: src/sinks/aws_cloudwatch_logs/mod.rs (hunk 1 above)
Comment (Hoverbear) [reply src/sinks/aws_cloudwatch_logs/mod.rs:287]: Another option might be to return a result from this function?

So other places would have like:

```diff
-            .map(|e| self.encode_log(e))
+            .filter_map(|e| self.encode_log(e).map_err(error!(...)).ok())
```

**Review by Hoverbear — APPROVED** [review]
Looks good. :)

**Review by lukesteensen — COMMENTED** [review]
:+1:
