### PR TITLE
fix(influxdb_logs): encode influx line when no tags present

### LINKED ISSUE #17020: Influxdb_logs should encode when there's not tags at all
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

For the `influxdb_logs` sink, it should encode correctly when there's no tags at all. Currently if such event submit to influxdb, it will result in following error:

2023-03-31T07:04:25.045060Z ERROR sink{component_kind="sink" component_id=influx_logs component_type=influxdb_logs component_name=influx_logs}:request{request_id=0}: vector::sinks::util::sink: Response failed. response=Response { status: 400, version: HTTP/1.1, headers: {"date": "Fri, 31 Mar 2023 07:04:25 GMT", "content-type": "application/json; charset=utf-8", "content-length": "206", "connection": "keep-alive", "trace-id": "136xxxxxxxxxx3f5", "trace-sampled": "false", "x-platform-error-code": "invalid", "strict-transport-security": "max-age=15724800; includeSubDomains", "x-influxdb-request-id": "7d9xxxxxxxxxxxxxxxxxxxxxxxxxxea1", "x-influxdb-build": "Cloud"}, body: b"{\"code\":\"invalid\",\"message\":\"2/2 points rejected; first error: at line 1:6: expected tag key after comma; got white space instead (check rejected_points in your _monitoring bucket for further information)\"}" }

It means no tags present after measurement, i.e.

```
logs, message="hello world" # current behavior, which is invalid
logs message="hello world"  # expected behavior
logs,host=localhost message="hello world" # if tags present
```

Currently, it encodes

### Configuration

```text
# App logs
[sources.logs]
type = "file"
include = ["/var/log/app/*.log.*"]

oldest_first = true

[transforms.logs_fields]
type = "remap"
inputs = ["logs"]

source = '''
  . = parse_regex!(.message, r'^(?P<timestamp>\S+) (?P<level>\S+) (?P<target>\S+) \| (?P<message>.*)$')
  .timestamp = parse_timestamp!(.timestamp, "%+")
'''

## InfluxDB sink
[sinks.influx_logs]
type = "influxdb_logs"
inputs = ["logs_fields"]

endpoint = "https://eu-central-1-1.aws.cloud2.influxdata.com"
token = "${INFLUX_TOKEN}"

org = "org"
bucket = "org-app"

measurement = "logs"
# tags = ["level", "target"]

[sinks.influx_logs.encoding]
except_fields = ["metric_type", "source_type"]
```

### Version

0.16.4

### Debug Output

```text
2023-03-31T07:04:25.045060Z ERROR sink{component_kind="sink" component_id=influx_logs component_type=influxdb_logs component_name=influx_logs}:request{request_id=0}: vector::sinks::util::sink: Response failed. response=Response { status: 400, version: HTTP/1.1, headers: {"date": "Fri, 31 Mar 2023 07:04:25 GMT", "content-type": "application/json; charset=utf-8", "content-length": "206", "connection": "keep-alive", "trace-id": "136xxxxxxxxxx3f5", "trace-sampled": "false", "x-platform-error-code": "invalid", "strict-transport-security": "max-age=15724800; includeSubDomains", "x-influxdb-request-id": "7d9xxxxxxxxxxxxxxxxxxxxxxxxxxea1", "x-influxdb-build": "Cloud"}, body: b"{\"code\":\"invalid\",\"message\":\"2/2 points rejected; first error: at line 1:6: expected tag key after comma; got white space instead (check rejected_points in your _monitoring bucket for further information)\"}" }
```

### Example Data

_No response_

### Additional Context

_No response_

### References

https://github.com/vectordotdev/vector/pull/10217#issuecomment-1491421796

### PR DESCRIPTION
**Pull request by juvenn**
When trying to sink log without tags into influxdb, influxdb will error out `expected tag key after comma`. Which means the comma `,` should be omitted if there are no tags.

```
logs, message="hello world" # current behavior, which is invalid
logs message="hello world"  # expected behavior
```

Close #17020

### CODE REVIEW

File: src/sinks/influxdb/logs.rs [hunk 1]
```diff
@@ -592,24 +592,32 @@ mod tests {
...
             "http://localhost:9999",
             "my-token",
             ProtocolVersion::V2,
             "vector",
-            ["metric_type"].to_vec(),
+            [].to_vec(),
         );
+        sink.transformer
+            .set_except_fields(Some(vec!["metric_type".into()]))
+            .unwrap();
```
Comment (juvenn) [inline src/sinks/influxdb/logs.rs:604]: exclude default `metric_type` tag, so no tags present in final event.

File: src/sinks/influxdb/logs.rs [hunk 2]
```diff
@@ -592,24 +592,32 @@ mod tests {
...
         let mut encoder = sink.build_encoder();
 
         let bytes = encoder.encode_event(event).unwrap();
-        let string = std::str::from_utf8(&bytes).unwrap();
+        let line = std::str::from_utf8(&bytes).unwrap();
+        assert!(line.starts_with("vector "));
```
Comment (juvenn) [inline src/sinks/influxdb/logs.rs:609]: Should have no comma after measurement.

File: src/sinks/influxdb/logs.rs [hunk 3]
```diff
@@ -592,24 +592,32 @@ mod tests {
...
 
-        let line_protocol = split_line_protocol(string);
+       let line_protocol = split_line_protocol(line);
         assert_eq!("vector", line_protocol.0);
-        assert_eq!("metric_type=logs", line_protocol.1);
+        assert_eq!("", line_protocol.1);
```
Comment (juvenn) [inline src/sinks/influxdb/logs.rs:613]: No tags present

File: src/sinks/influxdb/mod.rs [hunk 4]
```diff
@@ -442,12 +446,12 @@ pub mod test_util {
...
-        let measurement = split[0];
-
-        split = split[1].splitn(3, ' ').collect::<Vec<&str>>();
+        // tags and ts may not be present
+        let parts: Vec<&str> = line_protocol.splitn(2, " ").collect();
+        let (measurement, tags) = parts[0].split_once(",").unwrap_or((parts[0], ""));
+        let (fields, ts) = parts[1].split_once(" ").unwrap_or((parts[1], ""));
 
-        (measurement, split[0], split[1].to_string(), split[2])
+        (measurement, tags, fields.to_string(), ts)
```
Comment (juvenn) [inline src/sinks/influxdb/mod.rs:454]: Both tags and timestamp are optional.

**Review by spencergilbert — APPROVED** [review]
LGTM, thanks for the contribution!

File: src/sinks/influxdb/mod.rs [hunk 5]
```diff
@@ -244,12 +244,16 @@ pub(in crate::sinks) fn influx_line_protocol(
...
     let unwrapped_tags = tags.unwrap_or_default();
-    encode_tags(unwrapped_tags, line_protocol);
-    line_protocol.put_u8(b' ');
+    if unwrapped_tags.is_empty() {
+        line_protocol.put_u8(b' ');
+    } else {
+        line_protocol.put_u8(b',');
+        encode_tags(unwrapped_tags, line_protocol);
+        line_protocol.put_u8(b' ');
+    }
```
Comment (bruceg) [inline src/sinks/influxdb/mod.rs:256]: nit: Could technically de-duplicate this trailing put:
```suggestion
    if !unwrapped_tags.is_empty() {
        line_protocol.put_u8(b',');
        encode_tags(unwrapped_tags, line_protocol);
    }
    line_protocol.put_u8(b' ');
```

File: src/sinks/influxdb/mod.rs [hunk 6]
```diff
@@ -442,12 +446,12 @@ pub mod test_util {
...
     //
     pub(crate) fn split_line_protocol(line_protocol: &str) -> (&str, &str, String, &str) {
-        let mut split = line_protocol.splitn(2, ',').collect::<Vec<&str>>();
-        let measurement = split[0];
-
-        split = split[1].splitn(3, ' ').collect::<Vec<&str>>();
+        // tags and ts may not be present
+        let parts: Vec<&str> = line_protocol.splitn(2, ' ').collect();
+        let (measurement, tags) = parts[0].split_once(',').unwrap_or((parts[0], ""));
+        let (fields, ts) = parts[1].split_once(' ').unwrap_or((parts[1], ""));
```
Comment (bruceg) [inline src/sinks/influxdb/mod.rs:452]: Would be better to use `split_once` instead of `splitn(2)` here, as it doesn't need to allocate a new `Vec` for the results. However, as a test it doesn't really matter.

File: src/sinks/influxdb/logs.rs (hunk 1 above)
Comment (bruceg) [reply src/sinks/influxdb/logs.rs:604]: These comments would be useful in the code to explain what is being tested.

**Review by bruceg — APPROVED** [review]
The code looks correct and the testing is great, particularly with the explanations. I have a couple of non-blocking suggestions below.

File: src/sinks/influxdb/mod.rs (hunk 6 above)
Comment (juvenn) [reply src/sinks/influxdb/mod.rs:452]: Thanks @bruceg , they are all nice suggestions, and I'm learning from it. I'll update them soon.

**Comment by juvenn** [comment]
Hi @bruceg , please take another look.
