### PR TITLE
fix: Generate valid config for all components

### LINKED ISSUE #3885: `vector generate` output does not include required fieds
It appears `vector generate` is out-of-sync with the currently required fields on multiple components.

I've only checked two, but both missed a required field, so it's safe to assume there are others as well:

* `console` sink config misses the required `encoding.codec` field
* `blackhole` sink config misses the required `print_amount` field

### PR DESCRIPTION
**Pull request by juchiast**
close #3885 

Also added `generate_all` test which will generate and parse all submitted components.

Signed-off-by: Duy Do <juchiast@gmail.com>

### CODE REVIEW

File: src/transforms/add_fields.rs [hunk 1]
```diff
@@ -51,7 +51,11 @@ inventory::submit! {
     TransformDescription::new::<AddFieldsConfig>("add_fields")
 }
 
-impl GenerateConfig for AddFieldsConfig {}
+impl GenerateConfig for AddFieldsConfig {
+    fn generate_config() -> toml::Value {
+        toml::from_str(r#"fields.name = "TODO""#).unwrap()
```
Comment (bruceg) [inline src/transforms/add_fields.rs:56]: Is this something that needs completing? If not, I suggest changing the name above.

File: src/transforms/swimlanes.rs [hunk 2]
```diff
@@ -71,7 +71,14 @@ inventory::submit! {
...
 
-impl GenerateConfig for SwimlanesConfig {}
+impl GenerateConfig for SwimlanesConfig {
+    fn generate_config() -> toml::Value {
+        toml::Value::try_from(Self {
+            lanes: IndexMap::new(),
+        })
+        .unwrap()
+    }
+}
```
Comment (bruceg) [inline src/transforms/swimlanes.rs:81]: Should this transform also have a `generate_config` test like the others?

File: src/transforms/tag_cardinality_limit.rs [hunk 3]
```diff
@@ -69,7 +69,16 @@ inventory::submit! {
...
+impl GenerateConfig for TagCardinalityLimitConfig {
+    fn generate_config() -> toml::Value {
+        toml::Value::try_from(Self {
+            mode: Mode::Exact,
+            value_limit: default_value_limit(),
+            limit_exceeded_action: default_limit_exceeded_action(),
+        })
+        .unwrap()
+    }
+}
```
Comment (bruceg) [inline src/transforms/tag_cardinality_limit.rs:81]: Ditto comment about `generate_config` test

File: src/generate.rs [hunk 4]
```diff
@@ -417,8 +464,12 @@ when_full = "block"
 [sinks.sink0]
 healthcheck = true
 inputs = ["TODO"]
```
Comment (bruceg) [inline src/generate.rs:466]: Is this still incomplete?

File: src/generate.rs [hunk 5]
```diff
@@ -435,6 +486,9 @@ when_full = "block"
 inputs = []
 type = "add_fields"
 
+[transforms.transform0.fields]
+name = "TODO"
```
Comment (bruceg) [inline src/generate.rs:490]: I this still TODO?

**Review by bruceg — COMMENTED** [review]
I have some questions about bits that look incomplete, but it looks ok otherwise.

File: src/transforms/add_fields.rs (hunk 1 above)
Comment (juchiast) [reply src/transforms/add_fields.rs:56]: changed to `field_name`

File: src/transforms/tag_cardinality_limit.rs (hunk 3 above)
Comment (juchiast) [reply src/transforms/tag_cardinality_limit.rs:81]: Added!

File: src/transforms/swimlanes.rs (hunk 2 above)
Comment (juchiast) [reply src/transforms/swimlanes.rs:81]: Added!

File: src/generate.rs (hunk 5 above)
Comment (juchiast) [reply src/generate.rs:490]: This is generated from fields.name = "TODO" above.

File: src/generate.rs (hunk 4 above)
Comment (juchiast) [reply src/generate.rs:466]: This happens when there is no input for the component, TODO here is meant for the user to fill it up. We can either output an empty list or `["TODO"]` here.

Comment (bruceg) [reply src/generate.rs:466]: If it is not something for a developer to fill in, I think we should avoid the "TODO" token. That implies that there is something left incomplete within Vector. This could be something like `"source-name-goes-here"` or equivalent to indicate what kind of value it should be filled with.

**Review by bruceg — APPROVED** [review]

**Review by jszwedko — APPROVED** [review]
Should we drop the default implementation of `generate_config` on `GenerateConfig`? Or is it still useful in some circumstances?

**Comment by juchiast** [comment]
@jszwedko some components still use the default implementation. I removed the default implementation and added tests for those components.

File: src/transforms/dedupe.rs [hunk 6]
```diff
@@ -18,8 +18,6 @@ pub enum FieldMatchConfig {
     MatchFields(Vec<String>),
     #[serde(rename = "ignore")]
     IgnoreFields(Vec<String>),
-    #[serde(skip)]
-    Default,
```
Comment (juchiast) [inline src/transforms/dedupe.rs:22]: Hit error `FieldMatchConfig::Default` cannot be serialized. I fixed this and also remove runtime panic.
