### PR TITLE
fix(tests): Wait for shutdown in `file_start_position_server_restart`

### LINKED ISSUE #7988: Test `file_start_position_server_restart_acknowledged` is flakey on non-Linux
This test appears to be fairly stable on Linux, but is showing occasional failures on both MacOS and Windows:
```
2021-06-22T15:22:35.4260697Z ---- sources::file::tests::file_start_position_server_restart_acknowledged stdout ----
2021-06-22T15:22:35.4262113Z Jun 22 15:21:12.610  WARN vector::sources::file: The `fingerprint.bytes` option will be used to convert old file fingerprints created by vector < v0.11.0, but are not supported for new file fingerprints. The first line will be used instead.
2021-06-22T15:22:35.4264644Z Jun 22 15:21:12.611  INFO vector::sources::file: Starting file server. include=["C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\.tmpUqbOTa\\*"] exclude=[]
2021-06-22T15:22:35.4265906Z Jun 22 15:21:12.618  WARN file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. path=C:\Users\ADMINI~1\AppData\Local\Temp\.tmpUqbOTa\checkpoints.json
2021-06-22T15:22:35.4267108Z Jun 22 15:21:12.629  INFO file_server: vector::internal_events::file::source: Found new file to watch. path=C:\Users\ADMINI~1\AppData\Local\Temp\.tmpUqbOTa\file
2021-06-22T15:22:35.4268005Z Jun 22 15:21:12.734 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=3
2021-06-22T15:22:35.4269328Z Jun 22 15:21:12.735  WARN file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. path=C:\Users\ADMINI~1\AppData\Local\Temp\.tmpUqbOTa\checkpoints.new.json
2021-06-22T15:22:35.4270418Z Jun 22 15:21:12.847 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=3
2021-06-22T15:22:35.4271262Z Jun 22 15:21:12.952 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=3
2021-06-22T15:22:35.4272033Z Jun 22 15:21:13.064 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=3
2021-06-22T15:22:35.4272878Z Jun 22 15:21:13.180 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=3
2021-06-22T15:22:35.4274084Z Jun 22 15:21:13.288 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=4
2021-06-22T15:22:35.4274857Z Jun 22 15:21:13.399 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=2
2021-06-22T15:22:35.4275637Z Jun 22 15:21:13.509 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=8
2021-06-22T15:22:35.4276399Z Jun 22 15:21:13.614 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=2
2021-06-22T15:22:35.4277517Z Jun 22 15:21:13.615  WARN vector::sources::file: The `fingerprint.bytes` option will be used to convert old file fingerprints created by vector < v0.11.0, but are not supported for new file fingerprints. The first line will be used instead.
2021-06-22T15:22:35.4278766Z Jun 22 15:21:13.615  INFO vector::sources::file: Starting file server. include=["C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\.tmpUqbOTa\\*"] exclude=[]
2021-06-22T15:22:35.4279626Z Jun 22 15:21:13.619 DEBUG vector::internal_events::file::source: Files checkpointed. count=1 duration_ms=3
2021-06-22T15:22:35.4280694Z Jun 22 15:21:13.624  WARN file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. path=C:\Users\ADMINI~1\AppData\Local\Temp\.tmpUqbOTa\checkpoints.json
2021-06-22T15:22:35.4282242Z Jun 22 15:21:13.624 ERROR file_server: vector::internal_events::file::source: Failed reading file for fingerprinting. path=C:\Users\ADMINI~1\AppData\Local\Temp\.tmpUqbOTa\checkpoints.new.json error=The system cannot find the file specified. (os error 2)
2021-06-22T15:22:35.4283615Z Jun 22 15:21:13.628  INFO file_server: vector::internal_events::file::source: Found new file to watch. path=C:\Users\ADMINI~1\AppData\Local\Temp\.tmpUqbOTa\file
2021-06-22T15:22:35.4284498Z Jun 22 15:21:13.733 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=2
2021-06-22T15:22:35.4285592Z Jun 22 15:21:13.734  WARN file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. path=C:\Users\ADMINI~1\AppData\Local\Temp\.tmpUqbOTa\checkpoints.new.json
2021-06-22T15:22:35.4286674Z Jun 22 15:21:13.842 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=5
2021-06-22T15:22:35.4287429Z Jun 22 15:21:13.956 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=3
2021-06-22T15:22:35.4288200Z Jun 22 15:21:14.069 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=3
2021-06-22T15:22:35.4288952Z Jun 22 15:21:14.182 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=2
2021-06-22T15:22:35.4289713Z Jun 22 15:21:14.288 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=3
2021-06-22T15:22:35.4290482Z Jun 22 15:21:14.400 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=3
2021-06-22T15:22:35.4291227Z Jun 22 15:21:14.512 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=2
2021-06-22T15:22:35.4291997Z Jun 22 15:21:14.627 DEBUG vector::internal_events::file::source: Files checkpointed. count=0 duration_ms=4
2021-06-22T15:22:35.4292732Z thread 'main' panicked at 'assertion failed: `(left == right)`
2021-06-22T15:22:35.4293197Z 
2021-06-22T15:22:35.4293533Z Diff < left / right > :
2021-06-22T15:22:35.4293909Z  [
2021-06-22T15:22:35.4294201Z <    "zeroth line",
2021-06-22T15:22:35.4294512Z <    "first line",
2021-06-22T15:22:35.4294828Z      "second line",
2021-06-22T15:22:35.4295086Z  ]
```

### PR DESCRIPTION
**Pull request by bruceg**
AFAICT the race is between the checkpoint file being written by the
first server and then read by the second (restarted) server. With this
pause I have been unable to trigger the race.

Signed-off-by: Bruce Guenter <bruce.guenter@datadoghq.com>

Closes #7988 (again)

### CODE REVIEW

File: src/sources/file.rs [hunk 1]
```diff
@@ -987,6 +987,7 @@ mod tests {
             let lines = extract_messages_string(received);
             assert_eq!(lines, vec!["zeroth line", "first line"]);
         }
+        sleep_500_millis().await;
```
Comment (jszwedko) [inline src/sources/file.rs:990]: Weird, do I take it to mean that it takes this long for the checkpoint files to be fully flushed to disk from the first run?

**Review by jszwedko — APPROVED** [review]
Nice!

File: src/sources/file.rs (hunk 1 above)
Comment (bruceg) [reply src/sources/file.rs:990]: I think it means that the checkpoint writer, which executes asynchronously, *occasionally* finishes writing the file (and flushing any internal buffers) after the next server test starts and loads it. It doesn't take 500ms, those waits are probably overkill, but the function was already there so I re-used it.

Comment (jszwedko) [reply src/sources/file.rs:990]: Hmm, it looks like `run_file_source` is shutting down the component before it returns though. I would imagine this includes stopping the checkpointing writer task?

Comment (bruceg) [reply src/sources/file.rs:990]: It should, yes, but only if the `wait_shutdown` condition is `true`, which I had missed. Turning it on should also resolve the problem, but doesn't appear to. I'll dig some more.

Comment (bruceg) [reply src/sources/file.rs:990]: I think this is happening because the checkpointer task occasionally fails to write the checkpoints a final time at shutdown. I'm running the test now with additional debug info, but that seems to have made it harder to trigger.

Comment (ktff) [reply src/sources/file.rs:990]: From what I see in `file_server` the checkpointer and regular read future don't synchronize the shutdown, so the checkpointer can finish writing current state then shutdown while the read future is still reading some file, updating state and only then checking for shutdown condition. This seems like it fits

>  the checkpointer task occasionally fails to write the checkpoints a final time at shutdown

**Review by ktff — APPROVED** [review]
