### PR TITLE
fix(datadog_metrics sink): properly encode rate metrics

### LINKED ISSUE #14740: bug(datadog_metrics sink): rate counters being sent as counts (again)
In #13394, we added the ability for the `datadog_metrics` sink to properly send "rate" metrics to Datadog, which describe a counter in terms of its total value over a given interval.

In #13960, while fixing another closely-related issue, I mistaken broke the logic introduced in #13394 such that regardless of whether or not an interval was present, we were sending all counters as "count" metrics.

Long story short, this sends those rate metrics in a way that makes them incorrect when compared to the same metric being sent directly by the Datadog Agent. We need to reapply the logic that sends counters as a rate if they have an interval.

### PR DESCRIPTION
**Pull request by tobz**
This PR reintroduces the logic to differentiate rate metrics and count metrics in the `datadog_metrics` sink. This was a regression introduced in #13960.

We also now have a unit test making sure this is handled correctly, so hopefully no more regressions by yours truly, or anyone, as far as rate metrics go. 🤞🏻 😅 

Fixes #14740.

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

File: src/sinks/datadog/metrics/encoder.rs [hunk 1]
```diff
@@ -757,6 +769,33 @@ mod tests {
...
+
+        // Encode the metric and make sure we did the rate conversion correctly.
+        let result = generate_series_metrics(&rate_counter, &None, log_schema());
+        assert!(result.is_ok());
+
+        let metrics = result.unwrap();
+        assert_eq!(metrics.len(), 1);
+
+        let actual = &metrics[0];
+        assert_eq!(actual.r#type, DatadogMetricType::Rate);
```
Comment (neuronull) [inline src/sinks/datadog/metrics/encoder.rs:793]: Would it be valuable add a test to ensure the `DatadogMetricType::Count` is set as the type, in the event that an interval is not defined?

**Review by neuronull — APPROVED** [review]
