### PR TITLE
fix(graphql api): `--no-default-features --features api` build failure

### LINKED ISSUE #7222: Check build fails with flags `--no-default-features --features api`
While working on #7200 I ran `cargo hack check --feature-powerset --clean-per-run` and found that the build string in the issue title causes a build failure. 

```
error[E0432]: unresolved import `crate::sources::host_metrics`
 --> src/api/schema/metrics/host.rs:3:21
  |
3 | use crate::sources::host_metrics::HostMetricsConfig;
  |                     ^^^^^^^^^^^^ could not find `host_metrics` in `sources`

error[E0432]: unresolved import `uuid`
  --> src/api/tap.rs:16:5
   |
16 | use uuid::Uuid;
   |     ^^^^ use of undeclared crate or module `uuid`

error[E0433]: failed to resolve: could not find `host_metrics` in `sources`
   --> src/api/schema/metrics/host.rs:265:23
    |
265 |         Self(sources::host_metrics::HostMetricsConfig::default())
    |                       ^^^^^^^^^^^^ could not find `host_metrics` in `sources`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `vector`

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by leebenson**
Fixes #7222.

Signed-off-by: Lee Benson <lee@leebenson.com>

### CODE REVIEW

File: src/api/schema/metrics/mod.rs [hunk 1]
```diff
@@ -30,6 +31,9 @@ pub use source::{IntoSourceMetrics, SourceMetrics};
 pub use transform::{IntoTransformMetrics, TransformMetrics};
 pub use uptime::Uptime;
 
+#[cfg(feature = "sources-host_metrics")]
+pub use host::HostMetrics;
```
Comment (jszwedko) [inline src/api/schema/metrics/mod.rs:35]: Is this used outside of this module?

**Review by jszwedko — APPROVED** [review]
Nice, thanks @leebenson !

File: src/api/schema/metrics/mod.rs (hunk 1 above)
Comment (leebenson) [reply src/api/schema/metrics/mod.rs]: Nope! Nixed this line (along with the `cfg` guard) in favour of `host::HostMetrics` where used 👍🏻
